# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConsultationCharges.ui'
#
# Created: Sun Aug 26 21:03:37 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(647, 468)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/coins-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnAjouter = QtGui.QPushButton(Dialog)
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.horizontalLayout_2.addWidget(self.btnAjouter)
        self.btnEnleverAutre = QtGui.QPushButton(Dialog)
        self.btnEnleverAutre.setObjectName(_fromUtf8("btnEnleverAutre"))
        self.horizontalLayout_2.addWidget(self.btnEnleverAutre)
        self.btnDetailsAutre = QtGui.QPushButton(Dialog)
        self.btnDetailsAutre.setObjectName(_fromUtf8("btnDetailsAutre"))
        self.horizontalLayout_2.addWidget(self.btnDetailsAutre)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableWidgetAutreCharge = QtGui.QTableWidget(self.groupBox)
        self.tableWidgetAutreCharge.setObjectName(_fromUtf8("tableWidgetAutreCharge"))
        self.tableWidgetAutreCharge.setColumnCount(2)
        self.tableWidgetAutreCharge.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetAutreCharge.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetAutreCharge.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.tableWidgetAutreCharge)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnEnleverHypotheque = QtGui.QPushButton(self.groupBox_2)
        self.btnEnleverHypotheque.setObjectName(_fromUtf8("btnEnleverHypotheque"))
        self.horizontalLayout_4.addWidget(self.btnEnleverHypotheque)
        self.btnDetailsHypotheque = QtGui.QPushButton(self.groupBox_2)
        self.btnDetailsHypotheque.setObjectName(_fromUtf8("btnDetailsHypotheque"))
        self.horizontalLayout_4.addWidget(self.btnDetailsHypotheque)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tableWidgetHypotheque = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetHypotheque.setObjectName(_fromUtf8("tableWidgetHypotheque"))
        self.tableWidgetHypotheque.setColumnCount(5)
        self.tableWidgetHypotheque.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHypotheque.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHypotheque.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHypotheque.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHypotheque.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHypotheque.setHorizontalHeaderItem(4, item)
        self.verticalLayout_4.addWidget(self.tableWidgetHypotheque)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnEnleverServitude = QtGui.QPushButton(self.groupBox_3)
        self.btnEnleverServitude.setObjectName(_fromUtf8("btnEnleverServitude"))
        self.horizontalLayout_3.addWidget(self.btnEnleverServitude)
        self.btnDetailsServitude = QtGui.QPushButton(self.groupBox_3)
        self.btnDetailsServitude.setObjectName(_fromUtf8("btnDetailsServitude"))
        self.horizontalLayout_3.addWidget(self.btnDetailsServitude)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tableWidgetServitude = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidgetServitude.setObjectName(_fromUtf8("tableWidgetServitude"))
        self.tableWidgetServitude.setColumnCount(5)
        self.tableWidgetServitude.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServitude.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServitude.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServitude.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServitude.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServitude.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidgetServitude)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnValider = QtGui.QPushButton(Dialog)
        self.btnValider.setObjectName(_fromUtf8("btnValider"))
        self.horizontalLayout.addWidget(self.btnValider)
        self.btnAnnuler = QtGui.QPushButton(Dialog)
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))
        self.horizontalLayout.addWidget(self.btnAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Charge", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouter.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnleverAutre.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetailsAutre.setText(QtGui.QApplication.translate("Dialog", "Détails", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Autre charge", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetAutreCharge.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetAutreCharge.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Date d\'inscription ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Hypothèque", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnleverHypotheque.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetailsHypotheque.setText(QtGui.QApplication.translate("Dialog", "Détails", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHypotheque.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Date d\'inscription", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHypotheque.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Valeur", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHypotheque.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Creancier", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHypotheque.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Duree", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHypotheque.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "Date radiation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Servitude", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnleverServitude.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetailsServitude.setText(QtGui.QApplication.translate("Dialog", "Détails", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetServitude.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Numero", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetServitude.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetServitude.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Date inscription", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetServitude.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Origine", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetServitude.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "Date levée", None, QtGui.QApplication.UnicodeUTF8))
        self.btnValider.setText(QtGui.QApplication.translate("Dialog", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAnnuler.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
