# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConsultationCF.ui'
#
# Created: Thu Jun 02 10:36:33 2022
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(596, 619)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridGroupBox = QtGui.QGroupBox(Dialog)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBoxConsist = QtGui.QComboBox(self.gridGroupBox)
        self.comboBoxConsist.setObjectName(_fromUtf8("comboBoxConsist"))
        self.gridLayout.addWidget(self.comboBoxConsist, 3, 1, 1, 1)
        self.lineEditNumCert = QtGui.QLineEdit(self.gridGroupBox)
        self.lineEditNumCert.setObjectName(_fromUtf8("lineEditNumCert"))
        self.gridLayout.addWidget(self.lineEditNumCert, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxTypeCert = QtGui.QComboBox(self.gridGroupBox)
        self.comboBoxTypeCert.setObjectName(_fromUtf8("comboBoxTypeCert"))
        self.gridLayout.addWidget(self.comboBoxTypeCert, 0, 1, 1, 1)
        self.btnDetailDmd = QtGui.QPushButton(self.gridGroupBox)
        self.btnDetailDmd.setObjectName(_fromUtf8("btnDetailDmd"))
        self.gridLayout.addWidget(self.btnDetailDmd, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditNumDmd = QtGui.QLineEdit(self.gridGroupBox)
        self.lineEditNumDmd.setObjectName(_fromUtf8("lineEditNumDmd"))
        self.gridLayout.addWidget(self.lineEditNumDmd, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridGroupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.lineEditEtat = QtGui.QLineEdit(self.gridGroupBox)
        self.lineEditEtat.setObjectName(_fromUtf8("lineEditEtat"))
        self.gridLayout.addWidget(self.lineEditEtat, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.gridGroupBox)
        self.horizontalGroupBox = QtGui.QGroupBox(Dialog)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditSurface = QtGui.QLineEdit(self.horizontalGroupBox)
        self.lineEditSurface.setObjectName(_fromUtf8("lineEditSurface"))
        self.horizontalLayout.addWidget(self.lineEditSurface)
        self.label_6 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEditHa = QtGui.QLineEdit(self.horizontalGroupBox)
        self.lineEditHa.setObjectName(_fromUtf8("lineEditHa"))
        self.horizontalLayout.addWidget(self.lineEditHa)
        self.label_7 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEditA = QtGui.QLineEdit(self.horizontalGroupBox)
        self.lineEditA.setObjectName(_fromUtf8("lineEditA"))
        self.horizontalLayout.addWidget(self.lineEditA)
        self.label_8 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEditCa = QtGui.QLineEdit(self.horizontalGroupBox)
        self.lineEditCa.setObjectName(_fromUtf8("lineEditCa"))
        self.horizontalLayout.addWidget(self.lineEditCa)
        self.label_9 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.gridGroupBox_2 = QtGui.QGroupBox(Dialog)
        self.gridGroupBox_2.setObjectName(_fromUtf8("gridGroupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEditInscriptionReg = QtGui.QLineEdit(self.gridGroupBox_2)
        self.lineEditInscriptionReg.setObjectName(_fromUtf8("lineEditInscriptionReg"))
        self.gridLayout_2.addWidget(self.lineEditInscriptionReg, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEditDelivrance = QtGui.QLineEdit(self.gridGroupBox_2)
        self.lineEditDelivrance.setObjectName(_fromUtf8("lineEditDelivrance"))
        self.gridLayout_2.addWidget(self.lineEditDelivrance, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.lineEditEdition = QtGui.QLineEdit(self.gridGroupBox_2)
        self.lineEditEdition.setObjectName(_fromUtf8("lineEditEdition"))
        self.gridLayout_2.addWidget(self.lineEditEdition, 2, 1, 1, 1)
        self.lineEditDateReconnaissance = QtGui.QLineEdit(self.gridGroupBox_2)
        self.lineEditDateReconnaissance.setObjectName(_fromUtf8("lineEditDateReconnaissance"))
        self.gridLayout_2.addWidget(self.lineEditDateReconnaissance, 0, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridGroupBox_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 2, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridGroupBox_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 2, 2, 1)
        self.verticalLayout.addWidget(self.gridGroupBox_2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnProprietaire = QtGui.QPushButton(self.groupBox_2)
        self.btnProprietaire.setObjectName(_fromUtf8("btnProprietaire"))
        self.horizontalLayout_3.addWidget(self.btnProprietaire)
        self.btnCharges = QtGui.QPushButton(self.groupBox_2)
        self.btnCharges.setObjectName(_fromUtf8("btnCharges"))
        self.horizontalLayout_3.addWidget(self.btnCharges)
        self.btnRepere = QtGui.QPushButton(self.groupBox_2)
        self.btnRepere.setObjectName(_fromUtf8("btnRepere"))
        self.horizontalLayout_3.addWidget(self.btnRepere)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridGroupBox_3 = QtGui.QGroupBox(Dialog)
        self.gridGroupBox_3.setObjectName(_fromUtf8("gridGroupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.gridGroupBox_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_12 = QtGui.QLabel(self.gridGroupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.comboBoxRegion = QtGui.QComboBox(self.gridGroupBox_3)
        self.comboBoxRegion.setObjectName(_fromUtf8("comboBoxRegion"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxRegion)
        self.label_13 = QtGui.QLabel(self.gridGroupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.comboBoxDistrict = QtGui.QComboBox(self.gridGroupBox_3)
        self.comboBoxDistrict.setObjectName(_fromUtf8("comboBoxDistrict"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxDistrict)
        self.label_14 = QtGui.QLabel(self.gridGroupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.comboBoxCommune = QtGui.QComboBox(self.gridGroupBox_3)
        self.comboBoxCommune.setObjectName(_fromUtf8("comboBoxCommune"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxCommune)
        self.label_15 = QtGui.QLabel(self.gridGroupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.comboBoxFokontany = QtGui.QComboBox(self.gridGroupBox_3)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxFokontany)
        self.label_16 = QtGui.QLabel(self.gridGroupBox_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.comboBoxHameau = QtGui.QComboBox(self.gridGroupBox_3)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBoxHameau)
        self.verticalLayout.addWidget(self.gridGroupBox_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnAide = QtGui.QPushButton(Dialog)
        self.btnAide.setObjectName(_fromUtf8("btnAide"))
        self.horizontalLayout_2.addWidget(self.btnAide)
        self.btnHtml = QtGui.QPushButton(Dialog)
        self.btnHtml.setObjectName(_fromUtf8("btnHtml"))
        self.horizontalLayout_2.addWidget(self.btnHtml)
        self.btnFiscaliser = QtGui.QPushButton(Dialog)
        self.btnFiscaliser.setObjectName(_fromUtf8("btnFiscaliser"))
        self.horizontalLayout_2.addWidget(self.btnFiscaliser)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_2.addWidget(self.btnFermer)
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setMinimumSize(QtCore.QSize(163, 0))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_4.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Création initiale de certficat foncier", None, QtGui.QApplication.UnicodeUTF8))
        self.gridGroupBox.setTitle(QtGui.QApplication.translate("Dialog", "Demande", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Type certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetailDmd.setText(QtGui.QApplication.translate("Dialog", "Détail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Numéro demande", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Numéro certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Categorie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalGroupBox.setTitle(QtGui.QApplication.translate("Dialog", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "m2 ou ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Ha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Ca", None, QtGui.QApplication.UnicodeUTF8))
        self.gridGroupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Reconnaissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Délivrance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Inscription dans le registre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Edition (impression)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Opération cause", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Historique", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProprietaire.setText(QtGui.QApplication.translate("Dialog", "Propriétaires", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCharges.setText(QtGui.QApplication.translate("Dialog", "Charges", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRepere.setText(QtGui.QApplication.translate("Dialog", "Repères", None, QtGui.QApplication.UnicodeUTF8))
        self.gridGroupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Localisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Région", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "District", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Commune", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Fokontany", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Hameau", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAide.setText(QtGui.QApplication.translate("Dialog", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHtml.setText(QtGui.QApplication.translate("Dialog", "Exporter Html", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFiscaliser.setText(QtGui.QApplication.translate("Dialog", "Fiscaliser", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Autres Informations", None, QtGui.QApplication.UnicodeUTF8))

