# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditionCF.ui'
#
# Created: Thu Jun 02 13:44:40 2022
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(893, 617)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(520, 10, 361, 341))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 341, 311))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayoutGeom = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutGeom.setMargin(0)
        self.horizontalLayoutGeom.setObjectName(_fromUtf8("horizontalLayoutGeom"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(570, 370, 151, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(520, 400, 361, 201))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(510, 390, 120, 80))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 491, 601))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout_3.addWidget(self.comboBoxFokontany, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.comboBoxRegion = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxRegion.setObjectName(_fromUtf8("comboBoxRegion"))
        self.gridLayout_3.addWidget(self.comboBoxRegion, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.comboBoxDistrict = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxDistrict.setObjectName(_fromUtf8("comboBoxDistrict"))
        self.gridLayout_3.addWidget(self.comboBoxDistrict, 1, 1, 1, 1)
        self.comboBoxHameau = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.gridLayout_3.addWidget(self.comboBoxHameau, 4, 1, 1, 1)
        self.comboBoxCommune = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxCommune.setObjectName(_fromUtf8("comboBoxCommune"))
        self.gridLayout_3.addWidget(self.comboBoxCommune, 2, 1, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.gridLayout_3)
        self.gridLayout_4.addWidget(self.groupBox_2, 4, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBoxConsist = QtGui.QComboBox(self.frame)
        self.comboBoxConsist.setObjectName(_fromUtf8("comboBoxConsist"))
        self.gridLayout.addWidget(self.comboBoxConsist, 3, 1, 1, 1)
        self.lineEditNumCert = QtGui.QLineEdit(self.frame)
        self.lineEditNumCert.setObjectName(_fromUtf8("lineEditNumCert"))
        self.gridLayout.addWidget(self.lineEditNumCert, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxTypeCert = QtGui.QComboBox(self.frame)
        self.comboBoxTypeCert.setObjectName(_fromUtf8("comboBoxTypeCert"))
        self.comboBoxTypeCert.addItem(_fromUtf8(""))
        self.comboBoxTypeCert.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxTypeCert, 0, 1, 1, 1)
        self.btnListeDmd = QtGui.QPushButton(self.frame)
        self.btnListeDmd.setObjectName(_fromUtf8("btnListeDmd"))
        self.gridLayout.addWidget(self.btnListeDmd, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.lineEditEtat = QtGui.QLineEdit(self.frame)
        self.lineEditEtat.setObjectName(_fromUtf8("lineEditEtat"))
        self.gridLayout.addWidget(self.lineEditEtat, 4, 1, 1, 1)
        self.comboBoxNumDemande = QtGui.QComboBox(self.frame)
        self.comboBoxNumDemande.setObjectName(_fromUtf8("comboBoxNumDemande"))
        self.gridLayout.addWidget(self.comboBoxNumDemande, 2, 1, 1, 1)
        self.btnListeConsist = QtGui.QPushButton(self.frame)
        self.btnListeConsist.setObjectName(_fromUtf8("btnListeConsist"))
        self.gridLayout.addWidget(self.btnListeConsist, 3, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnProprietaire = QtGui.QPushButton(self.frame_2)
        self.btnProprietaire.setObjectName(_fromUtf8("btnProprietaire"))
        self.horizontalLayout_3.addWidget(self.btnProprietaire)
        self.btnCharges = QtGui.QPushButton(self.frame_2)
        self.btnCharges.setObjectName(_fromUtf8("btnCharges"))
        self.horizontalLayout_3.addWidget(self.btnCharges)
        self.btnRepere = QtGui.QPushButton(self.frame_2)
        self.btnRepere.setObjectName(_fromUtf8("btnRepere"))
        self.horizontalLayout_3.addWidget(self.btnRepere)
        self.gridLayout_4.addWidget(self.frame_2, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEditSurface = QtGui.QLineEdit(self.frame)
        self.lineEditSurface.setObjectName(_fromUtf8("lineEditSurface"))
        self.horizontalLayout.addWidget(self.lineEditSurface)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEditHa = QtGui.QLineEdit(self.frame)
        self.lineEditHa.setObjectName(_fromUtf8("lineEditHa"))
        self.horizontalLayout.addWidget(self.lineEditHa)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEditA = QtGui.QLineEdit(self.frame)
        self.lineEditA.setObjectName(_fromUtf8("lineEditA"))
        self.horizontalLayout.addWidget(self.lineEditA)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEditCa = QtGui.QLineEdit(self.frame)
        self.lineEditCa.setObjectName(_fromUtf8("lineEditCa"))
        self.horizontalLayout.addWidget(self.lineEditCa)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEditEdition = QtGui.QLineEdit(self.groupBox)
        self.lineEditEdition.setObjectName(_fromUtf8("lineEditEdition"))
        self.gridLayout_2.addWidget(self.lineEditEdition, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 2, 1)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 2, 2, 1)
        self.dateEditReconnaissance = QtGui.QDateEdit(self.groupBox)
        self.dateEditReconnaissance.setCalendarPopup(True)
        self.dateEditReconnaissance.setObjectName(_fromUtf8("dateEditReconnaissance"))
        self.gridLayout_2.addWidget(self.dateEditReconnaissance, 0, 1, 1, 1)
        self.dateEditInscriptionRegistre = QtGui.QDateEdit(self.groupBox)
        self.dateEditInscriptionRegistre.setCalendarPopup(True)
        self.dateEditInscriptionRegistre.setObjectName(_fromUtf8("dateEditInscriptionRegistre"))
        self.gridLayout_2.addWidget(self.dateEditInscriptionRegistre, 1, 1, 1, 1)
        self.dateEditDelivrance = QtGui.QDateEdit(self.groupBox)
        self.dateEditDelivrance.setCalendarPopup(True)
        self.dateEditDelivrance.setObjectName(_fromUtf8("dateEditDelivrance"))
        self.gridLayout_2.addWidget(self.dateEditDelivrance, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAide = QtGui.QPushButton(self.frame)
        self.btnAide.setObjectName(_fromUtf8("btnAide"))
        self.horizontalLayout_2.addWidget(self.btnAide)
        self.btnSuppr = QtGui.QPushButton(self.frame)
        self.btnSuppr.setObjectName(_fromUtf8("btnSuppr"))
        self.horizontalLayout_2.addWidget(self.btnSuppr)
        self.btnEnreg = QtGui.QPushButton(self.frame)
        self.btnEnreg.setObjectName(_fromUtf8("btnEnreg"))
        self.horizontalLayout_2.addWidget(self.btnEnreg)
        self.btnFermer = QtGui.QPushButton(self.frame)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_2.addWidget(self.btnFermer)
        self.checkBox = QtGui.QCheckBox(self.frame)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Edition certificat foncier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Autres informations", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Localisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Commune", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Région", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "District", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Hameau", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Fokontany", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Type certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTypeCert.setItemText(0, QtGui.QApplication.translate("Dialog", "Certificat Foncier", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTypeCert.setItemText(1, QtGui.QApplication.translate("Dialog", "Attestation de reconnaissance", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListeDmd.setText(QtGui.QApplication.translate("Dialog", "Liste", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Numéro demande", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Numéro certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Categorie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListeConsist.setText(QtGui.QApplication.translate("Dialog", "Liste", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProprietaire.setText(QtGui.QApplication.translate("Dialog", "Propriétaires", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCharges.setText(QtGui.QApplication.translate("Dialog", "Charges", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRepere.setText(QtGui.QApplication.translate("Dialog", "Repères", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "m2 ou ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Ha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Ca", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Reconnaissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Délivrance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Inscription dans le registre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Edition (impression)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Opération cause", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Historique", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAide.setText(QtGui.QApplication.translate("Dialog", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSuppr.setText(QtGui.QApplication.translate("Dialog", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnreg.setText(QtGui.QApplication.translate("Dialog", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))

