# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listePersonnesPque.ui'
#
# Created: Tue Jun 12 03:13:56 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(541, 625)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/users/icone/user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxPrenom = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxPrenom.setText(_fromUtf8(""))
        self.checkBoxPrenom.setObjectName(_fromUtf8("checkBoxPrenom"))
        self.gridLayout.addWidget(self.checkBoxPrenom, 1, 0, 1, 1)
        self.checkBoxNom = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxNom.setText(_fromUtf8(""))
        self.checkBoxNom.setObjectName(_fromUtf8("checkBoxNom"))
        self.gridLayout.addWidget(self.checkBoxNom, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.lineEditNom = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.gridLayout.addWidget(self.lineEditNom, 0, 2, 1, 1)
        self.lineEditPrenom = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.gridLayout.addWidget(self.lineEditPrenom, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBoxNomMere = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxNomMere.setText(_fromUtf8(""))
        self.checkBoxNomMere.setObjectName(_fromUtf8("checkBoxNomMere"))
        self.gridLayout_2.addWidget(self.checkBoxNomMere, 1, 0, 1, 1)
        self.checkBoxNomPere = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxNomPere.setText(_fromUtf8(""))
        self.checkBoxNomPere.setObjectName(_fromUtf8("checkBoxNomPere"))
        self.gridLayout_2.addWidget(self.checkBoxNomPere, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.lineEditNomPere = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNomPere.setObjectName(_fromUtf8("lineEditNomPere"))
        self.gridLayout_2.addWidget(self.lineEditNomPere, 0, 2, 1, 1)
        self.lineEditNomMere = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNomMere.setObjectName(_fromUtf8("lineEditNomMere"))
        self.gridLayout_2.addWidget(self.lineEditNomMere, 1, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEditNumActN = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditNumActN.setObjectName(_fromUtf8("lineEditNumActN"))
        self.gridLayout_3.addWidget(self.lineEditNumActN, 1, 2, 1, 4)
        self.lineEditCIN_3 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN_3.setObjectName(_fromUtf8("lineEditCIN_3"))
        self.gridLayout_3.addWidget(self.lineEditCIN_3, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 1, 1, 1)
        self.lineEditCIN_1 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN_1.setObjectName(_fromUtf8("lineEditCIN_1"))
        self.gridLayout_3.addWidget(self.lineEditCIN_1, 0, 3, 1, 1)
        self.radioButtonCIN = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonCIN.setText(_fromUtf8(""))
        self.radioButtonCIN.setObjectName(_fromUtf8("radioButtonCIN"))
        self.gridLayout_3.addWidget(self.radioButtonCIN, 0, 0, 1, 1)
        self.radioButtonNumActN = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonNumActN.setText(_fromUtf8(""))
        self.radioButtonNumActN.setObjectName(_fromUtf8("radioButtonNumActN"))
        self.gridLayout_3.addWidget(self.radioButtonNumActN, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.lineEditCIN = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN.setObjectName(_fromUtf8("lineEditCIN"))
        self.gridLayout_3.addWidget(self.lineEditCIN, 0, 2, 1, 1)
        self.lineEditCIN_2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN_2.setObjectName(_fromUtf8("lineEditCIN_2"))
        self.gridLayout_3.addWidget(self.lineEditCIN_2, 0, 4, 1, 1)
        self.radioButtonRien = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonRien.setText(_fromUtf8(""))
        self.radioButtonRien.setObjectName(_fromUtf8("radioButtonRien"))
        self.gridLayout_3.addWidget(self.radioButtonRien, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAfficherTous = QtGui.QPushButton(Dialog)
        self.btnAfficherTous.setObjectName(_fromUtf8("btnAfficherTous"))
        self.horizontalLayout.addWidget(self.btnAfficherTous)
        self.btnAjouter = QtGui.QPushButton(Dialog)
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.horizontalLayout.addWidget(self.btnAjouter)
        self.btnRechercher = QtGui.QPushButton(Dialog)
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.horizontalLayout.addWidget(self.btnRechercher)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnDebut = QtGui.QPushButton(Dialog)
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.horizontalLayout_4.addWidget(self.btnDebut)
        self.btnPrecedent = QtGui.QPushButton(Dialog)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.horizontalLayout_4.addWidget(self.btnPrecedent)
        self.lineEditNumPage = QtGui.QLineEdit(Dialog)
        self.lineEditNumPage.setEnabled(False)
        self.lineEditNumPage.setObjectName(_fromUtf8("lineEditNumPage"))
        self.horizontalLayout_4.addWidget(self.lineEditNumPage)
        self.comboBoxNumPage = QtGui.QComboBox(Dialog)
        self.comboBoxNumPage.setObjectName(_fromUtf8("comboBoxNumPage"))
        self.horizontalLayout_4.addWidget(self.comboBoxNumPage)
        self.btnSuivant = QtGui.QPushButton(Dialog)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.horizontalLayout_4.addWidget(self.btnSuivant)
        self.btnFin = QtGui.QPushButton(Dialog)
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.horizontalLayout_4.addWidget(self.btnFin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnDetails = QtGui.QPushButton(Dialog)
        self.btnDetails.setObjectName(_fromUtf8("btnDetails"))
        self.horizontalLayout_2.addWidget(self.btnDetails)
        self.btnSelectionner = QtGui.QPushButton(Dialog)
        self.btnSelectionner.setObjectName(_fromUtf8("btnSelectionner"))
        self.horizontalLayout_2.addWidget(self.btnSelectionner)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_2.addWidget(self.btnFermer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Rechercher une personne", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Nom et prénoms", None))
        self.label.setText(_translate("Dialog", "Nom", None))
        self.label_2.setText(_translate("Dialog", "Prénoms", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Filiation", None))
        self.label_3.setText(_translate("Dialog", "Nom du père ", None))
        self.label_4.setText(_translate("Dialog", "Nom de la mère", None))
        self.groupBox_4.setTitle(_translate("Dialog", "N° d\'identification", None))
        self.label_6.setText(_translate("Dialog", "N° Acte de naissance", None))
        self.label_5.setText(_translate("Dialog", "CIN", None))
        self.label_7.setText(_translate("Dialog", "Rien", None))
        self.btnAfficherTous.setText(_translate("Dialog", "Afficher tous", None))
        self.btnAjouter.setText(_translate("Dialog", "Ajouter", None))
        self.btnRechercher.setText(_translate("Dialog", "Rechercher", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nom", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Prenoms", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date de naissance", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Sexe", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Adresse", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Numero CIN", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Numero Acte de naissance", None))
        self.btnDebut.setText(_translate("Dialog", " <<=", None))
        self.btnPrecedent.setText(_translate("Dialog", "<=", None))
        self.btnSuivant.setText(_translate("Dialog", "=>", None))
        self.btnFin.setText(_translate("Dialog", "=>>", None))
        self.btnDetails.setText(_translate("Dialog", "Détails", None))
        self.btnSelectionner.setText(_translate("Dialog", "Selectionner", None))
        self.btnFermer.setText(_translate("Dialog", "Fermer", None))

import icons_rc
