# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListePersonneMorale.ui'
#
# Created: Sun Mar 10 05:45:35 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(552, 390)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/users/icone/user_02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_4 = QtGui.QPushButton(Dialog)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAjouter = QtGui.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_plus_circle_12296.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAjouter.setIcon(icon1)
        self.pushButtonAjouter.setObjectName(_fromUtf8("pushButtonAjouter"))
        self.horizontalLayout.addWidget(self.pushButtonAjouter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnDebut = QtGui.QPushButton(Dialog)
        self.btnDebut.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDebut.setIcon(icon2)
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.horizontalLayout_4.addWidget(self.btnDebut)
        self.btnPrecedent = QtGui.QPushButton(Dialog)
        self.btnPrecedent.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrecedent.setIcon(icon3)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.horizontalLayout_4.addWidget(self.btnPrecedent)
        self.lineEditNumPage = QtGui.QLineEdit(Dialog)
        self.lineEditNumPage.setEnabled(False)
        self.lineEditNumPage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditNumPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditNumPage.setObjectName(_fromUtf8("lineEditNumPage"))
        self.horizontalLayout_4.addWidget(self.lineEditNumPage)
        self.comboBoxNumPage = QtGui.QComboBox(Dialog)
        self.comboBoxNumPage.setObjectName(_fromUtf8("comboBoxNumPage"))
        self.horizontalLayout_4.addWidget(self.comboBoxNumPage)
        self.btnSuivant = QtGui.QPushButton(Dialog)
        self.btnSuivant.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuivant.setIcon(icon4)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.horizontalLayout_4.addWidget(self.btnSuivant)
        self.btnFin = QtGui.QPushButton(Dialog)
        self.btnFin.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFin.setIcon(icon5)
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.horizontalLayout_4.addWidget(self.btnFin)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_5 = QtGui.QPushButton(Dialog)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(Dialog)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButtonAnnuler = QtGui.QPushButton(Dialog)
        self.pushButtonAnnuler.setObjectName(_fromUtf8("pushButtonAnnuler"))
        self.horizontalLayout_2.addWidget(self.pushButtonAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.pushButtonAjouter)
        Dialog.setTabOrder(self.pushButtonAjouter, self.btnDebut)
        Dialog.setTabOrder(self.btnDebut, self.btnPrecedent)
        Dialog.setTabOrder(self.btnPrecedent, self.lineEditNumPage)
        Dialog.setTabOrder(self.lineEditNumPage, self.comboBoxNumPage)
        Dialog.setTabOrder(self.comboBoxNumPage, self.btnSuivant)
        Dialog.setTabOrder(self.btnSuivant, self.btnFin)
        Dialog.setTabOrder(self.btnFin, self.pushButton_6)
        Dialog.setTabOrder(self.pushButton_6, self.pushButtonAnnuler)
        Dialog.setTabOrder(self.pushButtonAnnuler, self.tableWidget)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Liste des personnes morales", None))
        self.groupBox.setTitle(_translate("Dialog", "Rechercher", None))
        self.label_2.setText(_translate("Dialog", "Dénomination", None))
        self.label.setText(_translate("Dialog", "Type", None))
        self.pushButton_4.setText(_translate("Dialog", "Afficher tous", None))
        self.pushButton_2.setText(_translate("Dialog", "Rechercher", None))
        self.pushButtonAjouter.setText(_translate("Dialog", "Ajouter", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Type", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Dénomination", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date de Création", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Siège", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Observation", None))
        self.pushButton_5.setText(_translate("Dialog", "Selectionner", None))
        self.pushButton_6.setText(_translate("Dialog", "Details", None))
        self.pushButtonAnnuler.setText(_translate("Dialog", "Annuler", None))

import icons_rc
