# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Operation.ui'
#
# Created: Thu Dec 14 02:44:02 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(761, 329)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 2, 1, 1)
        self.lineEditDateInscription = QtGui.QLineEdit(self.groupBox)
        self.lineEditDateInscription.setObjectName(_fromUtf8("lineEditDateInscription"))
        self.gridLayout.addWidget(self.lineEditDateInscription, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditCout1 = QtGui.QLineEdit(self.groupBox)
        self.lineEditCout1.setObjectName(_fromUtf8("lineEditCout1"))
        self.gridLayout.addWidget(self.lineEditCout1, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.lineEditTypeOperation = QtGui.QLineEdit(self.groupBox)
        self.lineEditTypeOperation.setObjectName(_fromUtf8("lineEditTypeOperation"))
        self.gridLayout.addWidget(self.lineEditTypeOperation, 0, 1, 1, 1)
        self.lineEditCout2 = QtGui.QLineEdit(self.groupBox)
        self.lineEditCout2.setObjectName(_fromUtf8("lineEditCout2"))
        self.gridLayout.addWidget(self.lineEditCout2, 4, 1, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.groupBox)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout.addWidget(self.dateEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnVoirActe = QtGui.QPushButton(self.groupBox)
        self.btnVoirActe.setObjectName(_fromUtf8("btnVoirActe"))
        self.horizontalLayout_2.addWidget(self.btnVoirActe)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox1 = QtGui.QGroupBox(Dialog)
        self.groupBox1.setMinimumSize(QtCore.QSize(271, 0))
        self.groupBox1.setMaximumSize(QtCore.QSize(271, 16777215))
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textEditCFMere = QtGui.QTextEdit(self.groupBox1)
        self.textEditCFMere.setObjectName(_fromUtf8("textEditCFMere"))
        self.verticalLayout_2.addWidget(self.textEditCFMere)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnDetails_2 = QtGui.QPushButton(self.groupBox1)
        self.btnDetails_2.setObjectName(_fromUtf8("btnDetails_2"))
        self.horizontalLayout_3.addWidget(self.btnDetails_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(271, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(271, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textEditCFFilles = QtGui.QTextEdit(self.groupBox_2)
        self.textEditCFFilles.setObjectName(_fromUtf8("textEditCFFilles"))
        self.verticalLayout_3.addWidget(self.textEditCFFilles)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btnDetails_3 = QtGui.QPushButton(self.groupBox_2)
        self.btnDetails_3.setObjectName(_fromUtf8("btnDetails_3"))
        self.horizontalLayout_4.addWidget(self.btnDetails_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.btnAide = QtGui.QPushButton(Dialog)
        self.btnAide.setObjectName(_fromUtf8("btnAide"))
        self.horizontalLayout.addWidget(self.btnAide)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout.addWidget(self.btnFermer)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Opération", None))
        self.label_7.setText(_translate("Dialog", "Ar", None))
        self.label.setText(_translate("Dialog", "Type opération", None))
        self.label_4.setText(_translate("Dialog", "Coût 1", None))
        self.label_5.setText(_translate("Dialog", "Coût 2", None))
        self.label_3.setText(_translate("Dialog", "Date d\'inscription au registre", None))
        self.label_2.setText(_translate("Dialog", "Date dépot demande", None))
        self.label_6.setText(_translate("Dialog", "Ar", None))
        self.btnVoirActe.setText(_translate("Dialog", "Voir acte", None))
        self.groupBox1.setTitle(_translate("Dialog", "Liste de certificats mères", None))
        self.btnDetails_2.setText(_translate("Dialog", "Details", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Liste de certificats filles", None))
        self.btnDetails_3.setText(_translate("Dialog", "Details", None))
        self.btnAide.setText(_translate("Dialog", "Aide", None))
        self.btnFermer.setText(_translate("Dialog", "Fermer", None))

