# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RechercheCF.ui'
#
# Created: Sun Mar 10 05:38:40 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(652, 568)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/listing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBoxNumDemande = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumDemande.setObjectName(_fromUtf8("checkBoxNumDemande"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxNumDemande)
        self.lineEditNumCF = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumCF.setEnabled(False)
        self.lineEditNumCF.setObjectName(_fromUtf8("lineEditNumCF"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNumCF)
        self.checkBoxNomDemandeur = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNomDemandeur.setObjectName(_fromUtf8("checkBoxNomDemandeur"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxNomDemandeur)
        self.lineEditNomProprietaire = QtGui.QLineEdit(self.groupBox)
        self.lineEditNomProprietaire.setEnabled(False)
        self.lineEditNomProprietaire.setObjectName(_fromUtf8("lineEditNomProprietaire"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNomProprietaire)
        self.checkBoxDateCreation = QtGui.QCheckBox(self.groupBox)
        self.checkBoxDateCreation.setObjectName(_fromUtf8("checkBoxDateCreation"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBoxDateCreation)
        self.checkBoxType = QtGui.QCheckBox(self.groupBox)
        self.checkBoxType.setObjectName(_fromUtf8("checkBoxType"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkBoxType)
        self.comboBoxType = QtGui.QComboBox(self.groupBox)
        self.comboBoxType.setEnabled(False)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxType)
        self.checkBoxFokontany = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFokontany.setObjectName(_fromUtf8("checkBoxFokontany"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.checkBoxFokontany)
        self.comboBoxFokotany = QtGui.QComboBox(self.groupBox)
        self.comboBoxFokotany.setEnabled(False)
        self.comboBoxFokotany.setObjectName(_fromUtf8("comboBoxFokotany"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBoxFokotany)
        self.checkBoxEtat = QtGui.QCheckBox(self.groupBox)
        self.checkBoxEtat.setObjectName(_fromUtf8("checkBoxEtat"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.checkBoxEtat)
        self.comboBoxEtat = QtGui.QComboBox(self.groupBox)
        self.comboBoxEtat.setEnabled(False)
        self.comboBoxEtat.setObjectName(_fromUtf8("comboBoxEtat"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBoxEtat)
        self.dateEditCreation = QtGui.QDateEdit(self.groupBox)
        self.dateEditCreation.setEnabled(False)
        self.dateEditCreation.setCalendarPopup(True)
        self.dateEditCreation.setObjectName(_fromUtf8("dateEditCreation"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEditCreation)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAfficherTous = QtGui.QPushButton(Dialog)
        self.btnAfficherTous.setObjectName(_fromUtf8("btnAfficherTous"))
        self.horizontalLayout.addWidget(self.btnAfficherTous)
        self.btnRechercher = QtGui.QPushButton(Dialog)
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.horizontalLayout.addWidget(self.btnRechercher)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolBtnSelectionSurCarte = QtGui.QToolButton(self.groupBox_2)
        self.toolBtnSelectionSurCarte.setObjectName(_fromUtf8("toolBtnSelectionSurCarte"))
        self.horizontalLayout_2.addWidget(self.toolBtnSelectionSurCarte)
        self.toolBtnSelectionSurCarte_2 = QtGui.QToolButton(self.groupBox_2)
        self.toolBtnSelectionSurCarte_2.setObjectName(_fromUtf8("toolBtnSelectionSurCarte_2"))
        self.horizontalLayout_2.addWidget(self.toolBtnSelectionSurCarte_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(168)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnDebut = QtGui.QPushButton(Dialog)
        self.btnDebut.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDebut.setIcon(icon1)
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.horizontalLayout_4.addWidget(self.btnDebut)
        self.btnPrecedent = QtGui.QPushButton(Dialog)
        self.btnPrecedent.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrecedent.setIcon(icon2)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.horizontalLayout_4.addWidget(self.btnPrecedent)
        self.lineEditNumPage = QtGui.QLineEdit(Dialog)
        self.lineEditNumPage.setEnabled(False)
        self.lineEditNumPage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditNumPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditNumPage.setObjectName(_fromUtf8("lineEditNumPage"))
        self.horizontalLayout_4.addWidget(self.lineEditNumPage)
        self.comboBoxNumPage = QtGui.QComboBox(Dialog)
        self.comboBoxNumPage.setObjectName(_fromUtf8("comboBoxNumPage"))
        self.horizontalLayout_4.addWidget(self.comboBoxNumPage)
        self.btnSuivant = QtGui.QPushButton(Dialog)
        self.btnSuivant.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuivant.setIcon(icon3)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.horizontalLayout_4.addWidget(self.btnSuivant)
        self.btnFin = QtGui.QPushButton(Dialog)
        self.btnFin.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFin.setIcon(icon4)
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.horizontalLayout_4.addWidget(self.btnFin)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.SelBtn = QtGui.QPushButton(Dialog)
        self.SelBtn.setObjectName(_fromUtf8("SelBtn"))
        self.horizontalLayout_3.addWidget(self.SelBtn)
        self.btnDetail = QtGui.QPushButton(Dialog)
        self.btnDetail.setObjectName(_fromUtf8("btnDetail"))
        self.horizontalLayout_3.addWidget(self.btnDetail)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_3.addWidget(self.btnFermer)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Recherche des certificats fonciers", None))
        self.groupBox.setTitle(_translate("Dialog", "Recherche d\'un certificat", None))
        self.checkBoxNumDemande.setText(_translate("Dialog", "Numéro Certificat", None))
        self.checkBoxNomDemandeur.setText(_translate("Dialog", "Nom Propriétaire", None))
        self.checkBoxDateCreation.setText(_translate("Dialog", "Date De Création", None))
        self.checkBoxType.setText(_translate("Dialog", "Type", None))
        self.comboBoxType.setItemText(0, _translate("Dialog", "Certificat foncier", None))
        self.comboBoxType.setItemText(1, _translate("Dialog", "Attestation de reconaissance", None))
        self.checkBoxFokontany.setText(_translate("Dialog", "Fokontany", None))
        self.checkBoxEtat.setText(_translate("Dialog", "Etat", None))
        self.btnAfficherTous.setText(_translate("Dialog", "Afficher tous", None))
        self.btnRechercher.setText(_translate("Dialog", "Rechercher", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Selection sur la carte", None))
        self.toolBtnSelectionSurCarte.setText(_translate("Dialog", "...", None))
        self.toolBtnSelectionSurCarte_2.setText(_translate("Dialog", "...", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "N° Certificat", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "N° demande", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date demande", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Date de reconnaissance", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Cout à la demande", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Liste Demandeur", None))
        self.SelBtn.setText(_translate("Dialog", "Selectionner", None))
        self.btnDetail.setText(_translate("Dialog", "Details", None))
        self.btnFermer.setText(_translate("Dialog", "Fermer", None))

import icons_rc
