# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'servitudePassage.ui'
#
# Created: Sat Feb 17 13:30:50 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(789, 560)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 371, 71))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 51))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxOrigine = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxOrigine.setObjectName(_fromUtf8("comboBoxOrigine"))
        self.comboBoxOrigine.addItem(_fromUtf8(""))
        self.comboBoxOrigine.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxOrigine, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateEditInscription = QtGui.QDateEdit(self.gridLayoutWidget)
        self.dateEditInscription.setCalendarPopup(True)
        self.dateEditInscription.setObjectName(_fromUtf8("dateEditInscription"))
        self.gridLayout.addWidget(self.dateEditInscription, 1, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 371, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 351, 128))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnEnlever = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnEnlever.setObjectName(_fromUtf8("btnEnlever"))
        self.gridLayout_2.addWidget(self.btnEnlever, 2, 2, 1, 1)
        self.lineEditIdentifiant = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditIdentifiant.setObjectName(_fromUtf8("lineEditIdentifiant"))
        self.gridLayout_2.addWidget(self.lineEditIdentifiant, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.btnAjouter = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.gridLayout_2.addWidget(self.btnAjouter, 1, 2, 1, 1)
        self.tableWidgetParcelle = QtGui.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidgetParcelle.setObjectName(_fromUtf8("tableWidgetParcelle"))
        self.tableWidgetParcelle.setColumnCount(1)
        self.tableWidgetParcelle.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParcelle.setHorizontalHeaderItem(0, item)
        self.gridLayout_2.addWidget(self.tableWidgetParcelle, 1, 0, 2, 2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 371, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 351, 128))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnEnlever_1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.btnEnlever_1.setObjectName(_fromUtf8("btnEnlever_1"))
        self.gridLayout_3.addWidget(self.btnEnlever_1, 2, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.btnAjouter_1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.btnAjouter_1.setObjectName(_fromUtf8("btnAjouter_1"))
        self.gridLayout_3.addWidget(self.btnAjouter_1, 1, 2, 1, 1)
        self.tableWidgetBeneficiaire = QtGui.QTableWidget(self.gridLayoutWidget_3)
        self.tableWidgetBeneficiaire.setObjectName(_fromUtf8("tableWidgetBeneficiaire"))
        self.tableWidgetBeneficiaire.setColumnCount(1)
        self.tableWidgetBeneficiaire.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBeneficiaire.setHorizontalHeaderItem(0, item)
        self.gridLayout_3.addWidget(self.tableWidgetBeneficiaire, 1, 0, 2, 2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 430, 371, 71))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 351, 31))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.dateEditLevee = QtGui.QDateEdit(self.gridLayoutWidget_4)
        self.dateEditLevee.setCalendarPopup(True)
        self.dateEditLevee.setObjectName(_fromUtf8("dateEditLevee"))
        self.gridLayout_4.addWidget(self.dateEditLevee, 0, 1, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 510, 321, 31))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnAide = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnAide.setObjectName(_fromUtf8("btnAide"))
        self.gridLayout_5.addWidget(self.btnAide, 0, 0, 1, 1)
        self.btnAnnuler = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))
        self.gridLayout_5.addWidget(self.btnAnnuler, 0, 2, 1, 1)
        self.btnOk = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.gridLayout_5.addWidget(self.btnOk, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_5.addWidget(self.checkBox, 0, 3, 1, 1)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(400, 10, 381, 321))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(420, 360, 191, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_3 = QtGui.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(410, 390, 361, 151))
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Date d\'inscription", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOrigine.setItemText(0, QtGui.QApplication.translate("Dialog", "Par convention", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOrigine.setItemText(1, QtGui.QApplication.translate("Dialog", "Per décision du tribunal", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Origine", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Liste des parcelles grévées", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnlever.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Identifiant", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouter.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Liste des bénéficiaires", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnlever_1.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Identifiant", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouter_1.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Levée de la servitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAide.setText(QtGui.QApplication.translate("Dialog", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAnnuler.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("Dialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Description de la servitude", None, QtGui.QApplication.UnicodeUTF8))

