# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransformationGroupeeDmd.ui'
#
# Created: Fri Sep 29 21:18:16 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1027, 678)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 951, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButtonRechercher = QtGui.QPushButton(self.groupBox)
        self.pushButtonRechercher.setGeometry(QtCore.QRect(560, 150, 353, 23))
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))
        self.dateEditDatedcision = QtGui.QDateEdit(self.groupBox)
        self.dateEditDatedcision.setEnabled(False)
        self.dateEditDatedcision.setGeometry(QtCore.QRect(378, 124, 535, 20))
        self.dateEditDatedcision.setObjectName(_fromUtf8("dateEditDatedcision"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(195, 72, 177, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.checkBoxdateDecision = QtGui.QCheckBox(self.groupBox)
        self.checkBoxdateDecision.setGeometry(QtCore.QRect(13, 127, 176, 13))
        self.checkBoxdateDecision.setText(_fromUtf8(""))
        self.checkBoxdateDecision.setObjectName(_fromUtf8("checkBoxdateDecision"))
        self.lineEditNumeroDemande = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumeroDemande.setEnabled(False)
        self.lineEditNumeroDemande.setGeometry(QtCore.QRect(378, 20, 535, 20))
        self.lineEditNumeroDemande.setObjectName(_fromUtf8("lineEditNumeroDemande"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(195, 46, 177, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(195, 98, 177, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(195, 124, 177, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBoxHameau = QtGui.QComboBox(self.groupBox)
        self.comboBoxHameau.setEnabled(False)
        self.comboBoxHameau.setGeometry(QtCore.QRect(378, 72, 535, 20))
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.checkBoxNumDemande = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumDemande.setGeometry(QtCore.QRect(13, 23, 176, 13))
        self.checkBoxNumDemande.setText(_fromUtf8(""))
        self.checkBoxNumDemande.setObjectName(_fromUtf8("checkBoxNumDemande"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(195, 20, 177, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.checkBoxFkt = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFkt.setGeometry(QtCore.QRect(13, 49, 176, 13))
        self.checkBoxFkt.setText(_fromUtf8(""))
        self.checkBoxFkt.setObjectName(_fromUtf8("checkBoxFkt"))
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBox)
        self.comboBoxFokontany.setEnabled(False)
        self.comboBoxFokontany.setGeometry(QtCore.QRect(378, 46, 535, 20))
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.checkBoxNumdecision = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumdecision.setGeometry(QtCore.QRect(13, 101, 176, 13))
        self.checkBoxNumdecision.setText(_fromUtf8(""))
        self.checkBoxNumdecision.setObjectName(_fromUtf8("checkBoxNumdecision"))
        self.checkBoxHameau = QtGui.QCheckBox(self.groupBox)
        self.checkBoxHameau.setGeometry(QtCore.QRect(13, 75, 176, 13))
        self.checkBoxHameau.setText(_fromUtf8(""))
        self.checkBoxHameau.setObjectName(_fromUtf8("checkBoxHameau"))
        self.lineEditNumdecision = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumdecision.setEnabled(False)
        self.lineEditNumdecision.setGeometry(QtCore.QRect(378, 98, 535, 20))
        self.lineEditNumdecision.setObjectName(_fromUtf8("lineEditNumdecision"))
        self.checkBoxCocherTous = QtGui.QCheckBox(Dialog)
        self.checkBoxCocherTous.setGeometry(QtCore.QRect(10, 200, 825, 17))
        self.checkBoxCocherTous.setObjectName(_fromUtf8("checkBoxCocherTous"))
        self.tableWidgetDemande = QtGui.QTableWidget(Dialog)
        self.tableWidgetDemande.setGeometry(QtCore.QRect(10, 220, 1001, 421))
        self.tableWidgetDemande.setObjectName(_fromUtf8("tableWidgetDemande"))
        self.tableWidgetDemande.setColumnCount(11)
        self.tableWidgetDemande.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(10, item)
        self.progressBarlisting = QtGui.QProgressBar(Dialog)
        self.progressBarlisting.setGeometry(QtCore.QRect(9, 651, 871, 21))
        self.progressBarlisting.setProperty("value", 24)
        self.progressBarlisting.setObjectName(_fromUtf8("progressBarlisting"))
        self.pushButtonTransformer = QtGui.QPushButton(Dialog)
        self.pushButtonTransformer.setGeometry(QtCore.QRect(900, 650, 111, 23))
        self.pushButtonTransformer.setObjectName(_fromUtf8("pushButtonTransformer"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Transformation Groupée Demande en CF", None))
        self.groupBox.setTitle(_translate("Dialog", "RECHERCHE", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Recherher", None))
        self.label_3.setText(_translate("Dialog", "Hameau", None))
        self.label_2.setText(_translate("Dialog", "Fokontany", None))
        self.label_5.setText(_translate("Dialog", "Num Décision", None))
        self.label_4.setText(_translate("Dialog", "Date Décision", None))
        self.label.setText(_translate("Dialog", "N° Demande", None))
        self.checkBoxCocherTous.setText(_translate("Dialog", "Cocher tous", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "iddemande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Num demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Date Demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Num Décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Date Décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Catégorie", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Consistance", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Date RL", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "idFKT", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "CQE", None))
        self.pushButtonTransformer.setText(_translate("Dialog", "TRANSFORMER", None))

