# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreationProjet.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(713, 483)
#        self.centralwidget = QtGui.QWidget(MainWindow)
#        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
#        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 321, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.nomProjet = QtGui.QLabel(self.groupBox)
        self.nomProjet.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.nomProjet.setObjectName(_fromUtf8("nomProjet"))
        self.projet = QtGui.QLineEdit(self.groupBox)
        self.projet.setGeometry(QtCore.QRect(130, 30, 161, 20))
        self.projet.setObjectName(_fromUtf8("projet"))
        self.dateLancement = QtGui.QLabel(self.groupBox)
        self.dateLancement.setGeometry(QtCore.QRect(20, 60, 101, 20))
        self.dateLancement.setObjectName(_fromUtf8("dateLancement"))
        self.date = QtGui.QLineEdit(self.groupBox)
        self.date.setGeometry(QtCore.QRect(130, 60, 161, 20))
        self.date.setObjectName(_fromUtf8("date"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(270, 60, 20, 21))
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../EN COURS/PYTHON/DatePickerDialog.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 159, 341, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.region = QtGui.QLabel(self.groupBox_2)
        self.region.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.region.setObjectName(_fromUtf8("region"))
        self.comboRegion = QtGui.QComboBox(self.groupBox_2)
        self.comboRegion.setGeometry(QtCore.QRect(120, 20, 131, 22))
        self.comboRegion.setObjectName(_fromUtf8("comboRegion"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.ListeRegion = QtGui.QPushButton(self.groupBox_2)
        self.ListeRegion.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.ListeRegion.setObjectName(_fromUtf8("ListeRegion"))
        self.comboDistrict = QtGui.QComboBox(self.groupBox_2)
        self.comboDistrict.setGeometry(QtCore.QRect(120, 60, 131, 22))
        self.comboDistrict.setObjectName(_fromUtf8("comboDistrict"))
        self.ListeDistrict = QtGui.QPushButton(self.groupBox_2)
        self.ListeDistrict.setGeometry(QtCore.QRect(260, 60, 75, 23))
        self.ListeDistrict.setObjectName(_fromUtf8("ListeDistrict"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboCommune = QtGui.QComboBox(self.groupBox_2)
        self.comboCommune.setGeometry(QtCore.QRect(120, 100, 131, 22))
        self.comboCommune.setObjectName(_fromUtf8("comboCommune"))
        self.ListeCommune = QtGui.QPushButton(self.groupBox_2)
        self.ListeCommune.setGeometry(QtCore.QRect(260, 100, 75, 23))
        self.ListeCommune.setObjectName(_fromUtf8("ListeCommune"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 150, 301, 151))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.listeCommune = QtGui.QPlainTextEdit(self.groupBox_3)
        self.listeCommune.setGeometry(QtCore.QRect(30, 50, 171, 71))
        self.listeCommune.setObjectName(_fromUtf8("listeCommune"))
        self.ListeCommunes = QtGui.QLabel(self.groupBox_3)
        self.ListeCommunes.setGeometry(QtCore.QRect(30, 20, 211, 21))
        self.ListeCommunes.setObjectName(_fromUtf8("ListeCommunes"))
        self.ajouterCommune = QtGui.QPushButton(self.groupBox_3)
        self.ajouterCommune.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.ajouterCommune.setObjectName(_fromUtf8("ajouterCommune"))
        self.supprimerCommune = QtGui.QPushButton(self.groupBox_3)
        self.supprimerCommune.setGeometry(QtCore.QRect(210, 90, 75, 23))
        self.supprimerCommune.setObjectName(_fromUtf8("supprimerCommune"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 320, 651, 80))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.TableProjet = QtGui.QTableWidget(self.groupBox_4)
        self.TableProjet.setGeometry(QtCore.QRect(10, 10, 631, 61))
        self.TableProjet.setObjectName(_fromUtf8("TableProjet"))
        self.TableProjet.setColumnCount(3)
        self.TableProjet.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.TableProjet.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TableProjet.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TableProjet.setHorizontalHeaderItem(2, item)
        self.Supprimer = QtGui.QPushButton(self.centralwidget)
        self.Supprimer.setGeometry(QtCore.QRect(30, 410, 111, 23))
        self.Supprimer.setObjectName(_fromUtf8("Supprimer"))
        self.AjouterProjet = QtGui.QPushButton(self.centralwidget)
        self.AjouterProjet.setGeometry(QtCore.QRect(160, 410, 111, 23))
        self.AjouterProjet.setObjectName(_fromUtf8("AjouterProjet"))
        self.ModifierProjet = QtGui.QPushButton(self.centralwidget)
        self.ModifierProjet.setGeometry(QtCore.QRect(290, 410, 111, 23))
        self.ModifierProjet.setObjectName(_fromUtf8("ModifierProjet"))
        self.NouveauProjet = QtGui.QPushButton(self.centralwidget)
        self.NouveauProjet.setGeometry(QtCore.QRect(420, 410, 111, 23))
        self.NouveauProjet.setObjectName(_fromUtf8("NouveauProjet"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Description Projet", None))
        self.nomProjet.setText(_translate("MainWindow", "NOM PROJET :", None))
        self.dateLancement.setText(_translate("MainWindow", "DATE LANCEMENT :", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox", None))
        self.region.setText(_translate("MainWindow", "REGION :", None))
        self.label.setText(_translate("MainWindow", "DISTRICT:", None))
        self.ListeRegion.setText(_translate("MainWindow", "Liste", None))
        self.ListeDistrict.setText(_translate("MainWindow", "Liste", None))
        self.label_2.setText(_translate("MainWindow", "COMMUNE : ", None))
        self.ListeCommune.setText(_translate("MainWindow", "Liste", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox", None))
        self.ListeCommunes.setText(_translate("MainWindow", "Liste des communes dans le projet :", None))
        self.ajouterCommune.setText(_translate("MainWindow", "+ Commune", None))
        self.supprimerCommune.setText(_translate("MainWindow", "- Commune", None))
        item = self.TableProjet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PROJET", None))
        item = self.TableProjet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DATE LANCEMENT", None))
        item = self.TableProjet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CODES COMMUNES", None))
        self.Supprimer.setText(_translate("MainWindow", "Supprimer Projet", None))
        self.AjouterProjet.setText(_translate("MainWindow", "Ajouter  Projet", None))
        self.ModifierProjet.setText(_translate("MainWindow", "Modifier  Projet", None))
        self.NouveauProjet.setText(_translate("MainWindow", "Nouveau  Projet", None))

