# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Journal.ui'
#
# Created: Sat Mar 17 02:16:43 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(514, 488)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.recherche = QtGui.QWidget()
        self.recherche.setObjectName(_fromUtf8("recherche"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.recherche)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.criteres = QtGui.QGroupBox(self.recherche)
        self.criteres.setObjectName(_fromUtf8("criteres"))
        self.gridLayout = QtGui.QGridLayout(self.criteres)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxLogin = QtGui.QCheckBox(self.criteres)
        self.checkBoxLogin.setEnabled(True)
        self.checkBoxLogin.setObjectName(_fromUtf8("checkBoxLogin"))
        self.gridLayout.addWidget(self.checkBoxLogin, 0, 0, 1, 1)
        self.comboBoxLogin = QtGui.QComboBox(self.criteres)
        self.comboBoxLogin.setObjectName(_fromUtf8("comboBoxLogin"))
        self.gridLayout.addWidget(self.comboBoxLogin, 0, 1, 1, 2)
        self.checkBoxDu = QtGui.QCheckBox(self.criteres)
        self.checkBoxDu.setObjectName(_fromUtf8("checkBoxDu"))
        self.gridLayout.addWidget(self.checkBoxDu, 1, 0, 1, 1)
        self.checkBoxAu = QtGui.QCheckBox(self.criteres)
        self.checkBoxAu.setObjectName(_fromUtf8("checkBoxAu"))
        self.gridLayout.addWidget(self.checkBoxAu, 2, 0, 1, 1)
        self.dateEditDu = QtGui.QDateEdit(self.criteres)
        self.dateEditDu.setCalendarPopup(True)
        self.dateEditDu.setObjectName(_fromUtf8("dateEditDu"))
        self.gridLayout.addWidget(self.dateEditDu, 1, 1, 1, 2)
        self.dateEditAu = QtGui.QDateEdit(self.criteres)
        self.dateEditAu.setCalendarPopup(True)
        self.dateEditAu.setObjectName(_fromUtf8("dateEditAu"))
        self.gridLayout.addWidget(self.dateEditAu, 2, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.criteres)
        self.groupBox = QtGui.QGroupBox(self.recherche)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboGroupeAction = QtGui.QComboBox(self.groupBox)
        self.comboGroupeAction.setObjectName(_fromUtf8("comboGroupeAction"))
        self.gridLayout_2.addWidget(self.comboGroupeAction, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboAction = QtGui.QComboBox(self.groupBox)
        self.comboAction.setObjectName(_fromUtf8("comboAction"))
        self.gridLayout_2.addWidget(self.comboAction, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditObjet = QtGui.QLineEdit(self.groupBox)
        self.lineEditObjet.setObjectName(_fromUtf8("lineEditObjet"))
        self.gridLayout_2.addWidget(self.lineEditObjet, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.recherche)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAfficherTous = QtGui.QPushButton(self.groupBox_2)
        self.btnAfficherTous.setObjectName(_fromUtf8("btnAfficherTous"))
        self.horizontalLayout_2.addWidget(self.btnAfficherTous)
        self.chkCritereavancees = QtGui.QCheckBox(self.groupBox_2)
        self.chkCritereavancees.setObjectName(_fromUtf8("chkCritereavancees"))
        self.horizontalLayout_2.addWidget(self.chkCritereavancees)
        self.btnRecherche = QtGui.QPushButton(self.groupBox_2)
        self.btnRecherche.setObjectName(_fromUtf8("btnRecherche"))
        self.horizontalLayout_2.addWidget(self.btnRecherche)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tableWidget = QtGui.QTableWidget(self.recherche)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.recherche, _fromUtf8(""))
        self.information = QtGui.QWidget()
        self.information.setObjectName(_fromUtf8("information"))
        self.formLayout = QtGui.QFormLayout(self.information)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.information)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditLogin = QtGui.QLineEdit(self.information)
        self.lineEditLogin.setEnabled(False)
        self.lineEditLogin.setObjectName(_fromUtf8("lineEditLogin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditLogin)
        self.label_5 = QtGui.QLabel(self.information)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditObjetid = QtGui.QLineEdit(self.information)
        self.lineEditObjetid.setEnabled(False)
        self.lineEditObjetid.setObjectName(_fromUtf8("lineEditObjetid"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditObjetid)
        self.label_6 = QtGui.QLabel(self.information)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.information)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEditHeureAction = QtGui.QLineEdit(self.information)
        self.lineEditHeureAction.setEnabled(False)
        self.lineEditHeureAction.setObjectName(_fromUtf8("lineEditHeureAction"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditHeureAction)
        self.label_8 = QtGui.QLabel(self.information)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEditDescriptionAction = QtGui.QTextEdit(self.information)
        self.lineEditDescriptionAction.setEnabled(False)
        self.lineEditDescriptionAction.setObjectName(_fromUtf8("lineEditDescriptionAction"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEditDescriptionAction)
        self.dateEditAction = QtGui.QDateEdit(self.information)
        self.dateEditAction.setEnabled(False)
        self.dateEditAction.setCalendarPopup(True)
        self.dateEditAction.setObjectName(_fromUtf8("dateEditAction"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.dateEditAction)
        self.tabWidget.addTab(self.information, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnExtraction = QtGui.QPushButton(self.groupBox_3)
        self.btnExtraction.setObjectName(_fromUtf8("btnExtraction"))
        self.horizontalLayout.addWidget(self.btnExtraction)
        self.btnFermer = QtGui.QPushButton(self.groupBox_3)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout.addWidget(self.btnFermer)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.criteres.setTitle(QtGui.QApplication.translate("Dialog", "Criteres", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLogin.setText(QtGui.QApplication.translate("Dialog", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDu.setText(QtGui.QApplication.translate("Dialog", "Du", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAu.setText(QtGui.QApplication.translate("Dialog", "Au", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Avancées", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Groupe action :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Action :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Objet : ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAfficherTous.setText(QtGui.QApplication.translate("Dialog", "Afficher tous ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCritereavancees.setText(QtGui.QApplication.translate("Dialog", "Criteres avancees", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRecherche.setText(QtGui.QApplication.translate("Dialog", "Recherche", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "LOGIN", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "DATE CREATION", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "HEURE ACTION", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "OBJET CIBLE", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "DESCRIPTION", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recherche), QtGui.QApplication.translate("Dialog", "Recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Identifiant :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Identifiant Objet :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Date action :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Heure action :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Description :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.information), QtGui.QApplication.translate("Dialog", "Informations", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExtraction.setText(QtGui.QApplication.translate("Dialog", "Extraction et Suppression", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))

