# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'certificatCreation.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(701, 598)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 240, 451, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.DateReconnaissance = QtGui.QLineEdit(self.groupBox)
        self.DateReconnaissance.setEnabled(False)
        self.DateReconnaissance.setGeometry(QtCore.QRect(190, 20, 171, 20))
        self.DateReconnaissance.setObjectName(_fromUtf8("DateReconnaissance"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(190, 50, 171, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.BtCharge = QtGui.QPushButton(self.groupBox)
        self.BtCharge.setGeometry(QtCore.QRect(190, 80, 75, 23))
        self.BtCharge.setObjectName(_fromUtf8("BtCharge"))
        self.BtRepere = QtGui.QPushButton(self.groupBox)
        self.BtRepere.setGeometry(QtCore.QRect(290, 80, 75, 23))
        self.BtRepere.setObjectName(_fromUtf8("BtRepere"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 451, 211))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.typeCF = QtGui.QComboBox(self.groupBox_2)
        self.typeCF.setGeometry(QtCore.QRect(190, 20, 171, 22))
        self.typeCF.setObjectName(_fromUtf8("typeCF"))
        self.LibConsistance = QtGui.QComboBox(self.groupBox_2)
        self.LibConsistance.setGeometry(QtCore.QRect(190, 140, 171, 22))
        self.LibConsistance.setEditable(True)
        self.LibConsistance.setObjectName(_fromUtf8("LibConsistance"))
        self.NumeroCertificat = QtGui.QLineEdit(self.groupBox_2)
        self.NumeroCertificat.setGeometry(QtCore.QRect(190, 50, 171, 20))
        self.NumeroCertificat.setObjectName(_fromUtf8("NumeroCertificat"))
        self.NumeroDemande = QtGui.QLineEdit(self.groupBox_2)
        self.NumeroDemande.setEnabled(False)
        self.NumeroDemande.setGeometry(QtCore.QRect(190, 80, 171, 20))
        self.NumeroDemande.setObjectName(_fromUtf8("NumeroDemande"))
        self.Demandeur = QtGui.QLineEdit(self.groupBox_2)
        self.Demandeur.setEnabled(False)
        self.Demandeur.setGeometry(QtCore.QRect(190, 110, 171, 20))
        self.Demandeur.setObjectName(_fromUtf8("Demandeur"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 121, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 121, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.splitter_2 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_2.setGeometry(QtCore.QRect(110, 170, 318, 20))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.surfacem2 = QtGui.QLineEdit(self.splitter)
        self.surfacem2.setObjectName(_fromUtf8("surfacem2"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName(_fromUtf8("label"))
        self.SurfaceHa = QtGui.QLineEdit(self.splitter)
        self.SurfaceHa.setObjectName(_fromUtf8("SurfaceHa"))
        self.label_2 = QtGui.QLabel(self.splitter_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 370, 451, 171))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.NomRegion = QtGui.QLineEdit(self.groupBox_3)
        self.NomRegion.setGeometry(QtCore.QRect(190, 20, 171, 20))
        self.NomRegion.setObjectName(_fromUtf8("NomRegion"))
        self.NomDistrict = QtGui.QLineEdit(self.groupBox_3)
        self.NomDistrict.setGeometry(QtCore.QRect(190, 50, 171, 20))
        self.NomDistrict.setObjectName(_fromUtf8("NomDistrict"))
        self.NomCommune = QtGui.QComboBox(self.groupBox_3)
        self.NomCommune.setGeometry(QtCore.QRect(190, 80, 171, 22))
        self.NomCommune.setAcceptDrops(False)
        self.NomCommune.setAutoFillBackground(False)
        self.NomCommune.setEditable(True)
        self.NomCommune.setObjectName(_fromUtf8("NomCommune"))
        self.NomFokontany = QtGui.QComboBox(self.groupBox_3)
        self.NomFokontany.setGeometry(QtCore.QRect(190, 110, 171, 22))
        self.NomFokontany.setAcceptDrops(False)
        self.NomFokontany.setAutoFillBackground(False)
        self.NomFokontany.setEditable(True)
        self.NomFokontany.setObjectName(_fromUtf8("NomFokontany"))
        self.NomHameau = QtGui.QComboBox(self.groupBox_3)
        self.NomHameau.setGeometry(QtCore.QRect(190, 140, 171, 22))
        self.NomHameau.setAcceptDrops(False)
        self.NomHameau.setAutoFillBackground(False)
        self.NomHameau.setEditable(True)
        self.NomHameau.setObjectName(_fromUtf8("NomHameau"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 50, 141, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 80, 141, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 110, 141, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(20, 140, 141, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.BtValider = QtGui.QPushButton(Dialog)
        self.BtValider.setGeometry(QtCore.QRect(220, 560, 75, 23))
        self.BtValider.setObjectName(_fromUtf8("BtValider"))
        self.BtApercu = QtGui.QPushButton(Dialog)
        self.BtApercu.setGeometry(QtCore.QRect(390, 560, 75, 23))
        self.BtApercu.setObjectName(_fromUtf8("BtApercu"))
        self.BtImprimer = QtGui.QPushButton(Dialog)
        self.BtImprimer.setGeometry(QtCore.QRect(300, 560, 75, 23))
        self.BtImprimer.setObjectName(_fromUtf8("BtImprimer"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 20, 211, 211))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 240, 211, 301))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Creation Certificat Foncier", None))
        self.groupBox.setTitle(_translate("Dialog", "Date", None))
        self.BtCharge.setText(_translate("Dialog", "Charge", None))
        self.BtRepere.setText(_translate("Dialog", "Repères", None))
        self.label_9.setText(_translate("Dialog", "Reconnaissance :", None))
        self.label_10.setText(_translate("Dialog", "Inscription dans le registre : ", None))
        self.label_3.setText(_translate("Dialog", "Type certificat :", None))
        self.label_4.setText(_translate("Dialog", "Numero certificat :", None))
        self.label_5.setText(_translate("Dialog", "Numero demande :", None))
        self.label_6.setText(_translate("Dialog", "Proprietaire :", None))
        self.label_7.setText(_translate("Dialog", "Consistance :", None))
        self.label_8.setText(_translate("Dialog", "Surface :", None))
        self.label.setText(_translate("Dialog", "m2    Ou", None))
        self.label_2.setText(_translate("Dialog", "ha", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Localisation", None))
        self.label_11.setText(_translate("Dialog", "Région :", None))
        self.label_12.setText(_translate("Dialog", "District  :", None))
        self.label_13.setText(_translate("Dialog", "Commune :", None))
        self.label_14.setText(_translate("Dialog", "Fokontany : ", None))
        self.label_15.setText(_translate("Dialog", "Hameau :", None))
        self.BtValider.setText(_translate("Dialog", "Valider", None))
        self.BtApercu.setText(_translate("Dialog", "Aperçu", None))
        self.BtImprimer.setText(_translate("Dialog", "Imprimer", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Aperçu parcelle", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Autres informations", None))

