# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filtreInventaire.ui'
#
# Created: Tue Oct 10 07:05:23 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(974, 790)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 9, 951, 301))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(10)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.dateEditInventaire = QtGui.QDateEdit(self.groupBox_3)
        self.dateEditInventaire.setEnabled(False)
        self.dateEditInventaire.setGeometry(QtCore.QRect(130, 110, 731, 20))
        self.dateEditInventaire.setCalendarPopup(True)
        self.dateEditInventaire.setObjectName(_fromUtf8("dateEditInventaire"))
        self.checkBoxDateInventaire = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxDateInventaire.setGeometry(QtCore.QRect(10, 110, 106, 17))
        self.checkBoxDateInventaire.setObjectName(_fromUtf8("checkBoxDateInventaire"))
        self.checkBoxNomOccupant = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxNomOccupant.setGeometry(QtCore.QRect(10, 80, 69, 17))
        self.checkBoxNomOccupant.setObjectName(_fromUtf8("checkBoxNomOccupant"))
        self.checkBoxSujetDemande = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxSujetDemande.setGeometry(QtCore.QRect(10, 20, 110, 17))
        self.checkBoxSujetDemande.setObjectName(_fromUtf8("checkBoxSujetDemande"))
        self.lineEditNomOccupant = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNomOccupant.setEnabled(False)
        self.lineEditNomOccupant.setGeometry(QtCore.QRect(130, 80, 731, 20))
        self.lineEditNomOccupant.setObjectName(_fromUtf8("lineEditNomOccupant"))
        self.checkBoxDateInventaireEntre = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxDateInventaireEntre.setGeometry(QtCore.QRect(10, 140, 106, 17))
        self.checkBoxDateInventaireEntre.setObjectName(_fromUtf8("checkBoxDateInventaireEntre"))
        self.dateEditDebutInvantaire = QtGui.QDateEdit(self.groupBox_3)
        self.dateEditDebutInvantaire.setEnabled(False)
        self.dateEditDebutInvantaire.setGeometry(QtCore.QRect(130, 140, 291, 20))
        self.dateEditDebutInvantaire.setCalendarPopup(True)
        self.dateEditDebutInvantaire.setObjectName(_fromUtf8("dateEditDebutInvantaire"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(460, 140, 21, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.dateEditFinInventaire = QtGui.QDateEdit(self.groupBox_3)
        self.dateEditFinInventaire.setEnabled(False)
        self.dateEditFinInventaire.setGeometry(QtCore.QRect(500, 140, 361, 20))
        self.dateEditFinInventaire.setCalendarPopup(True)
        self.dateEditFinInventaire.setObjectName(_fromUtf8("dateEditFinInventaire"))
        self.checkBoxInventaireFokontany = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxInventaireFokontany.setGeometry(QtCore.QRect(10, 180, 71, 17))
        self.checkBoxInventaireFokontany.setObjectName(_fromUtf8("checkBoxInventaireFokontany"))
        self.checkBoxInventaireHameau = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxInventaireHameau.setGeometry(QtCore.QRect(10, 210, 74, 17))
        self.checkBoxInventaireHameau.setObjectName(_fromUtf8("checkBoxInventaireHameau"))
        self.comboBoxInventaireHameau = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxInventaireHameau.setEnabled(False)
        self.comboBoxInventaireHameau.setGeometry(QtCore.QRect(130, 210, 731, 20))
        self.comboBoxInventaireHameau.setObjectName(_fromUtf8("comboBoxInventaireHameau"))
        self.comboBoxInventaireFonkontany = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxInventaireFonkontany.setEnabled(False)
        self.comboBoxInventaireFonkontany.setGeometry(QtCore.QRect(130, 180, 731, 20))
        self.comboBoxInventaireFonkontany.setObjectName(_fromUtf8("comboBoxInventaireFonkontany"))
        self.btnAfficherTousInventaire = QtGui.QPushButton(self.groupBox_3)
        self.btnAfficherTousInventaire.setGeometry(QtCore.QRect(100, 250, 75, 23))
        self.btnAfficherTousInventaire.setObjectName(_fromUtf8("btnAfficherTousInventaire"))
        self.btnRechercherInventaire = QtGui.QPushButton(self.groupBox_3)
        self.btnRechercherInventaire.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.btnRechercherInventaire.setObjectName(_fromUtf8("btnRechercherInventaire"))
        self.checkBoxCodeParcelle = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxCodeParcelle.setGeometry(QtCore.QRect(10, 50, 111, 17))
        self.checkBoxCodeParcelle.setObjectName(_fromUtf8("checkBoxCodeParcelle"))
        self.lineEditCodeParcelle = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditCodeParcelle.setEnabled(False)
        self.lineEditCodeParcelle.setGeometry(QtCore.QRect(130, 50, 731, 20))
        self.lineEditCodeParcelle.setObjectName(_fromUtf8("lineEditCodeParcelle"))
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 360, 951, 351))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableWidgetInventaire = QtGui.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidgetInventaire.setFrameShape(QtGui.QFrame.Box)
        self.tableWidgetInventaire.setObjectName(_fromUtf8("tableWidgetInventaire"))
        self.tableWidgetInventaire.setColumnCount(8)
        self.tableWidgetInventaire.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInventaire.setHorizontalHeaderItem(7, item)
        self.tableWidgetInventaire.horizontalHeader().setDefaultSectionSize(168)
        self.horizontalLayout_2.addWidget(self.tableWidgetInventaire)
        self.layoutWidget_2 = QtGui.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(630, 720, 321, 31))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonFirst = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonFirst.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFirst.setIcon(icon)
        self.pushButtonFirst.setObjectName(_fromUtf8("pushButtonFirst"))
        self.horizontalLayout_5.addWidget(self.pushButtonFirst)
        self.label_2 = QtGui.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.labelCurrent = QtGui.QLabel(self.layoutWidget_2)
        self.labelCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrent.setObjectName(_fromUtf8("labelCurrent"))
        self.horizontalLayout_5.addWidget(self.labelCurrent)
        self.pushButtonNext = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonNext.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNext.setIcon(icon1)
        self.pushButtonNext.setObjectName(_fromUtf8("pushButtonNext"))
        self.horizontalLayout_5.addWidget(self.pushButtonNext)
        self.pushButtonPrevious = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonPrevious.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPrevious.setIcon(icon2)
        self.pushButtonPrevious.setObjectName(_fromUtf8("pushButtonPrevious"))
        self.horizontalLayout_5.addWidget(self.pushButtonPrevious)
        self.comboBoxPages = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBoxPages.setObjectName(_fromUtf8("comboBoxPages"))
        self.horizontalLayout_5.addWidget(self.comboBoxPages)
        self.pushButtonLast = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonLast.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLast.setIcon(icon3)
        self.pushButtonLast.setObjectName(_fromUtf8("pushButtonLast"))
        self.horizontalLayout_5.addWidget(self.pushButtonLast)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(631, 750, 321, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnInventaireDetail = QtGui.QPushButton(self.layoutWidget)
        self.btnInventaireDetail.setObjectName(_fromUtf8("btnInventaireDetail"))
        self.horizontalLayout_3.addWidget(self.btnInventaireDetail)
        self.btnInventaireFermer = QtGui.QPushButton(self.layoutWidget)
        self.btnInventaireFermer.setEnabled(True)
        self.btnInventaireFermer.setObjectName(_fromUtf8("btnInventaireFermer"))
        self.horizontalLayout_3.addWidget(self.btnInventaireFermer)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 320, 131, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBoxInventaireCheckAll = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxInventaireCheckAll.setObjectName(_fromUtf8("checkBoxInventaireCheckAll"))
        self.horizontalLayout_4.addWidget(self.checkBoxInventaireCheckAll)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 750, 331, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 720, 331, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.dateEditDateTransformationDemande = QtGui.QDateEdit(self.horizontalLayoutWidget_5)
        self.dateEditDateTransformationDemande.setEnabled(True)
        self.dateEditDateTransformationDemande.setCalendarPopup(True)
        self.dateEditDateTransformationDemande.setObjectName(_fromUtf8("dateEditDateTransformationDemande"))
        self.horizontalLayout_10.addWidget(self.dateEditDateTransformationDemande)
        self.pushButtonTransformerDemande = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButtonTransformerDemande.setObjectName(_fromUtf8("pushButtonTransformerDemande"))
        self.horizontalLayout_10.addWidget(self.pushButtonTransformerDemande)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Filtre inventaire", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Tri inventaire", None))
        self.checkBoxDateInventaire.setText(_translate("Dialog", "Date Inventaire", None))
        self.checkBoxNomOccupant.setText(_translate("Dialog", "Occupant", None))
        self.checkBoxSujetDemande.setText(_translate("Dialog", "Sujet de demande", None))
        self.checkBoxDateInventaireEntre.setText(_translate("Dialog", "Entre", None))
        self.label.setText(_translate("Dialog", "et", None))
        self.checkBoxInventaireFokontany.setText(_translate("Dialog", "Fokontany", None))
        self.checkBoxInventaireHameau.setText(_translate("Dialog", "Hameau", None))
        self.btnAfficherTousInventaire.setText(_translate("Dialog", "Afficher tous", None))
        self.btnRechercherInventaire.setText(_translate("Dialog", "Rechercher", None))
        self.checkBoxCodeParcelle.setText(_translate("Dialog", "Code Parcelle", None))
        item = self.tableWidgetInventaire.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Date Inventaire", None))
        item = self.tableWidgetInventaire.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Code Parcelle", None))
        item = self.tableWidgetInventaire.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Nom Occupant", None))
        item = self.tableWidgetInventaire.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "N° demande", None))
        item = self.tableWidgetInventaire.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Date Demande", None))
        item = self.tableWidgetInventaire.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Hameau", None))
        item = self.tableWidgetInventaire.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Fokontany", None))
        self.label_2.setText(_translate("Dialog", "Page : ", None))
        self.labelCurrent.setText(_translate("Dialog", "TextLabel", None))
        self.btnInventaireDetail.setText(_translate("Dialog", "Details", None))
        self.btnInventaireFermer.setText(_translate("Dialog", "Fermer", None))
        self.checkBoxInventaireCheckAll.setText(_translate("Dialog", "Tout Cocher", None))
        self.pushButtonTransformerDemande.setText(_translate("Dialog", "Transformer en demande", None))

import icons_rc
