# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VenteDonationEchange.ui'
#
# Created: Sat Feb 11 18:18:33 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(780, 497)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 381))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 10, 331, 321))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 311, 181))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalGroupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.horizontalGroupBox_3.setGeometry(QtCore.QRect(150, 210, 171, 35))
        self.horizontalGroupBox_3.setObjectName(_fromUtf8("horizontalGroupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setMargin(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.precedent = QtGui.QPushButton(self.horizontalGroupBox_3)
        self.precedent.setObjectName(_fromUtf8("precedent"))
        self.horizontalLayout_3.addWidget(self.precedent)
        self.suivant = QtGui.QPushButton(self.horizontalGroupBox_3)
        self.suivant.setObjectName(_fromUtf8("suivant"))
        self.horizontalLayout_3.addWidget(self.suivant)
        self.formGroupBox = QtGui.QGroupBox(self.groupBox_2)
        self.formGroupBox.setGeometry(QtCore.QRect(10, 250, 311, 62))
        self.formGroupBox.setObjectName(_fromUtf8("formGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(8, 8, 10, 8)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.nDeLaParcelleObjetDuNouveauCFLabel = QtGui.QLabel(self.formGroupBox)
        self.nDeLaParcelleObjetDuNouveauCFLabel.setObjectName(_fromUtf8("nDeLaParcelleObjetDuNouveauCFLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nDeLaParcelleObjetDuNouveauCFLabel)
        self.nDeLaParcelleObjetDuNouveauCFLineEdit = QtGui.QLineEdit(self.formGroupBox)
        self.nDeLaParcelleObjetDuNouveauCFLineEdit.setObjectName(_fromUtf8("nDeLaParcelleObjetDuNouveauCFLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nDeLaParcelleObjetDuNouveauCFLineEdit)
        self.nombreDeParcellesLabel = QtGui.QLabel(self.formGroupBox)
        self.nombreDeParcellesLabel.setObjectName(_fromUtf8("nombreDeParcellesLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.nombreDeParcellesLabel)
        self.nombreDeParcellesLineEdit = QtGui.QLineEdit(self.formGroupBox)
        self.nombreDeParcellesLineEdit.setObjectName(_fromUtf8("nombreDeParcellesLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nombreDeParcellesLineEdit)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 291))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 321, 241))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 731, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.surfaceLineEdit_10 = QtGui.QLineEdit(self.groupBox_3)
        self.surfaceLineEdit_10.setGeometry(QtCore.QRect(240, 50, 133, 20))
        self.surfaceLineEdit_10.setObjectName(_fromUtf8("surfaceLineEdit_10"))
        self.surfaceLineEdit_11 = QtGui.QLineEdit(self.groupBox_3)
        self.surfaceLineEdit_11.setGeometry(QtCore.QRect(380, 50, 133, 20))
        self.surfaceLineEdit_11.setObjectName(_fromUtf8("surfaceLineEdit_11"))
        self.surfaceLineEdit_12 = QtGui.QLineEdit(self.groupBox_3)
        self.surfaceLineEdit_12.setGeometry(QtCore.QRect(520, 50, 141, 20))
        self.surfaceLineEdit_12.setObjectName(_fromUtf8("surfaceLineEdit_12"))
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(100, 70, 131, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.surfaceLineEdit_9 = QtGui.QLineEdit(self.groupBox_3)
        self.surfaceLineEdit_9.setGeometry(QtCore.QRect(99, 47, 133, 20))
        self.surfaceLineEdit_9.setObjectName(_fromUtf8("surfaceLineEdit_9"))
        self.surfaceLabel_3 = QtGui.QLabel(self.groupBox_3)
        self.surfaceLabel_3.setGeometry(QtCore.QRect(11, 47, 37, 16))
        self.surfaceLabel_3.setObjectName(_fromUtf8("surfaceLabel_3"))
        self.numRoCertificatLabel_3 = QtGui.QLabel(self.groupBox_3)
        self.numRoCertificatLabel_3.setGeometry(QtCore.QRect(11, 21, 82, 16))
        self.numRoCertificatLabel_3.setObjectName(_fromUtf8("numRoCertificatLabel_3"))
        self.numRoCertificatLineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.numRoCertificatLineEdit_3.setGeometry(QtCore.QRect(99, 21, 561, 20))
        self.numRoCertificatLineEdit_3.setObjectName(_fromUtf8("numRoCertificatLineEdit_3"))
        self.consistanceLabel_3 = QtGui.QLabel(self.groupBox_3)
        self.consistanceLabel_3.setGeometry(QtCore.QRect(11, 73, 61, 16))
        self.consistanceLabel_3.setObjectName(_fromUtf8("consistanceLabel_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 110, 731, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_12.setGeometry(QtCore.QRect(0, 100, 731, 101))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.surfaceLineEdit_5 = QtGui.QLineEdit(self.groupBox_12)
        self.surfaceLineEdit_5.setGeometry(QtCore.QRect(240, 50, 133, 20))
        self.surfaceLineEdit_5.setObjectName(_fromUtf8("surfaceLineEdit_5"))
        self.surfaceLineEdit_6 = QtGui.QLineEdit(self.groupBox_12)
        self.surfaceLineEdit_6.setGeometry(QtCore.QRect(380, 50, 133, 20))
        self.surfaceLineEdit_6.setObjectName(_fromUtf8("surfaceLineEdit_6"))
        self.surfaceLineEdit_7 = QtGui.QLineEdit(self.groupBox_12)
        self.surfaceLineEdit_7.setGeometry(QtCore.QRect(530, 50, 133, 20))
        self.surfaceLineEdit_7.setObjectName(_fromUtf8("surfaceLineEdit_7"))
        self.numRoCertificatLineEdit_2 = QtGui.QLineEdit(self.groupBox_12)
        self.numRoCertificatLineEdit_2.setGeometry(QtCore.QRect(102, 24, 571, 20))
        self.numRoCertificatLineEdit_2.setObjectName(_fromUtf8("numRoCertificatLineEdit_2"))
        self.numRoCertificatLabel_2 = QtGui.QLabel(self.groupBox_12)
        self.numRoCertificatLabel_2.setGeometry(QtCore.QRect(14, 24, 82, 16))
        self.numRoCertificatLabel_2.setObjectName(_fromUtf8("numRoCertificatLabel_2"))
        self.surfaceLineEdit_8 = QtGui.QLineEdit(self.groupBox_12)
        self.surfaceLineEdit_8.setGeometry(QtCore.QRect(102, 50, 133, 20))
        self.surfaceLineEdit_8.setObjectName(_fromUtf8("surfaceLineEdit_8"))
        self.surfaceLabel_2 = QtGui.QLabel(self.groupBox_12)
        self.surfaceLabel_2.setGeometry(QtCore.QRect(14, 50, 37, 16))
        self.surfaceLabel_2.setObjectName(_fromUtf8("surfaceLabel_2"))
        self.consistanceComboBox_2 = QtGui.QComboBox(self.groupBox_12)
        self.consistanceComboBox_2.setGeometry(QtCore.QRect(102, 76, 69, 20))
        self.consistanceComboBox_2.setObjectName(_fromUtf8("consistanceComboBox_2"))
        self.consistanceLabel_2 = QtGui.QLabel(self.groupBox_12)
        self.consistanceLabel_2.setGeometry(QtCore.QRect(14, 76, 58, 16))
        self.consistanceLabel_2.setObjectName(_fromUtf8("consistanceLabel_2"))
        self.numRoCertificatLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.numRoCertificatLineEdit.setGeometry(QtCore.QRect(102, 24, 561, 20))
        self.numRoCertificatLineEdit.setObjectName(_fromUtf8("numRoCertificatLineEdit"))
        self.numRoCertificatLabel = QtGui.QLabel(self.groupBox_4)
        self.numRoCertificatLabel.setGeometry(QtCore.QRect(14, 24, 82, 16))
        self.numRoCertificatLabel.setObjectName(_fromUtf8("numRoCertificatLabel"))
        self.surfaceLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.surfaceLineEdit.setGeometry(QtCore.QRect(102, 50, 133, 20))
        self.surfaceLineEdit.setObjectName(_fromUtf8("surfaceLineEdit"))
        self.surfaceLabel = QtGui.QLabel(self.groupBox_4)
        self.surfaceLabel.setGeometry(QtCore.QRect(14, 50, 71, 16))
        self.surfaceLabel.setObjectName(_fromUtf8("surfaceLabel"))
        self.consistanceComboBox = QtGui.QComboBox(self.groupBox_4)
        self.consistanceComboBox.setGeometry(QtCore.QRect(102, 76, 69, 20))
        self.consistanceComboBox.setObjectName(_fromUtf8("consistanceComboBox"))
        self.consistanceLabel = QtGui.QLabel(self.groupBox_4)
        self.consistanceLabel.setGeometry(QtCore.QRect(14, 76, 58, 16))
        self.consistanceLabel.setObjectName(_fromUtf8("consistanceLabel"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 220, 731, 131))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.formGroupBox_2 = QtGui.QGroupBox(self.groupBox_11)
        self.formGroupBox_2.setGeometry(QtCore.QRect(10, 20, 711, 109))
        self.formGroupBox_2.setObjectName(_fromUtf8("formGroupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.formGroupBox_2)
        self.formLayout_3.setContentsMargins(6, 1, 15, 10)
        self.formLayout_3.setHorizontalSpacing(10)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.rGionLabel = QtGui.QLabel(self.formGroupBox_2)
        self.rGionLabel.setObjectName(_fromUtf8("rGionLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.rGionLabel)
        self.districtLabel = QtGui.QLabel(self.formGroupBox_2)
        self.districtLabel.setObjectName(_fromUtf8("districtLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.districtLabel)
        self.communeLabel = QtGui.QLabel(self.formGroupBox_2)
        self.communeLabel.setObjectName(_fromUtf8("communeLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.communeLabel)
        self.fokontanyLabel = QtGui.QLabel(self.formGroupBox_2)
        self.fokontanyLabel.setObjectName(_fromUtf8("fokontanyLabel"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.fokontanyLabel)
        self.lineEditRegion = QtGui.QLineEdit(self.formGroupBox_2)
        self.lineEditRegion.setObjectName(_fromUtf8("lineEditRegion"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditRegion)
        self.lineEditDistrict = QtGui.QLineEdit(self.formGroupBox_2)
        self.lineEditDistrict.setObjectName(_fromUtf8("lineEditDistrict"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditDistrict)
        self.lineEditCommune = QtGui.QLineEdit(self.formGroupBox_2)
        self.lineEditCommune.setObjectName(_fromUtf8("lineEditCommune"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditCommune)
        self.comboFokontany = QtGui.QComboBox(self.formGroupBox_2)
        self.comboFokontany.setObjectName(_fromUtf8("comboFokontany"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboFokontany)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 731, 151))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalGroupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.horizontalGroupBox_6.setGeometry(QtCore.QRect(10, 20, 711, 41))
        self.horizontalGroupBox_6.setObjectName(_fromUtf8("horizontalGroupBox_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalGroupBox_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.detail = QtGui.QPushButton(self.horizontalGroupBox_6)
        self.detail.setObjectName(_fromUtf8("detail"))
        self.horizontalLayout_6.addWidget(self.detail)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 711, 73))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 170, 731, 151))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalGroupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.horizontalGroupBox_7.setGeometry(QtCore.QRect(10, 20, 711, 41))
        self.horizontalGroupBox_7.setObjectName(_fromUtf8("horizontalGroupBox_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalGroupBox_7)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.remove = QtGui.QPushButton(self.horizontalGroupBox_7)
        self.remove.setObjectName(_fromUtf8("remove"))
        self.horizontalLayout_7.addWidget(self.remove)
        self.pushButtonAddition = QtGui.QPushButton(self.horizontalGroupBox_7)
        self.pushButtonAddition.setObjectName(_fromUtf8("pushButtonAddition"))
        self.horizontalLayout_7.addWidget(self.pushButtonAddition)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.details = QtGui.QPushButton(self.horizontalGroupBox_7)
        self.details.setObjectName(_fromUtf8("details"))
        self.horizontalLayout_7.addWidget(self.details)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 711, 80))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tableWidget_2 = QtGui.QTableWidget(self.gridLayoutWidget_3)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 731, 151))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalGroupBox_10 = QtGui.QGroupBox(self.groupBox_9)
        self.horizontalGroupBox_10.setGeometry(QtCore.QRect(10, 20, 711, 41))
        self.horizontalGroupBox_10.setObjectName(_fromUtf8("horizontalGroupBox_10"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalGroupBox_10)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.Enlever = QtGui.QPushButton(self.horizontalGroupBox_10)
        self.Enlever.setObjectName(_fromUtf8("Enlever"))
        self.horizontalLayout_10.addWidget(self.Enlever)
        self.Ajouter_LimiteAncien = QtGui.QPushButton(self.horizontalGroupBox_10)
        self.Ajouter_LimiteAncien.setObjectName(_fromUtf8("Ajouter_LimiteAncien"))
        self.horizontalLayout_10.addWidget(self.Ajouter_LimiteAncien)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.lineEditCFRestant = QtGui.QLineEdit(self.horizontalGroupBox_10)
        self.lineEditCFRestant.setObjectName(_fromUtf8("lineEditCFRestant"))
        self.horizontalLayout_10.addWidget(self.lineEditCFRestant)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.groupBox_9)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 70, 711, 73))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tableWidget_5 = QtGui.QTableWidget(self.gridLayoutWidget_6)
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.gridLayout_6.addWidget(self.tableWidget_5, 0, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 170, 731, 161))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalGroupBox_11 = QtGui.QGroupBox(self.groupBox_10)
        self.horizontalGroupBox_11.setGeometry(QtCore.QRect(10, 20, 711, 41))
        self.horizontalGroupBox_11.setObjectName(_fromUtf8("horizontalGroupBox_11"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalGroupBox_11)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.Enlever_2 = QtGui.QPushButton(self.horizontalGroupBox_11)
        self.Enlever_2.setObjectName(_fromUtf8("Enlever_2"))
        self.horizontalLayout_11.addWidget(self.Enlever_2)
        self.Ajouter_LimiteNew = QtGui.QPushButton(self.horizontalGroupBox_11)
        self.Ajouter_LimiteNew.setObjectName(_fromUtf8("Ajouter_LimiteNew"))
        self.horizontalLayout_11.addWidget(self.Ajouter_LimiteNew)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.lineEditNouveauCF = QtGui.QLineEdit(self.horizontalGroupBox_11)
        self.lineEditNouveauCF.setObjectName(_fromUtf8("lineEditNouveauCF"))
        self.horizontalLayout_11.addWidget(self.lineEditNouveauCF)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.groupBox_10)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 70, 711, 81))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tableWidget_6 = QtGui.QTableWidget(self.gridLayoutWidget_7)
        self.tableWidget_6.setObjectName(_fromUtf8("tableWidget_6"))
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.gridLayout_7.addWidget(self.tableWidget_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalGroupBox_4 = QtGui.QGroupBox(Dialog)
        self.horizontalGroupBox_4.setGeometry(QtCore.QRect(10, 400, 761, 41))
        self.horizontalGroupBox_4.setObjectName(_fromUtf8("horizontalGroupBox_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalGroupBox_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.precedent_2 = QtGui.QPushButton(self.horizontalGroupBox_4)
        self.precedent_2.setObjectName(_fromUtf8("precedent_2"))
        self.horizontalLayout_4.addWidget(self.precedent_2)
        self.suivant_2 = QtGui.QPushButton(self.horizontalGroupBox_4)
        self.suivant_2.setObjectName(_fromUtf8("suivant_2"))
        self.horizontalLayout_4.addWidget(self.suivant_2)
        self.horizontalGroupBox_5 = QtGui.QGroupBox(Dialog)
        self.horizontalGroupBox_5.setGeometry(QtCore.QRect(10, 450, 761, 41))
        self.horizontalGroupBox_5.setObjectName(_fromUtf8("horizontalGroupBox_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalGroupBox_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.save = QtGui.QPushButton(self.horizontalGroupBox_5)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_5.addWidget(self.save)
        self.cancel = QtGui.QPushButton(self.horizontalGroupBox_5)
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.horizontalLayout_5.addWidget(self.cancel)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Saisie informations", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Première parcelle morcellé", None))
        self.precedent.setText(_translate("Dialog", "<<", None))
        self.suivant.setText(_translate("Dialog", ">>", None))
        self.nDeLaParcelleObjetDuNouveauCFLabel.setText(_translate("Dialog", "N° de la parcelle objet du nouveau CF", None))
        self.nombreDeParcellesLabel.setText(_translate("Dialog", "Nombre de parcelles", None))
        self.groupBox.setTitle(_translate("Dialog", "CF Mère", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Choix de la parcelle objet du nouveau certificat", None))
        self.groupBox_3.setTitle(_translate("Dialog", "CF qui garde l\'ancien numéro ", None))
        self.surfaceLabel_3.setText(_translate("Dialog", "Surface", None))
        self.numRoCertificatLabel_3.setText(_translate("Dialog", "Numéro certificat", None))
        self.consistanceLabel_3.setText(_translate("Dialog", " Consistance", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Nouveau CF", None))
        self.groupBox_12.setTitle(_translate("Dialog", "CF qui garde l\'ancien numéro ", None))
        self.numRoCertificatLabel_2.setText(_translate("Dialog", "Numéro certificat", None))
        self.surfaceLabel_2.setText(_translate("Dialog", "Surface", None))
        self.consistanceLabel_2.setText(_translate("Dialog", "Consistance", None))
        self.numRoCertificatLabel.setText(_translate("Dialog", "Numéro certificat", None))
        self.surfaceLabel.setText(_translate("Dialog", "N° Demande", None))
        self.consistanceLabel.setText(_translate("Dialog", "Consistance", None))
        self.groupBox_11.setTitle(_translate("Dialog", "Localisation", None))
        self.rGionLabel.setText(_translate("Dialog", "Région", None))
        self.districtLabel.setText(_translate("Dialog", "District", None))
        self.communeLabel.setText(_translate("Dialog", "Commune", None))
        self.fokontanyLabel.setText(_translate("Dialog", "Fokontany", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Nouveau Certificat", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Propriétaires du CF restant", None))
        self.detail.setText(_translate("Dialog", "Détail", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nom", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Prenoms", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Sexe", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "DateNaissance", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Propriétaire du nouveau CF", None))
        self.remove.setText(_translate("Dialog", "Enlever", None))
        self.pushButtonAddition.setText(_translate("Dialog", "Ajouter", None))
        self.details.setText(_translate("Dialog", "Détails", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Noms", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Prenoms", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Sexe", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Date", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Propriétaires", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Limites de la parcelle pour le CF restant", None))
        self.Enlever.setText(_translate("Dialog", "Enlever", None))
        self.Ajouter_LimiteAncien.setText(_translate("Dialog", "Ajouter", None))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Reperes", None))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Position", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Limite de la parcelle du nouveau CF", None))
        self.Enlever_2.setText(_translate("Dialog", "Enlever", None))
        self.Ajouter_LimiteNew.setText(_translate("Dialog", "Ajouter", None))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Reperes", None))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Limites de la parcelle", None))
        self.precedent_2.setText(_translate("Dialog", "Précédent", None))
        self.suivant_2.setText(_translate("Dialog", "Suivant", None))
        self.save.setText(_translate("Dialog", "Enregistrer", None))
        self.cancel.setText(_translate("Dialog", "Annuler", None))

