# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CertificatFoncier.ui'
#
# Created: Mon Jun 11 20:21:04 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(632, 554)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/printer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditTypeCertificat = QtGui.QLineEdit(self.groupBox)
        self.lineEditTypeCertificat.setEnabled(False)
        self.lineEditTypeCertificat.setObjectName(_fromUtf8("lineEditTypeCertificat"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditTypeCertificat)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditNumCertificat = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumCertificat.setEnabled(False)
        self.lineEditNumCertificat.setObjectName(_fromUtf8("lineEditNumCertificat"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNumCertificat)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditNumDemande = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumDemande.setEnabled(False)
        self.lineEditNumDemande.setObjectName(_fromUtf8("lineEditNumDemande"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditNumDemande)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditConsistance = QtGui.QLineEdit(self.groupBox)
        self.lineEditConsistance.setEnabled(False)
        self.lineEditConsistance.setObjectName(_fromUtf8("lineEditConsistance"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditConsistance)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditSurface = QtGui.QLineEdit(self.groupBox)
        self.lineEditSurface.setEnabled(False)
        self.lineEditSurface.setObjectName(_fromUtf8("lineEditSurface"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditSurface)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditEtat = QtGui.QLineEdit(self.groupBox)
        self.lineEditEtat.setEnabled(False)
        self.lineEditEtat.setObjectName(_fromUtf8("lineEditEtat"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditEtat)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEditReconnaissance = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditReconnaissance.setEnabled(False)
        self.lineEditReconnaissance.setObjectName(_fromUtf8("lineEditReconnaissance"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditReconnaissance)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEditInscription = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditInscription.setEnabled(False)
        self.lineEditInscription.setObjectName(_fromUtf8("lineEditInscription"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditInscription)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEditEdition = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditEdition.setEnabled(False)
        self.lineEditEdition.setObjectName(_fromUtf8("lineEditEdition"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditEdition)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEditDelivrance = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditDelivrance.setEnabled(False)
        self.lineEditDelivrance.setObjectName(_fromUtf8("lineEditDelivrance"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditDelivrance)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButtonOperation = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonOperation.setObjectName(_fromUtf8("pushButtonOperation"))
        self.verticalLayout_3.addWidget(self.pushButtonOperation)
        self.pushButtonHistorique = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonHistorique.setObjectName(_fromUtf8("pushButtonHistorique"))
        self.verticalLayout_3.addWidget(self.pushButtonHistorique)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonProprietaires = QtGui.QPushButton(Dialog)
        self.pushButtonProprietaires.setObjectName(_fromUtf8("pushButtonProprietaires"))
        self.horizontalLayout_3.addWidget(self.pushButtonProprietaires)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonCharges = QtGui.QPushButton(Dialog)
        self.pushButtonCharges.setObjectName(_fromUtf8("pushButtonCharges"))
        self.horizontalLayout_3.addWidget(self.pushButtonCharges)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButtonReperes = QtGui.QPushButton(Dialog)
        self.pushButtonReperes.setObjectName(_fromUtf8("pushButtonReperes"))
        self.horizontalLayout_3.addWidget(self.pushButtonReperes)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEditRegion = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditRegion.setEnabled(False)
        self.lineEditRegion.setObjectName(_fromUtf8("lineEditRegion"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditRegion)
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEditDistrict = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditDistrict.setEnabled(False)
        self.lineEditDistrict.setObjectName(_fromUtf8("lineEditDistrict"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditDistrict)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEditCommune = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCommune.setEnabled(False)
        self.lineEditCommune.setObjectName(_fromUtf8("lineEditCommune"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditCommune)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEditFokontany = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditFokontany.setEnabled(False)
        self.lineEditFokontany.setObjectName(_fromUtf8("lineEditFokontany"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditFokontany)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEditHameau = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditHameau.setEnabled(False)
        self.lineEditHameau.setObjectName(_fromUtf8("lineEditHameau"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditHameau)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonImprimer = QtGui.QPushButton(Dialog)
        self.pushButtonImprimer.setIcon(icon)
        self.pushButtonImprimer.setObjectName(_fromUtf8("pushButtonImprimer"))
        self.horizontalLayout_4.addWidget(self.pushButtonImprimer)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButtonAnnuler = QtGui.QPushButton(Dialog)
        self.pushButtonAnnuler.setObjectName(_fromUtf8("pushButtonAnnuler"))
        self.horizontalLayout_4.addWidget(self.pushButtonAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayoutPreview = QtGui.QHBoxLayout()
        self.horizontalLayoutPreview.setObjectName(_fromUtf8("horizontalLayoutPreview"))
        self.verticalLayout_4.addLayout(self.horizontalLayoutPreview)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Edition Certificat Foncier", None))
        self.label.setText(_translate("Dialog", "Type Certificat", None))
        self.label_2.setText(_translate("Dialog", "Numéro Certificat", None))
        self.label_3.setText(_translate("Dialog", "Numéro Demande", None))
        self.label_4.setText(_translate("Dialog", "Consistance", None))
        self.label_5.setText(_translate("Dialog", "Surface", None))
        self.label_6.setText(_translate("Dialog", "Etat", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Date", None))
        self.label_7.setText(_translate("Dialog", "Reconnaissance", None))
        self.label_8.setText(_translate("Dialog", "Inscription dans le registre", None))
        self.label_9.setText(_translate("Dialog", "Edition (impression)", None))
        self.label_10.setText(_translate("Dialog", "Delivrance", None))
        self.pushButtonOperation.setText(_translate("Dialog", "Opération cause", None))
        self.pushButtonHistorique.setText(_translate("Dialog", "Historique", None))
        self.pushButtonProprietaires.setText(_translate("Dialog", "Propriétaires", None))
        self.pushButtonCharges.setText(_translate("Dialog", "Charges", None))
        self.pushButtonReperes.setText(_translate("Dialog", "Repères", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Localisation", None))
        self.label_11.setText(_translate("Dialog", "Région", None))
        self.label_12.setText(_translate("Dialog", "District", None))
        self.label_13.setText(_translate("Dialog", "Commune", None))
        self.label_14.setText(_translate("Dialog", "Fokontany", None))
        self.label_15.setText(_translate("Dialog", "Hameau", None))
        self.pushButtonImprimer.setText(_translate("Dialog", "Imprimer", None))
        self.pushButtonAnnuler.setText(_translate("Dialog", "Fermer", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Aperçu", None))

import icons_rc
