# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attribution_date.ui'
#
# Created: Mon Oct 09 13:51:42 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1053, 816)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBoxDemande = QtGui.QGroupBox(Dialog)
        self.groupBoxDemande.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxDemande.setCheckable(True)
        self.groupBoxDemande.setChecked(False)
        self.groupBoxDemande.setObjectName(_fromUtf8("groupBoxDemande"))
        self.labelDateRL_2 = QtGui.QLabel(self.groupBoxDemande)
        self.labelDateRL_2.setGeometry(QtCore.QRect(8, 40, 71, 20))
        self.labelDateRL_2.setObjectName(_fromUtf8("labelDateRL_2"))
        self.dateDemande = QtGui.QDateEdit(self.groupBoxDemande)
        self.dateDemande.setGeometry(QtCore.QRect(90, 40, 83, 20))
        self.dateDemande.setCalendarPopup(True)
        self.dateDemande.setObjectName(_fromUtf8("dateDemande"))
        self.gridLayout_4.addWidget(self.groupBoxDemande, 1, 0, 1, 1)
        self.pushButtonAttribuerDate = QtGui.QPushButton(Dialog)
        self.pushButtonAttribuerDate.setObjectName(_fromUtf8("pushButtonAttribuerDate"))
        self.gridLayout_4.addWidget(self.pushButtonAttribuerDate, 3, 0, 1, 5)
        self.groupBoxAffichage = QtGui.QGroupBox(Dialog)
        self.groupBoxAffichage.setCheckable(True)
        self.groupBoxAffichage.setChecked(False)
        self.groupBoxAffichage.setObjectName(_fromUtf8("groupBoxAffichage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxAffichage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dateEditFinAffichage = QtGui.QDateEdit(self.groupBoxAffichage)
        self.dateEditFinAffichage.setObjectName(_fromUtf8("dateEditFinAffichage"))
        self.gridLayout_2.addWidget(self.dateEditFinAffichage, 1, 1, 1, 1)
        self.dateEditDebutAffichage = QtGui.QDateEdit(self.groupBoxAffichage)
        self.dateEditDebutAffichage.setObjectName(_fromUtf8("dateEditDebutAffichage"))
        self.gridLayout_2.addWidget(self.dateEditDebutAffichage, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxAffichage)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBoxAffichage)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxAffichage, 1, 2, 1, 1)
        self.groupBoxDecision = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxDecision.sizePolicy().hasHeightForWidth())
        self.groupBoxDecision.setSizePolicy(sizePolicy)
        self.groupBoxDecision.setCheckable(True)
        self.groupBoxDecision.setChecked(False)
        self.groupBoxDecision.setObjectName(_fromUtf8("groupBoxDecision"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxDecision)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBoxDecision)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEditNumeroDecision = QtGui.QLineEdit(self.groupBoxDecision)
        self.lineEditNumeroDecision.setObjectName(_fromUtf8("lineEditNumeroDecision"))
        self.gridLayout_3.addWidget(self.lineEditNumeroDecision, 0, 1, 1, 1)
        self.dateEditDateDecision = QtGui.QDateEdit(self.groupBoxDecision)
        self.dateEditDateDecision.setObjectName(_fromUtf8("dateEditDateDecision"))
        self.gridLayout_3.addWidget(self.dateEditDateDecision, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBoxDecision)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxDecision, 1, 1, 1, 1)
        self.groupBoxdateRL = QtGui.QGroupBox(Dialog)
        self.groupBoxdateRL.setCheckable(True)
        self.groupBoxdateRL.setChecked(False)
        self.groupBoxdateRL.setObjectName(_fromUtf8("groupBoxdateRL"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxdateRL)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelDateRL = QtGui.QLabel(self.groupBoxdateRL)
        self.labelDateRL.setObjectName(_fromUtf8("labelDateRL"))
        self.gridLayout_6.addWidget(self.labelDateRL, 0, 0, 1, 1)
        self.dateEditRL = QtGui.QDateEdit(self.groupBoxdateRL)
        self.dateEditRL.setCalendarPopup(True)
        self.dateEditRL.setObjectName(_fromUtf8("dateEditRL"))
        self.gridLayout_6.addWidget(self.dateEditRL, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxdateRL, 1, 3, 1, 2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.checkBoxHameau = QtGui.QCheckBox(self.groupBox)
        self.checkBoxHameau.setText(_fromUtf8(""))
        self.checkBoxHameau.setObjectName(_fromUtf8("checkBoxHameau"))
        self.gridLayout.addWidget(self.checkBoxHameau, 2, 0, 1, 1)
        self.checkBoxFkt = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFkt.setText(_fromUtf8(""))
        self.checkBoxFkt.setObjectName(_fromUtf8("checkBoxFkt"))
        self.gridLayout.addWidget(self.checkBoxFkt, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBox)
        self.comboBoxFokontany.setEnabled(False)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout.addWidget(self.comboBoxFokontany, 1, 2, 1, 3)
        self.lineEditNumeroDemande = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumeroDemande.setEnabled(False)
        self.lineEditNumeroDemande.setObjectName(_fromUtf8("lineEditNumeroDemande"))
        self.gridLayout.addWidget(self.lineEditNumeroDemande, 0, 2, 1, 3)
        self.comboBoxHameau = QtGui.QComboBox(self.groupBox)
        self.comboBoxHameau.setEnabled(False)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.gridLayout.addWidget(self.comboBoxHameau, 2, 2, 1, 3)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.checkBoxNumDemande = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumDemande.setText(_fromUtf8(""))
        self.checkBoxNumDemande.setObjectName(_fromUtf8("checkBoxNumDemande"))
        self.gridLayout.addWidget(self.checkBoxNumDemande, 0, 0, 1, 1)
        self.pushButtonRechercher = QtGui.QPushButton(self.groupBox)
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))
        self.gridLayout.addWidget(self.pushButtonRechercher, 3, 2, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 5)
        self.groupBoxGestionCRL = QtGui.QGroupBox(Dialog)
        self.groupBoxGestionCRL.setObjectName(_fromUtf8("groupBoxGestionCRL"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxGestionCRL)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.toolButtonAjouter = QtGui.QToolButton(self.groupBoxGestionCRL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAjouter.setIcon(icon1)
        self.toolButtonAjouter.setObjectName(_fromUtf8("toolButtonAjouter"))
        self.gridLayout_5.addWidget(self.toolButtonAjouter, 0, 2, 1, 1)
        self.pushButtonAssigner = QtGui.QPushButton(self.groupBoxGestionCRL)
        self.pushButtonAssigner.setObjectName(_fromUtf8("pushButtonAssigner"))
        self.gridLayout_5.addWidget(self.pushButtonAssigner, 2, 0, 1, 4)
        self.toolButtonSupprimer = QtGui.QToolButton(self.groupBoxGestionCRL)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/moins.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSupprimer.setIcon(icon2)
        self.toolButtonSupprimer.setObjectName(_fromUtf8("toolButtonSupprimer"))
        self.gridLayout_5.addWidget(self.toolButtonSupprimer, 0, 3, 1, 1)
        self.tableWidgetCRL = QtGui.QTableWidget(self.groupBoxGestionCRL)
        self.tableWidgetCRL.setObjectName(_fromUtf8("tableWidgetCRL"))
        self.tableWidgetCRL.setColumnCount(5)
        self.tableWidgetCRL.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.tableWidgetCRL, 1, 0, 1, 4)
        self.gridLayout_4.addWidget(self.groupBoxGestionCRL, 4, 0, 1, 5)
        self.checkBoxCocherTous = QtGui.QCheckBox(Dialog)
        self.checkBoxCocherTous.setObjectName(_fromUtf8("checkBoxCocherTous"))
        self.gridLayout_4.addWidget(self.checkBoxCocherTous, 5, 0, 1, 1)
        self.tableWidgetDemande = QtGui.QTableWidget(Dialog)
        self.tableWidgetDemande.setObjectName(_fromUtf8("tableWidgetDemande"))
        self.tableWidgetDemande.setColumnCount(10)
        self.tableWidgetDemande.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(9, item)
        self.gridLayout_4.addWidget(self.tableWidgetDemande, 6, 0, 1, 5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Attribution date et CRL", None))
        self.groupBoxDemande.setTitle(_translate("Dialog", "Demande", None))
        self.labelDateRL_2.setText(_translate("Dialog", "Date Demande", None))
        self.pushButtonAttribuerDate.setText(_translate("Dialog", "Attribuer Dates", None))
        self.groupBoxAffichage.setTitle(_translate("Dialog", "Affichage", None))
        self.label_4.setText(_translate("Dialog", "Date Début", None))
        self.label_5.setText(_translate("Dialog", "Date Fin", None))
        self.groupBoxDecision.setTitle(_translate("Dialog", "Décision", None))
        self.label_7.setText(_translate("Dialog", "Date", None))
        self.label_6.setText(_translate("Dialog", "Numero", None))
        self.groupBoxdateRL.setTitle(_translate("Dialog", "Reconnaissance Locale", None))
        self.labelDateRL.setText(_translate("Dialog", "Date RL", None))
        self.groupBox.setTitle(_translate("Dialog", "Recherche", None))
        self.label_2.setText(_translate("Dialog", "Fokontany", None))
        self.label_3.setText(_translate("Dialog", "Hameau", None))
        self.label.setText(_translate("Dialog", "N° Demande", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Recherher", None))
        self.groupBoxGestionCRL.setTitle(_translate("Dialog", "Gestion CRL", None))
        self.toolButtonAjouter.setText(_translate("Dialog", "...", None))
        self.pushButtonAssigner.setText(_translate("Dialog", "Assigner", None))
        self.toolButtonSupprimer.setText(_translate("Dialog", "...", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Rôle", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Titulaire", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Supléant", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "idTit", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "idSup", None))
        self.checkBoxCocherTous.setText(_translate("Dialog", "Cocher tous", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "iddemande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Numero demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Numero décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Date décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Date debut affichage", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Date fin affichage", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Date RL", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "CQ", None))

import icons_rc
