# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListePersonne.ui'
#
# Created: Thu Dec 14 00:11:19 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(439, 583)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBoxNom = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxNom.setObjectName(_fromUtf8("checkBoxNom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxNom)
        self.lineEditNom = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditNom.setEnabled(False)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNom)
        self.checkBoxPrenom = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxPrenom.setObjectName(_fromUtf8("checkBoxPrenom"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxPrenom)
        self.lineEditPrenom = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditPrenom.setEnabled(False)
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditPrenom)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.checkBoxNomPere = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxNomPere.setObjectName(_fromUtf8("checkBoxNomPere"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxNomPere)
        self.lineEditNomPere = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNomPere.setEnabled(False)
        self.lineEditNomPere.setObjectName(_fromUtf8("lineEditNomPere"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNomPere)
        self.checkBoxNomMere = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxNomMere.setObjectName(_fromUtf8("checkBoxNomMere"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxNomMere)
        self.lineEditNomMere = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNomMere.setEnabled(False)
        self.lineEditNomMere.setObjectName(_fromUtf8("lineEditNomMere"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNomMere)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButtonCIN = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonCIN.setObjectName(_fromUtf8("radioButtonCIN"))
        self.gridLayout.addWidget(self.radioButtonCIN, 0, 0, 1, 1)
        self.lineEditCIN1 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN1.setEnabled(False)
        self.lineEditCIN1.setMaxLength(3)
        self.lineEditCIN1.setObjectName(_fromUtf8("lineEditCIN1"))
        self.gridLayout.addWidget(self.lineEditCIN1, 0, 1, 1, 1)
        self.lineEditCIN2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN2.setEnabled(False)
        self.lineEditCIN2.setMaxLength(3)
        self.lineEditCIN2.setObjectName(_fromUtf8("lineEditCIN2"))
        self.gridLayout.addWidget(self.lineEditCIN2, 0, 2, 1, 1)
        self.lineEditCIN3 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN3.setEnabled(False)
        self.lineEditCIN3.setMaxLength(3)
        self.lineEditCIN3.setObjectName(_fromUtf8("lineEditCIN3"))
        self.gridLayout.addWidget(self.lineEditCIN3, 0, 3, 1, 1)
        self.lineEditCIN4 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN4.setEnabled(False)
        self.lineEditCIN4.setMaxLength(3)
        self.lineEditCIN4.setObjectName(_fromUtf8("lineEditCIN4"))
        self.gridLayout.addWidget(self.lineEditCIN4, 0, 4, 1, 2)
        self.radioButtonActe = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonActe.setObjectName(_fromUtf8("radioButtonActe"))
        self.gridLayout.addWidget(self.radioButtonActe, 1, 0, 1, 1)
        self.radioButtonRien = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonRien.setChecked(True)
        self.radioButtonRien.setObjectName(_fromUtf8("radioButtonRien"))
        self.gridLayout.addWidget(self.radioButtonRien, 2, 0, 1, 1)
        self.lineEditActe = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditActe.setEnabled(False)
        self.lineEditActe.setObjectName(_fromUtf8("lineEditActe"))
        self.gridLayout.addWidget(self.lineEditActe, 1, 1, 1, 5)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonAfficherTous = QtGui.QPushButton(self.groupBox)
        self.pushButtonAfficherTous.setObjectName(_fromUtf8("pushButtonAfficherTous"))
        self.horizontalLayout.addWidget(self.pushButtonAfficherTous)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAjouter = QtGui.QPushButton(self.groupBox)
        self.pushButtonAjouter.setObjectName(_fromUtf8("pushButtonAjouter"))
        self.horizontalLayout.addWidget(self.pushButtonAjouter)
        self.pushButtonRechercher = QtGui.QPushButton(self.groupBox)
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))
        self.horizontalLayout.addWidget(self.pushButtonRechercher)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonDetails = QtGui.QPushButton(Dialog)
        self.pushButtonDetails.setObjectName(_fromUtf8("pushButtonDetails"))
        self.horizontalLayout_2.addWidget(self.pushButtonDetails)
        self.pushButtonFermer = QtGui.QPushButton(Dialog)
        self.pushButtonFermer.setObjectName(_fromUtf8("pushButtonFermer"))
        self.horizontalLayout_2.addWidget(self.pushButtonFermer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditNom, self.lineEditPrenom)
        Dialog.setTabOrder(self.lineEditPrenom, self.lineEditNomPere)
        Dialog.setTabOrder(self.lineEditNomPere, self.lineEditNomMere)
        Dialog.setTabOrder(self.lineEditNomMere, self.lineEditCIN1)
        Dialog.setTabOrder(self.lineEditCIN1, self.lineEditCIN2)
        Dialog.setTabOrder(self.lineEditCIN2, self.lineEditCIN3)
        Dialog.setTabOrder(self.lineEditCIN3, self.lineEditCIN4)
        Dialog.setTabOrder(self.lineEditCIN4, self.lineEditActe)
        Dialog.setTabOrder(self.lineEditActe, self.pushButtonAfficherTous)
        Dialog.setTabOrder(self.pushButtonAfficherTous, self.pushButtonAjouter)
        Dialog.setTabOrder(self.pushButtonAjouter, self.pushButtonRechercher)
        Dialog.setTabOrder(self.pushButtonRechercher, self.pushButtonFermer)
        Dialog.setTabOrder(self.pushButtonFermer, self.pushButtonDetails)
        Dialog.setTabOrder(self.pushButtonDetails, self.radioButtonCIN)
        Dialog.setTabOrder(self.radioButtonCIN, self.radioButtonActe)
        Dialog.setTabOrder(self.radioButtonActe, self.tableWidget)
        Dialog.setTabOrder(self.tableWidget, self.radioButtonRien)
        Dialog.setTabOrder(self.radioButtonRien, self.checkBoxNomPere)
        Dialog.setTabOrder(self.checkBoxNomPere, self.checkBoxNomMere)
        Dialog.setTabOrder(self.checkBoxNomMere, self.checkBoxNom)
        Dialog.setTabOrder(self.checkBoxNom, self.checkBoxPrenom)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Personne Physique", None))
        self.groupBox.setTitle(_translate("Dialog", "Rechercher Personne", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Nom et Prénom", None))
        self.checkBoxNom.setText(_translate("Dialog", "Nom", None))
        self.checkBoxPrenom.setText(_translate("Dialog", "Prénom", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Filiation", None))
        self.checkBoxNomPere.setText(_translate("Dialog", "Nom du père", None))
        self.checkBoxNomMere.setText(_translate("Dialog", "Nom de la mère", None))
        self.groupBox_4.setTitle(_translate("Dialog", "N° Identification", None))
        self.radioButtonCIN.setText(_translate("Dialog", "CIN", None))
        self.radioButtonActe.setText(_translate("Dialog", "N ° Acte de naissance", None))
        self.radioButtonRien.setText(_translate("Dialog", "Rien", None))
        self.pushButtonAfficherTous.setText(_translate("Dialog", "Afficher tous", None))
        self.pushButtonAjouter.setText(_translate("Dialog", "Ajouter", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Rechercher", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "N°Proprietaire", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nom", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Prenom", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Nom pere", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Nom mere", None))
        self.pushButtonDetails.setText(_translate("Dialog", "Details", None))
        self.pushButtonFermer.setText(_translate("Dialog", "Fermer", None))

