# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proprio-back.ui'
#
# Created: Sat Jul 28 01:53:48 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(645, 446)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 631, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalGroupBox = QtGui.QGroupBox(self.groupBox)
        self.horizontalGroupBox.setGeometry(QtCore.QRect(10, 20, 611, 41))
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setContentsMargins(8, 6, 6, 6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.detailsAncien = QtGui.QPushButton(self.horizontalGroupBox)
        self.detailsAncien.setObjectName(_fromUtf8("detailsAncien"))
        self.horizontalLayout.addWidget(self.detailsAncien)
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 70, 611, 111))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 631, 181))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalGroupBox_2 = QtGui.QGroupBox(self.groupBox_2)
        self.horizontalGroupBox_2.setGeometry(QtCore.QRect(10, 20, 611, 41))
        self.horizontalGroupBox_2.setObjectName(_fromUtf8("horizontalGroupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.delete_2 = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.delete_2.setObjectName(_fromUtf8("delete_2"))
        self.horizontalLayout_2.addWidget(self.delete_2)
        self.add = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.add.setObjectName(_fromUtf8("add"))
        self.horizontalLayout_2.addWidget(self.add)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.DetailNouveau = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.DetailNouveau.setObjectName(_fromUtf8("DetailNouveau"))
        self.horizontalLayout_2.addWidget(self.DetailNouveau)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 611, 101))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget_2 = QtGui.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.horizontalGroupBox_3 = QtGui.QGroupBox(Dialog)
        self.horizontalGroupBox_3.setGeometry(QtCore.QRect(10, 400, 631, 41))
        self.horizontalGroupBox_3.setObjectName(_fromUtf8("horizontalGroupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_3.setMargin(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.help = QtGui.QPushButton(self.horizontalGroupBox_3)
        self.help.setObjectName(_fromUtf8("help"))
        self.horizontalLayout_3.addWidget(self.help)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.save = QtGui.QPushButton(self.horizontalGroupBox_3)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_3.addWidget(self.save)
        self.cancel = QtGui.QPushButton(self.horizontalGroupBox_3)
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.horizontalLayout_3.addWidget(self.cancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Propriétaires", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Anciens proriétaires", None, QtGui.QApplication.UnicodeUTF8))
        self.detailsAncien.setText(QtGui.QApplication.translate("Dialog", "Details", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Personne physique", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "N° Certificat", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Nom ", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Prénom", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Nouveau(x) propriétaires", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_2.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.DetailNouveau.setText(QtGui.QApplication.translate("Dialog", "Details", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Type de proprietaire", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "N° Certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.help.setText(QtGui.QApplication.translate("Dialog", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("Dialog", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))

