# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DemandeDetails.ui'
#
# Created: Tue May 14 04:00:39 2024
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DemandeDetailsForm(object):
    def setupUi(self, DemandeDetailsForm):
        DemandeDetailsForm.setObjectName(_fromUtf8("DemandeDetailsForm"))
        DemandeDetailsForm.resize(1057, 670)
        self.gridLayout_4 = QtGui.QGridLayout(DemandeDetailsForm)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalGroupBox_2 = QtGui.QGroupBox(DemandeDetailsForm)
        self.horizontalGroupBox_2.setObjectName(_fromUtf8("horizontalGroupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setContentsMargins(16, 8, 8, 8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.numeroDemandeLineEdit1 = QtGui.QLineEdit(self.horizontalGroupBox_2)
        self.numeroDemandeLineEdit1.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numeroDemandeLineEdit1.setFont(font)
        self.numeroDemandeLineEdit1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numeroDemandeLineEdit1.setObjectName(_fromUtf8("numeroDemandeLineEdit1"))
        self.horizontalLayout_3.addWidget(self.numeroDemandeLineEdit1)
        self.label_4 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.numeroDemandeLineEdit2 = QtGui.QLineEdit(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numeroDemandeLineEdit2.setFont(font)
        self.numeroDemandeLineEdit2.setObjectName(_fromUtf8("numeroDemandeLineEdit2"))
        self.horizontalLayout_3.addWidget(self.numeroDemandeLineEdit2)
        self.gridLayout_4.addWidget(self.horizontalGroupBox_2, 0, 0, 1, 1)
        self.formGroupBox = QtGui.QGroupBox(DemandeDetailsForm)
        self.formGroupBox.setObjectName(_fromUtf8("formGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.formGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.coutLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coutLabel.setFont(font)
        self.coutLabel.setObjectName(_fromUtf8("coutLabel"))
        self.gridLayout.addWidget(self.coutLabel, 3, 5, 1, 1)
        self.lineEditConsistances = QtGui.QLineEdit(self.formGroupBox)
        self.lineEditConsistances.setObjectName(_fromUtf8("lineEditConsistances"))
        self.gridLayout.addWidget(self.lineEditConsistances, 3, 4, 1, 1)
        self.coutLineEdit = QtGui.QLineEdit(self.formGroupBox)
        self.coutLineEdit.setObjectName(_fromUtf8("coutLineEdit"))
        self.gridLayout.addWidget(self.coutLineEdit, 3, 6, 1, 1)
        self.lineEditCodeParcelle = QtGui.QLineEdit(self.formGroupBox)
        self.lineEditCodeParcelle.setObjectName(_fromUtf8("lineEditCodeParcelle"))
        self.gridLayout.addWidget(self.lineEditCodeParcelle, 0, 2, 1, 5)
        self.label_6 = QtGui.QLabel(self.formGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        self.dateDemandeLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateDemandeLabel.setFont(font)
        self.dateDemandeLabel.setObjectName(_fromUtf8("dateDemandeLabel"))
        self.gridLayout.addWidget(self.dateDemandeLabel, 1, 0, 1, 2)
        self.dateDemandeDateEdit = QtGui.QDateEdit(self.formGroupBox)
        self.dateDemandeDateEdit.setCalendarPopup(True)
        self.dateDemandeDateEdit.setObjectName(_fromUtf8("dateDemandeDateEdit"))
        self.gridLayout.addWidget(self.dateDemandeDateEdit, 1, 2, 1, 4)
        self.consistanceLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consistanceLabel.setFont(font)
        self.consistanceLabel.setObjectName(_fromUtf8("consistanceLabel"))
        self.gridLayout.addWidget(self.consistanceLabel, 3, 0, 1, 1)
        self.consistanceComboBox = QtGui.QComboBox(self.formGroupBox)
        self.consistanceComboBox.setObjectName(_fromUtf8("consistanceComboBox"))
        self.gridLayout.addWidget(self.consistanceComboBox, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 2, 1, 1)
        self.groupBoxDates = QtGui.QGroupBox(self.formGroupBox)
        self.groupBoxDates.setCheckable(True)
        self.groupBoxDates.setObjectName(_fromUtf8("groupBoxDates"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBoxDates)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.checkBoxFinAffichage = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxFinAffichage.setText(_fromUtf8(""))
        self.checkBoxFinAffichage.setObjectName(_fromUtf8("checkBoxFinAffichage"))
        self.gridLayout_7.addWidget(self.checkBoxFinAffichage, 5, 0, 1, 1)
        self.dateEditDebutAffichage = QtGui.QDateEdit(self.groupBoxDates)
        self.dateEditDebutAffichage.setCalendarPopup(True)
        self.dateEditDebutAffichage.setObjectName(_fromUtf8("dateEditDebutAffichage"))
        self.gridLayout_7.addWidget(self.dateEditDebutAffichage, 4, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBoxDates)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBoxDates)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 5, 1, 1, 1)
        self.checkBoxDebutAffichage = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxDebutAffichage.setText(_fromUtf8(""))
        self.checkBoxDebutAffichage.setObjectName(_fromUtf8("checkBoxDebutAffichage"))
        self.gridLayout_7.addWidget(self.checkBoxDebutAffichage, 4, 0, 1, 1)
        self.checkBoxDateReconnaissance = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxDateReconnaissance.setText(_fromUtf8(""))
        self.checkBoxDateReconnaissance.setObjectName(_fromUtf8("checkBoxDateReconnaissance"))
        self.gridLayout_7.addWidget(self.checkBoxDateReconnaissance, 1, 0, 1, 1)
        self.dateDCisionLabel = QtGui.QLabel(self.groupBoxDates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateDCisionLabel.setFont(font)
        self.dateDCisionLabel.setObjectName(_fromUtf8("dateDCisionLabel"))
        self.gridLayout_7.addWidget(self.dateDCisionLabel, 0, 1, 1, 1)
        self.dateDecision = QtGui.QDateEdit(self.groupBoxDates)
        self.dateDecision.setCalendarPopup(True)
        self.dateDecision.setObjectName(_fromUtf8("dateDecision"))
        self.gridLayout_7.addWidget(self.dateDecision, 0, 2, 1, 1)
        self.dateReconnaissanceDateEdit = QtGui.QDateEdit(self.groupBoxDates)
        self.dateReconnaissanceDateEdit.setCalendarPopup(True)
        self.dateReconnaissanceDateEdit.setObjectName(_fromUtf8("dateReconnaissanceDateEdit"))
        self.gridLayout_7.addWidget(self.dateReconnaissanceDateEdit, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBoxDates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 3, 1, 1, 1)
        self.lineEditNumDecision = QtGui.QLineEdit(self.groupBoxDates)
        self.lineEditNumDecision.setObjectName(_fromUtf8("lineEditNumDecision"))
        self.gridLayout_7.addWidget(self.lineEditNumDecision, 3, 2, 1, 1)
        self.checkBoxNumDecision = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxNumDecision.setText(_fromUtf8(""))
        self.checkBoxNumDecision.setObjectName(_fromUtf8("checkBoxNumDecision"))
        self.gridLayout_7.addWidget(self.checkBoxNumDecision, 3, 0, 1, 1)
        self.checkBoxDateDecision = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxDateDecision.setText(_fromUtf8(""))
        self.checkBoxDateDecision.setObjectName(_fromUtf8("checkBoxDateDecision"))
        self.gridLayout_7.addWidget(self.checkBoxDateDecision, 0, 0, 1, 1)
        self.dateReconnaissanceLabel = QtGui.QLabel(self.groupBoxDates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateReconnaissanceLabel.setFont(font)
        self.dateReconnaissanceLabel.setObjectName(_fromUtf8("dateReconnaissanceLabel"))
        self.gridLayout_7.addWidget(self.dateReconnaissanceLabel, 1, 1, 1, 1)
        self.dateEditFinAffichage = QtGui.QDateEdit(self.groupBoxDates)
        self.dateEditFinAffichage.setCalendarPopup(True)
        self.dateEditFinAffichage.setObjectName(_fromUtf8("dateEditFinAffichage"))
        self.gridLayout_7.addWidget(self.dateEditFinAffichage, 5, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBoxDates, 2, 0, 1, 6)
        self.gridLayout_4.addWidget(self.formGroupBox, 1, 0, 1, 1)
        self.verticalGroupBox = QtGui.QGroupBox(DemandeDetailsForm)
        self.verticalGroupBox.setObjectName(_fromUtf8("verticalGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidgetOppositionDemande = QtGui.QTabWidget(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidgetOppositionDemande.setFont(font)
        self.tabWidgetOppositionDemande.setObjectName(_fromUtf8("tabWidgetOppositionDemande"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableDemande = QtGui.QTableWidget(self.tab_2)
        self.tableDemande.setEnabled(True)
        self.tableDemande.setObjectName(_fromUtf8("tableDemande"))
        self.tableDemande.setColumnCount(6)
        self.tableDemande.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(5, item)
        self.gridLayout_5.addWidget(self.tableDemande, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comboBoxPrincipale = QtGui.QComboBox(self.tab_2)
        self.comboBoxPrincipale.setObjectName(_fromUtf8("comboBoxPrincipale"))
        self.gridLayout_3.addWidget(self.comboBoxPrincipale, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.tabWidgetOppositionDemande.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableVoisins = QtGui.QTableWidget(self.tab)
        self.tableVoisins.setGeometry(QtCore.QRect(10, 0, 321, 141))
        self.tableVoisins.setObjectName(_fromUtf8("tableVoisins"))
        self.tableVoisins.setColumnCount(3)
        self.tableVoisins.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableVoisins.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableVoisins.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableVoisins.setHorizontalHeaderItem(2, item)
        self.tabWidgetOppositionDemande.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tableWidgetOppositions = QtGui.QTableWidget(self.tab_3)
        self.tableWidgetOppositions.setGeometry(QtCore.QRect(0, 10, 331, 131))
        self.tableWidgetOppositions.setObjectName(_fromUtf8("tableWidgetOppositions"))
        self.tableWidgetOppositions.setColumnCount(5)
        self.tableWidgetOppositions.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOppositions.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOppositions.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOppositions.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOppositions.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOppositions.setHorizontalHeaderItem(4, item)
        self.tabWidgetOppositionDemande.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidgetOppositionDemande)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.addBtn = QtGui.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icone/user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtn.setIcon(icon)
        self.addBtn.setObjectName(_fromUtf8("addBtn"))
        self.horizontalLayout_4.addWidget(self.addBtn)
        self.updateBtn = QtGui.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updateBtn.setFont(font)
        self.updateBtn.setObjectName(_fromUtf8("updateBtn"))
        self.horizontalLayout_4.addWidget(self.updateBtn)
        self.delBtn = QtGui.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../icone/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delBtn.setIcon(icon1)
        self.delBtn.setObjectName(_fromUtf8("delBtn"))
        self.horizontalLayout_4.addWidget(self.delBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addWidget(self.verticalGroupBox, 2, 0, 2, 1)
        self.formGroupBox1 = QtGui.QGroupBox(DemandeDetailsForm)
        self.formGroupBox1.setObjectName(_fromUtf8("formGroupBox1"))
        self.formLayout = QtGui.QFormLayout(self.formGroupBox1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.numeroGrilleLabel = QtGui.QLabel(self.formGroupBox1)
        self.numeroGrilleLabel.setObjectName(_fromUtf8("numeroGrilleLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.numeroGrilleLabel)
        self.numeroGrilleLineEdit = QtGui.QLineEdit(self.formGroupBox1)
        self.numeroGrilleLineEdit.setObjectName(_fromUtf8("numeroGrilleLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.numeroGrilleLineEdit)
        self.numeroDemandeSurPLOFPapierLabel = QtGui.QLabel(self.formGroupBox1)
        self.numeroDemandeSurPLOFPapierLabel.setObjectName(_fromUtf8("numeroDemandeSurPLOFPapierLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.numeroDemandeSurPLOFPapierLabel)
        self.numdmdsurplof = QtGui.QLineEdit(self.formGroupBox1)
        self.numdmdsurplof.setObjectName(_fromUtf8("numdmdsurplof"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.numdmdsurplof)
        self.gridLayout_4.addWidget(self.formGroupBox1, 2, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(DemandeDetailsForm)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textEditOrigine = QtGui.QTextEdit(self.groupBox)
        self.textEditOrigine.setObjectName(_fromUtf8("textEditOrigine"))
        self.gridLayout_6.addWidget(self.textEditOrigine, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 1, 1, 1)
        self.lineEditDureeMiseEnValeur = QtGui.QLineEdit(self.groupBox)
        self.lineEditDureeMiseEnValeur.setObjectName(_fromUtf8("lineEditDureeMiseEnValeur"))
        self.gridLayout_6.addWidget(self.lineEditDureeMiseEnValeur, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 1, 1, 1)
        self.verticalGroupBox1 = QtGui.QGroupBox(self.groupBox)
        self.verticalGroupBox1.setObjectName(_fromUtf8("verticalGroupBox1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_2.setMargin(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Reglement = QtGui.QPushButton(self.verticalGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Reglement.setFont(font)
        self.Reglement.setObjectName(_fromUtf8("Reglement"))
        self.verticalLayout_2.addWidget(self.Reglement)
        self.gridLayout_6.addWidget(self.verticalGroupBox1, 2, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 3, 1, 2, 1)
        self.formGroupBox_2 = QtGui.QGroupBox(DemandeDetailsForm)
        self.formGroupBox_2.setObjectName(_fromUtf8("formGroupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.formGroupBox_2)
        self.gridLayout_2.setContentsMargins(16, 8, 8, 8)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.districtLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.districtLabel.setFont(font)
        self.districtLabel.setObjectName(_fromUtf8("districtLabel"))
        self.gridLayout_2.addWidget(self.districtLabel, 0, 2, 1, 1)
        self.horizontalGroupBox = QtGui.QGroupBox(self.formGroupBox_2)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setMargin(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.BtnCreate = QtGui.QPushButton(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnCreate.setFont(font)
        self.BtnCreate.setObjectName(_fromUtf8("BtnCreate"))
        self.horizontalLayout.addWidget(self.BtnCreate)
        self.BtnCancel = QtGui.QPushButton(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnCancel.setFont(font)
        self.BtnCancel.setObjectName(_fromUtf8("BtnCancel"))
        self.horizontalLayout.addWidget(self.BtnCancel)
        self.gridLayout_2.addWidget(self.horizontalGroupBox, 5, 0, 1, 4)
        self.communeLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.communeLabel.setFont(font)
        self.communeLabel.setObjectName(_fromUtf8("communeLabel"))
        self.gridLayout_2.addWidget(self.communeLabel, 0, 4, 1, 1)
        self.districtLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.districtLineEdit.setObjectName(_fromUtf8("districtLineEdit"))
        self.gridLayout_2.addWidget(self.districtLineEdit, 0, 3, 1, 1)
        self.regionLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.regionLabel.setFont(font)
        self.regionLabel.setObjectName(_fromUtf8("regionLabel"))
        self.gridLayout_2.addWidget(self.regionLabel, 0, 0, 1, 1)
        self.regionLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.regionLineEdit.setObjectName(_fromUtf8("regionLineEdit"))
        self.gridLayout_2.addWidget(self.regionLineEdit, 0, 1, 1, 1)
        self.communeLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.communeLineEdit.setObjectName(_fromUtf8("communeLineEdit"))
        self.gridLayout_2.addWidget(self.communeLineEdit, 0, 5, 1, 1)
        self.fokontanyLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fokontanyLabel.setFont(font)
        self.fokontanyLabel.setObjectName(_fromUtf8("fokontanyLabel"))
        self.gridLayout_2.addWidget(self.fokontanyLabel, 2, 0, 1, 1)
        self.fokontanyComboBox = QtGui.QComboBox(self.formGroupBox_2)
        self.fokontanyComboBox.setObjectName(_fromUtf8("fokontanyComboBox"))
        self.gridLayout_2.addWidget(self.fokontanyComboBox, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.formGroupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)
        self.HameauComboBox = QtGui.QComboBox(self.formGroupBox_2)
        self.HameauComboBox.setObjectName(_fromUtf8("HameauComboBox"))
        self.gridLayout_2.addWidget(self.HameauComboBox, 2, 3, 1, 1)
        self.toolButtonHameau = QtGui.QToolButton(self.formGroupBox_2)
        self.toolButtonHameau.setObjectName(_fromUtf8("toolButtonHameau"))
        self.gridLayout_2.addWidget(self.toolButtonHameau, 2, 4, 1, 1)
        self.gridLayout_4.addWidget(self.formGroupBox_2, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 1, 2, 1)

        self.retranslateUi(DemandeDetailsForm)
        self.tabWidgetOppositionDemande.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DemandeDetailsForm)

    def retranslateUi(self, DemandeDetailsForm):
        DemandeDetailsForm.setWindowTitle(_translate("DemandeDetailsForm", "Saisie informations demande", None))
        self.label_3.setText(_translate("DemandeDetailsForm", "Numero Demande :           ", None))
        self.label_4.setText(_translate("DemandeDetailsForm", "-F-", None))
        self.coutLabel.setText(_translate("DemandeDetailsForm", "Cout", None))
        self.label_6.setText(_translate("DemandeDetailsForm", "Code parcelle", None))
        self.dateDemandeLabel.setText(_translate("DemandeDetailsForm", "Date Demande", None))
        self.consistanceLabel.setText(_translate("DemandeDetailsForm", "Categorie", None))
        self.label.setText(_translate("DemandeDetailsForm", "Consistance", None))
        self.groupBoxDates.setTitle(_translate("DemandeDetailsForm", "Remplir toutes les dates", None))
        self.label_9.setText(_translate("DemandeDetailsForm", "Date Début Affichage", None))
        self.label_11.setText(_translate("DemandeDetailsForm", "Date Fin Affichage", None))
        self.dateDCisionLabel.setText(_translate("DemandeDetailsForm", "Date Decision", None))
        self.label_2.setText(_translate("DemandeDetailsForm", "Num Decision", None))
        self.dateReconnaissanceLabel.setText(_translate("DemandeDetailsForm", "Date Reconnaissance", None))
        item = self.tableDemande.horizontalHeaderItem(0)
        item.setText(_translate("DemandeDetailsForm", "Nom", None))
        item = self.tableDemande.horizontalHeaderItem(1)
        item.setText(_translate("DemandeDetailsForm", "Prenom", None))
        item = self.tableDemande.horizontalHeaderItem(2)
        item.setText(_translate("DemandeDetailsForm", "Date Naissance", None))
        item = self.tableDemande.horizontalHeaderItem(3)
        item.setText(_translate("DemandeDetailsForm", "CIN", None))
        item = self.tableDemande.horizontalHeaderItem(4)
        item.setText(_translate("DemandeDetailsForm", "Sexe", None))
        item = self.tableDemande.horizontalHeaderItem(5)
        item.setText(_translate("DemandeDetailsForm", "ID", None))
        self.label_7.setText(_translate("DemandeDetailsForm", "Principale", None))
        self.tabWidgetOppositionDemande.setTabText(self.tabWidgetOppositionDemande.indexOf(self.tab_2), _translate("DemandeDetailsForm", "Demandeurs", None))
        item = self.tableVoisins.horizontalHeaderItem(0)
        item.setText(_translate("DemandeDetailsForm", "Repère", None))
        item = self.tableVoisins.horizontalHeaderItem(1)
        item.setText(_translate("DemandeDetailsForm", "Description", None))
        item = self.tableVoisins.horizontalHeaderItem(2)
        item.setText(_translate("DemandeDetailsForm", "IdRepere", None))
        self.tabWidgetOppositionDemande.setTabText(self.tabWidgetOppositionDemande.indexOf(self.tab), _translate("DemandeDetailsForm", "Voisins", None))
        item = self.tableWidgetOppositions.horizontalHeaderItem(0)
        item.setText(_translate("DemandeDetailsForm", "description", None))
        item = self.tableWidgetOppositions.horizontalHeaderItem(1)
        item.setText(_translate("DemandeDetailsForm", "type", None))
        item = self.tableWidgetOppositions.horizontalHeaderItem(2)
        item.setText(_translate("DemandeDetailsForm", "date demande", None))
        item = self.tableWidgetOppositions.horizontalHeaderItem(3)
        item.setText(_translate("DemandeDetailsForm", "date opposition", None))
        item = self.tableWidgetOppositions.horizontalHeaderItem(4)
        item.setText(_translate("DemandeDetailsForm", "id", None))
        self.tabWidgetOppositionDemande.setTabText(self.tabWidgetOppositionDemande.indexOf(self.tab_3), _translate("DemandeDetailsForm", "Oppositions", None))
        self.addBtn.setText(_translate("DemandeDetailsForm", "Nouveau", None))
        self.updateBtn.setText(_translate("DemandeDetailsForm", "Modifier", None))
        self.delBtn.setText(_translate("DemandeDetailsForm", "Supprimer", None))
        self.numeroGrilleLabel.setText(_translate("DemandeDetailsForm", "Numero grille", None))
        self.numeroDemandeSurPLOFPapierLabel.setText(_translate("DemandeDetailsForm", "Numero Demande sur PLOF papier", None))
        self.groupBox.setTitle(_translate("DemandeDetailsForm", "Mise en valeur", None))
        self.label_5.setText(_translate("DemandeDetailsForm", "Durée occupation (ans):", None))
        self.label_8.setText(_translate("DemandeDetailsForm", "Origine:", None))
        self.Reglement.setText(_translate("DemandeDetailsForm", "Regler Opposition", None))
        self.districtLabel.setText(_translate("DemandeDetailsForm", "District", None))
        self.BtnCreate.setText(_translate("DemandeDetailsForm", "Enregistrer", None))
        self.BtnCancel.setText(_translate("DemandeDetailsForm", "Annuler", None))
        self.communeLabel.setText(_translate("DemandeDetailsForm", "Commune", None))
        self.regionLabel.setText(_translate("DemandeDetailsForm", "Region", None))
        self.fokontanyLabel.setText(_translate("DemandeDetailsForm", "Fokontany", None))
        self.label_10.setText(_translate("DemandeDetailsForm", "Hameau", None))
        self.toolButtonHameau.setText(_translate("DemandeDetailsForm", "...", None))

