# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Historique.ui'
#
# Created: Mon Jun 11 23:48:50 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(582, 343)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalGroupBox = QtGui.QGroupBox(Dialog)
        self.verticalGroupBox.setMinimumSize(QtCore.QSize(186, 0))
        self.verticalGroupBox.setMaximumSize(QtCore.QSize(186, 16777215))
        self.verticalGroupBox.setObjectName(_fromUtf8("verticalGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.verticalGroupBox)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout.addWidget(self.verticalGroupBox)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setMinimumSize(QtCore.QSize(182, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(182, 16777215))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(161)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.tableWidget_2 = QtGui.QTableWidget(Dialog)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(182, 0))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(11)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(179)
        self.horizontalLayout.addWidget(self.tableWidget_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonAide = QtGui.QPushButton(Dialog)
        self.pushButtonAide.setObjectName(_fromUtf8("pushButtonAide"))
        self.horizontalLayout_2.addWidget(self.pushButtonAide)
        self.pushButtonDetails = QtGui.QPushButton(Dialog)
        self.pushButtonDetails.setObjectName(_fromUtf8("pushButtonDetails"))
        self.horizontalLayout_2.addWidget(self.pushButtonDetails)
        self.pushButtonFermer = QtGui.QPushButton(Dialog)
        self.pushButtonFermer.setObjectName(_fromUtf8("pushButtonFermer"))
        self.horizontalLayout_2.addWidget(self.pushButtonFermer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Historique d\'un certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalGroupBox.setTitle(QtGui.QApplication.translate("Dialog", "Liste Des Certificats", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("Dialog", "Certificat", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Type de l\'opération", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "N° certificat", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "N° demande", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Type certificat", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Date de création", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "Date d\'édition", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog", "Date de délivrance", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog", "Mémo", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog", "Région", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog", "District", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("Dialog", "Commune", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("Dialog", "Hameau", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAide.setText(QtGui.QApplication.translate("Dialog", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDetails.setText(QtGui.QApplication.translate("Dialog", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))

