# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MarquagePaiementImpot.ui'
#
# Created: Mon Dec 18 11:22:09 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(980, 579)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxContribuable = QtGui.QCheckBox(self.groupBox)
        self.checkBoxContribuable.setObjectName(_fromUtf8("checkBoxContribuable"))
        self.gridLayout.addWidget(self.checkBoxContribuable, 0, 0, 1, 1)
        self.lineEditContribuable = QtGui.QLineEdit(self.groupBox)
        self.lineEditContribuable.setObjectName(_fromUtf8("lineEditContribuable"))
        self.gridLayout.addWidget(self.lineEditContribuable, 0, 1, 1, 3)
        self.checkBoxPaiement = QtGui.QCheckBox(self.groupBox)
        self.checkBoxPaiement.setObjectName(_fromUtf8("checkBoxPaiement"))
        self.gridLayout.addWidget(self.checkBoxPaiement, 1, 0, 1, 1)
        self.btnVoir = QtGui.QPushButton(self.groupBox)
        self.btnVoir.setObjectName(_fromUtf8("btnVoir"))
        self.gridLayout.addWidget(self.btnVoir, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.comboBoxEtatPayement = QtGui.QComboBox(self.groupBox)
        self.comboBoxEtatPayement.setEditable(True)
        self.comboBoxEtatPayement.setObjectName(_fromUtf8("comboBoxEtatPayement"))
        self.comboBoxEtatPayement.addItem(_fromUtf8(""))
        self.comboBoxEtatPayement.addItem(_fromUtf8(""))
        self.comboBoxEtatPayement.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxEtatPayement, 1, 1, 2, 1)
        self.btnRechercher = QtGui.QPushButton(self.groupBox)
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.gridLayout.addWidget(self.btnRechercher, 2, 4, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.groupBox)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout.addWidget(self.dateEdit, 1, 3, 2, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBoxMarquagePaiement = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxMarquagePaiement.setEditable(True)
        self.comboBoxMarquagePaiement.setObjectName(_fromUtf8("comboBoxMarquagePaiement"))
        self.comboBoxMarquagePaiement.addItem(_fromUtf8(""))
        self.comboBoxMarquagePaiement.addItem(_fromUtf8(""))
        self.comboBoxMarquagePaiement.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxMarquagePaiement, 0, 1, 1, 1)
        self.btnModifier = QtGui.QPushButton(self.groupBox_2)
        self.btnModifier.setObjectName(_fromUtf8("btnModifier"))
        self.gridLayout_2.addWidget(self.btnModifier, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnVoir2 = QtGui.QPushButton(self.groupBox_3)
        self.btnVoir2.setObjectName(_fromUtf8("btnVoir2"))
        self.gridLayout_3.addWidget(self.btnVoir2, 0, 0, 1, 2)
        self.tableWidget = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 6)
        self.btnDebut = QtGui.QPushButton(self.groupBox_3)
        self.btnDebut.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDebut.setIcon(icon)
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.gridLayout_3.addWidget(self.btnDebut, 2, 0, 1, 1)
        self.btnFin = QtGui.QPushButton(self.groupBox_3)
        self.btnFin.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFin.setIcon(icon1)
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.gridLayout_3.addWidget(self.btnFin, 2, 5, 1, 1)
        self.btnPrecedent = QtGui.QPushButton(self.groupBox_3)
        self.btnPrecedent.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrecedent.setIcon(icon2)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.gridLayout_3.addWidget(self.btnPrecedent, 2, 1, 1, 1)
        self.comboBoxListePage = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxListePage.setEditable(True)
        self.comboBoxListePage.setObjectName(_fromUtf8("comboBoxListePage"))
        self.gridLayout_3.addWidget(self.comboBoxListePage, 2, 3, 1, 1)
        self.lineEditNumPage = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNumPage.setEnabled(False)
        self.lineEditNumPage.setObjectName(_fromUtf8("lineEditNumPage"))
        self.gridLayout_3.addWidget(self.lineEditNumPage, 2, 2, 1, 1)
        self.btnSuivant = QtGui.QPushButton(self.groupBox_3)
        self.btnSuivant.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuivant.setIcon(icon3)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.gridLayout_3.addWidget(self.btnSuivant, 2, 4, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_4.addWidget(self.pushButton_10, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Marquage de paiement d\'impôt", None))
        self.groupBox.setTitle(_translate("Dialog", "Rechercher", None))
        self.checkBoxContribuable.setText(_translate("Dialog", "Contribuable :", None))
        self.checkBoxPaiement.setText(_translate("Dialog", "Payement :", None))
        self.btnVoir.setText(_translate("Dialog", "Voir", None))
        self.label.setText(_translate("Dialog", "Année :", None))
        self.comboBoxEtatPayement.setItemText(0, _translate("Dialog", "Non Payé", None))
        self.comboBoxEtatPayement.setItemText(1, _translate("Dialog", "Payé en partie", None))
        self.comboBoxEtatPayement.setItemText(2, _translate("Dialog", "Payé", None))
        self.btnRechercher.setText(_translate("Dialog", "Rechercher", None))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "yyyy", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Marquage", None))
        self.label_2.setText(_translate("Dialog", "Etat de paiement : ", None))
        self.comboBoxMarquagePaiement.setItemText(0, _translate("Dialog", "Non payé", None))
        self.comboBoxMarquagePaiement.setItemText(1, _translate("Dialog", "Payé en partie", None))
        self.comboBoxMarquagePaiement.setItemText(2, _translate("Dialog", "Payé", None))
        self.btnModifier.setText(_translate("Dialog", "Modifier", None))
        self.btnVoir2.setText(_translate("Dialog", "Voir", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nom et prenoms", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "CIN", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Etat", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Hetra (Ar)", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Fokontany", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Hameau", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Adresse", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "ID", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "annee", None))
        self.pushButton_10.setText(_translate("Dialog", "Fermer", None))

import icons_rc
