# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DetailsDemande.ui'
#
# Created: Fri May 11 16:36:00 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreationDemande(object):
    def setupUi(self, CreationDemande):
        CreationDemande.setObjectName(_fromUtf8("CreationDemande"))
        CreationDemande.resize(580, 409)
        self.formGroupBox = QtGui.QGroupBox(CreationDemande)
        self.formGroupBox.setGeometry(QtCore.QRect(20, 10, 281, 144))
        self.formGroupBox.setObjectName(_fromUtf8("formGroupBox"))
        self.label = QtGui.QLabel(self.formGroupBox)
        self.label.setGeometry(QtCore.QRect(8, 10, 85, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.dateDemandeLabel = QtGui.QLabel(self.formGroupBox)
        self.dateDemandeLabel.setGeometry(QtCore.QRect(8, 36, 70, 16))
        self.dateDemandeLabel.setObjectName(_fromUtf8("dateDemandeLabel"))

        self.dateDemandeLineEdit = QtGui.QDateEdit(self.formGroupBox)
        self.dateDemandeLineEdit.setGeometry(QtCore.QRect(129, 36, 129, 20))
        self.dateDemandeLineEdit.setEnabled(True)
        self.dateDemandeLineEdit.setCalendarPopup(True)
        self.dateDemandeLineEdit.setObjectName(_fromUtf8("dateDemandeLineEdit"))

        self.dateDeReconnaissanceLabel = QtGui.QLabel(self.formGroupBox)
        self.dateDeReconnaissanceLabel.setGeometry(QtCore.QRect(8, 62, 115, 16))
        self.dateDeReconnaissanceLabel.setObjectName(_fromUtf8("dateDeReconnaissanceLabel"))

        self.dateDeReconnaissanceLineEdit = QtGui.QDateEdit(self.formGroupBox)
        self.dateDeReconnaissanceLineEdit.setGeometry(QtCore.QRect(129, 62, 129, 20))
        self.dateDeReconnaissanceLineEdit.setEnabled(True)
        self.dateDeReconnaissanceLineEdit.setCalendarPopup(True)
        self.dateDeReconnaissanceLineEdit.setObjectName(_fromUtf8("dateDeReconnaissanceLineEdit"))

        self.consistanceLabel = QtGui.QLabel(self.formGroupBox)
        self.consistanceLabel.setGeometry(QtCore.QRect(8, 88, 58, 16))
        self.consistanceLabel.setObjectName(_fromUtf8("consistanceLabel"))
        self.consistanceComboBox = QtGui.QComboBox(self.formGroupBox)
        self.consistanceComboBox.setGeometry(QtCore.QRect(129, 88, 131, 20))
        self.consistanceComboBox.setObjectName(_fromUtf8("consistanceComboBox"))
        self.coutLabel = QtGui.QLabel(self.formGroupBox)
        self.coutLabel.setGeometry(QtCore.QRect(8, 114, 23, 16))
        self.coutLabel.setObjectName(_fromUtf8("coutLabel"))
        self.coutLineEdit = QtGui.QLineEdit(self.formGroupBox)
        self.coutLineEdit.setGeometry(QtCore.QRect(129, 114, 131, 20))
        self.coutLineEdit.setObjectName(_fromUtf8("coutLineEdit"))
        self.lineEditDemande = QtGui.QLineEdit(self.formGroupBox)
        self.lineEditDemande.setGeometry(QtCore.QRect(130, 10, 131, 20))
        self.lineEditDemande.setObjectName(_fromUtf8("lineEditDemande"))
        self.formGroupBox_2 = QtGui.QGroupBox(CreationDemande)
        self.formGroupBox_2.setGeometry(QtCore.QRect(20, 220, 281, 121))
        self.formGroupBox_2.setObjectName(_fromUtf8("formGroupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formGroupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(7, 9, 15, -1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.regionLabel = QtGui.QLabel(self.formGroupBox_2)
        self.regionLabel.setObjectName(_fromUtf8("regionLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.regionLabel)
        self.lineEditRegion = QtGui.QLineEdit(self.formGroupBox_2)
        self.lineEditRegion.setObjectName(_fromUtf8("lineEditRegion"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditRegion)
        self.districtLabel = QtGui.QLabel(self.formGroupBox_2)
        self.districtLabel.setObjectName(_fromUtf8("districtLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.districtLabel)
        self.lineEditDistrict = QtGui.QLineEdit(self.formGroupBox_2)
        self.lineEditDistrict.setObjectName(_fromUtf8("lineEditDistrict"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditDistrict)
        self.communeLabel = QtGui.QLabel(self.formGroupBox_2)
        self.communeLabel.setObjectName(_fromUtf8("communeLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.communeLabel)
        self.communeComboBox = QtGui.QLineEdit(self.formGroupBox_2)
        self.communeComboBox.setObjectName(_fromUtf8("communeComboBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.communeComboBox)
        self.fokontanyLabel = QtGui.QLabel(self.formGroupBox_2)
        self.fokontanyLabel.setObjectName(_fromUtf8("fokontanyLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.fokontanyLabel)
        self.fokontanyComboBox = QtGui.QComboBox(self.formGroupBox_2)
        self.fokontanyComboBox.setObjectName(_fromUtf8("fokontanyComboBox"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.fokontanyComboBox)
        self.horizontalGroupBox_2 = QtGui.QGroupBox(CreationDemande)
        self.horizontalGroupBox_2.setGeometry(QtCore.QRect(20, 350, 281, 51))
        self.horizontalGroupBox_2.setObjectName(_fromUtf8("horizontalGroupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_4 = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.horizontalLayoutWidget = QtGui.QWidget(CreationDemande)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(310, 10, 261, 391))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalGroupBox_21 = QtGui.QGroupBox(CreationDemande)
        self.horizontalGroupBox_21.setGeometry(QtCore.QRect(20, 160, 281, 51))
        self.horizontalGroupBox_21.setObjectName(_fromUtf8("horizontalGroupBox_21"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox_21)
        self.horizontalLayout.setMargin(8)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.horizontalGroupBox_21)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.horizontalGroupBox_21)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_6 = QtGui.QPushButton(self.horizontalGroupBox_21)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout.addWidget(self.pushButton_6)

        self.retranslateUi(CreationDemande)
        QtCore.QMetaObject.connectSlotsByName(CreationDemande)

    def retranslateUi(self, CreationDemande):
        CreationDemande.setWindowTitle(QtGui.QApplication.translate("CreationDemande", "Demande certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CreationDemande", "Numero Demande", None, QtGui.QApplication.UnicodeUTF8))
        self.dateDemandeLabel.setText(QtGui.QApplication.translate("CreationDemande", "Date demande", None, QtGui.QApplication.UnicodeUTF8))
        self.dateDeReconnaissanceLabel.setText(QtGui.QApplication.translate("CreationDemande", "Date de reconnaissance", None, QtGui.QApplication.UnicodeUTF8))
        self.consistanceLabel.setText(QtGui.QApplication.translate("CreationDemande", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.coutLabel.setText(QtGui.QApplication.translate("CreationDemande", "Cout", None, QtGui.QApplication.UnicodeUTF8))
        self.regionLabel.setText(QtGui.QApplication.translate("CreationDemande", "Region", None, QtGui.QApplication.UnicodeUTF8))
        self.districtLabel.setText(QtGui.QApplication.translate("CreationDemande", "District", None, QtGui.QApplication.UnicodeUTF8))
        self.communeLabel.setText(QtGui.QApplication.translate("CreationDemande", "Commune", None, QtGui.QApplication.UnicodeUTF8))
        self.fokontanyLabel.setText(QtGui.QApplication.translate("CreationDemande", "Fokontany", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("CreationDemande", "Creer demande", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("CreationDemande", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("CreationDemande", "Rejeter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("CreationDemande", "Oppositions", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("CreationDemande", "Demandeurs", None, QtGui.QApplication.UnicodeUTF8))

