# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\FIPLOF-010820222\trunk\Demande\RechercheDemande.ui'
#
# Created: Fri Aug 05 12:32:00 2022
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(647, 518)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/listing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxNomDemandeur = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxNomDemandeur.setFont(font)
        self.checkBoxNomDemandeur.setObjectName(_fromUtf8("checkBoxNomDemandeur"))
        self.gridLayout.addWidget(self.checkBoxNomDemandeur, 1, 0, 1, 1)
        self.checkBoxDateDemande = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxDateDemande.setFont(font)
        self.checkBoxDateDemande.setObjectName(_fromUtf8("checkBoxDateDemande"))
        self.gridLayout.addWidget(self.checkBoxDateDemande, 2, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 3, 0, 1, 1)
        self.lineEditNomDemandeur = QtGui.QLineEdit(self.groupBox)
        self.lineEditNomDemandeur.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditNomDemandeur.setFont(font)
        self.lineEditNomDemandeur.setObjectName(_fromUtf8("lineEditNomDemandeur"))
        self.gridLayout.addWidget(self.lineEditNomDemandeur, 1, 1, 1, 1)
        self.auDateEdit = QtGui.QDateEdit(self.groupBox)
        self.auDateEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auDateEdit.setFont(font)
        self.auDateEdit.setCalendarPopup(True)
        self.auDateEdit.setObjectName(_fromUtf8("auDateEdit"))
        self.gridLayout.addWidget(self.auDateEdit, 3, 1, 1, 1)
        self.checkBoxNumeroDemande = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxNumeroDemande.setFont(font)
        self.checkBoxNumeroDemande.setObjectName(_fromUtf8("checkBoxNumeroDemande"))
        self.gridLayout.addWidget(self.checkBoxNumeroDemande, 0, 0, 1, 1)
        self.lineEditNumeroDemande = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumeroDemande.setEnabled(False)
        self.lineEditNumeroDemande.setObjectName(_fromUtf8("lineEditNumeroDemande"))
        self.gridLayout.addWidget(self.lineEditNumeroDemande, 0, 1, 1, 1)
        self.dateEditDateDemande = QtGui.QDateEdit(self.groupBox)
        self.dateEditDateDemande.setEnabled(False)
        self.dateEditDateDemande.setCalendarPopup(True)
        self.dateEditDateDemande.setObjectName(_fromUtf8("dateEditDateDemande"))
        self.gridLayout.addWidget(self.dateEditDateDemande, 2, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonAfficherTous = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAfficherTous.setFont(font)
        self.pushButtonAfficherTous.setObjectName(_fromUtf8("pushButtonAfficherTous"))
        self.horizontalLayout.addWidget(self.pushButtonAfficherTous)
        self.pushButtonRechercher = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonRechercher.setFont(font)
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))
        self.horizontalLayout.addWidget(self.pushButtonRechercher)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(168)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnDebut = QtGui.QPushButton(self.frame_3)
        self.btnDebut.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDebut.setIcon(icon1)
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.horizontalLayout_5.addWidget(self.btnDebut)
        self.btnPrecedent = QtGui.QPushButton(self.frame_3)
        self.btnPrecedent.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrecedent.setIcon(icon2)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.horizontalLayout_5.addWidget(self.btnPrecedent)
        self.lineEditNumPage = QtGui.QLineEdit(self.frame_3)
        self.lineEditNumPage.setEnabled(False)
        self.lineEditNumPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditNumPage.setObjectName(_fromUtf8("lineEditNumPage"))
        self.horizontalLayout_5.addWidget(self.lineEditNumPage)
        self.comboBoxNumPage = QtGui.QComboBox(self.frame_3)
        self.comboBoxNumPage.setObjectName(_fromUtf8("comboBoxNumPage"))
        self.horizontalLayout_5.addWidget(self.comboBoxNumPage)
        self.btnSuivant = QtGui.QPushButton(self.frame_3)
        self.btnSuivant.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuivant.setIcon(icon3)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.horizontalLayout_5.addWidget(self.btnSuivant)
        self.btnFin = QtGui.QPushButton(self.frame_3)
        self.btnFin.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFin.setIcon(icon4)
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.horizontalLayout_5.addWidget(self.btnFin)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonDetails = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonDetails.setFont(font)
        self.pushButtonDetails.setObjectName(_fromUtf8("pushButtonDetails"))
        self.horizontalLayout_3.addWidget(self.pushButtonDetails)
        self.pushButtonSelection = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSelection.setFont(font)
        self.pushButtonSelection.setObjectName(_fromUtf8("pushButtonSelection"))
        self.horizontalLayout_3.addWidget(self.pushButtonSelection)
        self.pushButtonQuitter = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonQuitter.setFont(font)
        self.pushButtonQuitter.setObjectName(_fromUtf8("pushButtonQuitter"))
        self.horizontalLayout_3.addWidget(self.pushButtonQuitter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Recherche demande certficat", None))
        self.groupBox.setTitle(_translate("Dialog", "Recherche", None))
        self.checkBoxNomDemandeur.setText(_translate("Dialog", "Nom Demandeur", None))
        self.checkBoxDateDemande.setText(_translate("Dialog", "Du (Date Demande)", None))
        self.checkBox.setText(_translate("Dialog", "Au", None))
        self.checkBoxNumeroDemande.setText(_translate("Dialog", "Numéro Demande", None))
        self.pushButtonAfficherTous.setText(_translate("Dialog", "Afficher tous", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Rechercher", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Numero demande", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nom demandeurs", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date demande", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Surface", None))
        self.pushButtonDetails.setText(_translate("Dialog", "Details", None))
        self.pushButtonSelection.setText(_translate("Dialog", "Selectionner", None))
        self.pushButtonQuitter.setText(_translate("Dialog", "Fermer", None))

import icons_rc
