# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditUtilisateur.ui'
#
# Created: Wed Mar 20 08:55:33 2024
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(332, 527)
        Dialog.setMinimumSize(QtCore.QSize(332, 440))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/users/icone/user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditNom = QtGui.QLineEdit(Dialog)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNom)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditPrenom = QtGui.QLineEdit(Dialog)
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditPrenom)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditIdentifiant = QtGui.QLineEdit(Dialog)
        self.lineEditIdentifiant.setObjectName(_fromUtf8("lineEditIdentifiant"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditIdentifiant)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditTelephone = QtGui.QLineEdit(Dialog)
        self.lineEditTelephone.setObjectName(_fromUtf8("lineEditTelephone"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditTelephone)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.plainTextEditAdresse = QtGui.QPlainTextEdit(Dialog)
        self.plainTextEditAdresse.setObjectName(_fromUtf8("plainTextEditAdresse"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.plainTextEditAdresse)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEditFonction = QtGui.QLineEdit(Dialog)
        self.lineEditFonction.setObjectName(_fromUtf8("lineEditFonction"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditFonction)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBoxGroupe = QtGui.QComboBox(Dialog)
        self.comboBoxGroupe.setObjectName(_fromUtf8("comboBoxGroupe"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxGroupe)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBoxMotdepasse = QtGui.QCheckBox(self.groupBox)
        self.checkBoxMotdepasse.setObjectName(_fromUtf8("checkBoxMotdepasse"))
        self.verticalLayout_2.addWidget(self.checkBoxMotdepasse)
        self.lineEditOldMdp = QtGui.QLineEdit(self.groupBox)
        self.lineEditOldMdp.setEnabled(False)
        self.lineEditOldMdp.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditOldMdp.setObjectName(_fromUtf8("lineEditOldMdp"))
        self.verticalLayout_2.addWidget(self.lineEditOldMdp)
        self.lineEditMotdepasse = QtGui.QLineEdit(self.groupBox)
        self.lineEditMotdepasse.setEnabled(False)
        self.lineEditMotdepasse.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditMotdepasse.setObjectName(_fromUtf8("lineEditMotdepasse"))
        self.verticalLayout_2.addWidget(self.lineEditMotdepasse)
        self.lineEditMotdepasse2 = QtGui.QLineEdit(self.groupBox)
        self.lineEditMotdepasse2.setEnabled(False)
        self.lineEditMotdepasse2.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditMotdepasse2.setObjectName(_fromUtf8("lineEditMotdepasse2"))
        self.verticalLayout_2.addWidget(self.lineEditMotdepasse2)
        self.listWidgetComplexity = QtGui.QListWidget(self.groupBox)
        self.listWidgetComplexity.setEnabled(False)
        self.listWidgetComplexity.setObjectName(_fromUtf8("listWidgetComplexity"))
        item = QtGui.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/bullet_red.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidgetComplexity.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidgetComplexity.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidgetComplexity.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidgetComplexity.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidgetComplexity.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidgetComplexity)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonEnregistrer = QtGui.QPushButton(Dialog)
        self.pushButtonEnregistrer.setObjectName(_fromUtf8("pushButtonEnregistrer"))
        self.horizontalLayout.addWidget(self.pushButtonEnregistrer)
        self.pushButtonAnnuler = QtGui.QPushButton(Dialog)
        self.pushButtonAnnuler.setObjectName(_fromUtf8("pushButtonAnnuler"))
        self.horizontalLayout.addWidget(self.pushButtonAnnuler)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBoxGroupe, self.lineEditNom)
        Dialog.setTabOrder(self.lineEditNom, self.lineEditPrenom)
        Dialog.setTabOrder(self.lineEditPrenom, self.lineEditIdentifiant)
        Dialog.setTabOrder(self.lineEditIdentifiant, self.lineEditTelephone)
        Dialog.setTabOrder(self.lineEditTelephone, self.plainTextEditAdresse)
        Dialog.setTabOrder(self.plainTextEditAdresse, self.lineEditFonction)
        Dialog.setTabOrder(self.lineEditFonction, self.lineEditMotdepasse)
        Dialog.setTabOrder(self.lineEditMotdepasse, self.lineEditMotdepasse2)
        Dialog.setTabOrder(self.lineEditMotdepasse2, self.pushButtonEnregistrer)
        Dialog.setTabOrder(self.pushButtonEnregistrer, self.pushButtonAnnuler)
        Dialog.setTabOrder(self.pushButtonAnnuler, self.checkBoxMotdepasse)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Edition Utilisateur", None))
        self.label.setText(_translate("Dialog", "Nom", None))
        self.label_2.setText(_translate("Dialog", "Prenom", None))
        self.label_3.setText(_translate("Dialog", "Identifiant", None))
        self.label_6.setText(_translate("Dialog", "Téléphone", None))
        self.label_7.setText(_translate("Dialog", "Adresse", None))
        self.label_8.setText(_translate("Dialog", "Fonction", None))
        self.label_4.setText(_translate("Dialog", "Groupe", None))
        self.groupBox.setTitle(_translate("Dialog", "Accès", None))
        self.checkBoxMotdepasse.setText(_translate("Dialog", "Modifier Mot de Passe", None))
        self.lineEditOldMdp.setPlaceholderText(_translate("Dialog", "Ancien mot de passe", None))
        self.lineEditMotdepasse.setPlaceholderText(_translate("Dialog", "Mot de Passe", None))
        self.lineEditMotdepasse2.setPlaceholderText(_translate("Dialog", "Confirmer Mot de Passe", None))
        __sortingEnabled = self.listWidgetComplexity.isSortingEnabled()
        self.listWidgetComplexity.setSortingEnabled(False)
        item = self.listWidgetComplexity.item(0)
        item.setText(_translate("Dialog", "8 caractères minimum", None))
        item = self.listWidgetComplexity.item(1)
        item.setText(_translate("Dialog", "Comporte des miniscules", None))
        item = self.listWidgetComplexity.item(2)
        item.setText(_translate("Dialog", "Comporte des majuscules", None))
        item = self.listWidgetComplexity.item(3)
        item.setText(_translate("Dialog", "Comporte des caractères spéciaux", None))
        item = self.listWidgetComplexity.item(4)
        item.setText(_translate("Dialog", "Comporte des chiffres", None))
        self.listWidgetComplexity.setSortingEnabled(__sortingEnabled)
        self.pushButtonEnregistrer.setText(_translate("Dialog", "Enregistrer", None))
        self.pushButtonAnnuler.setText(_translate("Dialog", "Annuler", None))

import icons_rc
