# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImportInventaire.ui'
#
# Created: Mon Mar 13 19:53:45 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(662, 490)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButtonPrcourir_parcelle = QtGui.QToolButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_folder_horizontal_open_11903.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPrcourir_parcelle.setIcon(icon)
        self.toolButtonPrcourir_parcelle.setObjectName(_fromUtf8("toolButtonPrcourir_parcelle"))
        self.gridLayout.addWidget(self.toolButtonPrcourir_parcelle, 1, 3, 1, 1)
        self.lineEditPersonnes = QtGui.QLineEdit(Dialog)
        self.lineEditPersonnes.setObjectName(_fromUtf8("lineEditPersonnes"))
        self.gridLayout.addWidget(self.lineEditPersonnes, 2, 2, 1, 1)
        self.lineEditParcelles = QtGui.QLineEdit(Dialog)
        self.lineEditParcelles.setObjectName(_fromUtf8("lineEditParcelles"))
        self.gridLayout.addWidget(self.lineEditParcelles, 1, 2, 1, 1)
        self.toolButtonParcourir_localite = QtGui.QToolButton(Dialog)
        self.toolButtonParcourir_localite.setIcon(icon)
        self.toolButtonParcourir_localite.setObjectName(_fromUtf8("toolButtonParcourir_localite"))
        self.gridLayout.addWidget(self.toolButtonParcourir_localite, 4, 3, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.toolButtonParcourir_occupant = QtGui.QToolButton(Dialog)
        self.toolButtonParcourir_occupant.setIcon(icon)
        self.toolButtonParcourir_occupant.setObjectName(_fromUtf8("toolButtonParcourir_occupant"))
        self.gridLayout.addWidget(self.toolButtonParcourir_occupant, 3, 3, 1, 1)
        self.toolButtonShape = QtGui.QToolButton(Dialog)
        self.toolButtonShape.setIcon(icon)
        self.toolButtonShape.setObjectName(_fromUtf8("toolButtonShape"))
        self.gridLayout.addWidget(self.toolButtonShape, 0, 3, 1, 1)
        self.lineEditOccupants = QtGui.QLineEdit(Dialog)
        self.lineEditOccupants.setObjectName(_fromUtf8("lineEditOccupants"))
        self.gridLayout.addWidget(self.lineEditOccupants, 3, 2, 1, 1)
        self.lineEditLocalites = QtGui.QLineEdit(Dialog)
        self.lineEditLocalites.setObjectName(_fromUtf8("lineEditLocalites"))
        self.gridLayout.addWidget(self.lineEditLocalites, 4, 2, 1, 1)
        self.toolButtonParcourir_personne = QtGui.QToolButton(Dialog)
        self.toolButtonParcourir_personne.setIcon(icon)
        self.toolButtonParcourir_personne.setObjectName(_fromUtf8("toolButtonParcourir_personne"))
        self.gridLayout.addWidget(self.toolButtonParcourir_personne, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.lineEditRefImport = QtGui.QLineEdit(Dialog)
        self.lineEditRefImport.setEnabled(True)
        self.lineEditRefImport.setReadOnly(True)
        self.lineEditRefImport.setObjectName(_fromUtf8("lineEditRefImport"))
        self.gridLayout.addWidget(self.lineEditRefImport, 5, 2, 1, 2)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.lineEditShape = QtGui.QLineEdit(Dialog)
        self.lineEditShape.setObjectName(_fromUtf8("lineEditShape"))
        self.gridLayout.addWidget(self.lineEditShape, 0, 2, 1, 1)
        self.checkBoxFichierForme = QtGui.QCheckBox(Dialog)
        self.checkBoxFichierForme.setText(_fromUtf8(""))
        self.checkBoxFichierForme.setObjectName(_fromUtf8("checkBoxFichierForme"))
        self.gridLayout.addWidget(self.checkBoxFichierForme, 0, 0, 1, 1)
        self.checkBoxParcelle = QtGui.QCheckBox(Dialog)
        self.checkBoxParcelle.setText(_fromUtf8(""))
        self.checkBoxParcelle.setObjectName(_fromUtf8("checkBoxParcelle"))
        self.gridLayout.addWidget(self.checkBoxParcelle, 1, 0, 1, 1)
        self.checkBoxPersonne = QtGui.QCheckBox(Dialog)
        self.checkBoxPersonne.setText(_fromUtf8(""))
        self.checkBoxPersonne.setObjectName(_fromUtf8("checkBoxPersonne"))
        self.gridLayout.addWidget(self.checkBoxPersonne, 2, 0, 1, 1)
        self.checkBoxOccupant = QtGui.QCheckBox(Dialog)
        self.checkBoxOccupant.setText(_fromUtf8(""))
        self.checkBoxOccupant.setObjectName(_fromUtf8("checkBoxOccupant"))
        self.gridLayout.addWidget(self.checkBoxOccupant, 3, 0, 1, 1)
        self.checkBoxLocalite = QtGui.QCheckBox(Dialog)
        self.checkBoxLocalite.setText(_fromUtf8(""))
        self.checkBoxLocalite.setObjectName(_fromUtf8("checkBoxLocalite"))
        self.gridLayout.addWidget(self.checkBoxLocalite, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listWidgetSteps = QtGui.QListWidget(Dialog)
        self.listWidgetSteps.setObjectName(_fromUtf8("listWidgetSteps"))
        self.horizontalLayout.addWidget(self.listWidgetSteps)
        self.listWidget = QtGui.QListWidget(Dialog)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.horizontalLayout.addWidget(self.listWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonLancer = QtGui.QPushButton(Dialog)
        self.pushButtonLancer.setObjectName(_fromUtf8("pushButtonLancer"))
        self.horizontalLayout_2.addWidget(self.pushButtonLancer)
        self.pushButtonFermer = QtGui.QPushButton(Dialog)
        self.pushButtonFermer.setObjectName(_fromUtf8("pushButtonFermer"))
        self.horizontalLayout_2.addWidget(self.pushButtonFermer)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Import Inventaire", None))
        self.toolButtonPrcourir_parcelle.setText(_translate("Dialog", "...", None))
        self.toolButtonParcourir_localite.setText(_translate("Dialog", "...", None))
        self.label_2.setText(_translate("Dialog", "Données personne physique", None))
        self.label_4.setText(_translate("Dialog", "Données localité", None))
        self.label_3.setText(_translate("Dialog", "Données occupant", None))
        self.toolButtonParcourir_occupant.setText(_translate("Dialog", "...", None))
        self.toolButtonShape.setText(_translate("Dialog", "...", None))
        self.toolButtonParcourir_personne.setText(_translate("Dialog", "...", None))
        self.label_6.setText(_translate("Dialog", "Référence de l\'import:", None))
        self.label.setText(_translate("Dialog", "Données parcelles inventoriées", None))
        self.label_5.setText(_translate("Dialog", "Fichier de forme", None))
        self.pushButtonLancer.setText(_translate("Dialog", "Lancer", None))
        self.pushButtonFermer.setText(_translate("Dialog", "Fermer", None))

import icons_rc
