# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\plofstandalone\PolygoneAutomatique.ui'
#
# Created: Wed Mar 13 21:17:32 2019
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PolyAuto(object):
    def setupUi(self, PolyAuto):
        PolyAuto.setObjectName(_fromUtf8("PolyAuto"))
        PolyAuto.resize(355, 278)
        self.verticalLayout_3 = QtGui.QVBoxLayout(PolyAuto)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formGroupBox = QtGui.QGroupBox(PolyAuto)
        self.formGroupBox.setObjectName(_fromUtf8("formGroupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.formGroupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(8)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.activLabel = QtGui.QLabel(self.formGroupBox)
        self.activLabel.setObjectName(_fromUtf8("activLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.activLabel)
        self.coucheCibleLabel_2 = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coucheCibleLabel_2.setFont(font)
        self.coucheCibleLabel_2.setObjectName(_fromUtf8("coucheCibleLabel_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.coucheCibleLabel_2)
        self.coucheCibleComboBox_2 = QtGui.QComboBox(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coucheCibleComboBox_2.setFont(font)
        self.coucheCibleComboBox_2.setObjectName(_fromUtf8("coucheCibleComboBox_2"))
        self.coucheCibleComboBox_2.addItem(_fromUtf8(""))
        self.coucheCibleComboBox_2.addItem(_fromUtf8(""))
        self.coucheCibleComboBox_2.addItem(_fromUtf8(""))
        self.coucheCibleComboBox_2.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.coucheCibleComboBox_2)
        self.modeLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.modeLabel.setFont(font)
        self.modeLabel.setObjectName(_fromUtf8("modeLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.modeLabel)
        self.modeComboBox = QtGui.QComboBox(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.modeComboBox.setFont(font)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.modeComboBox)
        self.tolRanceLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tolRanceLabel.setFont(font)
        self.tolRanceLabel.setObjectName(_fromUtf8("tolRanceLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.tolRanceLabel)
        self.tolRanceSpinBox = QtGui.QSpinBox(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tolRanceSpinBox.setFont(font)
        self.tolRanceSpinBox.setObjectName(_fromUtf8("tolRanceSpinBox"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.tolRanceSpinBox)
        self.unitSLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unitSLabel.setFont(font)
        self.unitSLabel.setObjectName(_fromUtf8("unitSLabel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.unitSLabel)
        self.unitSComboBox = QtGui.QComboBox(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unitSComboBox.setFont(font)
        self.unitSComboBox.setObjectName(_fromUtf8("unitSComboBox"))
        self.unitSComboBox.addItem(_fromUtf8(""))
        self.unitSComboBox.addItem(_fromUtf8(""))
        self.unitSComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.unitSComboBox)
        self.activCheckBox = QtGui.QCheckBox(self.formGroupBox)
        self.activCheckBox.setObjectName(_fromUtf8("activCheckBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.activCheckBox)
        self.verticalLayout.addWidget(self.formGroupBox)
        self.formGroupBox_2 = QtGui.QGroupBox(PolyAuto)
        self.formGroupBox_2.setObjectName(_fromUtf8("formGroupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.formGroupBox_2)
        self.verticalLayout_2.setMargin(8)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.eviterLesIntersectionsLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eviterLesIntersectionsLabel.setFont(font)
        self.eviterLesIntersectionsLabel.setObjectName(_fromUtf8("eviterLesIntersectionsLabel"))
        self.verticalLayout_2.addWidget(self.eviterLesIntersectionsLabel)
        self.notIntersecting = QtGui.QCheckBox(self.formGroupBox_2)
        self.notIntersecting.setObjectName(_fromUtf8("notIntersecting"))
        self.verticalLayout_2.addWidget(self.notIntersecting)
        self.horizontalGroupBox = QtGui.QGroupBox(self.formGroupBox_2)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Cancel = QtGui.QPushButton(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Cancel.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_minus_10199.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cancel.setIcon(icon)
        self.Cancel.setObjectName(_fromUtf8("Cancel"))
        self.horizontalLayout.addWidget(self.Cancel)
        self.Apply = QtGui.QPushButton(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Apply.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/accept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Apply.setIcon(icon1)
        self.Apply.setObjectName(_fromUtf8("Apply"))
        self.horizontalLayout.addWidget(self.Apply)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox)
        self.verticalLayout.addWidget(self.formGroupBox_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(PolyAuto)
        QtCore.QMetaObject.connectSlotsByName(PolyAuto)

    def retranslateUi(self, PolyAuto):
        PolyAuto.setWindowTitle(QtGui.QApplication.translate("PolyAuto", "Options d\'accrochage", None, QtGui.QApplication.UnicodeUTF8))
        self.activLabel.setText(QtGui.QApplication.translate("PolyAuto", "Activé", None, QtGui.QApplication.UnicodeUTF8))
        self.coucheCibleLabel_2.setText(QtGui.QApplication.translate("PolyAuto", "Couche cible", None, QtGui.QApplication.UnicodeUTF8))
        self.coucheCibleComboBox_2.setItemText(0, QtGui.QApplication.translate("PolyAuto", "Toutes les couches", None, QtGui.QApplication.UnicodeUTF8))
        self.coucheCibleComboBox_2.setItemText(1, QtGui.QApplication.translate("PolyAuto", "Couche Demande", None, QtGui.QApplication.UnicodeUTF8))
        self.coucheCibleComboBox_2.setItemText(2, QtGui.QApplication.translate("PolyAuto", "Couche Certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.coucheCibleComboBox_2.setItemText(3, QtGui.QApplication.translate("PolyAuto", "Couche Fiscalité", None, QtGui.QApplication.UnicodeUTF8))
        self.modeLabel.setText(QtGui.QApplication.translate("PolyAuto", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(0, QtGui.QApplication.translate("PolyAuto", "Choisir mode ...", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(1, QtGui.QApplication.translate("PolyAuto", "sur un sommet", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(2, QtGui.QApplication.translate("PolyAuto", "sur un segment", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(3, QtGui.QApplication.translate("PolyAuto", "sur un sommet et un segment", None, QtGui.QApplication.UnicodeUTF8))
        self.tolRanceLabel.setText(QtGui.QApplication.translate("PolyAuto", "Tolérance", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSLabel.setText(QtGui.QApplication.translate("PolyAuto", "Unités", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSComboBox.setItemText(0, QtGui.QApplication.translate("PolyAuto", "Unités de la couche", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSComboBox.setItemText(1, QtGui.QApplication.translate("PolyAuto", "Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.unitSComboBox.setItemText(2, QtGui.QApplication.translate("PolyAuto", "Unité de la carte", None, QtGui.QApplication.UnicodeUTF8))
        self.eviterLesIntersectionsLabel.setText(QtGui.QApplication.translate("PolyAuto", "Polygone Automatique", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("PolyAuto", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.Apply.setText(QtGui.QApplication.translate("PolyAuto", "Appliquer", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
