# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_personne.ui'
#
# Created: Mon Oct  9 09:26:59 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(682, 608)
        self.gridLayout_6 = QtGui.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tabWidgetIdentite = QtGui.QTabWidget(Dialog)
        self.tabWidgetIdentite.setObjectName(_fromUtf8("tabWidgetIdentite"))
        self.cin_recto = QtGui.QWidget()
        self.cin_recto.setObjectName(_fromUtf8("cin_recto"))
        self.gridLayout = QtGui.QGridLayout(self.cin_recto)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelCinRecto = QtGui.QLabel(self.cin_recto)
        self.labelCinRecto.setObjectName(_fromUtf8("labelCinRecto"))
        self.gridLayout.addWidget(self.labelCinRecto, 0, 0, 1, 1)
        self.graphicsViewCinRecto = QtGui.QGraphicsView(self.cin_recto)
        self.graphicsViewCinRecto.setObjectName(_fromUtf8("graphicsViewCinRecto"))
        self.gridLayout.addWidget(self.graphicsViewCinRecto, 1, 0, 1, 3)
        self.lineEditCinRecto = QtGui.QLineEdit(self.cin_recto)
        self.lineEditCinRecto.setObjectName(_fromUtf8("lineEditCinRecto"))
        self.gridLayout.addWidget(self.lineEditCinRecto, 0, 1, 1, 1)
        self.toolButtonParcourirCinRecto = QtGui.QToolButton(self.cin_recto)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_folder_horizontal_open_11903.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonParcourirCinRecto.setIcon(icon)
        self.toolButtonParcourirCinRecto.setObjectName(_fromUtf8("toolButtonParcourirCinRecto"))
        self.gridLayout.addWidget(self.toolButtonParcourirCinRecto, 0, 2, 1, 1)
        self.tabWidgetIdentite.addTab(self.cin_recto, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelPhotoCinVerso = QtGui.QLabel(self.tab_2)
        self.labelPhotoCinVerso.setObjectName(_fromUtf8("labelPhotoCinVerso"))
        self.gridLayout_2.addWidget(self.labelPhotoCinVerso, 0, 0, 1, 1)
        self.lineEditCinVerso = QtGui.QLineEdit(self.tab_2)
        self.lineEditCinVerso.setObjectName(_fromUtf8("lineEditCinVerso"))
        self.gridLayout_2.addWidget(self.lineEditCinVerso, 0, 1, 1, 1)
        self.toolButtonParcourirVerso = QtGui.QToolButton(self.tab_2)
        self.toolButtonParcourirVerso.setIcon(icon)
        self.toolButtonParcourirVerso.setObjectName(_fromUtf8("toolButtonParcourirVerso"))
        self.gridLayout_2.addWidget(self.toolButtonParcourirVerso, 0, 2, 1, 1)
        self.graphicsViewCinVerso = QtGui.QGraphicsView(self.tab_2)
        self.graphicsViewCinVerso.setObjectName(_fromUtf8("graphicsViewCinVerso"))
        self.gridLayout_2.addWidget(self.graphicsViewCinVerso, 1, 0, 1, 3)
        self.tabWidgetIdentite.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEditCinSignature = QtGui.QLineEdit(self.tab)
        self.lineEditCinSignature.setObjectName(_fromUtf8("lineEditCinSignature"))
        self.gridLayout_3.addWidget(self.lineEditCinSignature, 1, 1, 1, 1)
        self.labelPhotoSignature = QtGui.QLabel(self.tab)
        self.labelPhotoSignature.setObjectName(_fromUtf8("labelPhotoSignature"))
        self.gridLayout_3.addWidget(self.labelPhotoSignature, 1, 0, 1, 1)
        self.toolButtonParcourirSignature = QtGui.QToolButton(self.tab)
        self.toolButtonParcourirSignature.setIcon(icon)
        self.toolButtonParcourirSignature.setObjectName(_fromUtf8("toolButtonParcourirSignature"))
        self.gridLayout_3.addWidget(self.toolButtonParcourirSignature, 1, 2, 1, 1)
        self.graphicsViewSignature = QtGui.QGraphicsView(self.tab)
        self.graphicsViewSignature.setObjectName(_fromUtf8("graphicsViewSignature"))
        self.gridLayout_3.addWidget(self.graphicsViewSignature, 3, 0, 1, 3)
        self.tabWidgetIdentite.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labelPhoto_4 = QtGui.QLabel(self.tab_3)
        self.labelPhoto_4.setObjectName(_fromUtf8("labelPhoto_4"))
        self.gridLayout_4.addWidget(self.labelPhoto_4, 0, 0, 1, 1)
        self.lineEditEmpreinteD = QtGui.QLineEdit(self.tab_3)
        self.lineEditEmpreinteD.setObjectName(_fromUtf8("lineEditEmpreinteD"))
        self.gridLayout_4.addWidget(self.lineEditEmpreinteD, 0, 1, 1, 1)
        self.toolButtonParcourirEmpreinteD = QtGui.QToolButton(self.tab_3)
        self.toolButtonParcourirEmpreinteD.setIcon(icon)
        self.toolButtonParcourirEmpreinteD.setObjectName(_fromUtf8("toolButtonParcourirEmpreinteD"))
        self.gridLayout_4.addWidget(self.toolButtonParcourirEmpreinteD, 0, 2, 1, 1)
        self.graphicsViewEmpreinteD = QtGui.QGraphicsView(self.tab_3)
        self.graphicsViewEmpreinteD.setObjectName(_fromUtf8("graphicsViewEmpreinteD"))
        self.gridLayout_4.addWidget(self.graphicsViewEmpreinteD, 1, 0, 1, 3)
        self.tabWidgetIdentite.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelPhoto_5 = QtGui.QLabel(self.tab_4)
        self.labelPhoto_5.setObjectName(_fromUtf8("labelPhoto_5"))
        self.gridLayout_5.addWidget(self.labelPhoto_5, 0, 0, 1, 1)
        self.lineEditEmpreinteG = QtGui.QLineEdit(self.tab_4)
        self.lineEditEmpreinteG.setObjectName(_fromUtf8("lineEditEmpreinteG"))
        self.gridLayout_5.addWidget(self.lineEditEmpreinteG, 0, 1, 1, 1)
        self.toolButtonParcourirEmpreinteG = QtGui.QToolButton(self.tab_4)
        self.toolButtonParcourirEmpreinteG.setIcon(icon)
        self.toolButtonParcourirEmpreinteG.setObjectName(_fromUtf8("toolButtonParcourirEmpreinteG"))
        self.gridLayout_5.addWidget(self.toolButtonParcourirEmpreinteG, 0, 2, 1, 1)
        self.graphicsViewEmpreinteG = QtGui.QGraphicsView(self.tab_4)
        self.graphicsViewEmpreinteG.setObjectName(_fromUtf8("graphicsViewEmpreinteG"))
        self.gridLayout_5.addWidget(self.graphicsViewEmpreinteG, 1, 0, 1, 3)
        self.tabWidgetIdentite.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidgetIdentite, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonModifier = QtGui.QPushButton(Dialog)
        self.pushButtonModifier.setObjectName(_fromUtf8("pushButtonModifier"))
        self.horizontalLayout.addWidget(self.pushButtonModifier)
        self.pushButtonSupprimer = QtGui.QPushButton(Dialog)
        self.pushButtonSupprimer.setObjectName(_fromUtf8("pushButtonSupprimer"))
        self.horizontalLayout.addWidget(self.pushButtonSupprimer)
        self.pushButtonFermer = QtGui.QPushButton(Dialog)
        self.pushButtonFermer.setObjectName(_fromUtf8("pushButtonFermer"))
        self.horizontalLayout.addWidget(self.pushButtonFermer)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidgetIdentite.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Identités", None))
        self.labelCinRecto.setText(_translate("Dialog", "Chemin de la photo à importer: ", None))
        self.toolButtonParcourirCinRecto.setText(_translate("Dialog", "...", None))
        self.tabWidgetIdentite.setTabText(self.tabWidgetIdentite.indexOf(self.cin_recto), _translate("Dialog", "cin_recto", None))
        self.labelPhotoCinVerso.setText(_translate("Dialog", "Chemin de la photo à importer: ", None))
        self.toolButtonParcourirVerso.setText(_translate("Dialog", "...", None))
        self.tabWidgetIdentite.setTabText(self.tabWidgetIdentite.indexOf(self.tab_2), _translate("Dialog", "cin_verso", None))
        self.labelPhotoSignature.setText(_translate("Dialog", "Chemin de la photo à importer: ", None))
        self.toolButtonParcourirSignature.setText(_translate("Dialog", "...", None))
        self.tabWidgetIdentite.setTabText(self.tabWidgetIdentite.indexOf(self.tab), _translate("Dialog", "signature", None))
        self.labelPhoto_4.setText(_translate("Dialog", "Chemin de la photo à importer: ", None))
        self.toolButtonParcourirEmpreinteD.setText(_translate("Dialog", "...", None))
        self.tabWidgetIdentite.setTabText(self.tabWidgetIdentite.indexOf(self.tab_3), _translate("Dialog", "empreinte_droite", None))
        self.labelPhoto_5.setText(_translate("Dialog", "Chemin de la photo à importer: ", None))
        self.toolButtonParcourirEmpreinteG.setText(_translate("Dialog", "...", None))
        self.tabWidgetIdentite.setTabText(self.tabWidgetIdentite.indexOf(self.tab_4), _translate("Dialog", "empreinte_gauche", None))
        self.pushButtonModifier.setText(_translate("Dialog", "Modifier", None))
        self.pushButtonSupprimer.setText(_translate("Dialog", "Supprimer", None))
        self.pushButtonFermer.setText(_translate("Dialog", "Fermer", None))

import icons_rc
