# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\plofstandalone\OperationsSubsequentes\OperationsSubsequentes.ui'
#
# Created: Thu Mar 14 00:07:57 2019
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(613, 508)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.comboTypeOperation = QtGui.QComboBox(self.groupBox)
        self.comboTypeOperation.setObjectName(_fromUtf8("comboTypeOperation"))
        self.horizontalLayout_2.addWidget(self.comboTypeOperation)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxActeCharge = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxActeCharge.setObjectName(_fromUtf8("checkBoxActeCharge"))
        self.horizontalLayout_3.addWidget(self.checkBoxActeCharge)
        self.btnCahrgerActe = QtGui.QPushButton(self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/briefcase--plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCahrgerActe.setIcon(icon)
        self.btnCahrgerActe.setObjectName(_fromUtf8("btnCahrgerActe"))
        self.horizontalLayout_3.addWidget(self.btnCahrgerActe)
        self.btnDetailActe = QtGui.QPushButton(self.groupBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/magnifier-zoom-fit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetailActe.setIcon(icon1)
        self.btnDetailActe.setObjectName(_fromUtf8("btnDetailActe"))
        self.horizontalLayout_3.addWidget(self.btnDetailActe)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboNumCertificat = QtGui.QComboBox(self.groupBox_3)
        self.comboNumCertificat.setObjectName(_fromUtf8("comboNumCertificat"))
        self.gridLayout.addWidget(self.comboNumCertificat, 0, 1, 1, 1)
        self.btnRechercher = QtGui.QPushButton(self.groupBox_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRechercher.setIcon(icon2)
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.gridLayout.addWidget(self.btnRechercher, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnAjouter = QtGui.QPushButton(self.groupBox_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_plus_circle_12296.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAjouter.setIcon(icon3)
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.gridLayout.addWidget(self.btnAjouter, 1, 2, 1, 1)
        self.btnEnlever = QtGui.QPushButton(self.groupBox_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEnlever.setIcon(icon4)
        self.btnEnlever.setObjectName(_fromUtf8("btnEnlever"))
        self.gridLayout.addWidget(self.btnEnlever, 2, 2, 1, 1)
        self.listWidget = QtGui.QListWidget(self.groupBox_3)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout.addWidget(self.listWidget, 1, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEditCout2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCout2.setObjectName(_fromUtf8("lineEditCout2"))
        self.gridLayout_3.addWidget(self.lineEditCout2, 3, 1, 1, 1)
        self.lineEditCout1 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCout1.setObjectName(_fromUtf8("lineEditCout1"))
        self.gridLayout_3.addWidget(self.lineEditCout1, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 2, 1, 1)
        self.dateEditInscriptionRegistre = QtGui.QDateEdit(self.groupBox_4)
        self.dateEditInscriptionRegistre.setCalendarPopup(True)
        self.dateEditInscriptionRegistre.setObjectName(_fromUtf8("dateEditInscriptionRegistre"))
        self.gridLayout_3.addWidget(self.dateEditInscriptionRegistre, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.dateEditDepotDemande = QtGui.QDateEdit(self.groupBox_4)
        self.dateEditDepotDemande.setCalendarPopup(True)
        self.dateEditDepotDemande.setObjectName(_fromUtf8("dateEditDepotDemande"))
        self.gridLayout_3.addWidget(self.dateEditDepotDemande, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnLancerOperation = QtGui.QPushButton(Dialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/time_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLancerOperation.setIcon(icon5)
        self.btnLancerOperation.setObjectName(_fromUtf8("btnLancerOperation"))
        self.horizontalLayout_4.addWidget(self.btnLancerOperation)
        self.btnAnnuler = QtGui.QPushButton(Dialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_minus_10199.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnnuler.setIcon(icon6)
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))
        self.horizontalLayout_4.addWidget(self.btnAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Opérations subséquentes sur les certificats", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Choix de l\'opération", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Type opération*", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Acte", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxActeCharge.setText(QtGui.QApplication.translate("Dialog", "Acte chargé", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCahrgerActe.setText(QtGui.QApplication.translate("Dialog", "Charger acte", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetailActe.setText(QtGui.QApplication.translate("Dialog", "Détail acte", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Certificats concernés", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRechercher.setText(QtGui.QApplication.translate("Dialog", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "N° Certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouter.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnlever.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Info sur l\'opération", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Ar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Coût 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Date de dépôt de demande", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Date d\'inscription au registre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Coût 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Ar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLancerOperation.setText(QtGui.QApplication.translate("Dialog", "Lancer l\'opération", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAnnuler.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
