# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InformationFiscale.ui'
#
# Created: Tue Dec 12 16:49:38 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(753, 630)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 20, 741, 601))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 291))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEditNom = QtGui.QLineEdit(self.groupBox)
        self.lineEditNom.setGeometry(QtCore.QRect(120, 20, 210, 20))
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.lineEditPrenom = QtGui.QLineEdit(self.groupBox)
        self.lineEditPrenom.setGeometry(QtCore.QRect(120, 50, 210, 20))
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.lineEditAdresse = QtGui.QLineEdit(self.groupBox)
        self.lineEditAdresse.setGeometry(QtCore.QRect(120, 80, 210, 20))
        self.lineEditAdresse.setObjectName(_fromUtf8("lineEditAdresse"))
        self.lineEditLieuNaissance = QtGui.QLineEdit(self.groupBox)
        self.lineEditLieuNaissance.setGeometry(QtCore.QRect(120, 140, 210, 20))
        self.lineEditLieuNaissance.setObjectName(_fromUtf8("lineEditLieuNaissance"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 110, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 120, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.radioSexeHomme = QtGui.QRadioButton(self.groupBox)
        self.radioSexeHomme.setGeometry(QtCore.QRect(280, 110, 70, 17))
        self.radioSexeHomme.setObjectName(_fromUtf8("radioSexeHomme"))
        self.radioSexeFemme = QtGui.QRadioButton(self.groupBox)
        self.radioSexeFemme.setGeometry(QtCore.QRect(370, 110, 70, 17))
        self.radioSexeFemme.setObjectName(_fromUtf8("radioSexeFemme"))
        self.btnRechercher = QtGui.QPushButton(self.groupBox)
        self.btnRechercher.setGeometry(QtCore.QRect(360, 20, 75, 23))
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.btnConsorts = QtGui.QPushButton(self.groupBox)
        self.btnConsorts.setGeometry(QtCore.QRect(360, 80, 75, 23))
        self.btnConsorts.setObjectName(_fromUtf8("btnConsorts"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(340, 80, 20, 17))
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.dateEditNaissance = QtGui.QDateEdit(self.groupBox)
        self.dateEditNaissance.setGeometry(QtCore.QRect(120, 110, 131, 22))
        self.dateEditNaissance.setCalendarPopup(True)
        self.dateEditNaissance.setObjectName(_fromUtf8("dateEditNaissance"))
        self.CIN = QtGui.QTabWidget(self.groupBox)
        self.CIN.setGeometry(QtCore.QRect(6, 169, 521, 111))
        self.CIN.setObjectName(_fromUtf8("CIN"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.lineEditLieuCIN = QtGui.QLineEdit(self.tab_5)
        self.lineEditLieuCIN.setGeometry(QtCore.QRect(320, 50, 191, 20))
        self.lineEditLieuCIN.setObjectName(_fromUtf8("lineEditLieuCIN"))
        self.lineEditCIN2 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN2.setGeometry(QtCore.QRect(160, 20, 41, 20))
        self.lineEditCIN2.setObjectName(_fromUtf8("lineEditCIN2"))
        self.dateEditCIN = QtGui.QDateEdit(self.tab_5)
        self.dateEditCIN.setGeometry(QtCore.QRect(110, 50, 110, 22))
        self.dateEditCIN.setCalendarPopup(True)
        self.dateEditCIN.setObjectName(_fromUtf8("dateEditCIN"))
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEditCIN3 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN3.setGeometry(QtCore.QRect(210, 20, 41, 20))
        self.lineEditCIN3.setObjectName(_fromUtf8("lineEditCIN3"))
        self.lineEditCIN4 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN4.setGeometry(QtCore.QRect(260, 20, 41, 20))
        self.lineEditCIN4.setObjectName(_fromUtf8("lineEditCIN4"))
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(280, 50, 40, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEditCIN1 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN1.setGeometry(QtCore.QRect(110, 20, 41, 20))
        self.lineEditCIN1.setObjectName(_fromUtf8("lineEditCIN1"))
        self.CIN.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.dateEditActeNaissance = QtGui.QDateEdit(self.tab_4)
        self.dateEditActeNaissance.setGeometry(QtCore.QRect(110, 50, 110, 22))
        self.dateEditActeNaissance.setCalendarPopup(True)
        self.dateEditActeNaissance.setObjectName(_fromUtf8("dateEditActeNaissance"))
        self.lineEditLieuActeNaissance = QtGui.QLineEdit(self.tab_4)
        self.lineEditLieuActeNaissance.setGeometry(QtCore.QRect(320, 50, 191, 20))
        self.lineEditLieuActeNaissance.setObjectName(_fromUtf8("lineEditLieuActeNaissance"))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(280, 50, 40, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEditNumActeNaissance = QtGui.QLineEdit(self.tab_4)
        self.lineEditNumActeNaissance.setGeometry(QtCore.QRect(110, 20, 111, 20))
        self.lineEditNumActeNaissance.setObjectName(_fromUtf8("lineEditNumActeNaissance"))
        self.CIN.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.CIN.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 310, 631, 231))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 621, 202))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioSRI = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioSRI.setObjectName(_fromUtf8("radioSRI"))
        self.gridLayout_3.addWidget(self.radioSRI, 2, 2, 1, 1)
        self.lineEditNumParcelle = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditNumParcelle.setText(_fromUtf8(""))
        self.lineEditNumParcelle.setObjectName(_fromUtf8("lineEditNumParcelle"))
        self.gridLayout_3.addWidget(self.lineEditNumParcelle, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.radioSRA = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioSRA.setObjectName(_fromUtf8("radioSRA"))
        self.gridLayout_3.addWidget(self.radioSRA, 2, 3, 1, 1)
        self.textEditObservation = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEditObservation.setObjectName(_fromUtf8("textEditObservation"))
        self.gridLayout_3.addWidget(self.textEditObservation, 4, 1, 1, 1)
        self.checkBoxAlloue = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxAlloue.setObjectName(_fromUtf8("checkBoxAlloue"))
        self.gridLayout_3.addWidget(self.checkBoxAlloue, 3, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.lineEditCodeParcelle = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditCodeParcelle.setText(_fromUtf8(""))
        self.lineEditCodeParcelle.setObjectName(_fromUtf8("lineEditCodeParcelle"))
        self.gridLayout_3.addWidget(self.lineEditCodeParcelle, 3, 1, 1, 1)
        self.comboHameau = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboHameau.setObjectName(_fromUtf8("comboHameau"))
        self.gridLayout_3.addWidget(self.comboHameau, 0, 3, 1, 1)
        self.comboFokontany = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboFokontany.setObjectName(_fromUtf8("comboFokontany"))
        self.gridLayout_3.addWidget(self.comboFokontany, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 35))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 20))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioTitree = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioTitree.setObjectName(_fromUtf8("radioTitree"))
        self.horizontalLayout_3.addWidget(self.radioTitree)
        self.radioCadastree = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioCadastree.setObjectName(_fromUtf8("radioCadastree"))
        self.horizontalLayout_3.addWidget(self.radioCadastree)
        self.radioCertifiee = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioCertifiee.setObjectName(_fromUtf8("radioCertifiee"))
        self.horizontalLayout_3.addWidget(self.radioCertifiee)
        self.radioAucun = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioAucun.setObjectName(_fromUtf8("radioAucun"))
        self.horizontalLayout_3.addWidget(self.radioAucun)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 641, 141))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayoutWidget_16 = QtGui.QWidget(self.groupBox_4)
        self.formLayoutWidget_16.setGeometry(QtCore.QRect(10, 20, 211, 51))
        self.formLayoutWidget_16.setObjectName(_fromUtf8("formLayoutWidget_16"))
        self.formLayout_16 = QtGui.QFormLayout(self.formLayoutWidget_16)
        self.formLayout_16.setMargin(0)
        self.formLayout_16.setObjectName(_fromUtf8("formLayout_16"))
        self.surfaceLabel_4 = QtGui.QLabel(self.formLayoutWidget_16)
        self.surfaceLabel_4.setObjectName(_fromUtf8("surfaceLabel_4"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.LabelRole, self.surfaceLabel_4)
        self.lineEditSurfaceM2 = QtGui.QLineEdit(self.formLayoutWidget_16)
        self.lineEditSurfaceM2.setObjectName(_fromUtf8("lineEditSurfaceM2"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditSurfaceM2)
        self.Label_2 = QtGui.QLabel(self.formLayoutWidget_16)
        self.Label_2.setText(_fromUtf8(""))
        self.Label_2.setObjectName(_fromUtf8("Label_2"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.LabelRole, self.Label_2)
        self.LineEditSutfaceHa = QtGui.QLineEdit(self.formLayoutWidget_16)
        self.LineEditSutfaceHa.setObjectName(_fromUtf8("LineEditSutfaceHa"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.FieldRole, self.LineEditSutfaceHa)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(240, 20, 21, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(240, 50, 21, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayoutWidget_17 = QtGui.QWidget(self.groupBox_4)
        self.formLayoutWidget_17.setGeometry(QtCore.QRect(300, 50, 331, 51))
        self.formLayoutWidget_17.setObjectName(_fromUtf8("formLayoutWidget_17"))
        self.formLayout_17 = QtGui.QFormLayout(self.formLayoutWidget_17)
        self.formLayout_17.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_17.setMargin(0)
        self.formLayout_17.setObjectName(_fromUtf8("formLayout_17"))
        self.categorieLabel_4 = QtGui.QLabel(self.formLayoutWidget_17)
        self.categorieLabel_4.setObjectName(_fromUtf8("categorieLabel_4"))
        self.formLayout_17.setWidget(0, QtGui.QFormLayout.LabelRole, self.categorieLabel_4)
        self.comboCategorieParcelle = QtGui.QComboBox(self.formLayoutWidget_17)
        self.comboCategorieParcelle.setObjectName(_fromUtf8("comboCategorieParcelle"))
        self.formLayout_17.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboCategorieParcelle)
        self.classeLabel_2 = QtGui.QLabel(self.formLayoutWidget_17)
        self.classeLabel_2.setObjectName(_fromUtf8("classeLabel_2"))
        self.formLayout_17.setWidget(1, QtGui.QFormLayout.LabelRole, self.classeLabel_2)
        self.comboBoxClasse = QtGui.QComboBox(self.formLayoutWidget_17)
        self.comboBoxClasse.setObjectName(_fromUtf8("comboBoxClasse"))
        self.formLayout_17.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxClasse)
        self.formLayoutWidget_18 = QtGui.QWidget(self.groupBox_4)
        self.formLayoutWidget_18.setGeometry(QtCore.QRect(10, 110, 241, 21))
        self.formLayoutWidget_18.setObjectName(_fromUtf8("formLayoutWidget_18"))
        self.formLayout_18 = QtGui.QFormLayout(self.formLayoutWidget_18)
        self.formLayout_18.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_18.setMargin(0)
        self.formLayout_18.setObjectName(_fromUtf8("formLayout_18"))
        self.comboConsistanceParcelle = QtGui.QComboBox(self.formLayoutWidget_18)
        self.comboConsistanceParcelle.setObjectName(_fromUtf8("comboConsistanceParcelle"))
        self.formLayout_18.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboConsistanceParcelle)
        self.consistanceLabel_4 = QtGui.QLabel(self.formLayoutWidget_18)
        self.consistanceLabel_4.setObjectName(_fromUtf8("consistanceLabel_4"))
        self.formLayout_18.setWidget(0, QtGui.QFormLayout.LabelRole, self.consistanceLabel_4)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(290, 20, 341, 21))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButton_Surface = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_Surface.setObjectName(_fromUtf8("radioButton_Surface"))
        self.horizontalLayout_2.addWidget(self.radioButton_Surface)
        self.radioButton_Classe = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_Classe.setObjectName(_fromUtf8("radioButton_Classe"))
        self.horizontalLayout_2.addWidget(self.radioButton_Classe)
        self.radioButton_Venale = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_Venale.setObjectName(_fromUtf8("radioButton_Venale"))
        self.horizontalLayout_2.addWidget(self.radioButton_Venale)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 170, 651, 191))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayoutWidget_10 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(20, 30, 241, 22))
        self.formLayoutWidget_10.setObjectName(_fromUtf8("formLayoutWidget_10"))
        self.formLayout_10 = QtGui.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_10.setMargin(0)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.codeLabel_2 = QtGui.QLabel(self.formLayoutWidget_10)
        self.codeLabel_2.setObjectName(_fromUtf8("codeLabel_2"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.codeLabel_2)
        self.lineEditCode = QtGui.QLineEdit(self.formLayoutWidget_10)
        self.lineEditCode.setObjectName(_fromUtf8("lineEditCode"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditCode)
        self.formLayoutWidget_12 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(20, 60, 241, 22))
        self.formLayoutWidget_12.setObjectName(_fromUtf8("formLayoutWidget_12"))
        self.formLayout_12 = QtGui.QFormLayout(self.formLayoutWidget_12)
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setMargin(0)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.consistanceLabel_3 = QtGui.QLabel(self.formLayoutWidget_12)
        self.consistanceLabel_3.setObjectName(_fromUtf8("consistanceLabel_3"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.consistanceLabel_3)
        self.comboConsistanceBatiment = QtGui.QComboBox(self.formLayoutWidget_12)
        self.comboConsistanceBatiment.setObjectName(_fromUtf8("comboConsistanceBatiment"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboConsistanceBatiment)
        self.formLayoutWidget_13 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_13.setGeometry(QtCore.QRect(20, 130, 181, 22))
        self.formLayoutWidget_13.setObjectName(_fromUtf8("formLayoutWidget_13"))
        self.formLayout_13 = QtGui.QFormLayout(self.formLayoutWidget_13)
        self.formLayout_13.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_13.setMargin(0)
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.surfaceLabel_3 = QtGui.QLabel(self.formLayoutWidget_13)
        self.surfaceLabel_3.setObjectName(_fromUtf8("surfaceLabel_3"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.surfaceLabel_3)
        self.surfaceLineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget_13)
        self.surfaceLineEdit_3.setObjectName(_fromUtf8("surfaceLineEdit_3"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.surfaceLineEdit_3)
        self.formLayoutWidget_14 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_14.setGeometry(QtCore.QRect(210, 130, 181, 22))
        self.formLayoutWidget_14.setObjectName(_fromUtf8("formLayoutWidget_14"))
        self.formLayout_14 = QtGui.QFormLayout(self.formLayoutWidget_14)
        self.formLayout_14.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_14.setMargin(0)
        self.formLayout_14.setObjectName(_fromUtf8("formLayout_14"))
        self.nombrePiCesLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_14)
        self.nombrePiCesLineEdit_2.setObjectName(_fromUtf8("nombrePiCesLineEdit_2"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.FieldRole, self.nombrePiCesLineEdit_2)
        self.nombrePiCesLabel_2 = QtGui.QLabel(self.formLayoutWidget_14)
        self.nombrePiCesLabel_2.setObjectName(_fromUtf8("nombrePiCesLabel_2"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.LabelRole, self.nombrePiCesLabel_2)
        self.formLayoutWidget_15 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_15.setGeometry(QtCore.QRect(400, 130, 115, 21))
        self.formLayoutWidget_15.setObjectName(_fromUtf8("formLayoutWidget_15"))
        self.formLayout_15 = QtGui.QFormLayout(self.formLayoutWidget_15)
        self.formLayout_15.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_15.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_15.setMargin(0)
        self.formLayout_15.setObjectName(_fromUtf8("formLayout_15"))
        self.avecLocationLabel_2 = QtGui.QLabel(self.formLayoutWidget_15)
        self.avecLocationLabel_2.setObjectName(_fromUtf8("avecLocationLabel_2"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.LabelRole, self.avecLocationLabel_2)
        self.avecLocationCheckBox_2 = QtGui.QCheckBox(self.formLayoutWidget_15)
        self.avecLocationCheckBox_2.setObjectName(_fromUtf8("avecLocationCheckBox_2"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.FieldRole, self.avecLocationCheckBox_2)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(300, 30, 341, 21))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButton_SurfaceBatiment = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_SurfaceBatiment.setObjectName(_fromUtf8("radioButton_SurfaceBatiment"))
        self.horizontalLayout_4.addWidget(self.radioButton_SurfaceBatiment)
        self.radioButton_ClasseBatiment = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_ClasseBatiment.setObjectName(_fromUtf8("radioButton_ClasseBatiment"))
        self.horizontalLayout_4.addWidget(self.radioButton_ClasseBatiment)
        self.radioButton_LocativeBatiment = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_LocativeBatiment.setObjectName(_fromUtf8("radioButton_LocativeBatiment"))
        self.horizontalLayout_4.addWidget(self.radioButton_LocativeBatiment)
        self.formLayoutWidget_21 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_21.setGeometry(QtCore.QRect(310, 60, 331, 51))
        self.formLayoutWidget_21.setObjectName(_fromUtf8("formLayoutWidget_21"))
        self.formLayout_22 = QtGui.QFormLayout(self.formLayoutWidget_21)
        self.formLayout_22.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_22.setMargin(0)
        self.formLayout_22.setObjectName(_fromUtf8("formLayout_22"))
        self.categorieLabel_6 = QtGui.QLabel(self.formLayoutWidget_21)
        self.categorieLabel_6.setObjectName(_fromUtf8("categorieLabel_6"))
        self.formLayout_22.setWidget(0, QtGui.QFormLayout.LabelRole, self.categorieLabel_6)
        self.comboCategorieBatiment = QtGui.QComboBox(self.formLayoutWidget_21)
        self.comboCategorieBatiment.setObjectName(_fromUtf8("comboCategorieBatiment"))
        self.formLayout_22.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboCategorieBatiment)
        self.classeLabel_4 = QtGui.QLabel(self.formLayoutWidget_21)
        self.classeLabel_4.setObjectName(_fromUtf8("classeLabel_4"))
        self.formLayout_22.setWidget(1, QtGui.QFormLayout.LabelRole, self.classeLabel_4)
        self.comboBoxClasseBatiment = QtGui.QComboBox(self.formLayoutWidget_21)
        self.comboBoxClasseBatiment.setObjectName(_fromUtf8("comboBoxClasseBatiment"))
        self.formLayout_22.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxClasseBatiment)
        self.btnAjouter = QtGui.QPushButton(self.tab_2)
        self.btnAjouter.setGeometry(QtCore.QRect(510, 370, 95, 31))
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.btnSupprimer = QtGui.QPushButton(self.tab_2)
        self.btnSupprimer.setGeometry(QtCore.QRect(620, 370, 95, 31))
        self.btnSupprimer.setObjectName(_fromUtf8("btnSupprimer"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(15, 410, 701, 131))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame = QtGui.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(10, 10, 421, 100))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayoutWidget_19 = QtGui.QWidget(self.frame)
        self.formLayoutWidget_19.setGeometry(QtCore.QRect(10, 10, 401, 80))
        self.formLayoutWidget_19.setObjectName(_fromUtf8("formLayoutWidget_19"))
        self.formLayout_19 = QtGui.QFormLayout(self.formLayoutWidget_19)
        self.formLayout_19.setMargin(0)
        self.formLayout_19.setObjectName(_fromUtf8("formLayout_19"))
        self.numeroDemandeLabel = QtGui.QLabel(self.formLayoutWidget_19)
        self.numeroDemandeLabel.setObjectName(_fromUtf8("numeroDemandeLabel"))
        self.formLayout_19.setWidget(0, QtGui.QFormLayout.LabelRole, self.numeroDemandeLabel)
        self.numeroDemandeLineEdit = QtGui.QLineEdit(self.formLayoutWidget_19)
        self.numeroDemandeLineEdit.setObjectName(_fromUtf8("numeroDemandeLineEdit"))
        self.formLayout_19.setWidget(0, QtGui.QFormLayout.FieldRole, self.numeroDemandeLineEdit)
        self.numeroCertificatLabel = QtGui.QLabel(self.formLayoutWidget_19)
        self.numeroCertificatLabel.setObjectName(_fromUtf8("numeroCertificatLabel"))
        self.formLayout_19.setWidget(1, QtGui.QFormLayout.LabelRole, self.numeroCertificatLabel)
        self.numeroCertificatLineEdit = QtGui.QLineEdit(self.formLayoutWidget_19)
        self.numeroCertificatLineEdit.setObjectName(_fromUtf8("numeroCertificatLineEdit"))
        self.formLayout_19.setWidget(1, QtGui.QFormLayout.FieldRole, self.numeroCertificatLineEdit)
        self.frame_2 = QtGui.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(10, 120, 531, 361))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 511, 331))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayoutWidget_20 = QtGui.QWidget(self.groupBox_6)
        self.formLayoutWidget_20.setGeometry(QtCore.QRect(0, 30, 401, 70))
        self.formLayoutWidget_20.setObjectName(_fromUtf8("formLayoutWidget_20"))
        self.formLayout_20 = QtGui.QFormLayout(self.formLayoutWidget_20)
        self.formLayout_20.setMargin(0)
        self.formLayout_20.setObjectName(_fromUtf8("formLayout_20"))
        self.positionLabel = QtGui.QLabel(self.formLayoutWidget_20)
        self.positionLabel.setObjectName(_fromUtf8("positionLabel"))
        self.formLayout_20.setWidget(0, QtGui.QFormLayout.LabelRole, self.positionLabel)
        self.positionComboBox = QtGui.QComboBox(self.formLayoutWidget_20)
        self.positionComboBox.setObjectName(_fromUtf8("positionComboBox"))
        self.formLayout_20.setWidget(0, QtGui.QFormLayout.FieldRole, self.positionComboBox)
        self.descriptionLabel = QtGui.QLabel(self.formLayoutWidget_20)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.formLayout_20.setWidget(1, QtGui.QFormLayout.LabelRole, self.descriptionLabel)
        self.descriptionLineEdit = QtGui.QLineEdit(self.formLayoutWidget_20)
        self.descriptionLineEdit.setObjectName(_fromUtf8("descriptionLineEdit"))
        self.formLayout_20.setWidget(1, QtGui.QFormLayout.FieldRole, self.descriptionLineEdit)
        self.btnAjouter2 = QtGui.QPushButton(self.groupBox_6)
        self.btnAjouter2.setGeometry(QtCore.QRect(280, 120, 95, 31))
        self.btnAjouter2.setObjectName(_fromUtf8("btnAjouter2"))
        self.btnSupprimer2 = QtGui.QPushButton(self.groupBox_6)
        self.btnSupprimer2.setGeometry(QtCore.QRect(380, 120, 95, 31))
        self.btnSupprimer2.setObjectName(_fromUtf8("btnSupprimer2"))
        self.tableWidget_2 = QtGui.QTableWidget(self.groupBox_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 160, 491, 161))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(220)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.convertirDemande = QtGui.QPushButton(self.verticalLayoutWidget)
        self.convertirDemande.setObjectName(_fromUtf8("convertirDemande"))
        self.horizontalLayout.addWidget(self.convertirDemande)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnEnregistrer = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnEnregistrer.setObjectName(_fromUtf8("btnEnregistrer"))
        self.horizontalLayout.addWidget(self.btnEnregistrer)
        self.btnAnnuler = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))
        self.horizontalLayout.addWidget(self.btnAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.CIN.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Information fiscale", None))
        self.groupBox.setTitle(_translate("Dialog", "Contribuable", None))
        self.label.setText(_translate("Dialog", "Nom :", None))
        self.label_2.setText(_translate("Dialog", "Prénom :", None))
        self.label_3.setText(_translate("Dialog", "Adresse :", None))
        self.label_4.setText(_translate("Dialog", "Date de naissance : ", None))
        self.label_5.setText(_translate("Dialog", "Lieu de naissance :", None))
        self.radioSexeHomme.setText(_translate("Dialog", "Homme", None))
        self.radioSexeFemme.setText(_translate("Dialog", "Femme", None))
        self.btnRechercher.setText(_translate("Dialog", "Recherche", None))
        self.btnConsorts.setText(_translate("Dialog", "Consorts", None))
        self.label_8.setText(_translate("Dialog", "Date :", None))
        self.label_9.setText(_translate("Dialog", "Lieu :", None))
        self.label_7.setText(_translate("Dialog", "Numero : ", None))
        self.CIN.setTabText(self.CIN.indexOf(self.tab_5), _translate("Dialog", "CIN", None))
        self.label_14.setText(_translate("Dialog", "Date :", None))
        self.label_15.setText(_translate("Dialog", "Lieu :", None))
        self.label_18.setText(_translate("Dialog", "Numero : ", None))
        self.CIN.setTabText(self.CIN.indexOf(self.tab_4), _translate("Dialog", "Acte de naissnace", None))
        self.CIN.setTabText(self.CIN.indexOf(self.tab_6), _translate("Dialog", "Rien", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Parcelle", None))
        self.radioSRI.setText(_translate("Dialog", "SRI", None))
        self.label_12.setText(_translate("Dialog", "Code :", None))
        self.label_6.setText(_translate("Dialog", "Numero: ", None))
        self.label_10.setText(_translate("Dialog", "Fokotany :", None))
        self.radioSRA.setText(_translate("Dialog", "SRA", None))
        self.checkBoxAlloue.setText(_translate("Dialog", "En location", None))
        self.label_13.setText(_translate("Dialog", "Observation :", None))
        self.label_11.setText(_translate("Dialog", "Hameau :", None))
        self.radioTitree.setText(_translate("Dialog", "Titré", None))
        self.radioCadastree.setText(_translate("Dialog", "Cadastré", None))
        self.radioCertifiee.setText(_translate("Dialog", "Certifié", None))
        self.radioAucun.setText(_translate("Dialog", "Aucun", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Contribuable & parcelle", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Parcelle", None))
        self.surfaceLabel_4.setText(_translate("Dialog", "Surface", None))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p>m<span style=\" vertical-align:super;\">2</span></p></body></html>", None))
        self.label_17.setText(_translate("Dialog", "Ha", None))
        self.categorieLabel_4.setText(_translate("Dialog", "Categorie", None))
        self.classeLabel_2.setText(_translate("Dialog", "Classe", None))
        self.consistanceLabel_4.setText(_translate("Dialog", "Consistance", None))
        self.radioButton_Surface.setText(_translate("Dialog", "Surface", None))
        self.radioButton_Classe.setText(_translate("Dialog", "Classe", None))
        self.radioButton_Venale.setText(_translate("Dialog", "Valeur Vénale", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Batiments", None))
        self.codeLabel_2.setText(_translate("Dialog", "Code", None))
        self.consistanceLabel_3.setText(_translate("Dialog", "Consistance", None))
        self.surfaceLabel_3.setText(_translate("Dialog", "<html><head/><body><p>Surface (m<span style=\" vertical-align:super;\">2</span>)</p></body></html>", None))
        self.nombrePiCesLabel_2.setText(_translate("Dialog", "Nombre pièces", None))
        self.avecLocationLabel_2.setText(_translate("Dialog", "En location", None))
        self.radioButton_SurfaceBatiment.setText(_translate("Dialog", "Surface", None))
        self.radioButton_ClasseBatiment.setText(_translate("Dialog", "Classe", None))
        self.radioButton_LocativeBatiment.setText(_translate("Dialog", "Valeur Locative", None))
        self.categorieLabel_6.setText(_translate("Dialog", "Categorie", None))
        self.classeLabel_4.setText(_translate("Dialog", "Classe", None))
        self.btnAjouter.setText(_translate("Dialog", "Ajouter", None))
        self.btnSupprimer.setText(_translate("Dialog", "Supprimer", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Code", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Catégorie", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Consistance", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Surface", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Pièces", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Forfait", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Classe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Parcelle & bâtiment", None))
        self.numeroDemandeLabel.setText(_translate("Dialog", "Numero demande", None))
        self.numeroCertificatLabel.setText(_translate("Dialog", "Numero certificat", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Limites et repères du certificat foncier", None))
        self.positionLabel.setText(_translate("Dialog", "Position", None))
        self.descriptionLabel.setText(_translate("Dialog", "Description", None))
        self.btnAjouter2.setText(_translate("Dialog", "Ajouter", None))
        self.btnSupprimer2.setText(_translate("Dialog", "Supprimer", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Position", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Certificat", None))
        self.convertirDemande.setText(_translate("Dialog", "Convertir en demande", None))
        self.btnEnregistrer.setText(_translate("Dialog", "Enregistrer", None))
        self.btnAnnuler.setText(_translate("Dialog", "Annuler", None))

