# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditProjet.ui'
#
# Created: Sat Jan 27 23:50:34 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(496, 390)
        Dialog.setMinimumSize(QtCore.QSize(496, 390))
        Dialog.setMaximumSize(QtCore.QSize(496, 390))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupbox = QtGui.QGroupBox(Dialog)
        self.groupbox.setObjectName(_fromUtf8("groupbox"))
        self.formLayout = QtGui.QFormLayout(self.groupbox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupbox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.groupbox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditNomProjet = QtGui.QLineEdit(self.groupbox)
        self.lineEditNomProjet.setObjectName(_fromUtf8("lineEditNomProjet"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNomProjet)
        self.dateEditDateLancement = QtGui.QDateEdit(self.groupbox)
        self.dateEditDateLancement.setCalendarPopup(True)
        self.dateEditDateLancement.setObjectName(_fromUtf8("dateEditDateLancement"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateEditDateLancement)
        self.dateEditDatePremierImport = QtGui.QDateEdit(self.groupbox)
        self.dateEditDatePremierImport.setCalendarPopup(True)
        self.dateEditDatePremierImport.setObjectName(_fromUtf8("dateEditDatePremierImport"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEditDatePremierImport)
        self.dateEditDateDernierImport = QtGui.QDateEdit(self.groupbox)
        self.dateEditDateDernierImport.setCalendarPopup(True)
        self.dateEditDateDernierImport.setObjectName(_fromUtf8("dateEditDateDernierImport"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dateEditDateDernierImport)
        self.label_3 = QtGui.QLabel(self.groupbox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupbox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout.addWidget(self.groupbox)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.comboBoxRegion = QtGui.QComboBox(self.groupBox)
        self.comboBoxRegion.setMinimumSize(QtCore.QSize(175, 0))
        self.comboBoxRegion.setObjectName(_fromUtf8("comboBoxRegion"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxRegion)
        self.comboBoxDistrict = QtGui.QComboBox(self.groupBox)
        self.comboBoxDistrict.setObjectName(_fromUtf8("comboBoxDistrict"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxDistrict)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.comboBoxCommune = QtGui.QComboBox(self.groupBox)
        self.comboBoxCommune.setObjectName(_fromUtf8("comboBoxCommune"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxCommune)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButtonAjouter = QtGui.QPushButton(self.groupBox)
        self.pushButtonAjouter.setEnabled(False)
        self.pushButtonAjouter.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/if_arrow-right-01_186409.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAjouter.setIcon(icon)
        self.pushButtonAjouter.setObjectName(_fromUtf8("pushButtonAjouter"))
        self.verticalLayout_2.addWidget(self.pushButtonAjouter)
        self.pushButtonSupprimer = QtGui.QPushButton(self.groupBox)
        self.pushButtonSupprimer.setEnabled(False)
        self.pushButtonSupprimer.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/if_arrow-left-01_186410.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSupprimer.setIcon(icon1)
        self.pushButtonSupprimer.setObjectName(_fromUtf8("pushButtonSupprimer"))
        self.verticalLayout_2.addWidget(self.pushButtonSupprimer)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.listWidgetCommunes = QtGui.QListWidget(self.groupBox)
        self.listWidgetCommunes.setMinimumSize(QtCore.QSize(0, 161))
        self.listWidgetCommunes.setMaximumSize(QtCore.QSize(195, 16777215))
        self.listWidgetCommunes.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetCommunes.setObjectName(_fromUtf8("listWidgetCommunes"))
        self.horizontalLayout_2.addWidget(self.listWidgetCommunes)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonEnregistrer = QtGui.QPushButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEnregistrer.setIcon(icon2)
        self.pushButtonEnregistrer.setObjectName(_fromUtf8("pushButtonEnregistrer"))
        self.horizontalLayout.addWidget(self.pushButtonEnregistrer)
        self.pushButtonAnnuler = QtGui.QPushButton(Dialog)
        self.pushButtonAnnuler.setObjectName(_fromUtf8("pushButtonAnnuler"))
        self.horizontalLayout.addWidget(self.pushButtonAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditNomProjet, self.dateEditDateLancement)
        Dialog.setTabOrder(self.dateEditDateLancement, self.dateEditDatePremierImport)
        Dialog.setTabOrder(self.dateEditDatePremierImport, self.dateEditDateDernierImport)
        Dialog.setTabOrder(self.dateEditDateDernierImport, self.comboBoxRegion)
        Dialog.setTabOrder(self.comboBoxRegion, self.comboBoxDistrict)
        Dialog.setTabOrder(self.comboBoxDistrict, self.comboBoxCommune)
        Dialog.setTabOrder(self.comboBoxCommune, self.pushButtonAjouter)
        Dialog.setTabOrder(self.pushButtonAjouter, self.pushButtonSupprimer)
        Dialog.setTabOrder(self.pushButtonSupprimer, self.pushButtonEnregistrer)
        Dialog.setTabOrder(self.pushButtonEnregistrer, self.pushButtonAnnuler)
        Dialog.setTabOrder(self.pushButtonAnnuler, self.listWidgetCommunes)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Nouveau Projet", None))
        self.groupbox.setTitle(_translate("Dialog", "Caractéristiques", None))
        self.label.setText(_translate("Dialog", "Nom du Projet", None))
        self.label_2.setText(_translate("Dialog", "Date de Lancement", None))
        self.label_3.setText(_translate("Dialog", "Date Premier Import", None))
        self.label_4.setText(_translate("Dialog", "Date Dernier Import", None))
        self.groupBox.setTitle(_translate("Dialog", "Communes", None))
        self.label_5.setText(_translate("Dialog", "Région", None))
        self.label_6.setText(_translate("Dialog", "District", None))
        self.label_7.setText(_translate("Dialog", "Commune", None))
        self.pushButtonEnregistrer.setText(_translate("Dialog", "Enregistrer", None))
        self.pushButtonAnnuler.setText(_translate("Dialog", "Annuler", None))

import icons_rc
