# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestionProfil.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(435, 481)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 391, 61))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.labelProfil = QtGui.QLabel(self.groupBox)
        self.labelProfil.setGeometry(QtCore.QRect(20, 20, 71, 20))
        self.labelProfil.setObjectName(_fromUtf8("labelProfil"))
        self.comboProfil = QtGui.QComboBox(self.groupBox)
        self.comboProfil.setGeometry(QtCore.QRect(100, 20, 251, 22))
        self.comboProfil.setObjectName(_fromUtf8("comboProfil"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 90, 391, 131))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.NomProfil = QtGui.QLabel(self.groupBox_2)
        self.NomProfil.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.NomProfil.setObjectName(_fromUtf8("NomProfil"))
        self.lineEditProfil = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditProfil.setGeometry(QtCore.QRect(100, 10, 241, 20))
        self.lineEditProfil.setObjectName(_fromUtf8("lineEditProfil"))
        self.labelRemarques = QtGui.QLabel(self.groupBox_2)
        self.labelRemarques.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.labelRemarques.setObjectName(_fromUtf8("labelRemarques"))
        self.Remarques = QtGui.QTextEdit(self.groupBox_2)
        self.Remarques.setGeometry(QtCore.QRect(100, 40, 241, 71))
        self.Remarques.setObjectName(_fromUtf8("Remarques"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 230, 391, 181))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.chkRien = QtGui.QCheckBox(self.tab_7)
        self.chkRien.setGeometry(QtCore.QRect(10, 10, 70, 17))
        self.chkRien.setObjectName(_fromUtf8("chkRien"))
        self.chkTous = QtGui.QCheckBox(self.tab_7)
        self.chkTous.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.chkTous.setObjectName(_fromUtf8("chkTous"))
        self.chkCreation = QtGui.QCheckBox(self.tab_7)
        self.chkCreation.setGeometry(QtCore.QRect(10, 70, 70, 17))
        self.chkCreation.setObjectName(_fromUtf8("chkCreation"))
        self.chkConsultation = QtGui.QCheckBox(self.tab_7)
        self.chkConsultation.setGeometry(QtCore.QRect(10, 90, 81, 17))
        self.chkConsultation.setObjectName(_fromUtf8("chkConsultation"))
        self.chkEdition = QtGui.QCheckBox(self.tab_7)
        self.chkEdition.setGeometry(QtCore.QRect(10, 110, 70, 17))
        self.chkEdition.setObjectName(_fromUtf8("chkEdition"))
        self.chkSuppression = QtGui.QCheckBox(self.tab_7)
        self.chkSuppression.setGeometry(QtCore.QRect(110, 10, 81, 17))
        self.chkSuppression.setObjectName(_fromUtf8("chkSuppression"))
        self.chkImpression = QtGui.QCheckBox(self.tab_7)
        self.chkImpression.setGeometry(QtCore.QRect(110, 30, 81, 17))
        self.chkImpression.setObjectName(_fromUtf8("chkImpression"))
        self.chkReImpression = QtGui.QCheckBox(self.tab_7)
        self.chkReImpression.setGeometry(QtCore.QRect(110, 50, 91, 17))
        self.chkReImpression.setObjectName(_fromUtf8("chkReImpression"))
        self.chkOpsSubsequentes = QtGui.QCheckBox(self.tab_7)
        self.chkOpsSubsequentes.setGeometry(QtCore.QRect(110, 70, 151, 17))
        self.chkOpsSubsequentes.setObjectName(_fromUtf8("chkOpsSubsequentes"))
        self.chkExportHTML = QtGui.QCheckBox(self.tab_7)
        self.chkExportHTML.setGeometry(QtCore.QRect(110, 110, 91, 17))
        self.chkExportHTML.setObjectName(_fromUtf8("chkExportHTML"))
        self.chkAttestation = QtGui.QCheckBox(self.tab_7)
        self.chkAttestation.setGeometry(QtCore.QRect(230, 10, 121, 17))
        self.chkAttestation.setObjectName(_fromUtf8("chkAttestation"))
        self.chkDecoupage = QtGui.QCheckBox(self.tab_7)
        self.chkDecoupage.setGeometry(QtCore.QRect(230, 30, 121, 17))
        self.chkDecoupage.setObjectName(_fromUtf8("chkDecoupage"))
        self.chkExtraitPlan = QtGui.QCheckBox(self.tab_7)
        self.chkExtraitPlan.setGeometry(QtCore.QRect(230, 50, 91, 17))
        self.chkExtraitPlan.setObjectName(_fromUtf8("chkExtraitPlan"))
        self.chkListePersonne = QtGui.QCheckBox(self.tab_7)
        self.chkListePersonne.setGeometry(QtCore.QRect(230, 90, 111, 17))
        self.chkListePersonne.setObjectName(_fromUtf8("chkListePersonne"))
        self.chkListeActes = QtGui.QCheckBox(self.tab_7)
        self.chkListeActes.setGeometry(QtCore.QRect(230, 110, 70, 17))
        self.chkListeActes.setObjectName(_fromUtf8("chkListeActes"))
        self.Annulation = QtGui.QCheckBox(self.tab_7)
        self.Annulation.setGeometry(QtCore.QRect(230, 130, 91, 17))
        self.Annulation.setObjectName(_fromUtf8("Annulation"))
        self.chkRien.raise_()
        self.chkTous.raise_()
        self.chkCreation.raise_()
        self.chkConsultation.raise_()
        self.chkEdition.raise_()
        self.chkSuppression.raise_()
        self.chkImpression.raise_()
        self.chkReImpression.raise_()
        self.chkOpsSubsequentes.raise_()
        self.chkExportHTML.raise_()
        self.chkAttestation.raise_()
        self.chkDecoupage.raise_()
        self.chkExtraitPlan.raise_()
        self.chkListePersonne.raise_()
        self.chkListeActes.raise_()
        self.Annulation.raise_()
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 430, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 430, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 430, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 410, 131, 51))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 51, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 20, 51, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_3.clicked.connect(self.createNouveauProfil)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        
    def  createNouveauProfil (self):
        from NouveauProfilRun import NouveauProfilRunn
        np = NouveauProfilRunn()
        result = np.exec_() 
    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.labelProfil.setText(_translate("Dialog", "Profil :", None))
        self.NomProfil.setText(_translate("Dialog", "Nom profil :", None))
        self.labelRemarques.setText(_translate("Dialog", "Remarques :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Certificat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Demande Certificat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Propositions", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "DDSF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Liste", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Impression", None))
        self.chkRien.setText(_translate("Dialog", "RIEN", None))
        self.chkTous.setText(_translate("Dialog", "TOUS", None))
        self.chkCreation.setText(_translate("Dialog", "Creation", None))
        self.chkConsultation.setText(_translate("Dialog", "Consultation", None))
        self.chkEdition.setText(_translate("Dialog", "Edition", None))
        self.chkSuppression.setText(_translate("Dialog", "Suppression", None))
        self.chkImpression.setText(_translate("Dialog", "Impression", None))
        self.chkReImpression.setText(_translate("Dialog", "ReImpression", None))
        self.chkOpsSubsequentes.setText(_translate("Dialog", "Operations Subsequentes", None))
        self.chkExportHTML.setText(_translate("Dialog", "Export HTML", None))
        self.chkAttestation.setText(_translate("Dialog", "Attestation juridique", None))
        self.chkDecoupage.setText(_translate("Dialog", "Decoupage parcelle", None))
        self.chkExtraitPlan.setText(_translate("Dialog", "Extrait plan", None))
        self.chkListePersonne.setText(_translate("Dialog", "Liste personnes", None))
        self.chkListeActes.setText(_translate("Dialog", "Liste actes", None))
        self.Annulation.setText(_translate("Dialog", "Annulation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Administration", None))
        self.pushButton.setText(_translate("Dialog", "Supprimer", None))
        self.pushButton_2.setText(_translate("Dialog", "Modifier", None))
        self.pushButton_3.setText(_translate("Dialog", "Nouveau", None))
        self.pushButton_4.setText(_translate("Dialog", "Annuler", None))
        self.pushButton_5.setText(_translate("Dialog", "Fermer", None))

