# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EtatAffichage.ui'
#
# Created: Tue Jun 13 10:26:54 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(828, 499)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBoxNumDemande = QtGui.QCheckBox(Dialog)
        self.checkBoxNumDemande.setObjectName(_fromUtf8("checkBoxNumDemande"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxNumDemande)
        self.lineEditNumDemande = QtGui.QLineEdit(Dialog)
        self.lineEditNumDemande.setObjectName(_fromUtf8("lineEditNumDemande"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNumDemande)
        self.checkBoxDateDemande = QtGui.QCheckBox(Dialog)
        self.checkBoxDateDemande.setObjectName(_fromUtf8("checkBoxDateDemande"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkBoxDateDemande)
        self.dateEditDemande = QtGui.QDateEdit(Dialog)
        self.dateEditDemande.setCalendarPopup(True)
        self.dateEditDemande.setObjectName(_fromUtf8("dateEditDemande"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dateEditDemande)
        self.checkBoxDemandeur = QtGui.QCheckBox(Dialog)
        self.checkBoxDemandeur.setObjectName(_fromUtf8("checkBoxDemandeur"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.checkBoxDemandeur)
        self.lineEditDemandeur = QtGui.QLineEdit(Dialog)
        self.lineEditDemandeur.setObjectName(_fromUtf8("lineEditDemandeur"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditDemandeur)
        self.checkBoxHameau = QtGui.QCheckBox(Dialog)
        self.checkBoxHameau.setObjectName(_fromUtf8("checkBoxHameau"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.checkBoxHameau)
        self.lineEditHameau = QtGui.QLineEdit(Dialog)
        self.lineEditHameau.setObjectName(_fromUtf8("lineEditHameau"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditHameau)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditCommune = QtGui.QLineEdit(Dialog)
        self.lineEditCommune.setEnabled(False)
        self.lineEditCommune.setObjectName(_fromUtf8("lineEditCommune"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditCommune)
        self.lineEditNumDecision = QtGui.QLineEdit(Dialog)
        self.lineEditNumDecision.setObjectName(_fromUtf8("lineEditNumDecision"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNumDecision)
        self.checkBoxNumDecision = QtGui.QCheckBox(Dialog)
        self.checkBoxNumDecision.setObjectName(_fromUtf8("checkBoxNumDecision"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxNumDecision)
        self.checkBoxDateDecision = QtGui.QCheckBox(Dialog)
        self.checkBoxDateDecision.setObjectName(_fromUtf8("checkBoxDateDecision"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBoxDateDecision)
        self.dateEditDecision = QtGui.QDateEdit(Dialog)
        self.dateEditDecision.setCalendarPopup(True)
        self.dateEditDecision.setObjectName(_fromUtf8("dateEditDecision"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateEditDecision)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonFind = QtGui.QPushButton(Dialog)
        self.pushButtonFind.setObjectName(_fromUtf8("pushButtonFind"))
        self.horizontalLayout_3.addWidget(self.pushButtonFind)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.checkBoxCheckAll = QtGui.QCheckBox(Dialog)
        self.checkBoxCheckAll.setObjectName(_fromUtf8("checkBoxCheckAll"))
        self.verticalLayout.addWidget(self.checkBoxCheckAll)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonFirst = QtGui.QPushButton(Dialog)
        self.pushButtonFirst.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFirst.setIcon(icon)
        self.pushButtonFirst.setObjectName(_fromUtf8("pushButtonFirst"))
        self.horizontalLayout_2.addWidget(self.pushButtonFirst)
        self.pushButtonPrevious = QtGui.QPushButton(Dialog)
        self.pushButtonPrevious.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPrevious.setIcon(icon1)
        self.pushButtonPrevious.setObjectName(_fromUtf8("pushButtonPrevious"))
        self.horizontalLayout_2.addWidget(self.pushButtonPrevious)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.labelCurrent = QtGui.QLabel(Dialog)
        self.labelCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrent.setObjectName(_fromUtf8("labelCurrent"))
        self.horizontalLayout_2.addWidget(self.labelCurrent)
        self.comboBoxPages = QtGui.QComboBox(Dialog)
        self.comboBoxPages.setObjectName(_fromUtf8("comboBoxPages"))
        self.horizontalLayout_2.addWidget(self.comboBoxPages)
        self.pushButtonNext = QtGui.QPushButton(Dialog)
        self.pushButtonNext.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNext.setIcon(icon2)
        self.pushButtonNext.setObjectName(_fromUtf8("pushButtonNext"))
        self.horizontalLayout_2.addWidget(self.pushButtonNext)
        self.pushButtonLast = QtGui.QPushButton(Dialog)
        self.pushButtonLast.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLast.setIcon(icon3)
        self.pushButtonLast.setObjectName(_fromUtf8("pushButtonLast"))
        self.horizontalLayout_2.addWidget(self.pushButtonLast)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonPrint = QtGui.QPushButton(Dialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/printer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPrint.setIcon(icon4)
        self.pushButtonPrint.setDefault(True)
        self.pushButtonPrint.setObjectName(_fromUtf8("pushButtonPrint"))
        self.horizontalLayout.addWidget(self.pushButtonPrint)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setAutoDefault(False)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Etat - Affichage", None))
        self.checkBoxNumDemande.setText(_translate("Dialog", "Num Demande", None))
        self.checkBoxDateDemande.setText(_translate("Dialog", "Date de Demande", None))
        self.checkBoxDemandeur.setText(_translate("Dialog", "Demandeur", None))
        self.checkBoxHameau.setText(_translate("Dialog", "Hameau", None))
        self.label.setText(_translate("Dialog", "Commune", None))
        self.checkBoxNumDecision.setText(_translate("Dialog", "Numero Décision", None))
        self.checkBoxDateDecision.setText(_translate("Dialog", "Date Décision", None))
        self.pushButtonFind.setText(_translate("Dialog", "Rechercher", None))
        self.checkBoxCheckAll.setText(_translate("Dialog", "Tout Cocher", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Fangatahana N.", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Daty", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Mpangataka", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Adiresy", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Mpifanila", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Hameau", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Velarany", None))
        self.label_2.setText(_translate("Dialog", "Page : ", None))
        self.labelCurrent.setText(_translate("Dialog", "TextLabel", None))
        self.pushButtonPrint.setText(_translate("Dialog", "Imprimer", None))
        self.pushButtonCancel.setText(_translate("Dialog", "Annuler", None))

import icons_rc
