# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConsultationDemande.ui'
#
# Created: Tue Dec 12 03:43:33 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(552, 409)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dateEditDateReconnaissance = QtGui.QDateEdit(Dialog)
        #self.dateEditDateDemande.setEnabled(False)
        self.dateEditDateReconnaissance.setCalendarPopup(True)
        self.dateEditDateReconnaissance.setObjectName(_fromUtf8("dateEditDateReconnaissance"))
        #self.lineEditDateReconnaissance = QtGui.QLineEdit(Dialog)
        #self.lineEditDateReconnaissance.setObjectName(_fromUtf8("lineEditDateReconnaissance"))
        self.gridLayout.addWidget(self.dateEditDateReconnaissance, 2, 1, 1, 1)
        self.dateEditDateDemande = QtGui.QDateEdit(Dialog)
        self.dateEditDateDemande.setCalendarPopup(True)
        self.dateEditDateDemande.setObjectName(_fromUtf8("dateEditDateDemande"))
        self.gridLayout.addWidget(self.dateEditDateDemande, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.comboBoxConsistance = QtGui.QComboBox(Dialog)
        self.comboBoxConsistance.setObjectName(_fromUtf8("comboBoxConsistance"))
        self.gridLayout.addWidget(self.comboBoxConsistance, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditPrix = QtGui.QLineEdit(Dialog)
        self.lineEditPrix.setObjectName(_fromUtf8("lineEditPrix"))
        self.gridLayout.addWidget(self.lineEditPrix, 4, 1, 1, 1)
        self.lineEditEtat = QtGui.QLineEdit(Dialog)
        self.lineEditEtat.setObjectName(_fromUtf8("lineEditEtat"))
        self.gridLayout.addWidget(self.lineEditEtat, 5, 1, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditNumDemande = QtGui.QLineEdit(Dialog)
        self.lineEditNumDemande.setObjectName(_fromUtf8("lineEditNumDemande"))
        self.gridLayout.addWidget(self.lineEditNumDemande, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_2 = QtGui.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.frame_2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.rGionLabel = QtGui.QLabel(self.groupBox)
        self.rGionLabel.setObjectName(_fromUtf8("rGionLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.rGionLabel)
        self.rGionComboBox = QtGui.QComboBox(self.groupBox)
        self.rGionComboBox.setObjectName(_fromUtf8("rGionComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.rGionComboBox)
        self.districtLabel = QtGui.QLabel(self.groupBox)
        self.districtLabel.setObjectName(_fromUtf8("districtLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.districtLabel)
        self.districtComboBox = QtGui.QComboBox(self.groupBox)
        self.districtComboBox.setObjectName(_fromUtf8("districtComboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.districtComboBox)
        self.communeLabel = QtGui.QLabel(self.groupBox)
        self.communeLabel.setObjectName(_fromUtf8("communeLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.communeLabel)
        self.communeComboBox = QtGui.QComboBox(self.groupBox)
        self.communeComboBox.setObjectName(_fromUtf8("communeComboBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.communeComboBox)
        self.fokontanyLabel = QtGui.QLabel(self.groupBox)
        self.fokontanyLabel.setObjectName(_fromUtf8("fokontanyLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.fokontanyLabel)
        self.fokontanyComboBox = QtGui.QComboBox(self.groupBox)
        self.fokontanyComboBox.setObjectName(_fromUtf8("fokontanyComboBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.fokontanyComboBox)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_4)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_4 = QtGui.QPushButton(self.frame_4)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.checkBox = QtGui.QCheckBox(self.frame_4)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Consultation Demande", None))
        self.label_6.setText(_translate("Dialog", "Etat", None))
        self.label_5.setText(_translate("Dialog", "Cout", None))
        self.label_2.setText(_translate("Dialog", "Date demande", None))
        self.label.setText(_translate("Dialog", "Numéro delmande", None))
        self.label_3.setText(_translate("Dialog", "Date de reconnaissance", None))
        self.label_4.setText(_translate("Dialog", "Consistance", None))
        self.label_7.setText(_translate("Dialog", "Ar", None))
        self.pushButton_2.setText(_translate("Dialog", "Oppositions", None))
        self.pushButton.setText(_translate("Dialog", "Demandeurs", None))
        self.groupBox.setTitle(_translate("Dialog", "Localisation", None))
        self.rGionLabel.setText(_translate("Dialog", "Région", None))
        self.districtLabel.setText(_translate("Dialog", "District", None))
        self.communeLabel.setText(_translate("Dialog", "Commune", None))
        self.fokontanyLabel.setText(_translate("Dialog", "Fokontany", None))
        self.pushButton_5.setText(_translate("Dialog", "Aide", None))
        self.pushButton_4.setText(_translate("Dialog", "Export Html", None))
        self.pushButton_3.setText(_translate("Dialog", "Fermer", None))

