# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\FIPLOF-010820222\trunk\Admin\RechercheDmdeCert.ui'
#
# Created: Thu Aug 24 01:55:16 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(538, 453)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plof/icone/certificate_01.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxAu = QtGui.QCheckBox(self.groupBox)
        self.checkBoxAu.setObjectName(_fromUtf8("checkBoxAu"))
        self.gridLayout.addWidget(self.checkBoxAu, 4, 0, 1, 1)
        self.checkBoxDu = QtGui.QCheckBox(self.groupBox)
        self.checkBoxDu.setObjectName(_fromUtf8("checkBoxDu"))
        self.gridLayout.addWidget(self.checkBoxDu, 3, 0, 1, 1)
        self.dateEditDateDemande = QtGui.QDateEdit(self.groupBox)
        self.dateEditDateDemande.setEnabled(False)
        self.dateEditDateDemande.setCalendarPopup(True)
        self.dateEditDateDemande.setObjectName(_fromUtf8("dateEditDateDemande"))
        self.gridLayout.addWidget(self.dateEditDateDemande, 3, 1, 1, 1)
        self.dateEditDateDemandeFin = QtGui.QDateEdit(self.groupBox)
        self.dateEditDateDemandeFin.setEnabled(False)
        self.dateEditDateDemandeFin.setCalendarPopup(True)
        self.dateEditDateDemandeFin.setObjectName(_fromUtf8("dateEditDateDemandeFin"))
        self.gridLayout.addWidget(self.dateEditDateDemandeFin, 4, 1, 1, 1)
        self.checkBoxNumDemande = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumDemande.setObjectName(_fromUtf8("checkBoxNumDemande"))
        self.gridLayout.addWidget(self.checkBoxNumDemande, 0, 0, 1, 1)
        self.lineEditNumDemande = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumDemande.setEnabled(False)
        self.lineEditNumDemande.setObjectName(_fromUtf8("lineEditNumDemande"))
        self.gridLayout.addWidget(self.lineEditNumDemande, 0, 1, 1, 1)
        self.lineEditNomDemandeur = QtGui.QLineEdit(self.groupBox)
        self.lineEditNomDemandeur.setEnabled(False)
        self.lineEditNomDemandeur.setObjectName(_fromUtf8("lineEditNomDemandeur"))
        self.gridLayout.addWidget(self.lineEditNomDemandeur, 2, 1, 1, 1)
        self.checkBoxFokontany = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFokontany.setObjectName(_fromUtf8("checkBoxFokontany"))
        self.gridLayout.addWidget(self.checkBoxFokontany, 5, 0, 1, 1)
        self.checkBoxNomDemandeur = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNomDemandeur.setObjectName(_fromUtf8("checkBoxNomDemandeur"))
        self.gridLayout.addWidget(self.checkBoxNomDemandeur, 2, 0, 1, 1)
        self.comboBoxFokotany = QtGui.QComboBox(self.groupBox)
        self.comboBoxFokotany.setEnabled(False)
        self.comboBoxFokotany.setObjectName(_fromUtf8("comboBoxFokotany"))
        self.gridLayout.addWidget(self.comboBoxFokotany, 5, 1, 1, 1)
        self.checkBoxCF = QtGui.QCheckBox(self.groupBox)
        self.checkBoxCF.setObjectName(_fromUtf8("checkBoxCF"))
        self.gridLayout.addWidget(self.checkBoxCF, 1, 0, 1, 1)
        self.lineEditCF = QtGui.QLineEdit(self.groupBox)
        self.lineEditCF.setObjectName(_fromUtf8("lineEditCF"))
        self.gridLayout.addWidget(self.lineEditCF, 1, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAfficherTous = QtGui.QPushButton(self.frame)
        self.btnAfficherTous.setObjectName(_fromUtf8("btnAfficherTous"))
        self.horizontalLayout.addWidget(self.btnAfficherTous)
        self.btnRechercher = QtGui.QPushButton(self.frame)
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.horizontalLayout.addWidget(self.btnRechercher)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.frame_3)
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(168)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnDebut = QtGui.QPushButton(self.frame_3)
        self.btnDebut.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDebut.setIcon(icon1)
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.horizontalLayout_5.addWidget(self.btnDebut)
        self.btnPrecedent = QtGui.QPushButton(self.frame_3)
        self.btnPrecedent.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrecedent.setIcon(icon2)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.horizontalLayout_5.addWidget(self.btnPrecedent)
        self.lineEditNumPage = QtGui.QLineEdit(self.frame_3)
        self.lineEditNumPage.setEnabled(False)
        self.lineEditNumPage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditNumPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditNumPage.setObjectName(_fromUtf8("lineEditNumPage"))
        self.horizontalLayout_5.addWidget(self.lineEditNumPage)
        self.comboBoxNumPage = QtGui.QComboBox(self.frame_3)
        self.comboBoxNumPage.setObjectName(_fromUtf8("comboBoxNumPage"))
        self.horizontalLayout_5.addWidget(self.comboBoxNumPage)
        self.btnSuivant = QtGui.QPushButton(self.frame_3)
        self.btnSuivant.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuivant.setIcon(icon3)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.horizontalLayout_5.addWidget(self.btnSuivant)
        self.btnFin = QtGui.QPushButton(self.frame_3)
        self.btnFin.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFin.setIcon(icon4)
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.horizontalLayout_5.addWidget(self.btnFin)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnDetail = QtGui.QPushButton(Dialog)
        self.btnDetail.setObjectName(_fromUtf8("btnDetail"))
        self.horizontalLayout_3.addWidget(self.btnDetail)
        self.btnDelDemande = QtGui.QPushButton(Dialog)
        self.btnDelDemande.setObjectName(_fromUtf8("btnDelDemande"))
        self.horizontalLayout_3.addWidget(self.btnDelDemande)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_3.addWidget(self.btnFermer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Recherche demande certificat", None))
        self.groupBox.setTitle(_translate("Dialog", "Recherche", None))
        self.checkBoxAu.setText(_translate("Dialog", "Au", None))
        self.checkBoxDu.setText(_translate("Dialog", "Du (Date Demande)", None))
        self.checkBoxNumDemande.setText(_translate("Dialog", "Numéro Demande", None))
        self.checkBoxFokontany.setText(_translate("Dialog", "Fokontany", None))
        self.checkBoxNomDemandeur.setText(_translate("Dialog", "Nom Demandeur", None))
        self.checkBoxCF.setText(_translate("Dialog", "Numéro Certificat", None))
        self.btnAfficherTous.setText(_translate("Dialog", "Afficher tous", None))
        self.btnRechercher.setText(_translate("Dialog", "Rechercher", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "N° demande", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Date demande", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date de reconnaissance", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Cout à la demande", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Liste Demandeur", None))
        self.btnDetail.setText(_translate("Dialog", "Details", None))
        self.btnDelDemande.setText(_translate("Dialog", "Valider Suppression ", None))
        self.btnFermer.setText(_translate("Dialog", "Fermer", None))

import icons_rc
