# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreaDemande.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreationDemande(object):
    def setupUi(self, CreationDemande):
        CreationDemande.setObjectName(_fromUtf8("CreationDemande"))
        CreationDemande.setEnabled(True)
        CreationDemande.resize(536, 493)
        self.groupBox = QtGui.QGroupBox(CreationDemande)
        self.groupBox.setGeometry(QtCore.QRect(10, 260, 401, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.NomRegion = QtGui.QLineEdit(self.groupBox)
        self.NomRegion.setEnabled(False)
        self.NomRegion.setGeometry(QtCore.QRect(190, 20, 171, 20))
        self.NomRegion.setObjectName(_fromUtf8("NomRegion"))
        self.NomDistrict = QtGui.QLineEdit(self.groupBox)
        self.NomDistrict.setEnabled(False)
        self.NomDistrict.setGeometry(QtCore.QRect(190, 50, 171, 20))
        self.NomDistrict.setDragEnabled(True)
        self.NomDistrict.setObjectName(_fromUtf8("NomDistrict"))
        self.NomCommune = QtGui.QLineEdit(self.groupBox)
        self.NomCommune.setGeometry(QtCore.QRect(190, 80, 171, 20))
        self.NomCommune.setObjectName(_fromUtf8("NomCommune"))
        self.NomFokontany = QtGui.QComboBox(self.groupBox)
        self.NomFokontany.setGeometry(QtCore.QRect(190, 110, 171, 22))
        self.NomFokontany.setEditable(True)
        self.NomFokontany.setObjectName(_fromUtf8("NomFokontany"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(50, 20, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(50, 50, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(50, 80, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(50, 110, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.BtValider = QtGui.QPushButton(CreationDemande)
        self.BtValider.setGeometry(QtCore.QRect(250, 430, 75, 23))
        self.BtValider.setObjectName(_fromUtf8("BtValider"))
        self.BtAnnuler = QtGui.QPushButton(CreationDemande)
        self.BtAnnuler.setGeometry(QtCore.QRect(340, 430, 75, 23))
        self.BtAnnuler.setObjectName(_fromUtf8("BtAnnuler"))
        self.groupBox_2 = QtGui.QGroupBox(CreationDemande)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 401, 191))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.LibConsistance = QtGui.QComboBox(self.groupBox_2)
        self.LibConsistance.setGeometry(QtCore.QRect(190, 100, 171, 22))
        self.LibConsistance.setObjectName(_fromUtf8("LibConsistance"))
        self.LibConsistance.addItem(_fromUtf8(""))
        self.LibConsistance.addItem(_fromUtf8(""))
        self.LibConsistance.addItem(_fromUtf8(""))
        self.LibConsistance.addItem(_fromUtf8(""))
        self.LibConsistance.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(50, 100, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.DateReconnaissance = QtGui.QDateEdit(self.groupBox_2)
        self.DateReconnaissance.setGeometry(QtCore.QRect(190, 70, 171, 22))
        self.DateReconnaissance.setObjectName(_fromUtf8("DateReconnaissance"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.NumeroDemande = QtGui.QLineEdit(self.groupBox_2)
        self.NumeroDemande.setGeometry(QtCore.QRect(190, 10, 171, 20))
        self.NumeroDemande.setObjectName(_fromUtf8("NumeroDemande"))
        self.Demandeur = QtGui.QLineEdit(self.groupBox_2)
        self.Demandeur.setGeometry(QtCore.QRect(190, 160, 171, 20))
        self.Demandeur.setObjectName(_fromUtf8("Demandeur"))
        self.DateDemande = QtGui.QDateEdit(self.groupBox_2)
        self.DateDemande.setGeometry(QtCore.QRect(190, 40, 171, 22))
        self.DateDemande.setObjectName(_fromUtf8("DateDemande"))
        self.cout = QtGui.QLineEdit(self.groupBox_2)
        self.cout.setGeometry(QtCore.QRect(190, 130, 171, 20))
        self.cout.setObjectName(_fromUtf8("cout"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(50, 160, 101, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 131, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(50, 10, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(CreationDemande)
        self.pushButton.setGeometry(QtCore.QRect(430, 100, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox_3 = QtGui.QGroupBox(CreationDemande)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 200, 401, 61))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 20, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))

        self.retranslateUi(CreationDemande)
        QtCore.QObject.connect(self.BtValider, QtCore.SIGNAL(_fromUtf8("clicked()")), CreationDemande.update)
        QtCore.QMetaObject.connectSlotsByName(CreationDemande)

    def retranslateUi(self, CreationDemande):
        CreationDemande.setWindowTitle(_translate("CreationDemande", "Création de la demande", None))
        self.groupBox.setTitle(_translate("CreationDemande", "Localisation", None))
        self.label_6.setText(_translate("CreationDemande", "Région : ", None))
        self.label_7.setText(_translate("CreationDemande", "District : ", None))
        self.label_8.setText(_translate("CreationDemande", "Commune :", None))
        self.label_9.setText(_translate("CreationDemande", "Fokontany : ", None))
        self.BtValider.setText(_translate("CreationDemande", "Valider", None))
        self.BtAnnuler.setText(_translate("CreationDemande", "Annuler", None))
        self.LibConsistance.setItemText(0, _translate("CreationDemande", "ALA  SY DOBO", None))
        self.LibConsistance.setItemText(1, _translate("CreationDemande", "HAFA", None))
        self.LibConsistance.setItemText(2, _translate("CreationDemande", "TANETY SY TANY LAVA VOLO", None))
        self.LibConsistance.setItemText(3, _translate("CreationDemande", "TANIMBOLY", None))
        self.LibConsistance.setItemText(4, _translate("CreationDemande", "TANIMBARY", None))
        self.label_4.setText(_translate("CreationDemande", "Consistance : ", None))
        self.label_2.setText(_translate("CreationDemande", "Date de création :", None))
        self.label_10.setText(_translate("CreationDemande", "Demandeur : ", None))
        self.label_3.setText(_translate("CreationDemande", "Date de reconnaissance : ", None))
        self.label_5.setText(_translate("CreationDemande", "Coût :", None))
        self.label.setText(_translate("CreationDemande", "Numero demande :", None))
        self.pushButton.setText(_translate("CreationDemande", "Liste", None))
        self.pushButton_2.setText(_translate("CreationDemande", "Oppositions", None))
        self.pushButton_3.setText(_translate("CreationDemande", "Demandeurs", None))

