# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creationInitiale.ui'
#
# Created: Thu Jun 02 10:03:50 2022
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(857, 520)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 0, 471, 131))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 121))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.lineEditNumCert = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditNumCert.setObjectName(_fromUtf8("lineEditNumCert"))
        self.gridLayout.addWidget(self.lineEditNumCert, 1, 2, 1, 1)
        self.btnListeConsist = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnListeConsist.setObjectName(_fromUtf8("btnListeConsist"))
        self.gridLayout.addWidget(self.btnListeConsist, 3, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBoxTypeCert = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxTypeCert.setObjectName(_fromUtf8("comboBoxTypeCert"))
        self.comboBoxTypeCert.addItem(_fromUtf8(""))
        self.comboBoxTypeCert.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxTypeCert, 0, 2, 1, 1)
        self.lineEditNumDemande = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditNumDemande.setObjectName(_fromUtf8("lineEditNumDemande"))
        self.gridLayout.addWidget(self.lineEditNumDemande, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxConsist = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxConsist.setObjectName(_fromUtf8("comboBoxConsist"))
        self.gridLayout.addWidget(self.comboBoxConsist, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 4, 2, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 150, 461, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEditSurface = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSurface.setObjectName(_fromUtf8("lineEditSurface"))
        self.horizontalLayout.addWidget(self.lineEditSurface)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEditHa = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditHa.setObjectName(_fromUtf8("lineEditHa"))
        self.horizontalLayout.addWidget(self.lineEditHa)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEditA = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditA.setObjectName(_fromUtf8("lineEditA"))
        self.horizontalLayout.addWidget(self.lineEditA)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEditCa = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCa.setObjectName(_fromUtf8("lineEditCa"))
        self.horizontalLayout.addWidget(self.lineEditCa)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 190, 461, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 431, 51))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.dateEditDateReconnaissance = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.dateEditDateReconnaissance.setCalendarPopup(True)
        self.dateEditDateReconnaissance.setObjectName(_fromUtf8("dateEditDateReconnaissance"))
        self.gridLayout_2.addWidget(self.dateEditDateReconnaissance, 0, 1, 1, 1)
        self.dateEditInscriptionReg = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.dateEditInscriptionReg.setCalendarPopup(True)
        self.dateEditInscriptionReg.setObjectName(_fromUtf8("dateEditInscriptionReg"))
        self.gridLayout_2.addWidget(self.dateEditInscriptionReg, 1, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 280, 461, 51))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.btnRepere = QtGui.QPushButton(self.frame_2)
        self.btnRepere.setGeometry(QtCore.QRect(350, 0, 95, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/marker--plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRepere.setIcon(icon)
        self.btnRepere.setObjectName(_fromUtf8("btnRepere"))
        self.btnCharges = QtGui.QPushButton(self.frame_2)
        self.btnCharges.setGeometry(QtCore.QRect(250, 0, 95, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/compass.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCharges.setIcon(icon1)
        self.btnCharges.setObjectName(_fromUtf8("btnCharges"))
        self.btnProprietaire = QtGui.QPushButton(self.frame_2)
        self.btnProprietaire.setGeometry(QtCore.QRect(150, 0, 95, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/users/icone/group.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProprietaire.setIcon(icon2)
        self.btnProprietaire.setObjectName(_fromUtf8("btnProprietaire"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 451, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 431, 131))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBoxFokontany = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout_3.addWidget(self.comboBoxFokontany, 3, 1, 1, 1)
        self.comboBoxCommune = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxCommune.setObjectName(_fromUtf8("comboBoxCommune"))
        self.gridLayout_3.addWidget(self.comboBoxCommune, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.comboBoxRegion = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxRegion.setObjectName(_fromUtf8("comboBoxRegion"))
        self.gridLayout_3.addWidget(self.comboBoxRegion, 0, 1, 1, 1)
        self.comboBoxDistrict = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxDistrict.setObjectName(_fromUtf8("comboBoxDistrict"))
        self.gridLayout_3.addWidget(self.comboBoxDistrict, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.comboBoxHameau = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.gridLayout_3.addWidget(self.comboBoxHameau, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.btnListeFokontany = QtGui.QToolButton(self.gridLayoutWidget_3)
        self.btnListeFokontany.setObjectName(_fromUtf8("btnListeFokontany"))
        self.gridLayout_3.addWidget(self.btnListeFokontany, 3, 2, 1, 1)
        self.btnListeHameau = QtGui.QToolButton(self.gridLayoutWidget_3)
        self.btnListeHameau.setObjectName(_fromUtf8("btnListeHameau"))
        self.gridLayout_3.addWidget(self.btnListeHameau, 4, 2, 1, 1)
        self.btnAnnuler_2 = QtGui.QPushButton(Dialog)
        self.btnAnnuler_2.setGeometry(QtCore.QRect(340, 480, 95, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_minus_10199.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAnnuler_2.setIcon(icon3)
        self.btnAnnuler_2.setObjectName(_fromUtf8("btnAnnuler_2"))
        self.btnCreate = QtGui.QPushButton(Dialog)
        self.btnCreate.setGeometry(QtCore.QRect(240, 480, 95, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/accept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreate.setIcon(icon4)
        self.btnCreate.setObjectName(_fromUtf8("btnCreate"))
        self.btnAide = QtGui.QPushButton(Dialog)
        self.btnAide.setGeometry(QtCore.QRect(140, 480, 95, 31))
        self.btnAide.setObjectName(_fromUtf8("btnAide"))
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(450, 480, 16, 26))
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(490, 10, 391, 301))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.frame_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 361, 301))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(500, 320, 151, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(490, 340, 361, 171))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Création initiale de certficat foncier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListeConsist.setText(QtGui.QApplication.translate("Dialog", "Liste", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Numéro demande", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTypeCert.setItemText(0, QtGui.QApplication.translate("Dialog", "Certificat foncier", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTypeCert.setItemText(1, QtGui.QApplication.translate("Dialog", "Attestation de reconnaissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Numéro certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Type certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Categorie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "m2 ou ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Ha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Ca", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Reconnaissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Inscription dans le registre", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRepere.setText(QtGui.QApplication.translate("Dialog", "Repères", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCharges.setText(QtGui.QApplication.translate("Dialog", "Charges", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProprietaire.setText(QtGui.QApplication.translate("Dialog", "Propriétaires", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Localisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Région", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "District", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Fokontany", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Hameau", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Commune", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListeFokontany.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListeHameau.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAnnuler_2.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreate.setText(QtGui.QApplication.translate("Dialog", "Créer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAide.setText(QtGui.QApplication.translate("Dialog", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Autres informations", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
