# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Statistiques.ui'
#
# Created: Sun Aug 12 10:56:25 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(654, 348)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.dateEditAnnee = QtGui.QDateEdit(Dialog)
        self.dateEditAnnee.setObjectName(_fromUtf8("dateEditAnnee"))
        self.horizontalLayout.addWidget(self.dateEditAnnee)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditNombreCertificat = QtGui.QLineEdit(Dialog)
        self.lineEditNombreCertificat.setEnabled(False)
        self.lineEditNombreCertificat.setObjectName(_fromUtf8("lineEditNombreCertificat"))
        self.horizontalLayout.addWidget(self.lineEditNombreCertificat)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditNombreContribuable = QtGui.QLineEdit(Dialog)
        self.lineEditNombreContribuable.setEnabled(False)
        self.lineEditNombreContribuable.setObjectName(_fromUtf8("lineEditNombreContribuable"))
        self.horizontalLayout.addWidget(self.lineEditNombreContribuable)
        self.btnRecalculImpot = QtGui.QPushButton(Dialog)
        self.btnRecalculImpot.setObjectName(_fromUtf8("btnRecalculImpot"))
        self.horizontalLayout.addWidget(self.btnRecalculImpot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.lineEditNombreparcelle = QtGui.QLineEdit(self.groupBox)
        self.lineEditNombreparcelle.setEnabled(False)
        self.lineEditNombreparcelle.setObjectName(_fromUtf8("lineEditNombreparcelle"))
        self.gridLayout.addWidget(self.lineEditNombreparcelle, 0, 1, 1, 1)
        self.lineEditHetra = QtGui.QLineEdit(self.groupBox)
        self.lineEditHetra.setEnabled(False)
        self.lineEditHetra.setObjectName(_fromUtf8("lineEditHetra"))
        self.gridLayout.addWidget(self.lineEditHetra, 0, 3, 1, 1)
        self.lineEditNombreSRA = QtGui.QLineEdit(self.groupBox)
        self.lineEditNombreSRA.setEnabled(False)
        self.lineEditNombreSRA.setObjectName(_fromUtf8("lineEditNombreSRA"))
        self.gridLayout.addWidget(self.lineEditNombreSRA, 1, 3, 1, 1)
        self.lineEditNombreSRI = QtGui.QLineEdit(self.groupBox)
        self.lineEditNombreSRI.setEnabled(False)
        self.lineEditNombreSRI.setObjectName(_fromUtf8("lineEditNombreSRI"))
        self.gridLayout.addWidget(self.lineEditNombreSRI, 1, 1, 1, 1)
        self.lineEditMontant = QtGui.QLineEdit(self.groupBox)
        self.lineEditMontant.setEnabled(False)
        self.lineEditMontant.setObjectName(_fromUtf8("lineEditMontant"))
        self.gridLayout.addWidget(self.lineEditMontant, 1, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableWidgetParFokonatany = QtGui.QTableWidget(self.tab)
        self.tableWidgetParFokonatany.setObjectName(_fromUtf8("tableWidgetParFokonatany"))
        self.tableWidgetParFokonatany.setColumnCount(9)
        self.tableWidgetParFokonatany.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParFokonatany.setHorizontalHeaderItem(8, item)
        self.verticalLayout_3.addWidget(self.tableWidgetParFokonatany)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidgetParConsistance = QtGui.QTableWidget(self.tab_2)
        self.tableWidgetParConsistance.setObjectName(_fromUtf8("tableWidgetParConsistance"))
        self.tableWidgetParConsistance.setColumnCount(3)
        self.tableWidgetParConsistance.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParConsistance.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParConsistance.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParConsistance.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidgetParConsistance)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnExportExcel = QtGui.QPushButton(Dialog)
        self.btnExportExcel.setObjectName(_fromUtf8("btnExportExcel"))
        self.horizontalLayout_2.addWidget(self.btnExportExcel)
        self.btnRafraichirStat = QtGui.QPushButton(Dialog)
        self.btnRafraichirStat.setObjectName(_fromUtf8("btnRafraichirStat"))
        self.horizontalLayout_2.addWidget(self.btnRafraichirStat)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Statistiques", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Année", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEditAnnee.setDisplayFormat(QtGui.QApplication.translate("Dialog", "yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Nombre certificats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Nombre contribuables", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRecalculImpot.setText(QtGui.QApplication.translate("Dialog", "Recalculer les impots", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Nombre parcelles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Nombre SRI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Nombre SRA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Hetra[Ar]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Montant", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Fokontany", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Nombre parcelles", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Nombre Certificats", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Certificats % Parcelles", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "Nombre contribuables", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog", "Nombre SRI", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog", "Nombre SRA", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog", "Nombre avec location", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParFokonatany.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog", "Montant location (Ar)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Par Fokontany", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParConsistance.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParConsistance.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Nombre parcelles", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetParConsistance.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Hetra", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Par consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportExcel.setText(QtGui.QApplication.translate("Dialog", "Export vers Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRafraichirStat.setText(QtGui.QApplication.translate("Dialog", "Rafraichir le statistique", None, QtGui.QApplication.UnicodeUTF8))

