# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RechercheDomainePublic.ui'
#
# Created: Sat Mar 17 04:19:04 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(485, 518)
        Dialog.setModal(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxType = QtGui.QCheckBox(self.groupBox)
        self.checkBoxType.setObjectName(_fromUtf8("checkBoxType"))
        self.gridLayout.addWidget(self.checkBoxType, 0, 0, 1, 1)
        self.checkBoxNom = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNom.setObjectName(_fromUtf8("checkBoxNom"))
        self.gridLayout.addWidget(self.checkBoxNom, 1, 0, 1, 1)
        self.lineEditNom = QtGui.QLineEdit(self.groupBox)
        self.lineEditNom.setEnabled(False)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.gridLayout.addWidget(self.lineEditNom, 1, 1, 1, 1)
        self.btnListe = QtGui.QPushButton(self.groupBox)
        self.btnListe.setObjectName(_fromUtf8("btnListe"))
        self.gridLayout.addWidget(self.btnListe, 0, 2, 1, 1)
        self.comboBoxType = QtGui.QComboBox(self.groupBox)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.gridLayout.addWidget(self.comboBoxType, 0, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAfficherTous = QtGui.QPushButton(self.frame)
        self.btnAfficherTous.setObjectName(_fromUtf8("btnAfficherTous"))
        self.horizontalLayout.addWidget(self.btnAfficherTous)
        self.btnRechercher = QtGui.QPushButton(self.frame)
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.horizontalLayout.addWidget(self.btnRechercher)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolBtnSelectionSurCarte = QtGui.QToolButton(self.groupBox_2)
        self.toolBtnSelectionSurCarte.setObjectName(_fromUtf8("toolBtnSelectionSurCarte"))
        self.horizontalLayout_2.addWidget(self.toolBtnSelectionSurCarte)
        self.toolBtnSelectionSurCarte_2 = QtGui.QToolButton(self.groupBox_2)
        self.toolBtnSelectionSurCarte_2.setObjectName(_fromUtf8("toolBtnSelectionSurCarte_2"))
        self.horizontalLayout_2.addWidget(self.toolBtnSelectionSurCarte_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.frame_3)
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(168)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnDetail = QtGui.QPushButton(Dialog)
        self.btnDetail.setObjectName(_fromUtf8("btnDetail"))
        self.horizontalLayout_3.addWidget(self.btnDetail)
        self.btnSelectionner = QtGui.QPushButton(Dialog)
        self.btnSelectionner.setObjectName(_fromUtf8("btnSelectionner"))
        self.horizontalLayout_3.addWidget(self.btnSelectionner)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_3.addWidget(self.btnFermer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Recherche d\'un domaine public", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxType.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNom.setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListe.setText(QtGui.QApplication.translate("Dialog", "Liste", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAfficherTous.setText(QtGui.QApplication.translate("Dialog", "Afficher tous", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRechercher.setText(QtGui.QApplication.translate("Dialog", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Selection sur la carte", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBtnSelectionSurCarte.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBtnSelectionSurCarte_2.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Origine de contour", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetail.setText(QtGui.QApplication.translate("Dialog", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectionner.setText(QtGui.QApplication.translate("Dialog", "Selectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))

