# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormGeoreferencer.ui'
#
# Created: Thu Aug 02 06:01:19 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FormGeoreferencer(object):
    def setupUi(self, FormGeoreferencer):
        FormGeoreferencer.setObjectName(_fromUtf8("FormGeoreferencer"))
        FormGeoreferencer.resize(593, 607)
        self.verticalLayout = QtGui.QVBoxLayout(FormGeoreferencer)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolbarFrame = QtGui.QFrame(FormGeoreferencer)
        self.toolbarFrame.setMaximumSize(QtCore.QSize(16777215, 32))
        self.toolbarFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolbarFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.toolbarFrame.setObjectName(_fromUtf8("toolbarFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.toolbarFrame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout.addWidget(self.toolbarFrame)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.frame = QtGui.QFrame(FormGeoreferencer)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxTransformation = QtGui.QComboBox(self.frame)
        self.comboBoxTransformation.setObjectName(_fromUtf8("comboBoxTransformation"))
        self.comboBoxTransformation.addItem(_fromUtf8(""))
        self.comboBoxTransformation.addItem(_fromUtf8(""))
        self.comboBoxTransformation.addItem(_fromUtf8(""))
        self.comboBoxTransformation.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxTransformation, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.comboBoxResampling = QtGui.QComboBox(self.frame)
        self.comboBoxResampling.setObjectName(_fromUtf8("comboBoxResampling"))
        self.comboBoxResampling.addItem(_fromUtf8(""))
        self.comboBoxResampling.addItem(_fromUtf8(""))
        self.comboBoxResampling.addItem(_fromUtf8(""))
        self.comboBoxResampling.addItem(_fromUtf8(""))
        self.comboBoxResampling.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxResampling, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.tableWidget = QtGui.QTableWidget(FormGeoreferencer)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.actionPan = QtGui.QAction(FormGeoreferencer)
        self.actionPan.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/arrow-move.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionLoadLayer = QtGui.QAction(FormGeoreferencer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/layer--plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadLayer.setIcon(icon1)
        self.actionLoadLayer.setObjectName(_fromUtf8("actionLoadLayer"))
        self.actionAddPoint = QtGui.QAction(FormGeoreferencer)
        self.actionAddPoint.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/marker--plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddPoint.setIcon(icon2)
        self.actionAddPoint.setObjectName(_fromUtf8("actionAddPoint"))
        self.actionDelPoint = QtGui.QAction(FormGeoreferencer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/marker--minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelPoint.setIcon(icon3)
        self.actionDelPoint.setObjectName(_fromUtf8("actionDelPoint"))
        self.actionRun = QtGui.QAction(FormGeoreferencer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/time_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon4)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))

        self.retranslateUi(FormGeoreferencer)
        QtCore.QMetaObject.connectSlotsByName(FormGeoreferencer)

    def retranslateUi(self, FormGeoreferencer):
        FormGeoreferencer.setWindowTitle(QtGui.QApplication.translate("FormGeoreferencer", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormGeoreferencer", "Transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTransformation.setItemText(0, QtGui.QApplication.translate("FormGeoreferencer", "Polynomial 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTransformation.setItemText(1, QtGui.QApplication.translate("FormGeoreferencer", "Polynomial 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTransformation.setItemText(2, QtGui.QApplication.translate("FormGeoreferencer", "Polynomial 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTransformation.setItemText(3, QtGui.QApplication.translate("FormGeoreferencer", "Spline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FormGeoreferencer", "Echantillonnage", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResampling.setItemText(0, QtGui.QApplication.translate("FormGeoreferencer", "Nearest", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResampling.setItemText(1, QtGui.QApplication.translate("FormGeoreferencer", "Bilinear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResampling.setItemText(2, QtGui.QApplication.translate("FormGeoreferencer", "Cubic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResampling.setItemText(3, QtGui.QApplication.translate("FormGeoreferencer", "Cubic spline", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResampling.setItemText(4, QtGui.QApplication.translate("FormGeoreferencer", "Lanczos", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("FormGeoreferencer", "x origine", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("FormGeoreferencer", "y origine", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("FormGeoreferencer", "x destination", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("FormGeoreferencer", "y destination", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("FormGeoreferencer", "dX", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("FormGeoreferencer", "dY", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("FormGeoreferencer", "dXY", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setText(QtGui.QApplication.translate("FormGeoreferencer", "Se déplacer dans la carte", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadLayer.setText(QtGui.QApplication.translate("FormGeoreferencer", "Charger Couche", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddPoint.setText(QtGui.QApplication.translate("FormGeoreferencer", "Ajouter Point", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddPoint.setToolTip(QtGui.QApplication.translate("FormGeoreferencer", "Ajouter Point", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelPoint.setText(QtGui.QApplication.translate("FormGeoreferencer", "Supprimer Point", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("FormGeoreferencer", "Lancer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setToolTip(QtGui.QApplication.translate("FormGeoreferencer", "Lancer", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
