# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TableTransformations.ui'
#
# Created: Tue Aug 21 06:01:10 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(738, 354)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/marker--pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalGroupBox = QtGui.QGroupBox(Dialog)
        self.verticalGroupBox.setObjectName(_fromUtf8("verticalGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(4, 5, 4, 6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButtonDelete = QtGui.QPushButton(self.verticalGroupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/marker--minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDelete.setIcon(icon1)
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.verticalLayout.addWidget(self.pushButtonDelete)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.verticalGroupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formGroupBox = QtGui.QGroupBox(Dialog)
        self.formGroupBox.setObjectName(_fromUtf8("formGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(16, 10, 114, 6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.transformationsLabel = QtGui.QLabel(self.formGroupBox)
        self.transformationsLabel.setObjectName(_fromUtf8("transformationsLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.transformationsLabel)
        self.transformationsComboBox = QtGui.QComboBox(self.formGroupBox)
        self.transformationsComboBox.setObjectName(_fromUtf8("transformationsComboBox"))
        self.transformationsComboBox.addItem(_fromUtf8(""))
        self.transformationsComboBox.addItem(_fromUtf8(""))
        self.transformationsComboBox.addItem(_fromUtf8(""))
        self.transformationsComboBox.addItem(_fromUtf8(""))
        self.transformationsComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.transformationsComboBox)
        self.echantillonnageLabel = QtGui.QLabel(self.formGroupBox)
        self.echantillonnageLabel.setObjectName(_fromUtf8("echantillonnageLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.echantillonnageLabel)
        self.echantillonnageComboBox = QtGui.QComboBox(self.formGroupBox)
        self.echantillonnageComboBox.setObjectName(_fromUtf8("echantillonnageComboBox"))
        self.echantillonnageComboBox.addItem(_fromUtf8(""))
        self.echantillonnageComboBox.addItem(_fromUtf8(""))
        self.echantillonnageComboBox.addItem(_fromUtf8(""))
        self.echantillonnageComboBox.addItem(_fromUtf8(""))
        self.echantillonnageComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.echantillonnageComboBox)
        self.compressionLabel = QtGui.QLabel(self.formGroupBox)
        self.compressionLabel.setObjectName(_fromUtf8("compressionLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.compressionLabel)
        self.compressionComboBox = QtGui.QComboBox(self.formGroupBox)
        self.compressionComboBox.setObjectName(_fromUtf8("compressionComboBox"))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.compressionComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.compressionComboBox)
        self.horizontalLayout_3.addWidget(self.formGroupBox)
        self.formGroupBox_2 = QtGui.QGroupBox(Dialog)
        self.formGroupBox_2.setObjectName(_fromUtf8("formGroupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formGroupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(10)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.mXYLabel = QtGui.QLabel(self.formGroupBox_2)
        self.mXYLabel.setObjectName(_fromUtf8("mXYLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.mXYLabel)
        self.mXYLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.mXYLineEdit.setReadOnly(True)
        self.mXYLineEdit.setObjectName(_fromUtf8("mXYLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.mXYLineEdit)
        self.mXLabel = QtGui.QLabel(self.formGroupBox_2)
        self.mXLabel.setObjectName(_fromUtf8("mXLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.mXLabel)
        self.mXLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.mXLineEdit.setReadOnly(True)
        self.mXLineEdit.setObjectName(_fromUtf8("mXLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.mXLineEdit)
        self.mYLabel = QtGui.QLabel(self.formGroupBox_2)
        self.mYLabel.setObjectName(_fromUtf8("mYLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.mYLabel)
        self.mYLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.mYLineEdit.setReadOnly(True)
        self.mYLineEdit.setObjectName(_fromUtf8("mYLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.mYLineEdit)
        self.horizontalLayout_3.addWidget(self.formGroupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalGroupBox_2 = QtGui.QGroupBox(Dialog)
        self.horizontalGroupBox_2.setObjectName(_fromUtf8("horizontalGroupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setContentsMargins(5, 4, 5, 5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Charger = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.Charger.setEnabled(False)
        self.Charger.setObjectName(_fromUtf8("Charger"))
        self.horizontalLayout_2.addWidget(self.Charger)
        self.save = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.save.setEnabled(False)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_2.addWidget(self.save)
        self.restaurer = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.restaurer.setEnabled(False)
        self.restaurer.setObjectName(_fromUtf8("restaurer"))
        self.horizontalLayout_2.addWidget(self.restaurer)
        self.pushButtonOK = QtGui.QPushButton(self.horizontalGroupBox_2)
        self.pushButtonOK.setObjectName(_fromUtf8("pushButtonOK"))
        self.horizontalLayout_2.addWidget(self.pushButtonOK)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Table de transformations", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Lier", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Source X", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Source Y", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "X Carte", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Y Carte", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Résiduel", None))
        self.pushButtonDelete.setText(_translate("Dialog", "Supprimer", None))
        self.transformationsLabel.setText(_translate("Dialog", "Transformations", None))
        self.transformationsComboBox.setItemText(0, _translate("Dialog", "Helmert", None))
        self.transformationsComboBox.setItemText(1, _translate("Dialog", "Polynomial 1", None))
        self.transformationsComboBox.setItemText(2, _translate("Dialog", "Polynomial 2", None))
        self.transformationsComboBox.setItemText(3, _translate("Dialog", "Polynomial 3", None))
        self.transformationsComboBox.setItemText(4, _translate("Dialog", "Spline (TPS)", None))
        self.echantillonnageLabel.setText(_translate("Dialog", "Echantillonnage", None))
        self.echantillonnageComboBox.setItemText(0, _translate("Dialog", "Nearest", None))
        self.echantillonnageComboBox.setItemText(1, _translate("Dialog", "Bilinear", None))
        self.echantillonnageComboBox.setItemText(2, _translate("Dialog", "Cubic", None))
        self.echantillonnageComboBox.setItemText(3, _translate("Dialog", "Cubic Spline", None))
        self.echantillonnageComboBox.setItemText(4, _translate("Dialog", "Lanczos", None))
        self.compressionLabel.setText(_translate("Dialog", "Compression", None))
        self.compressionComboBox.setItemText(0, _translate("Dialog", "NONE", None))
        self.compressionComboBox.setItemText(1, _translate("Dialog", "LZW", None))
        self.compressionComboBox.setItemText(2, _translate("Dialog", "PACKBITS", None))
        self.compressionComboBox.setItemText(3, _translate("Dialog", "DEFLATE", None))
        self.mXYLabel.setText(_translate("Dialog", "m XY", None))
        self.mXLabel.setText(_translate("Dialog", "m X", None))
        self.mYLabel.setText(_translate("Dialog", "m Y", None))
        self.Charger.setText(_translate("Dialog", "Charger", None))
        self.save.setText(_translate("Dialog", "Enregistrer", None))
        self.restaurer.setText(_translate("Dialog", "Restaurer depuis jeu de données", None))
        self.pushButtonOK.setText(_translate("Dialog", "OK", None))

import icons_rc
