# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreationPropositionTitre.ui'
#
# Created: Fri Jul 06 20:01:56 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(837, 535)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 164))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditNomPropriete = QtGui.QLineEdit(self.groupBox)
        self.lineEditNomPropriete.setObjectName(_fromUtf8("lineEditNomPropriete"))
        self.gridLayout.addWidget(self.lineEditNomPropriete, 2, 1, 1, 1)
        self.lineEditNumTitre = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumTitre.setObjectName(_fromUtf8("lineEditNumTitre"))
        self.gridLayout.addWidget(self.lineEditNumTitre, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxConsistance = QtGui.QComboBox(self.groupBox)
        self.comboBoxConsistance.setObjectName(_fromUtf8("comboBoxConsistance"))
        self.gridLayout.addWidget(self.comboBoxConsistance, 3, 1, 1, 1)
        self.comboBoxType = QtGui.QComboBox(self.groupBox)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxType, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.btnListe = QtGui.QPushButton(self.groupBox)
        self.btnListe.setObjectName(_fromUtf8("btnListe"))
        self.gridLayout.addWidget(self.btnListe, 3, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEditSurfaceM2 = QtGui.QLineEdit(self.groupBox)
        self.lineEditSurfaceM2.setObjectName(_fromUtf8("lineEditSurfaceM2"))
        self.horizontalLayout.addWidget(self.lineEditSurfaceM2)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEditSurfaceHa = QtGui.QLineEdit(self.groupBox)
        self.lineEditSurfaceHa.setObjectName(_fromUtf8("lineEditSurfaceHa"))
        self.horizontalLayout.addWidget(self.lineEditSurfaceHa)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEditSurfaceA = QtGui.QLineEdit(self.groupBox)
        self.lineEditSurfaceA.setObjectName(_fromUtf8("lineEditSurfaceA"))
        self.horizontalLayout.addWidget(self.lineEditSurfaceA)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEditSurfaceCa = QtGui.QLineEdit(self.groupBox)
        self.lineEditSurfaceCa.setObjectName(_fromUtf8("lineEditSurfaceCa"))
        self.horizontalLayout.addWidget(self.lineEditSurfaceCa)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 451, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.btnListe_2 = QtGui.QPushButton(self.groupBox_2)
        self.btnListe_2.setObjectName(_fromUtf8("btnListe_2"))
        self.gridLayout_4.addWidget(self.btnListe_2, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.comboBoxDistrict = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxDistrict.setObjectName(_fromUtf8("comboBoxDistrict"))
        self.gridLayout_4.addWidget(self.comboBoxDistrict, 0, 1, 1, 1)
        self.comboBoxCommune = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxCommune.setObjectName(_fromUtf8("comboBoxCommune"))
        self.gridLayout_4.addWidget(self.comboBoxCommune, 1, 1, 1, 1)
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout_4.addWidget(self.comboBoxFokontany, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 310, 451, 164))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.btnEnlever = QtGui.QPushButton(self.groupBox_3)
        self.btnEnlever.setObjectName(_fromUtf8("btnEnlever"))
        self.gridLayout_6.addWidget(self.btnEnlever, 2, 2, 1, 1)
        self.lineEditNom = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.gridLayout_6.addWidget(self.lineEditNom, 0, 1, 1, 1)
        self.btnAjouter = QtGui.QPushButton(self.groupBox_3)
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.gridLayout_6.addWidget(self.btnAjouter, 1, 2, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.gridLayout_6.addWidget(self.tableWidget, 1, 0, 2, 2)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 480, 451, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAide = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnAide.setObjectName(_fromUtf8("btnAide"))
        self.horizontalLayout_2.addWidget(self.btnAide)
        self.btnCreer = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnCreer.setObjectName(_fromUtf8("btnCreer"))
        self.horizontalLayout_2.addWidget(self.btnCreer)
        self.btnAnnuler = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))
        self.horizontalLayout_2.addWidget(self.btnAnnuler)
        self.checkBox = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(470, 310, 71, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.textEditObservation = QtGui.QTextEdit(Dialog)
        self.textEditObservation.setGeometry(QtCore.QRect(470, 330, 361, 192))
        self.textEditObservation.setObjectName(_fromUtf8("textEditObservation"))
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(479, 19, 341, 281))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayoutGeom = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutGeom.setMargin(0)
        self.horizontalLayoutGeom.setObjectName(_fromUtf8("horizontalLayoutGeom"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Crétion d\'une proposition de titre ou requisition", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Titre ou requisition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Nom de la propriété", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Numero", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(0, QtGui.QApplication.translate("Dialog", "Titre foncier", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(1, QtGui.QApplication.translate("Dialog", "Réquisition", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Type*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListe.setText(QtGui.QApplication.translate("Dialog", "Liste", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Surface (sur carte)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "m2 Ou ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Ha ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Ca", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Localisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "District*", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListe_2.setText(QtGui.QApplication.translate("Dialog", "Liste", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Fokontany*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Commune*", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Les occupants", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnlever.setText(QtGui.QApplication.translate("Dialog", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouter.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Nom et Prenoms", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAide.setText(QtGui.QApplication.translate("Dialog", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreer.setText(QtGui.QApplication.translate("Dialog", "Créer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAnnuler.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Observations", None, QtGui.QApplication.UnicodeUTF8))

