# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VoirListeContribuable.ui'
#
# Created: Mon Mar 05 07:22:43 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(598, 416)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 581, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBoxNom = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNom.setGeometry(QtCore.QRect(30, 20, 101, 17))
        self.checkBoxNom.setObjectName(_fromUtf8("checkBoxNom"))
        self.checkBoxPrenom = QtGui.QCheckBox(self.groupBox)
        self.checkBoxPrenom.setGeometry(QtCore.QRect(30, 50, 80, 17))
        self.checkBoxPrenom.setObjectName(_fromUtf8("checkBoxPrenom"))
        self.lineEditNom = QtGui.QLineEdit(self.groupBox)
        self.lineEditNom.setGeometry(QtCore.QRect(140, 20, 290, 20))
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.btnRechercher = QtGui.QPushButton(self.groupBox)
        self.btnRechercher.setGeometry(QtCore.QRect(430, 110, 110, 23))
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.lineEditPrenom = QtGui.QLineEdit(self.groupBox)
        self.lineEditPrenom.setGeometry(QtCore.QRect(140, 50, 200, 20))
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.lineEditNumActe = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumActe.setGeometry(QtCore.QRect(140, 110, 200, 20))
        self.lineEditNumActe.setObjectName(_fromUtf8("lineEditNumActe"))
        self.checkCIN = QtGui.QCheckBox(self.groupBox)
        self.checkCIN.setGeometry(QtCore.QRect(30, 80, 100, 17))
        self.checkCIN.setObjectName(_fromUtf8("checkCIN"))
        self.checkBoxNumActe = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumActe.setGeometry(QtCore.QRect(30, 110, 80, 17))
        self.checkBoxNumActe.setObjectName(_fromUtf8("checkBoxNumActe"))
        self.lineEditCIN4 = QtGui.QLineEdit(Dialog)
        self.lineEditCIN4.setGeometry(QtCore.QRect(300, 80, 41, 20))
        self.lineEditCIN4.setObjectName(_fromUtf8("lineEditCIN4"))
        self.lineEditCIN1 = QtGui.QLineEdit(Dialog)
        self.lineEditCIN1.setGeometry(QtCore.QRect(150, 80, 41, 20))
        self.lineEditCIN1.setObjectName(_fromUtf8("lineEditCIN1"))
        self.lineEditCIN3 = QtGui.QLineEdit(Dialog)
        self.lineEditCIN3.setGeometry(QtCore.QRect(250, 80, 41, 20))
        self.lineEditCIN3.setObjectName(_fromUtf8("lineEditCIN3"))
        self.lineEditCIN2 = QtGui.QLineEdit(Dialog)
        self.lineEditCIN2.setGeometry(QtCore.QRect(200, 80, 41, 20))
        self.lineEditCIN2.setObjectName(_fromUtf8("lineEditCIN2"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 581, 221))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btnVoir = QtGui.QPushButton(self.groupBox_3)
        self.btnVoir.setGeometry(QtCore.QRect(10, 10, 60, 23))
        self.btnVoir.setObjectName(_fromUtf8("btnVoir"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 40, 580, 151))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.btnDebut = QtGui.QPushButton(self.groupBox_3)
        self.btnDebut.setGeometry(QtCore.QRect(0, 190, 75, 30))
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.btnPrecedent = QtGui.QPushButton(self.groupBox_3)
        self.btnPrecedent.setGeometry(QtCore.QRect(70, 190, 75, 30))
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.btnFin = QtGui.QPushButton(self.groupBox_3)
        self.btnFin.setGeometry(QtCore.QRect(500, 190, 81, 30))
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.btnSuivant = QtGui.QPushButton(self.groupBox_3)
        self.btnSuivant.setGeometry(QtCore.QRect(430, 190, 75, 30))
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(360, 190, 75, 30))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(230, 190, 130, 30))
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.lineEditRatio = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditRatio.setEnabled(False)
        self.lineEditRatio.setGeometry(QtCore.QRect(140, 190, 90, 30))
        self.lineEditRatio.setObjectName(_fromUtf8("lineEditRatio"))
        self.btnModifier = QtGui.QPushButton(self.groupBox_3)
        self.btnModifier.setGeometry(QtCore.QRect(70, 10, 90, 23))
        self.btnModifier.setObjectName(_fromUtf8("btnModifier"))
        self.btnAjouter = QtGui.QPushButton(self.groupBox_3)
        self.btnAjouter.setGeometry(QtCore.QRect(490, 10, 75, 23))
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 370, 580, 41))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btnSelectionner = QtGui.QPushButton(self.groupBox_4)
        self.btnSelectionner.setGeometry(QtCore.QRect(380, 10, 100, 23))
        self.btnSelectionner.setObjectName(_fromUtf8("btnSelectionner"))
        self.btnFermer = QtGui.QPushButton(self.groupBox_4)
        self.btnFermer.setGeometry(QtCore.QRect(500, 10, 75, 23))
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Liste des contribuable", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Critère de recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNom.setText(QtGui.QApplication.translate("Dialog", "Nom :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPrenom.setText(QtGui.QApplication.translate("Dialog", "Prénom :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRechercher.setText(QtGui.QApplication.translate("Dialog", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        self.checkCIN.setText(QtGui.QApplication.translate("Dialog", "N° CIN :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNumActe.setText(QtGui.QApplication.translate("Dialog", "N° Acte :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoir.setText(QtGui.QApplication.translate("Dialog", "Voir", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Prénoms", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "CIN", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Acte", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDebut.setText(QtGui.QApplication.translate("Dialog", "<<=", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrecedent.setText(QtGui.QApplication.translate("Dialog", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFin.setText(QtGui.QApplication.translate("Dialog", "=>>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSuivant.setText(QtGui.QApplication.translate("Dialog", "=>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Dialog", "ll", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModifier.setText(QtGui.QApplication.translate("Dialog", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouter.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectionner.setText(QtGui.QApplication.translate("Dialog", "Sélectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))

