# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListingDemande.ui'
#
# Created: Fri Jun 23 12:07:28 2023
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(938, 868)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButtonExport = QtGui.QPushButton(Dialog)
        self.pushButtonExport.setObjectName(_fromUtf8("pushButtonExport"))
        self.gridLayout_4.addWidget(self.pushButtonExport, 4, 1, 1, 1)
        self.checkBoxCocherTous = QtGui.QCheckBox(Dialog)
        self.checkBoxCocherTous.setObjectName(_fromUtf8("checkBoxCocherTous"))
        self.gridLayout_4.addWidget(self.checkBoxCocherTous, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonRechercher = QtGui.QPushButton(self.groupBox)
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))
        self.gridLayout.addWidget(self.pushButtonRechercher, 5, 3, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.checkBoxNumdecision = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumdecision.setText(_fromUtf8(""))
        self.checkBoxNumdecision.setObjectName(_fromUtf8("checkBoxNumdecision"))
        self.gridLayout.addWidget(self.checkBoxNumdecision, 3, 0, 1, 1)
        self.dateEditDatedcision = QtGui.QDateEdit(self.groupBox)
        self.dateEditDatedcision.setEnabled(False)
        self.dateEditDatedcision.setObjectName(_fromUtf8("dateEditDatedcision"))
        self.gridLayout.addWidget(self.dateEditDatedcision, 4, 2, 1, 3)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.checkBoxFkt = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFkt.setText(_fromUtf8(""))
        self.checkBoxFkt.setObjectName(_fromUtf8("checkBoxFkt"))
        self.gridLayout.addWidget(self.checkBoxFkt, 1, 0, 1, 1)
        self.checkBoxdateDecision = QtGui.QCheckBox(self.groupBox)
        self.checkBoxdateDecision.setText(_fromUtf8(""))
        self.checkBoxdateDecision.setObjectName(_fromUtf8("checkBoxdateDecision"))
        self.gridLayout.addWidget(self.checkBoxdateDecision, 4, 0, 1, 1)
        self.checkBoxHameau = QtGui.QCheckBox(self.groupBox)
        self.checkBoxHameau.setText(_fromUtf8(""))
        self.checkBoxHameau.setObjectName(_fromUtf8("checkBoxHameau"))
        self.gridLayout.addWidget(self.checkBoxHameau, 2, 0, 1, 1)
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBox)
        self.comboBoxFokontany.setEnabled(False)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout.addWidget(self.comboBoxFokontany, 1, 2, 1, 3)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.comboBoxHameau = QtGui.QComboBox(self.groupBox)
        self.comboBoxHameau.setEnabled(False)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.gridLayout.addWidget(self.comboBoxHameau, 2, 2, 1, 3)
        self.lineEditNumeroDemande = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumeroDemande.setEnabled(False)
        self.lineEditNumeroDemande.setObjectName(_fromUtf8("lineEditNumeroDemande"))
        self.gridLayout.addWidget(self.lineEditNumeroDemande, 0, 2, 1, 3)
        self.lineEditNumdecision = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumdecision.setEnabled(False)
        self.lineEditNumdecision.setObjectName(_fromUtf8("lineEditNumdecision"))
        self.gridLayout.addWidget(self.lineEditNumdecision, 3, 2, 1, 3)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.checkBoxNumDemande = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumDemande.setText(_fromUtf8(""))
        self.checkBoxNumDemande.setObjectName(_fromUtf8("checkBoxNumDemande"))
        self.gridLayout.addWidget(self.checkBoxNumDemande, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 2, 2)
        self.tableWidgetDemande = QtGui.QTableWidget(Dialog)
        self.tableWidgetDemande.setObjectName(_fromUtf8("tableWidgetDemande"))
        self.tableWidgetDemande.setColumnCount(9)
        self.tableWidgetDemande.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(8, item)
        self.gridLayout_4.addWidget(self.tableWidgetDemande, 3, 0, 1, 2)
        self.progressBarlisting = QtGui.QProgressBar(Dialog)
        self.progressBarlisting.setProperty("value", 24)
        self.progressBarlisting.setObjectName(_fromUtf8("progressBarlisting"))
        self.gridLayout_4.addWidget(self.progressBarlisting, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Export Listing demande", None))
        self.pushButtonExport.setText(_translate("Dialog", "Exoprter en Listing", None))
        self.checkBoxCocherTous.setText(_translate("Dialog", "Cocher tous", None))
        self.groupBox.setTitle(_translate("Dialog", "Recherche", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Recherher", None))
        self.label_4.setText(_translate("Dialog", "Date Décision", None))
        self.label_5.setText(_translate("Dialog", "Num Décision", None))
        self.label_2.setText(_translate("Dialog", "Fokontany", None))
        self.label_3.setText(_translate("Dialog", "Hameau", None))
        self.label.setText(_translate("Dialog", "N° Demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "iddemande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Numero demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Numero décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Date décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Date debut affichage", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Date fin affichage", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Date RL", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "CQ", None))

import icons_rc
