# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PersonnePhysique.ui'
#
# Created: Fri Jul 20 20:20:55 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(552, 571)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditNom = QtGui.QLineEdit(Dialog)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNom)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditPrenom = QtGui.QLineEdit(Dialog)
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditPrenom)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditDateNaiss = QtGui.QDateEdit(Dialog)
        self.lineEditDateNaiss.setCalendarPopup(True)
        self.lineEditDateNaiss.setObjectName(_fromUtf8("lineEditDateNaiss"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditDateNaiss)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.radioBtnMale = QtGui.QRadioButton(Dialog)
        self.radioBtnMale.setObjectName(_fromUtf8("radioBtnMale"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.radioBtnMale)
        self.radioBtnFemale = QtGui.QRadioButton(Dialog)
        self.radioBtnFemale.setObjectName(_fromUtf8("radioBtnFemale"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.radioBtnFemale)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditAdresse = QtGui.QLineEdit(Dialog)
        self.lineEditAdresse.setObjectName(_fromUtf8("lineEditAdresse"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditAdresse)
        self.nVersLabel = QtGui.QLabel(Dialog)
        self.nVersLabel.setObjectName(_fromUtf8("nVersLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.nVersLabel)
        self.neVersCheckBox = QtGui.QCheckBox(Dialog)
        self.neVersCheckBox.setObjectName(_fromUtf8("neVersCheckBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.neVersCheckBox)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.nomDuPReLabel = QtGui.QLabel(self.groupBox)
        self.nomDuPReLabel.setObjectName(_fromUtf8("nomDuPReLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nomDuPReLabel)
        self.nomDuPReLineEdit = QtGui.QLineEdit(self.groupBox)
        self.nomDuPReLineEdit.setObjectName(_fromUtf8("nomDuPReLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nomDuPReLineEdit)
        self.nomDeLaMReLabel = QtGui.QLabel(self.groupBox)
        self.nomDeLaMReLabel.setObjectName(_fromUtf8("nomDeLaMReLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.nomDeLaMReLabel)
        self.nomDeLaMReLineEdit = QtGui.QLineEdit(self.groupBox)
        self.nomDeLaMReLineEdit.setObjectName(_fromUtf8("nomDeLaMReLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nomDeLaMReLineEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.radioBtnCelib = QtGui.QRadioButton(self.groupBox_2)
        self.radioBtnCelib.setObjectName(_fromUtf8("radioBtnCelib"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.radioBtnCelib)
        self.radioBtnMarie = QtGui.QRadioButton(self.groupBox_2)
        self.radioBtnMarie.setObjectName(_fromUtf8("radioBtnMarie"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.radioBtnMarie)
        self.radioBtnVeuf = QtGui.QRadioButton(self.groupBox_2)
        self.radioBtnVeuf.setObjectName(_fromUtf8("radioBtnVeuf"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.radioBtnVeuf)
        self.btnEtatConjoint = QtGui.QPushButton(self.groupBox_2)
        self.btnEtatConjoint.setAutoDefault(True)
        self.btnEtatConjoint.setDefault(False)
        self.btnEtatConjoint.setFlat(False)
        self.btnEtatConjoint.setObjectName(_fromUtf8("btnEtatConjoint"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.btnEtatConjoint)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.radioBtnCIN = QtGui.QRadioButton(self.groupBox_3)
        self.radioBtnCIN.setObjectName(_fromUtf8("radioBtnCIN"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.radioBtnCIN)
        self.radioBtnActeDeNaiss = QtGui.QRadioButton(self.groupBox_3)
        self.radioBtnActeDeNaiss.setObjectName(_fromUtf8("radioBtnActeDeNaiss"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.radioBtnActeDeNaiss)
        self.radioBtnRien = QtGui.QRadioButton(self.groupBox_3)
        self.radioBtnRien.setObjectName(_fromUtf8("radioBtnRien"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.radioBtnRien)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.page)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEditCIN_1 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN_1.setObjectName(_fromUtf8("lineEditCIN_1"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_1)
        self.lineEditCIN_2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN_2.setObjectName(_fromUtf8("lineEditCIN_2"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_2)
        self.lineEditCIN_3 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN_3.setObjectName(_fromUtf8("lineEditCIN_3"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_3)
        self.lineEditCIN_4 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditCIN_4.setObjectName(_fromUtf8("lineEditCIN_4"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEditDateCIN = QtGui.QDateEdit(self.groupBox_4)
        self.lineEditDateCIN.setObjectName(_fromUtf8("lineEditDateCIN"))
        self.gridLayout_3.addWidget(self.lineEditDateCIN, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEditLeuCIN = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditLeuCIN.setObjectName(_fromUtf8("lineEditLeuCIN"))
        self.gridLayout_3.addWidget(self.lineEditLeuCIN, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.page_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_11)
        self.lineEditNumActeNaiss = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditNumActeNaiss.setObjectName(_fromUtf8("lineEditNumActeNaiss"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNumActeNaiss)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEditDateActeNaiss = QtGui.QDateEdit(self.groupBox_5)
        self.lineEditDateActeNaiss.setObjectName(_fromUtf8("lineEditDateActeNaiss"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditDateActeNaiss)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEditLieuActeNaiss = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditLieuActeNaiss.setObjectName(_fromUtf8("lineEditLieuActeNaiss"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditLieuActeNaiss)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setMinimumSize(QtCore.QSize(206, 0))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnListePersSimil = QtGui.QPushButton(Dialog)
        self.btnListePersSimil.setObjectName(_fromUtf8("btnListePersSimil"))
        self.horizontalLayout_3.addWidget(self.btnListePersSimil)
        self.btnOk = QtGui.QPushButton(Dialog)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout_3.addWidget(self.btnOk)
        self.btnAnnuler = QtGui.QPushButton(Dialog)
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))
        self.horizontalLayout_3.addWidget(self.btnAnnuler)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnSelectionner = QtGui.QPushButton(Dialog)
        self.btnSelectionner.setObjectName(_fromUtf8("btnSelectionner"))
        self.horizontalLayout_3.addWidget(self.btnSelectionner)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Personne physique", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Prénom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Date de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Sexe ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnMale.setText(QtGui.QApplication.translate("Dialog", "Macsulin", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnFemale.setText(QtGui.QApplication.translate("Dialog", "Feminin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Adresse", None, QtGui.QApplication.UnicodeUTF8))
        self.nVersLabel.setText(QtGui.QApplication.translate("Dialog", "Né vers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Filiation", None, QtGui.QApplication.UnicodeUTF8))
        self.nomDuPReLabel.setText(QtGui.QApplication.translate("Dialog", "Nom du père", None, QtGui.QApplication.UnicodeUTF8))
        self.nomDeLaMReLabel.setText(QtGui.QApplication.translate("Dialog", "Nom de la mère", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Situation matrimoniale", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnCelib.setText(QtGui.QApplication.translate("Dialog", "Célibataire", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnMarie.setText(QtGui.QApplication.translate("Dialog", "Marié(e)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnVeuf.setText(QtGui.QApplication.translate("Dialog", "Veuf(ve)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEtatConjoint.setText(QtGui.QApplication.translate("Dialog", "Etat civil du /de la conjoint(e)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Pièces d\'identification", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnCIN.setText(QtGui.QApplication.translate("Dialog", "CIN", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnActeDeNaiss.setText(QtGui.QApplication.translate("Dialog", "Acte de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnRien.setText(QtGui.QApplication.translate("Dialog", "Rien", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "CIN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Numéro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Lieu", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Acte de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Numéro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Lieu", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListePersSimil.setText(QtGui.QApplication.translate("Dialog", "Lister personnes similaires", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("Dialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAnnuler.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectionner.setText(QtGui.QApplication.translate("Dialog", "Sélectionner", None, QtGui.QApplication.UnicodeUTF8))

