# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crl.ui'
#
# Created: Tue Apr 08 09:35:45 2025
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1053, 785)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxHameau = QtGui.QCheckBox(self.groupBox)
        self.checkBoxHameau.setText(_fromUtf8(""))
        self.checkBoxHameau.setObjectName(_fromUtf8("checkBoxHameau"))
        self.gridLayout.addWidget(self.checkBoxHameau, 2, 0, 1, 1)
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBox)
        self.comboBoxFokontany.setEnabled(False)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout.addWidget(self.comboBoxFokontany, 1, 2, 1, 3)
        self.checkBoxFkt = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFkt.setText(_fromUtf8(""))
        self.checkBoxFkt.setObjectName(_fromUtf8("checkBoxFkt"))
        self.gridLayout.addWidget(self.checkBoxFkt, 1, 0, 1, 1)
        self.lineEditNumeroDecision = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumeroDecision.setEnabled(False)
        self.lineEditNumeroDecision.setObjectName(_fromUtf8("lineEditNumeroDecision"))
        self.gridLayout.addWidget(self.lineEditNumeroDecision, 0, 2, 1, 3)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.comboBoxHameau = QtGui.QComboBox(self.groupBox)
        self.comboBoxHameau.setEnabled(False)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.gridLayout.addWidget(self.comboBoxHameau, 2, 2, 1, 3)
        self.pushButtonRechercher = QtGui.QPushButton(self.groupBox)
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))
        self.gridLayout.addWidget(self.pushButtonRechercher, 3, 2, 1, 3)
        self.checkBoxNumDecision = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumDecision.setText(_fromUtf8(""))
        self.checkBoxNumDecision.setObjectName(_fromUtf8("checkBoxNumDecision"))
        self.gridLayout.addWidget(self.checkBoxNumDecision, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBoxGestionCRL = QtGui.QGroupBox(Dialog)
        self.groupBoxGestionCRL.setObjectName(_fromUtf8("groupBoxGestionCRL"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxGestionCRL)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.toolButtonAjouter = QtGui.QToolButton(self.groupBoxGestionCRL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAjouter.setIcon(icon1)
        self.toolButtonAjouter.setObjectName(_fromUtf8("toolButtonAjouter"))
        self.gridLayout_5.addWidget(self.toolButtonAjouter, 0, 2, 1, 1)
        self.pushButtonAssigner = QtGui.QPushButton(self.groupBoxGestionCRL)
        self.pushButtonAssigner.setObjectName(_fromUtf8("pushButtonAssigner"))
        self.gridLayout_5.addWidget(self.pushButtonAssigner, 2, 0, 1, 4)
        self.toolButtonSupprimer = QtGui.QToolButton(self.groupBoxGestionCRL)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/moins.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSupprimer.setIcon(icon2)
        self.toolButtonSupprimer.setObjectName(_fromUtf8("toolButtonSupprimer"))
        self.gridLayout_5.addWidget(self.toolButtonSupprimer, 0, 3, 1, 1)
        self.tableWidgetCRL = QtGui.QTableWidget(self.groupBoxGestionCRL)
        self.tableWidgetCRL.setObjectName(_fromUtf8("tableWidgetCRL"))
        self.tableWidgetCRL.setColumnCount(5)
        self.tableWidgetCRL.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCRL.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.tableWidgetCRL, 1, 0, 1, 4)
        self.gridLayout_4.addWidget(self.groupBoxGestionCRL, 2, 0, 1, 2)
        self.checkBoxCocherTous = QtGui.QCheckBox(Dialog)
        self.checkBoxCocherTous.setObjectName(_fromUtf8("checkBoxCocherTous"))
        self.gridLayout_4.addWidget(self.checkBoxCocherTous, 3, 0, 1, 1)
        self.tableWidgetDemande = QtGui.QTableWidget(Dialog)
        self.tableWidgetDemande.setObjectName(_fromUtf8("tableWidgetDemande"))
        self.tableWidgetDemande.setColumnCount(10)
        self.tableWidgetDemande.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetDemande.setHorizontalHeaderItem(9, item)
        self.gridLayout_4.addWidget(self.tableWidgetDemande, 4, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Gestion CRL", None))
        self.groupBox.setTitle(_translate("Dialog", "Recherche", None))
        self.label_3.setText(_translate("Dialog", "Hameau", None))
        self.label_2.setText(_translate("Dialog", "Fokontany", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Recherher", None))
        self.label.setText(_translate("Dialog", "N° Decision", None))
        self.groupBoxGestionCRL.setTitle(_translate("Dialog", "Gestion CRL", None))
        self.toolButtonAjouter.setText(_translate("Dialog", "...", None))
        self.pushButtonAssigner.setText(_translate("Dialog", "Assigner", None))
        self.toolButtonSupprimer.setText(_translate("Dialog", "...", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Rôle", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Titulaire", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Supléant", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "idTit", None))
        item = self.tableWidgetCRL.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "idSup", None))
        self.checkBoxCocherTous.setText(_translate("Dialog", "Cocher tous", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "iddemande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Numero demande", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Numero décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Date décision", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Date debut affichage", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Date fin affichage", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Date RL", None))
        item = self.tableWidgetDemande.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "CQ", None))

import icons_rc
