# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormRecherchePLOF.ui'
#
# Created: Mon Apr  7 16:15:08 2025
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(743, 560)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/listing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_1 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.gridLayout.addWidget(self.checkBox_1, 1, 0, 1, 1)
        self.comboListecouche = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboListecouche.setFont(font)
        self.comboListecouche.setObjectName(_fromUtf8("comboListecouche"))
        self.comboListecouche.addItem(_fromUtf8(""))
        self.comboListecouche.addItem(_fromUtf8(""))
        self.comboListecouche.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboListecouche, 0, 1, 1, 1)
        self.lineEdit_1 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_1.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setMouseTracking(True)
        self.lineEdit_1.setReadOnly(False)
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.gridLayout.addWidget(self.lineEdit_1, 1, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonAfficherTous = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButtonAfficherTous.setFont(font)
        self.pushButtonAfficherTous.setObjectName(_fromUtf8("pushButtonAfficherTous"))
        self.horizontalLayout.addWidget(self.pushButtonAfficherTous)
        self.pushButtonRechercher = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButtonRechercher.setFont(font)
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))
        self.horizontalLayout.addWidget(self.pushButtonRechercher)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(168)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnDebut = QtGui.QPushButton(self.frame_3)
        self.btnDebut.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDebut.setIcon(icon1)
        self.btnDebut.setObjectName(_fromUtf8("btnDebut"))
        self.horizontalLayout_5.addWidget(self.btnDebut)
        self.btnPrecedent = QtGui.QPushButton(self.frame_3)
        self.btnPrecedent.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrecedent.setIcon(icon2)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.horizontalLayout_5.addWidget(self.btnPrecedent)
        self.lineEditNumPage = QtGui.QLineEdit(self.frame_3)
        self.lineEditNumPage.setEnabled(False)
        self.lineEditNumPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditNumPage.setObjectName(_fromUtf8("lineEditNumPage"))
        self.horizontalLayout_5.addWidget(self.lineEditNumPage)
        self.comboBoxNumPage = QtGui.QComboBox(self.frame_3)
        self.comboBoxNumPage.setObjectName(_fromUtf8("comboBoxNumPage"))
        self.horizontalLayout_5.addWidget(self.comboBoxNumPage)
        self.btnSuivant = QtGui.QPushButton(self.frame_3)
        self.btnSuivant.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSuivant.setIcon(icon3)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.horizontalLayout_5.addWidget(self.btnSuivant)
        self.btnFin = QtGui.QPushButton(self.frame_3)
        self.btnFin.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrows/icone/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFin.setIcon(icon4)
        self.btnFin.setObjectName(_fromUtf8("btnFin"))
        self.horizontalLayout_5.addWidget(self.btnFin)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButtonFermer = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButtonFermer.setFont(font)
        self.pushButtonFermer.setObjectName(_fromUtf8("pushButtonFermer"))
        self.horizontalLayout_3.addWidget(self.pushButtonFermer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Recherche demande certficat", None))
        self.groupBox.setTitle(_translate("Dialog", "Filtre", None))
        self.checkBox_1.setText(_translate("Dialog", "Titres", None))
        self.comboListecouche.setItemText(0, _translate("Dialog", "Titre", None))
        self.comboListecouche.setItemText(1, _translate("Dialog", "Cadastre", None))
        self.comboListecouche.setItemText(2, _translate("Dialog", "DemandeFN", None))
        self.checkBox_2.setText(_translate("Dialog", "Propriete", None))
        self.label.setText(_translate("Dialog", "Couche", None))
        self.pushButtonAfficherTous.setText(_translate("Dialog", "Afficher tous", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Rechercher", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "gid", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Titres", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Sur_plan", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Titre_r", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Parcelle", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Partie", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Feuille", None))
        self.pushButtonFermer.setText(_translate("Dialog", "Fermer", None))

import icons_rc
