# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Fiplof_interop\Interroperabilite\ListeDossierExterne.ui'
#
# Created: Wed Jun 10 18:21:27 2026
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1405, 816)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/sig/icone/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.groupBoxDemande = QtGui.QGroupBox(Dialog)
        self.groupBoxDemande.setGeometry(QtCore.QRect(9, 149, 331, 79))
        self.groupBoxDemande.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxDemande.setCheckable(True)
        self.groupBoxDemande.setChecked(False)
        self.groupBoxDemande.setObjectName(_fromUtf8("groupBoxDemande"))
        self.labelDateRL_2 = QtGui.QLabel(self.groupBoxDemande)
        self.labelDateRL_2.setGeometry(QtCore.QRect(8, 40, 71, 20))
        self.labelDateRL_2.setObjectName(_fromUtf8("labelDateRL_2"))
        self.dateDemande = QtGui.QDateEdit(self.groupBoxDemande)
        self.dateDemande.setGeometry(QtCore.QRect(90, 40, 231, 20))
        self.dateDemande.setCalendarPopup(True)
        self.dateDemande.setObjectName(_fromUtf8("dateDemande"))
        self.groupBoxAffichage = QtGui.QGroupBox(Dialog)
        self.groupBoxAffichage.setGeometry(QtCore.QRect(720, 150, 351, 79))
        self.groupBoxAffichage.setCheckable(True)
        self.groupBoxAffichage.setChecked(False)
        self.groupBoxAffichage.setObjectName(_fromUtf8("groupBoxAffichage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxAffichage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dateEditFinAffichage = QtGui.QDateEdit(self.groupBoxAffichage)
        self.dateEditFinAffichage.setObjectName(_fromUtf8("dateEditFinAffichage"))
        self.gridLayout_2.addWidget(self.dateEditFinAffichage, 1, 1, 1, 1)
        self.dateEditDebutAffichage = QtGui.QDateEdit(self.groupBoxAffichage)
        self.dateEditDebutAffichage.setObjectName(_fromUtf8("dateEditDebutAffichage"))
        self.gridLayout_2.addWidget(self.dateEditDebutAffichage, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxAffichage)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBoxAffichage)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.groupBoxDecision = QtGui.QGroupBox(Dialog)
        self.groupBoxDecision.setGeometry(QtCore.QRect(355, 150, 351, 79))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxDecision.sizePolicy().hasHeightForWidth())
        self.groupBoxDecision.setSizePolicy(sizePolicy)
        self.groupBoxDecision.setCheckable(True)
        self.groupBoxDecision.setChecked(False)
        self.groupBoxDecision.setObjectName(_fromUtf8("groupBoxDecision"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxDecision)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBoxDecision)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEditNumeroDecision = QtGui.QLineEdit(self.groupBoxDecision)
        self.lineEditNumeroDecision.setObjectName(_fromUtf8("lineEditNumeroDecision"))
        self.gridLayout_3.addWidget(self.lineEditNumeroDecision, 0, 1, 1, 1)
        self.dateEditDateDecision = QtGui.QDateEdit(self.groupBoxDecision)
        self.dateEditDateDecision.setObjectName(_fromUtf8("dateEditDateDecision"))
        self.gridLayout_3.addWidget(self.dateEditDateDecision, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBoxDecision)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.groupBoxdateRL = QtGui.QGroupBox(Dialog)
        self.groupBoxdateRL.setGeometry(QtCore.QRect(1074, 160, 311, 51))
        self.groupBoxdateRL.setCheckable(True)
        self.groupBoxdateRL.setChecked(False)
        self.groupBoxdateRL.setObjectName(_fromUtf8("groupBoxdateRL"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxdateRL)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelDateRL = QtGui.QLabel(self.groupBoxdateRL)
        self.labelDateRL.setObjectName(_fromUtf8("labelDateRL"))
        self.gridLayout_6.addWidget(self.labelDateRL, 0, 0, 1, 1)
        self.dateEditRL = QtGui.QDateEdit(self.groupBoxdateRL)
        self.dateEditRL.setCalendarPopup(True)
        self.dateEditRL.setObjectName(_fromUtf8("dateEditRL"))
        self.gridLayout_6.addWidget(self.dateEditRL, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 1381, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_Parcelle = QtGui.QLabel(self.groupBox)
        self.label_Parcelle.setObjectName(_fromUtf8("label_Parcelle"))
        self.gridLayout.addWidget(self.label_Parcelle, 3, 1, 1, 1)
        self.checkBoxParcelle = QtGui.QCheckBox(self.groupBox)
        self.checkBoxParcelle.setText(_fromUtf8(""))
        self.checkBoxParcelle.setObjectName(_fromUtf8("checkBoxParcelle"))
        self.gridLayout.addWidget(self.checkBoxParcelle, 3, 0, 1, 1)
        self.label_FKT = QtGui.QLabel(self.groupBox)
        self.label_FKT.setObjectName(_fromUtf8("label_FKT"))
        self.gridLayout.addWidget(self.label_FKT, 0, 1, 1, 1)
        self.checkBoxHameau = QtGui.QCheckBox(self.groupBox)
        self.checkBoxHameau.setText(_fromUtf8(""))
        self.checkBoxHameau.setObjectName(_fromUtf8("checkBoxHameau"))
        self.gridLayout.addWidget(self.checkBoxHameau, 1, 0, 1, 1)
        self.label_Hamea = QtGui.QLabel(self.groupBox)
        self.label_Hamea.setObjectName(_fromUtf8("label_Hamea"))
        self.gridLayout.addWidget(self.label_Hamea, 1, 1, 1, 1)
        self.checkBoxFkt = QtGui.QCheckBox(self.groupBox)
        self.checkBoxFkt.setText(_fromUtf8(""))
        self.checkBoxFkt.setObjectName(_fromUtf8("checkBoxFkt"))
        self.gridLayout.addWidget(self.checkBoxFkt, 0, 0, 1, 1)
        self.comboBoxHameau = QtGui.QComboBox(self.groupBox)
        self.comboBoxHameau.setEnabled(False)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.gridLayout.addWidget(self.comboBoxHameau, 1, 2, 1, 2)
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBox)
        self.comboBoxFokontany.setEnabled(False)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout.addWidget(self.comboBoxFokontany, 0, 2, 1, 2)
        self.lineEditNumeroParcelle = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumeroParcelle.setObjectName(_fromUtf8("lineEditNumeroParcelle"))
        self.gridLayout.addWidget(self.lineEditNumeroParcelle, 3, 2, 1, 1)
        self.groupBoxDossier = QtGui.QGroupBox(Dialog)
        self.groupBoxDossier.setGeometry(QtCore.QRect(9, 263, 1371, 277))
        self.groupBoxDossier.setObjectName(_fromUtf8("groupBoxDossier"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxDossier)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBoxCocherTous = QtGui.QCheckBox(self.groupBoxDossier)
        self.checkBoxCocherTous.setObjectName(_fromUtf8("checkBoxCocherTous"))
        self.verticalLayout_3.addWidget(self.checkBoxCocherTous)
        self.tableWidget_dossier = QtGui.QTableWidget(self.groupBoxDossier)
        self.tableWidget_dossier.setObjectName(_fromUtf8("tableWidget_dossier"))
        self.tableWidget_dossier.setColumnCount(11)
        self.tableWidget_dossier.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dossier.setHorizontalHeaderItem(10, item)
        self.verticalLayout_3.addWidget(self.tableWidget_dossier)
        self.pushButtonTransformerDemande = QtGui.QPushButton(self.groupBoxDossier)
        self.pushButtonTransformerDemande.setObjectName(_fromUtf8("pushButtonTransformerDemande"))
        self.verticalLayout_3.addWidget(self.pushButtonTransformerDemande)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 550, 1371, 261))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.frame = QtGui.QFrame(self.groupBox_2)
        self.frame.setGeometry(QtCore.QRect(40, 40, 1321, 219))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 451, 201))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(100, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(0, 20, 71, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(0, 90, 71, 41))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.listView_principale = QtGui.QListView(self.frame_2)
        self.listView_principale.setGeometry(QtCore.QRect(0, 40, 441, 61))
        self.listView_principale.setObjectName(_fromUtf8("listView_principale"))
        self.listView_consors = QtGui.QListView(self.frame_2)
        self.listView_consors.setGeometry(QtCore.QRect(0, 120, 441, 71))
        self.listView_consors.setObjectName(_fromUtf8("listView_consors"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(450, 0, 441, 201))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(200, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.listView_CRL = QtGui.QListView(self.frame_3)
        self.listView_CRL.setGeometry(QtCore.QRect(10, 30, 421, 161))
        self.listView_CRL.setObjectName(_fromUtf8("listView_CRL"))
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(900, 0, 421, 201))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(170, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.listView_coordonees = QtGui.QListView(self.frame_4)
        self.listView_coordonees.setGeometry(QtCore.QRect(0, 30, 411, 161))
        self.listView_coordonees.setObjectName(_fromUtf8("listView_coordonees"))
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.pushButtonRechercher = QtGui.QPushButton(Dialog)
        self.pushButtonRechercher.setGeometry(QtCore.QRect(20, 230, 1361, 23))
        self.pushButtonRechercher.setObjectName(_fromUtf8("pushButtonRechercher"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Transformation Demande", None))
        self.groupBoxDemande.setTitle(_translate("Dialog", "Demande", None))
        self.labelDateRL_2.setText(_translate("Dialog", "Date Demande", None))
        self.groupBoxAffichage.setTitle(_translate("Dialog", "Affichage", None))
        self.label_4.setText(_translate("Dialog", "Date Début", None))
        self.label_5.setText(_translate("Dialog", "Date Fin", None))
        self.groupBoxDecision.setTitle(_translate("Dialog", "Décision", None))
        self.label_7.setText(_translate("Dialog", "Date", None))
        self.label_6.setText(_translate("Dialog", "Numero", None))
        self.groupBoxdateRL.setTitle(_translate("Dialog", "Reconnaissance Locale", None))
        self.labelDateRL.setText(_translate("Dialog", "Date RL", None))
        self.groupBox.setTitle(_translate("Dialog", "Critères de recherche", None))
        self.label_Parcelle.setText(_translate("Dialog", "Parcelle", None))
        self.label_FKT.setText(_translate("Dialog", "Fokontany", None))
        self.label_Hamea.setText(_translate("Dialog", "Hameau", None))
        self.groupBoxDossier.setTitle(_translate("Dialog", "Dossier", None))
        self.checkBoxCocherTous.setText(_translate("Dialog", "Cocher tous", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Parcelle", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Contenance", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Date demande", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Numero décision", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Date décision", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Date debut affichage", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Date fin affichage", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Date RL", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Occupation", None))
        item = self.tableWidget_dossier.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "Batch", None))
        self.pushButtonTransformerDemande.setText(_translate("Dialog", "TRANSFORMER EN DEMANDE ", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Autres informations", None))
        self.label.setText(_translate("Dialog", "PROPRIETAIRE", None))
        self.label_10.setText(_translate("Dialog", "Principale(s)", None))
        self.label_11.setText(_translate("Dialog", "Consors", None))
        self.label_8.setText(_translate("Dialog", "CRL", None))
        self.label_9.setText(_translate("Dialog", "COORDONNEES", None))
        self.pushButtonRechercher.setText(_translate("Dialog", "Recherher", None))

import icons_rc
