# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FusionCF.ui'
#
# Created: Sat Mar 22 16:24:50 2025
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(805, 479)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.numRoCertificatLabel_3 = QtGui.QLabel(self.groupBox_3)
        self.numRoCertificatLabel_3.setObjectName(_fromUtf8("numRoCertificatLabel_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.numRoCertificatLabel_3)
        self.numRoCertificatLineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.numRoCertificatLineEdit_3.setObjectName(_fromUtf8("numRoCertificatLineEdit_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.numRoCertificatLineEdit_3)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.NumDemande = QtGui.QLineEdit(self.groupBox_4)
        self.NumDemande.setObjectName(_fromUtf8("NumDemande"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.NumDemande)
        self.numRoCertificatLabel = QtGui.QLabel(self.groupBox_4)
        self.numRoCertificatLabel.setObjectName(_fromUtf8("numRoCertificatLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.numRoCertificatLabel)
        self.numRoCertificatLineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.numRoCertificatLineEdit.setObjectName(_fromUtf8("numRoCertificatLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.numRoCertificatLineEdit)
        self.consistanceLabel = QtGui.QLabel(self.groupBox_4)
        self.consistanceLabel.setObjectName(_fromUtf8("consistanceLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.consistanceLabel)
        self.consistanceComboBox = QtGui.QComboBox(self.groupBox_4)
        self.consistanceComboBox.setObjectName(_fromUtf8("consistanceComboBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.consistanceComboBox)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalGroupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.horizontalGroupBox_6.setObjectName(_fromUtf8("horizontalGroupBox_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalGroupBox_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.detail = QtGui.QPushButton(self.horizontalGroupBox_6)
        self.detail.setObjectName(_fromUtf8("detail"))
        self.horizontalLayout_6.addWidget(self.detail)
        self.verticalLayout_10.addWidget(self.horizontalGroupBox_6)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalGroupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.horizontalGroupBox_7.setObjectName(_fromUtf8("horizontalGroupBox_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalGroupBox_7)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.remove = QtGui.QPushButton(self.horizontalGroupBox_7)
        self.remove.setObjectName(_fromUtf8("remove"))
        self.horizontalLayout_7.addWidget(self.remove)
        self.pushButtonAddition = QtGui.QPushButton(self.horizontalGroupBox_7)
        self.pushButtonAddition.setObjectName(_fromUtf8("pushButtonAddition"))
        self.horizontalLayout_7.addWidget(self.pushButtonAddition)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.details = QtGui.QPushButton(self.horizontalGroupBox_7)
        self.details.setObjectName(_fromUtf8("details"))
        self.horizontalLayout_7.addWidget(self.details)
        self.verticalLayout_11.addWidget(self.horizontalGroupBox_7)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tableWidget_2 = QtGui.QTableWidget(self.groupBox_6)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.gridLayout_3.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalGroupBox_8 = QtGui.QGroupBox(self.groupBox_7)
        self.horizontalGroupBox_8.setObjectName(_fromUtf8("horizontalGroupBox_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalGroupBox_8)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.enlever = QtGui.QPushButton(self.horizontalGroupBox_8)
        self.enlever.setObjectName(_fromUtf8("enlever"))
        self.horizontalLayout_8.addWidget(self.enlever)
        self.add = QtGui.QPushButton(self.horizontalGroupBox_8)
        self.add.setObjectName(_fromUtf8("add"))
        self.horizontalLayout_8.addWidget(self.add)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.transfer = QtGui.QPushButton(self.horizontalGroupBox_8)
        self.transfer.setObjectName(_fromUtf8("transfer"))
        self.horizontalLayout_8.addWidget(self.transfer)
        self.details_2 = QtGui.QPushButton(self.horizontalGroupBox_8)
        self.details_2.setObjectName(_fromUtf8("details_2"))
        self.horizontalLayout_8.addWidget(self.details_2)
        self.verticalLayout_8.addWidget(self.horizontalGroupBox_8)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tableWidget_3 = QtGui.QTableWidget(self.groupBox_7)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalGroupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.horizontalGroupBox_9.setObjectName(_fromUtf8("horizontalGroupBox_9"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalGroupBox_9)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.enlever_2 = QtGui.QPushButton(self.horizontalGroupBox_9)
        self.enlever_2.setObjectName(_fromUtf8("enlever_2"))
        self.horizontalLayout_9.addWidget(self.enlever_2)
        self.add_2 = QtGui.QPushButton(self.horizontalGroupBox_9)
        self.add_2.setObjectName(_fromUtf8("add_2"))
        self.horizontalLayout_9.addWidget(self.add_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.detail_2 = QtGui.QPushButton(self.horizontalGroupBox_9)
        self.detail_2.setObjectName(_fromUtf8("detail_2"))
        self.horizontalLayout_9.addWidget(self.detail_2)
        self.verticalLayout_9.addWidget(self.horizontalGroupBox_9)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableWidget_4 = QtGui.QTableWidget(self.groupBox_8)
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.gridLayout_5.addWidget(self.tableWidget_4, 0, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_5)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalGroupBox_10 = QtGui.QGroupBox(self.groupBox_9)
        self.horizontalGroupBox_10.setObjectName(_fromUtf8("horizontalGroupBox_10"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalGroupBox_10)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.Enlever = QtGui.QPushButton(self.horizontalGroupBox_10)
        self.Enlever.setObjectName(_fromUtf8("Enlever"))
        self.horizontalLayout_10.addWidget(self.Enlever)
        self.Ajouter = QtGui.QPushButton(self.horizontalGroupBox_10)
        self.Ajouter.setObjectName(_fromUtf8("Ajouter"))
        self.horizontalLayout_10.addWidget(self.Ajouter)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_6.addWidget(self.horizontalGroupBox_10)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tableWidget_5 = QtGui.QTableWidget(self.groupBox_9)
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.gridLayout_6.addWidget(self.tableWidget_5, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalGroupBox_11 = QtGui.QGroupBox(self.groupBox_10)
        self.horizontalGroupBox_11.setObjectName(_fromUtf8("horizontalGroupBox_11"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalGroupBox_11)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.Enlever_2 = QtGui.QPushButton(self.horizontalGroupBox_11)
        self.Enlever_2.setObjectName(_fromUtf8("Enlever_2"))
        self.horizontalLayout_11.addWidget(self.Enlever_2)
        self.Ajouter_2 = QtGui.QPushButton(self.horizontalGroupBox_11)
        self.Ajouter_2.setObjectName(_fromUtf8("Ajouter_2"))
        self.horizontalLayout_11.addWidget(self.Ajouter_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_7.addWidget(self.horizontalGroupBox_11)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tableWidget_6 = QtGui.QTableWidget(self.groupBox_10)
        self.tableWidget_6.setObjectName(_fromUtf8("tableWidget_6"))
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.gridLayout_7.addWidget(self.tableWidget_6, 0, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_7)
        self.verticalLayout_5.addWidget(self.groupBox_10)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalGroupBox_4 = QtGui.QGroupBox(Dialog)
        self.horizontalGroupBox_4.setObjectName(_fromUtf8("horizontalGroupBox_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalGroupBox_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.precedent_2 = QtGui.QPushButton(self.horizontalGroupBox_4)
        self.precedent_2.setObjectName(_fromUtf8("precedent_2"))
        self.horizontalLayout_4.addWidget(self.precedent_2)
        self.suivant_2 = QtGui.QPushButton(self.horizontalGroupBox_4)
        self.suivant_2.setObjectName(_fromUtf8("suivant_2"))
        self.horizontalLayout_4.addWidget(self.suivant_2)
        self.verticalLayout.addWidget(self.horizontalGroupBox_4)
        self.horizontalGroupBox_5 = QtGui.QGroupBox(Dialog)
        self.horizontalGroupBox_5.setObjectName(_fromUtf8("horizontalGroupBox_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalGroupBox_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.save = QtGui.QPushButton(self.horizontalGroupBox_5)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_5.addWidget(self.save)
        self.cancel = QtGui.QPushButton(self.horizontalGroupBox_5)
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.horizontalLayout_5.addWidget(self.cancel)
        self.verticalLayout.addWidget(self.horizontalGroupBox_5)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Saisie informations fusion CF", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Ancien CF ", None))
        self.numRoCertificatLabel_3.setText(_translate("Dialog", "CF1 :", None))
        self.label.setText(_translate("Dialog", "CF2 :", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Nouveau CF", None))
        self.label_2.setText(_translate("Dialog", "Nouveau Numero Demande", None))
        self.numRoCertificatLabel.setText(_translate("Dialog", "Numéro certificat", None))
        self.consistanceLabel.setText(_translate("Dialog", "Consistance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Nouveau Certificat", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Propriétaires du CF ancien", None))
        self.detail.setText(_translate("Dialog", "Détail", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nom", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Prénom", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Propriétaire du nouveau CF", None))
        self.remove.setText(_translate("Dialog", "Enlever", None))
        self.pushButtonAddition.setText(_translate("Dialog", "Ajouter", None))
        self.details.setText(_translate("Dialog", "Détails", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Noms", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Prenoms", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Propriétaires", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Charges du CF restant", None))
        self.enlever.setText(_translate("Dialog", "Enlever", None))
        self.add.setText(_translate("Dialog", "Ajouter", None))
        self.transfer.setText(_translate("Dialog", "Transferer", None))
        self.details_2.setText(_translate("Dialog", "Details", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Types de charges", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "N° CF", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Charges du nouveau CF", None))
        self.enlever_2.setText(_translate("Dialog", "Enlever", None))
        self.add_2.setText(_translate("Dialog", "Ajouter", None))
        self.detail_2.setText(_translate("Dialog", "Détail ..", None))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Type charge", None))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "N° certificat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Charges", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Limites de la parcelle pour le CF restant", None))
        self.Enlever.setText(_translate("Dialog", "Enlever", None))
        self.Ajouter.setText(_translate("Dialog", "Ajouter", None))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "N° certificat", None))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Position", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Limite de la parcelle du nouveau CF", None))
        self.Enlever_2.setText(_translate("Dialog", "Enlever", None))
        self.Ajouter_2.setText(_translate("Dialog", "Ajouter", None))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "N° certificat", None))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Limites de la parcelle", None))
        self.precedent_2.setText(_translate("Dialog", "Précédent", None))
        self.suivant_2.setText(_translate("Dialog", "Suivant", None))
        self.save.setText(_translate("Dialog", "Enregistrer", None))
        self.cancel.setText(_translate("Dialog", "Annuler", None))

