# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Configurations.ui'
#
# Created: Thu Apr  3 11:18:50 2025
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(598, 318)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBoxRemote = QtGui.QGroupBox(Dialog)
        self.groupBoxRemote.setObjectName(_fromUtf8("groupBoxRemote"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxRemote)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBoxRemote)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditHostRemote = QtGui.QLineEdit(self.groupBoxRemote)
        self.lineEditHostRemote.setObjectName(_fromUtf8("lineEditHostRemote"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditHostRemote)
        self.label_2 = QtGui.QLabel(self.groupBoxRemote)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBoxRemote)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBoxRemote)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditPortRemote = QtGui.QLineEdit(self.groupBoxRemote)
        self.lineEditPortRemote.setObjectName(_fromUtf8("lineEditPortRemote"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditPortRemote)
        self.lineEditUserRemote = QtGui.QLineEdit(self.groupBoxRemote)
        self.lineEditUserRemote.setObjectName(_fromUtf8("lineEditUserRemote"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditUserRemote)
        self.lineEditNomBaseRemote = QtGui.QLineEdit(self.groupBoxRemote)
        self.lineEditNomBaseRemote.setObjectName(_fromUtf8("lineEditNomBaseRemote"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditNomBaseRemote)
        self.label_10 = QtGui.QLabel(self.groupBoxRemote)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEditPasswordRemote = QtGui.QLineEdit(self.groupBoxRemote)
        self.lineEditPasswordRemote.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditPasswordRemote.setObjectName(_fromUtf8("lineEditPasswordRemote"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditPasswordRemote)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButtonTestConnexRemote = QtGui.QPushButton(self.groupBoxRemote)
        self.pushButtonTestConnexRemote.setObjectName(_fromUtf8("pushButtonTestConnexRemote"))
        self.verticalLayout.addWidget(self.pushButtonTestConnexRemote)
        self.gridLayout_3.addWidget(self.groupBoxRemote, 0, 0, 1, 1)
        self.groupBoxBackup = QtGui.QGroupBox(Dialog)
        self.groupBoxBackup.setObjectName(_fromUtf8("groupBoxBackup"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxBackup)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBoxBackup)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditHostBackup = QtGui.QLineEdit(self.groupBoxBackup)
        self.lineEditHostBackup.setObjectName(_fromUtf8("lineEditHostBackup"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditHostBackup)
        self.label_6 = QtGui.QLabel(self.groupBoxBackup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBoxBackup)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBoxBackup)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEditPortBackup = QtGui.QLineEdit(self.groupBoxBackup)
        self.lineEditPortBackup.setObjectName(_fromUtf8("lineEditPortBackup"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditPortBackup)
        self.lineEditUserBackup = QtGui.QLineEdit(self.groupBoxBackup)
        self.lineEditUserBackup.setObjectName(_fromUtf8("lineEditUserBackup"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditUserBackup)
        self.lineEditNomBaseBackup = QtGui.QLineEdit(self.groupBoxBackup)
        self.lineEditNomBaseBackup.setObjectName(_fromUtf8("lineEditNomBaseBackup"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditNomBaseBackup)
        self.label_11 = QtGui.QLabel(self.groupBoxBackup)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEditPasswordBackup = QtGui.QLineEdit(self.groupBoxBackup)
        self.lineEditPasswordBackup.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditPasswordBackup.setObjectName(_fromUtf8("lineEditPasswordBackup"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditPasswordBackup)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.pushButtonTestConnexBackup = QtGui.QPushButton(self.groupBoxBackup)
        self.pushButtonTestConnexBackup.setObjectName(_fromUtf8("pushButtonTestConnexBackup"))
        self.verticalLayout_2.addWidget(self.pushButtonTestConnexBackup)
        self.gridLayout_3.addWidget(self.groupBoxBackup, 0, 1, 1, 1)
        self.groupBoxAutre = QtGui.QGroupBox(Dialog)
        self.groupBoxAutre.setObjectName(_fromUtf8("groupBoxAutre"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxAutre)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.groupBoxAutre)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEditPathAutosave = QtGui.QLineEdit(self.groupBoxAutre)
        self.lineEditPathAutosave.setObjectName(_fromUtf8("lineEditPathAutosave"))
        self.gridLayout.addWidget(self.lineEditPathAutosave, 0, 1, 1, 1)
        self.checkBoxHasZoneCertifiable = QtGui.QCheckBox(self.groupBoxAutre)
        self.checkBoxHasZoneCertifiable.setObjectName(_fromUtf8("checkBoxHasZoneCertifiable"))
        self.gridLayout.addWidget(self.checkBoxHasZoneCertifiable, 1, 0, 1, 3)
        self.toolButtonParcourir = QtGui.QToolButton(self.groupBoxAutre)
        self.toolButtonParcourir.setObjectName(_fromUtf8("toolButtonParcourir"))
        self.gridLayout.addWidget(self.toolButtonParcourir, 0, 2, 1, 1)
        self.checkBoxOnlineInterco = QtGui.QCheckBox(self.groupBoxAutre)
        self.checkBoxOnlineInterco.setObjectName(_fromUtf8("checkBoxOnlineInterco"))
        self.gridLayout.addWidget(self.checkBoxOnlineInterco, 2, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxAutre, 1, 0, 1, 2)
        self.pushButtonEnregistrer = QtGui.QPushButton(Dialog)
        self.pushButtonEnregistrer.setObjectName(_fromUtf8("pushButtonEnregistrer"))
        self.gridLayout_3.addWidget(self.pushButtonEnregistrer, 2, 0, 1, 1)
        self.pushButtonFermer = QtGui.QPushButton(Dialog)
        self.pushButtonFermer.setObjectName(_fromUtf8("pushButtonFermer"))
        self.gridLayout_3.addWidget(self.pushButtonFermer, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBoxRemote.setTitle(_translate("Dialog", "Base de données distante", None))
        self.label.setText(_translate("Dialog", "Hôte", None))
        self.label_2.setText(_translate("Dialog", "Port", None))
        self.label_3.setText(_translate("Dialog", "Utilisateur", None))
        self.label_4.setText(_translate("Dialog", "Nom de la base", None))
        self.label_10.setText(_translate("Dialog", "Mot de passe", None))
        self.pushButtonTestConnexRemote.setText(_translate("Dialog", "Tester la connexion", None))
        self.groupBoxBackup.setTitle(_translate("Dialog", "Base de données de sauvegarde", None))
        self.label_5.setText(_translate("Dialog", "Hôte", None))
        self.label_6.setText(_translate("Dialog", "Port", None))
        self.label_7.setText(_translate("Dialog", "Utilisateur", None))
        self.label_8.setText(_translate("Dialog", "Nom de la base", None))
        self.label_11.setText(_translate("Dialog", "Mot de passe", None))
        self.pushButtonTestConnexBackup.setText(_translate("Dialog", "Tester la connexion", None))
        self.groupBoxAutre.setTitle(_translate("Dialog", "Autres", None))
        self.label_9.setText(_translate("Dialog", "Chemin de sauvegarde", None))
        self.checkBoxHasZoneCertifiable.setText(_translate("Dialog", "Avec zone certifiable", None))
        self.toolButtonParcourir.setText(_translate("Dialog", "...", None))
        self.checkBoxOnlineInterco.setText(_translate("Dialog", "Interconnexion en ligne", None))
        self.pushButtonEnregistrer.setText(_translate("Dialog", "Enregistrer", None))
        self.pushButtonFermer.setText(_translate("Dialog", "Fermer", None))

