# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Contribuable.ui'
#
# Created: Fri Jul 20 22:28:07 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(550, 350)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 531, 291))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.CIN = QtGui.QTabWidget(self.groupBox)
        self.CIN.setGeometry(QtCore.QRect(10, 180, 511, 111))
        self.CIN.setObjectName(_fromUtf8("CIN"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.lineEditLieuCIN = QtGui.QLineEdit(self.tab_5)
        self.lineEditLieuCIN.setGeometry(QtCore.QRect(320, 50, 191, 20))
        self.lineEditLieuCIN.setObjectName(_fromUtf8("lineEditLieuCIN"))
        self.lineEditCIN2 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN2.setGeometry(QtCore.QRect(160, 20, 41, 20))
        self.lineEditCIN2.setObjectName(_fromUtf8("lineEditCIN2"))
        self.dateEditCIN = QtGui.QDateEdit(self.tab_5)
        self.dateEditCIN.setGeometry(QtCore.QRect(110, 50, 110, 22))
        self.dateEditCIN.setCalendarPopup(True)
        self.dateEditCIN.setObjectName(_fromUtf8("dateEditCIN"))
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEditCIN3 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN3.setGeometry(QtCore.QRect(210, 20, 41, 20))
        self.lineEditCIN3.setObjectName(_fromUtf8("lineEditCIN3"))
        self.lineEditCIN4 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN4.setGeometry(QtCore.QRect(260, 20, 41, 20))
        self.lineEditCIN4.setObjectName(_fromUtf8("lineEditCIN4"))
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(280, 50, 40, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEditCIN1 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN1.setGeometry(QtCore.QRect(110, 20, 41, 20))
        self.lineEditCIN1.setObjectName(_fromUtf8("lineEditCIN1"))
        self.CIN.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.dateEditActeNaissance = QtGui.QDateEdit(self.tab_4)
        self.dateEditActeNaissance.setGeometry(QtCore.QRect(110, 50, 110, 22))
        self.dateEditActeNaissance.setCalendarPopup(True)
        self.dateEditActeNaissance.setObjectName(_fromUtf8("dateEditActeNaissance"))
        self.lineEditLieuActeNaissance = QtGui.QLineEdit(self.tab_4)
        self.lineEditLieuActeNaissance.setGeometry(QtCore.QRect(320, 50, 181, 20))
        self.lineEditLieuActeNaissance.setObjectName(_fromUtf8("lineEditLieuActeNaissance"))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(280, 50, 40, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEditNumActeNaissance = QtGui.QLineEdit(self.tab_4)
        self.lineEditNumActeNaissance.setGeometry(QtCore.QRect(110, 20, 111, 20))
        self.lineEditNumActeNaissance.setObjectName(_fromUtf8("lineEditNumActeNaissance"))
        self.CIN.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.CIN.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 20, 442, 158))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditNom = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.gridLayout.addWidget(self.lineEditNom, 0, 1, 1, 1)
        self.btnRecherche = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnRecherche.setObjectName(_fromUtf8("btnRecherche"))
        self.gridLayout.addWidget(self.btnRecherche, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditPrenom = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.gridLayout.addWidget(self.lineEditPrenom, 1, 1, 1, 1)
        self.btnPersonnePhysique = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnPersonnePhysique.setObjectName(_fromUtf8("btnPersonnePhysique"))
        self.gridLayout.addWidget(self.btnPersonnePhysique, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditAdresse = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditAdresse.setObjectName(_fromUtf8("lineEditAdresse"))
        self.gridLayout.addWidget(self.lineEditAdresse, 2, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 2, 2, 1, 1)
        self.btnConsorts = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnConsorts.setObjectName(_fromUtf8("btnConsorts"))
        self.gridLayout.addWidget(self.btnConsorts, 2, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.dateEditNaissance = QtGui.QDateEdit(self.gridLayoutWidget)
        self.dateEditNaissance.setCalendarPopup(True)
        self.dateEditNaissance.setObjectName(_fromUtf8("dateEditNaissance"))
        self.gridLayout.addWidget(self.dateEditNaissance, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEditLieuNaissance = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditLieuNaissance.setObjectName(_fromUtf8("lineEditLieuNaissance"))
        self.gridLayout.addWidget(self.lineEditLieuNaissance, 5, 1, 1, 1)
        self.radioHomme = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioHomme.setObjectName(_fromUtf8("radioHomme"))
        self.gridLayout.addWidget(self.radioHomme, 4, 1, 1, 1)
        self.radioFemme = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioFemme.setObjectName(_fromUtf8("radioFemme"))
        self.gridLayout.addWidget(self.radioFemme, 4, 2, 1, 1)
        self.neVersCheckBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.neVersCheckBox.setObjectName(_fromUtf8("neVersCheckBox"))
        self.gridLayout.addWidget(self.neVersCheckBox, 3, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 300, 530, 41))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btnOk = QtGui.QPushButton(self.groupBox_3)
        self.btnOk.setGeometry(QtCore.QRect(350, 10, 75, 23))
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.btnAnnuler = QtGui.QPushButton(self.groupBox_3)
        self.btnAnnuler.setGeometry(QtCore.QRect(450, 10, 75, 23))
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))

        self.retranslateUi(Dialog)
        self.CIN.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Contribuable", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Contribuable", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Lieu :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Numero : ", None, QtGui.QApplication.UnicodeUTF8))
        self.CIN.setTabText(self.CIN.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "CIN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Lieu :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Numero : ", None, QtGui.QApplication.UnicodeUTF8))
        self.CIN.setTabText(self.CIN.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Acte de naissnace", None, QtGui.QApplication.UnicodeUTF8))
        self.CIN.setTabText(self.CIN.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog", "Rien", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Nom :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRecherche.setText(QtGui.QApplication.translate("Dialog", "Recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Prénom :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPersonnePhysique.setText(QtGui.QApplication.translate("Dialog", "Personnes physiques", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Adresse :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConsorts.setText(QtGui.QApplication.translate("Dialog", "Consorts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Date de naissance : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Lieu de naissance :", None, QtGui.QApplication.UnicodeUTF8))
        self.radioHomme.setText(QtGui.QApplication.translate("Dialog", "Homme", None, QtGui.QApplication.UnicodeUTF8))
        self.radioFemme.setText(QtGui.QApplication.translate("Dialog", "Femme", None, QtGui.QApplication.UnicodeUTF8))
        self.neVersCheckBox.setText(QtGui.QApplication.translate("Dialog", "Né vers", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAnnuler.setText(QtGui.QApplication.translate("Dialog", "Annuler", None, QtGui.QApplication.UnicodeUTF8))

