# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suivi.ui'
#
# Created: Fri Dec 21 14:16:48 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1154, 663)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../icone/suivi_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBoxParcelle = QtGui.QGroupBox(Dialog)
        self.groupBoxParcelle.setObjectName(_fromUtf8("groupBoxParcelle"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBoxParcelle)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label = QtGui.QLabel(self.groupBoxParcelle)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxFokontany = QtGui.QComboBox(self.groupBoxParcelle)
        self.comboBoxFokontany.setObjectName(_fromUtf8("comboBoxFokontany"))
        self.gridLayout_7.addWidget(self.comboBoxFokontany, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 3, 1, 1)
        self.comboBoxHameau = QtGui.QComboBox(self.groupBoxParcelle)
        self.comboBoxHameau.setObjectName(_fromUtf8("comboBoxHameau"))
        self.gridLayout_7.addWidget(self.comboBoxHameau, 0, 4, 1, 1)
        self.radioButtonTitree = QtGui.QRadioButton(self.groupBoxParcelle)
        self.radioButtonTitree.setObjectName(_fromUtf8("radioButtonTitree"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonTitree)
        self.gridLayout_7.addWidget(self.radioButtonTitree, 1, 0, 1, 1)
        self.radioButtonCadastre = QtGui.QRadioButton(self.groupBoxParcelle)
        self.radioButtonCadastre.setObjectName(_fromUtf8("radioButtonCadastre"))
        self.buttonGroup.addButton(self.radioButtonCadastre)
        self.gridLayout_7.addWidget(self.radioButtonCadastre, 1, 1, 1, 1)
        self.radioButtonCertifie = QtGui.QRadioButton(self.groupBoxParcelle)
        self.radioButtonCertifie.setObjectName(_fromUtf8("radioButtonCertifie"))
        self.buttonGroup.addButton(self.radioButtonCertifie)
        self.gridLayout_7.addWidget(self.radioButtonCertifie, 1, 2, 1, 2)
        self.radioButtonAucun = QtGui.QRadioButton(self.groupBoxParcelle)
        self.radioButtonAucun.setObjectName(_fromUtf8("radioButtonAucun"))
        self.buttonGroup.addButton(self.radioButtonAucun)
        self.gridLayout_7.addWidget(self.radioButtonAucun, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditNumero = QtGui.QLineEdit(self.groupBoxParcelle)
        self.lineEditNumero.setObjectName(_fromUtf8("lineEditNumero"))
        self.gridLayout_7.addWidget(self.lineEditNumero, 2, 1, 1, 1)
        self.radioButtonSRI = QtGui.QRadioButton(self.groupBoxParcelle)
        self.radioButtonSRI.setObjectName(_fromUtf8("radioButtonSRI"))
        self.buttonGroup_4 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButtonSRI)
        self.gridLayout_7.addWidget(self.radioButtonSRI, 2, 3, 1, 1)
        self.radioButtonSRA = QtGui.QRadioButton(self.groupBoxParcelle)
        self.radioButtonSRA.setObjectName(_fromUtf8("radioButtonSRA"))
        self.buttonGroup_4.addButton(self.radioButtonSRA)
        self.gridLayout_7.addWidget(self.radioButtonSRA, 2, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditCode = QtGui.QLineEdit(self.groupBoxParcelle)
        self.lineEditCode.setObjectName(_fromUtf8("lineEditCode"))
        self.gridLayout_7.addWidget(self.lineEditCode, 3, 1, 1, 1)
        self.checkBoxAlloueParcelle = QtGui.QCheckBox(self.groupBoxParcelle)
        self.checkBoxAlloueParcelle.setObjectName(_fromUtf8("checkBoxAlloueParcelle"))
        self.gridLayout_7.addWidget(self.checkBoxAlloueParcelle, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 4, 0, 1, 1)
        self.plainTextEditObservation = QtGui.QPlainTextEdit(self.groupBoxParcelle)
        self.plainTextEditObservation.setObjectName(_fromUtf8("plainTextEditObservation"))
        self.gridLayout_7.addWidget(self.plainTextEditObservation, 4, 1, 1, 4)
        self.label_6 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEditSurfaceM2 = QtGui.QLineEdit(self.groupBoxParcelle)
        self.lineEditSurfaceM2.setObjectName(_fromUtf8("lineEditSurfaceM2"))
        self.gridLayout_7.addWidget(self.lineEditSurfaceM2, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 5, 2, 1, 1)
        self.lineEditSurfaceHa = QtGui.QLineEdit(self.groupBoxParcelle)
        self.lineEditSurfaceHa.setObjectName(_fromUtf8("lineEditSurfaceHa"))
        self.gridLayout_7.addWidget(self.lineEditSurfaceHa, 5, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 5, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 6, 0, 1, 1)
        self.comboBoxCategorieParcelle = QtGui.QComboBox(self.groupBoxParcelle)
        self.comboBoxCategorieParcelle.setObjectName(_fromUtf8("comboBoxCategorieParcelle"))
        self.gridLayout_7.addWidget(self.comboBoxCategorieParcelle, 6, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBoxParcelle)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 7, 0, 1, 1)
        self.comboBoxConsistanceParcelle = QtGui.QComboBox(self.groupBoxParcelle)
        self.comboBoxConsistanceParcelle.setObjectName(_fromUtf8("comboBoxConsistanceParcelle"))
        self.gridLayout_7.addWidget(self.comboBoxConsistanceParcelle, 7, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBoxParcelle, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditNbrPieces = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditNbrPieces.setObjectName(_fromUtf8("lineEditNbrPieces"))
        self.gridLayout_2.addWidget(self.lineEditNbrPieces, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.checkBoxAvecLocationBat = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxAvecLocationBat.setObjectName(_fromUtf8("checkBoxAvecLocationBat"))
        self.gridLayout_2.addWidget(self.checkBoxAvecLocationBat, 1, 6, 1, 1)
        self.lineEditCodeBatiment = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditCodeBatiment.setObjectName(_fromUtf8("lineEditCodeBatiment"))
        self.gridLayout_2.addWidget(self.lineEditCodeBatiment, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.comboBoxConsistanceBatiment = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxConsistanceBatiment.setObjectName(_fromUtf8("comboBoxConsistanceBatiment"))
        self.gridLayout_2.addWidget(self.comboBoxConsistanceBatiment, 1, 1, 1, 1)
        self.lineEditSurfaceBatiment = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditSurfaceBatiment.setObjectName(_fromUtf8("lineEditSurfaceBatiment"))
        self.gridLayout_2.addWidget(self.lineEditSurfaceBatiment, 1, 3, 1, 1)
        self.comboBoxCategorieBatiment = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxCategorieBatiment.setObjectName(_fromUtf8("comboBoxCategorieBatiment"))
        self.gridLayout_2.addWidget(self.comboBoxCategorieBatiment, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 1, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBoxContribuable = QtGui.QGroupBox(Dialog)
        self.groupBoxContribuable.setObjectName(_fromUtf8("groupBoxContribuable"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBoxContribuable)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.radioButtonCIN = QtGui.QRadioButton(self.groupBoxContribuable)
        self.radioButtonCIN.setObjectName(_fromUtf8("radioButtonCIN"))
        self.buttonGroup_2 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButtonCIN)
        self.gridLayout_4.addWidget(self.radioButtonCIN, 6, 0, 1, 1)
        self.dateEditNaissance = QtGui.QDateEdit(self.groupBoxContribuable)
        self.dateEditNaissance.setObjectName(_fromUtf8("dateEditNaissance"))
        self.gridLayout_4.addWidget(self.dateEditNaissance, 3, 1, 1, 1)
        self.lineEditLieuNaissance = QtGui.QLineEdit(self.groupBoxContribuable)
        self.lineEditLieuNaissance.setObjectName(_fromUtf8("lineEditLieuNaissance"))
        self.gridLayout_4.addWidget(self.lineEditLieuNaissance, 4, 1, 1, 1)
        self.radioButtonRien = QtGui.QRadioButton(self.groupBoxContribuable)
        self.radioButtonRien.setObjectName(_fromUtf8("radioButtonRien"))
        self.buttonGroup_2.addButton(self.radioButtonRien)
        self.gridLayout_4.addWidget(self.radioButtonRien, 6, 2, 1, 1)
        self.radioButtonActeDeNaissance = QtGui.QRadioButton(self.groupBoxContribuable)
        self.radioButtonActeDeNaissance.setObjectName(_fromUtf8("radioButtonActeDeNaissance"))
        self.buttonGroup_2.addButton(self.radioButtonActeDeNaissance)
        self.gridLayout_4.addWidget(self.radioButtonActeDeNaissance, 6, 1, 1, 1)
        self.lineEditAdresse = QtGui.QLineEdit(self.groupBoxContribuable)
        self.lineEditAdresse.setObjectName(_fromUtf8("lineEditAdresse"))
        self.gridLayout_4.addWidget(self.lineEditAdresse, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBoxContribuable)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBoxContribuable)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBoxContribuable)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBoxContribuable)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBoxContribuable)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 4, 0, 1, 1)
        self.lineEditNomContribuable = QtGui.QLineEdit(self.groupBoxContribuable)
        self.lineEditNomContribuable.setObjectName(_fromUtf8("lineEditNomContribuable"))
        self.gridLayout_4.addWidget(self.lineEditNomContribuable, 0, 1, 1, 1)
        self.lineEditPrenomContribuable = QtGui.QLineEdit(self.groupBoxContribuable)
        self.lineEditPrenomContribuable.setObjectName(_fromUtf8("lineEditPrenomContribuable"))
        self.gridLayout_4.addWidget(self.lineEditPrenomContribuable, 1, 1, 1, 1)
        self.btnRrechercherContribuable = QtGui.QPushButton(self.groupBoxContribuable)
        self.btnRrechercherContribuable.setObjectName(_fromUtf8("btnRrechercherContribuable"))
        self.gridLayout_4.addWidget(self.btnRrechercherContribuable, 0, 2, 1, 2)
        self.radioButtonFemme = QtGui.QRadioButton(self.groupBoxContribuable)
        self.radioButtonFemme.setObjectName(_fromUtf8("radioButtonFemme"))
        self.buttonGroup_3 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButtonFemme)
        self.gridLayout_4.addWidget(self.radioButtonFemme, 5, 2, 1, 1)
        self.radioButtonHomme = QtGui.QRadioButton(self.groupBoxContribuable)
        self.radioButtonHomme.setObjectName(_fromUtf8("radioButtonHomme"))
        self.buttonGroup_3.addButton(self.radioButtonHomme)
        self.gridLayout_4.addWidget(self.radioButtonHomme, 5, 1, 1, 1)
        self.checkBoxNeVers = QtGui.QCheckBox(self.groupBoxContribuable)
        self.checkBoxNeVers.setObjectName(_fromUtf8("checkBoxNeVers"))
        self.gridLayout_4.addWidget(self.checkBoxNeVers, 3, 2, 1, 1)
        self.btnConsorts = QtGui.QPushButton(self.groupBoxContribuable)
        self.btnConsorts.setObjectName(_fromUtf8("btnConsorts"))
        self.gridLayout_4.addWidget(self.btnConsorts, 4, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.tabCIN = QtGui.QTabWidget(self.groupBoxContribuable)
        self.tabCIN.setObjectName(_fromUtf8("tabCIN"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 1)
        self.lineEditCIN1 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN1.setObjectName(_fromUtf8("lineEditCIN1"))
        self.gridLayout_5.addWidget(self.lineEditCIN1, 0, 1, 1, 1)
        self.lineEditCIN2 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN2.setObjectName(_fromUtf8("lineEditCIN2"))
        self.gridLayout_5.addWidget(self.lineEditCIN2, 0, 2, 1, 1)
        self.lineEditCIN3 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN3.setObjectName(_fromUtf8("lineEditCIN3"))
        self.gridLayout_5.addWidget(self.lineEditCIN3, 0, 3, 1, 1)
        self.lineEditCIN4 = QtGui.QLineEdit(self.tab_5)
        self.lineEditCIN4.setObjectName(_fromUtf8("lineEditCIN4"))
        self.gridLayout_5.addWidget(self.lineEditCIN4, 0, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 1, 0, 1, 1)
        self.dateEditCIN = QtGui.QDateEdit(self.tab_5)
        self.dateEditCIN.setCalendarPopup(True)
        self.dateEditCIN.setObjectName(_fromUtf8("dateEditCIN"))
        self.gridLayout_5.addWidget(self.dateEditCIN, 1, 1, 1, 3)
        self.label_25 = QtGui.QLabel(self.tab_5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 1, 4, 1, 1)
        self.lineEditLieuCIN = QtGui.QLineEdit(self.tab_5)
        self.lineEditLieuCIN.setObjectName(_fromUtf8("lineEditLieuCIN"))
        self.gridLayout_5.addWidget(self.lineEditLieuCIN, 1, 5, 1, 1)
        self.tabCIN.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_6.addWidget(self.label_29, 0, 0, 1, 1)
        self.lineEditNumActeNaissance = QtGui.QLineEdit(self.tab_4)
        self.lineEditNumActeNaissance.setObjectName(_fromUtf8("lineEditNumActeNaissance"))
        self.gridLayout_6.addWidget(self.lineEditNumActeNaissance, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_6.addWidget(self.label_27, 1, 0, 1, 1)
        self.dateEditActeNaissance = QtGui.QDateEdit(self.tab_4)
        self.dateEditActeNaissance.setCalendarPopup(True)
        self.dateEditActeNaissance.setObjectName(_fromUtf8("dateEditActeNaissance"))
        self.gridLayout_6.addWidget(self.dateEditActeNaissance, 1, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_6.addWidget(self.label_28, 1, 2, 1, 1)
        self.lineEditLieuActeNaissance = QtGui.QLineEdit(self.tab_4)
        self.lineEditLieuActeNaissance.setObjectName(_fromUtf8("lineEditLieuActeNaissance"))
        self.gridLayout_6.addWidget(self.lineEditLieuActeNaissance, 1, 3, 1, 1)
        self.tabCIN.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabCIN.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabCIN)
        self.gridLayout.addWidget(self.groupBoxContribuable, 1, 2, 2, 2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAjouterBat = QtGui.QPushButton(self.groupBox_3)
        self.btnAjouterBat.setObjectName(_fromUtf8("btnAjouterBat"))
        self.horizontalLayout.addWidget(self.btnAjouterBat)
        self.btnSupprimerBat = QtGui.QPushButton(self.groupBox_3)
        self.btnSupprimerBat.setObjectName(_fromUtf8("btnSupprimerBat"))
        self.horizontalLayout.addWidget(self.btnSupprimerBat)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidgetBatiment = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidgetBatiment.setObjectName(_fromUtf8("tableWidgetBatiment"))
        self.tableWidgetBatiment.setColumnCount(5)
        self.tableWidgetBatiment.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBatiment.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBatiment.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBatiment.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBatiment.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBatiment.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidgetBatiment)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnVoirConsorts = QtGui.QPushButton(self.groupBox_5)
        self.btnVoirConsorts.setObjectName(_fromUtf8("btnVoirConsorts"))
        self.horizontalLayout_3.addWidget(self.btnVoirConsorts)
        self.btnModifierConsorts = QtGui.QPushButton(self.groupBox_5)
        self.btnModifierConsorts.setObjectName(_fromUtf8("btnModifierConsorts"))
        self.horizontalLayout_3.addWidget(self.btnModifierConsorts)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tableWidgetConsorts = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidgetConsorts.setObjectName(_fromUtf8("tableWidgetConsorts"))
        self.tableWidgetConsorts.setColumnCount(4)
        self.tableWidgetConsorts.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConsorts.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConsorts.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConsorts.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConsorts.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableWidgetConsorts)
        self.gridLayout.addWidget(self.groupBox_5, 2, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_2.addWidget(self.label_16)
        self.lineEditNumDemande = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditNumDemande.setObjectName(_fromUtf8("lineEditNumDemande"))
        self.horizontalLayout_2.addWidget(self.lineEditNumDemande)
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_2.addWidget(self.label_17)
        self.lineEditNumCertificat = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditNumCertificat.setObjectName(_fromUtf8("lineEditNumCertificat"))
        self.horizontalLayout_2.addWidget(self.lineEditNumCertificat)
        self.gridLayout.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(Dialog)
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnPrecedent = QtGui.QPushButton(self.groupBox_9)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.horizontalLayout_5.addWidget(self.btnPrecedent)
        self.btnSuivant = QtGui.QPushButton(self.groupBox_9)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.horizontalLayout_5.addWidget(self.btnSuivant)
        self.checkBoxAvecProbleme = QtGui.QCheckBox(self.groupBox_9)
        self.checkBoxAvecProbleme.setObjectName(_fromUtf8("checkBoxAvecProbleme"))
        self.horizontalLayout_5.addWidget(self.checkBoxAvecProbleme)
        self.btnEnregistrer = QtGui.QPushButton(self.groupBox_9)
        self.btnEnregistrer.setObjectName(_fromUtf8("btnEnregistrer"))
        self.horizontalLayout_5.addWidget(self.btnEnregistrer)
        self.btnFermer = QtGui.QPushButton(self.groupBox_9)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_5.addWidget(self.btnFermer)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.groupBox_9, 3, 1, 1, 3)
        self.horizontalLayout_ = QtGui.QHBoxLayout()
        self.horizontalLayout_.setObjectName(_fromUtf8("horizontalLayout_"))
        self.gridLayout.addLayout(self.horizontalLayout_, 0, 3, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.positionLabel = QtGui.QLabel(self.groupBox_6)
        self.positionLabel.setObjectName(_fromUtf8("positionLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.positionLabel)
        self.positionComboBox = QtGui.QComboBox(self.groupBox_6)
        self.positionComboBox.setObjectName(_fromUtf8("positionComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.positionComboBox)
        self.descriptionLabel = QtGui.QLabel(self.groupBox_6)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.descriptionLabel)
        self.descriptionLineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.descriptionLineEdit.setObjectName(_fromUtf8("descriptionLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.descriptionLineEdit)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnAjoutLimite = QtGui.QPushButton(self.groupBox_7)
        self.btnAjoutLimite.setObjectName(_fromUtf8("btnAjoutLimite"))
        self.horizontalLayout_4.addWidget(self.btnAjoutLimite)
        self.btnSupprimerLimite = QtGui.QPushButton(self.groupBox_7)
        self.btnSupprimerLimite.setObjectName(_fromUtf8("btnSupprimerLimite"))
        self.horizontalLayout_4.addWidget(self.btnSupprimerLimite)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tableWidgetLimites = QtGui.QTableWidget(self.groupBox_7)
        self.tableWidgetLimites.setObjectName(_fromUtf8("tableWidgetLimites"))
        self.tableWidgetLimites.setColumnCount(2)
        self.tableWidgetLimites.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetLimites.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetLimites.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tableWidgetLimites)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.gridLayout.addWidget(self.groupBox_6, 0, 1, 1, 2)

        self.retranslateUi(Dialog)
        self.tabCIN.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Suivi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxParcelle.setTitle(QtGui.QApplication.translate("Dialog", "Parcelle", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Fokonatny", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Hameau", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonTitree.setText(QtGui.QApplication.translate("Dialog", "Titré", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCadastre.setText(QtGui.QApplication.translate("Dialog", "Cadastré", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCertifie.setText(QtGui.QApplication.translate("Dialog", "Certifié", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonAucun.setText(QtGui.QApplication.translate("Dialog", "Aucun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Numéro", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSRI.setText(QtGui.QApplication.translate("Dialog", "SRI", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSRA.setText(QtGui.QApplication.translate("Dialog", "SRA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAlloueParcelle.setText(QtGui.QApplication.translate("Dialog", "Allooué", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Observation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "m2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Ha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Catégorie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Batiments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAvecLocationBat.setText(QtGui.QApplication.translate("Dialog", "Avec location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Surface (m2)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Nombre de pièces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Catégorie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxContribuable.setTitle(QtGui.QApplication.translate("Dialog", "Contribuable", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCIN.setText(QtGui.QApplication.translate("Dialog", "CIN", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRien.setText(QtGui.QApplication.translate("Dialog", "Rien", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonActeDeNaissance.setText(QtGui.QApplication.translate("Dialog", "Acte de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Prénom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Adresse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Date de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Lieu de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRrechercherContribuable.setText(QtGui.QApplication.translate("Dialog", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonFemme.setText(QtGui.QApplication.translate("Dialog", "Femme", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonHomme.setText(QtGui.QApplication.translate("Dialog", "Homme", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNeVers.setText(QtGui.QApplication.translate("Dialog", "Né vers", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConsorts.setText(QtGui.QApplication.translate("Dialog", "Consorts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Numero : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Lieu :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCIN.setTabText(self.tabCIN.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "CIN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "Numero : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "Lieu :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCIN.setTabText(self.tabCIN.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Acte de naissnace", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCIN.setTabText(self.tabCIN.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog", "Rien", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouterBat.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSupprimerBat.setText(QtGui.QApplication.translate("Dialog", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetBatiment.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Code", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetBatiment.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Catégorie", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetBatiment.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Consistance", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetBatiment.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetBatiment.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "Pièces", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Consorts", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoirConsorts.setText(QtGui.QApplication.translate("Dialog", "Voir", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModifierConsorts.setText(QtGui.QApplication.translate("Dialog", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetConsorts.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetConsorts.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Prénom", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetConsorts.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "CIN", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetConsorts.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Acte", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Numéro demande", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Numéro certificat", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrecedent.setText(QtGui.QApplication.translate("Dialog", "Precedent", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSuivant.setText(QtGui.QApplication.translate("Dialog", "Suivant", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAvecProbleme.setText(QtGui.QApplication.translate("Dialog", "Avec problème", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnregistrer.setText(QtGui.QApplication.translate("Dialog", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Limite et repère du certificat foncier", None, QtGui.QApplication.UnicodeUTF8))
        self.positionLabel.setText(QtGui.QApplication.translate("Dialog", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionLabel.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjoutLimite.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSupprimerLimite.setText(QtGui.QApplication.translate("Dialog", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetLimites.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Position", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetLimites.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))

