# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListePiecesAnnulation.ui'
#
# Created: Sat Aug 18 10:09:28 2018
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(485, 518)
        Dialog.setModal(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxNumDecision = QtGui.QCheckBox(self.groupBox)
        self.checkBoxNumDecision.setObjectName(_fromUtf8("checkBoxNumDecision"))
        self.gridLayout.addWidget(self.checkBoxNumDecision, 1, 0, 1, 1)
        self.lineEditNumDecision = QtGui.QLineEdit(self.groupBox)
        self.lineEditNumDecision.setEnabled(False)
        self.lineEditNumDecision.setObjectName(_fromUtf8("lineEditNumDecision"))
        self.gridLayout.addWidget(self.lineEditNumDecision, 1, 1, 1, 1)
        self.checkBoxTypeDecision = QtGui.QCheckBox(self.groupBox)
        self.checkBoxTypeDecision.setObjectName(_fromUtf8("checkBoxTypeDecision"))
        self.gridLayout.addWidget(self.checkBoxTypeDecision, 0, 0, 1, 1)
        self.comboBoxTypeDecision = QtGui.QComboBox(self.groupBox)
        self.comboBoxTypeDecision.setObjectName(_fromUtf8("comboBoxTypeDecision"))
        self.comboBoxTypeDecision.addItem(_fromUtf8(""))
        self.comboBoxTypeDecision.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxTypeDecision, 0, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAfficherTous = QtGui.QPushButton(self.frame)
        self.btnAfficherTous.setObjectName(_fromUtf8("btnAfficherTous"))
        self.horizontalLayout.addWidget(self.btnAfficherTous)
        self.btnAjouter = QtGui.QPushButton(self.frame)
        self.btnAjouter.setObjectName(_fromUtf8("btnAjouter"))
        self.horizontalLayout.addWidget(self.btnAjouter)
        self.btnRechercher = QtGui.QPushButton(self.frame)
        self.btnRechercher.setObjectName(_fromUtf8("btnRechercher"))
        self.horizontalLayout.addWidget(self.btnRechercher)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.frame_3)
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(168)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnDetail = QtGui.QPushButton(Dialog)
        self.btnDetail.setObjectName(_fromUtf8("btnDetail"))
        self.horizontalLayout_3.addWidget(self.btnDetail)
        self.btnSelectionner = QtGui.QPushButton(Dialog)
        self.btnSelectionner.setObjectName(_fromUtf8("btnSelectionner"))
        self.horizontalLayout_3.addWidget(self.btnSelectionner)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))
        self.horizontalLayout_3.addWidget(self.btnFermer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Liste des pièces d\'annulation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNumDecision.setText(QtGui.QApplication.translate("Dialog", "N° décision", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTypeDecision.setText(QtGui.QApplication.translate("Dialog", "Type décision", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTypeDecision.setItemText(0, QtGui.QApplication.translate("Dialog", "Maire", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTypeDecision.setItemText(1, QtGui.QApplication.translate("Dialog", "Tribunal", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAfficherTous.setText(QtGui.QApplication.translate("Dialog", "Afficher tous", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAjouter.setText(QtGui.QApplication.translate("Dialog", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRechercher.setText(QtGui.QApplication.translate("Dialog", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "N° Acte", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Date de l\'acte", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "N° décision", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Type de décision", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "ID ACTE", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetail.setText(QtGui.QApplication.translate("Dialog", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectionner.setText(QtGui.QApplication.translate("Dialog", "Selectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFermer.setText(QtGui.QApplication.translate("Dialog", "Fermer", None, QtGui.QApplication.UnicodeUTF8))

