# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddLayer.ui'
#
# Created: Tue Oct  8 07:57:57 2024
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(560, 433)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/wrench-screwdriver-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.lineEditFichier = QtGui.QLineEdit(self.tab)
        self.lineEditFichier.setReadOnly(True)
        self.lineEditFichier.setObjectName(_fromUtf8("lineEditFichier"))
        self.gridLayout.addWidget(self.lineEditFichier, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.comboBoxType = QtGui.QComboBox(self.tab)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.comboBoxType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxType, 2, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("background:#808080;color:white;padding:5px"))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 3)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButtonParcourir = QtGui.QPushButton(self.tab)
        self.pushButtonParcourir.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_folder_horizontal_open_11903.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonParcourir.setIcon(icon1)
        self.pushButtonParcourir.setObjectName(_fromUtf8("pushButtonParcourir"))
        self.gridLayout.addWidget(self.pushButtonParcourir, 5, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.pushButtonCouleur = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCouleur.sizePolicy().hasHeightForWidth())
        self.pushButtonCouleur.setSizePolicy(sizePolicy)
        self.pushButtonCouleur.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonCouleur.setStyleSheet(_fromUtf8("text-align:left;padding:5px"))
        self.pushButtonCouleur.setObjectName(_fromUtf8("pushButtonCouleur"))
        self.gridLayout.addWidget(self.pushButtonCouleur, 3, 1, 1, 1)
        self.lineEditLibelle = QtGui.QLineEdit(self.tab)
        self.lineEditLibelle.setObjectName(_fromUtf8("lineEditLibelle"))
        self.gridLayout.addWidget(self.lineEditLibelle, 1, 1, 1, 2)
        self.remplissage = QtGui.QCheckBox(self.tab)
        self.remplissage.setText(_fromUtf8(""))
        self.remplissage.setChecked(True)
        self.remplissage.setObjectName(_fromUtf8("remplissage"))
        self.gridLayout.addWidget(self.remplissage, 4, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.checkPlofPaps = QtGui.QCheckBox(self.tab)
        self.checkPlofPaps.setText(_fromUtf8(""))
        self.checkPlofPaps.setObjectName(_fromUtf8("checkPlofPaps"))
        self.gridLayout.addWidget(self.checkPlofPaps, 6, 1, 1, 1)
        self.labelCertifiable = QtGui.QLabel(self.tab)
        self.labelCertifiable.setEnabled(False)
        self.labelCertifiable.setObjectName(_fromUtf8("labelCertifiable"))
        self.gridLayout.addWidget(self.labelCertifiable, 7, 0, 1, 1)
        self.checkBoxCertifiable = QtGui.QCheckBox(self.tab)
        self.checkBoxCertifiable.setEnabled(False)
        self.checkBoxCertifiable.setText(_fromUtf8(""))
        self.checkBoxCertifiable.setObjectName(_fromUtf8("checkBoxCertifiable"))
        self.gridLayout.addWidget(self.checkBoxCertifiable, 7, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.tabWidget.addTab(self.tab, icon, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("background:#808080;color:white;padding:5px"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBoxLabel = QtGui.QCheckBox(self.tab_2)
        self.checkBoxLabel.setObjectName(_fromUtf8("checkBoxLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxLabel)
        self.comboBoxLabel = QtGui.QComboBox(self.tab_2)
        self.comboBoxLabel.setEnabled(False)
        self.comboBoxLabel.setObjectName(_fromUtf8("comboBoxLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxLabel)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.groupBoxText = QtGui.QGroupBox(self.tab_2)
        self.groupBoxText.setEnabled(False)
        self.groupBoxText.setObjectName(_fromUtf8("groupBoxText"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxText)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBoxText)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.fontComboBox = QtGui.QFontComboBox(self.groupBoxText)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.gridLayout_3.addWidget(self.fontComboBox, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBoxText)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinBoxFontSize = QtGui.QSpinBox(self.groupBoxText)
        self.spinBoxFontSize.setObjectName(_fromUtf8("spinBoxFontSize"))
        self.gridLayout_3.addWidget(self.spinBoxFontSize, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBoxText)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.pushButtonLabelColor = QtGui.QPushButton(self.groupBoxText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLabelColor.sizePolicy().hasHeightForWidth())
        self.pushButtonLabelColor.setSizePolicy(sizePolicy)
        self.pushButtonLabelColor.setObjectName(_fromUtf8("pushButtonLabelColor"))
        self.gridLayout_3.addWidget(self.pushButtonLabelColor, 3, 1, 1, 1)
        self.checkBoxMapUnit = QtGui.QCheckBox(self.groupBoxText)
        self.checkBoxMapUnit.setObjectName(_fromUtf8("checkBoxMapUnit"))
        self.gridLayout_3.addWidget(self.checkBoxMapUnit, 2, 1, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(1, 300)
        self.verticalLayout_2.addWidget(self.groupBoxText)
        self.groupBoxStroke = QtGui.QGroupBox(self.tab_2)
        self.groupBoxStroke.setEnabled(False)
        self.groupBoxStroke.setObjectName(_fromUtf8("groupBoxStroke"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxStroke)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBoxStroke = QtGui.QCheckBox(self.groupBoxStroke)
        self.checkBoxStroke.setObjectName(_fromUtf8("checkBoxStroke"))
        self.gridLayout_2.addWidget(self.checkBoxStroke, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBoxStroke)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.spinBoxStrokeWidth = QtGui.QSpinBox(self.groupBoxStroke)
        self.spinBoxStrokeWidth.setEnabled(False)
        self.spinBoxStrokeWidth.setObjectName(_fromUtf8("spinBoxStrokeWidth"))
        self.gridLayout_2.addWidget(self.spinBoxStrokeWidth, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBoxStroke)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.pushButtonColorStroke = QtGui.QPushButton(self.groupBoxStroke)
        self.pushButtonColorStroke.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColorStroke.sizePolicy().hasHeightForWidth())
        self.pushButtonColorStroke.setSizePolicy(sizePolicy)
        self.pushButtonColorStroke.setObjectName(_fromUtf8("pushButtonColorStroke"))
        self.gridLayout_2.addWidget(self.pushButtonColorStroke, 2, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(1, 300)
        self.verticalLayout_2.addWidget(self.groupBoxStroke)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_pencil_14623.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonEnregistrer = QtGui.QPushButton(Dialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEnregistrer.setIcon(icon3)
        self.pushButtonEnregistrer.setObjectName(_fromUtf8("pushButtonEnregistrer"))
        self.horizontalLayout.addWidget(self.pushButtonEnregistrer)
        self.pushButtonAnnuler = QtGui.QPushButton(Dialog)
        self.pushButtonAnnuler.setObjectName(_fromUtf8("pushButtonAnnuler"))
        self.horizontalLayout.addWidget(self.pushButtonAnnuler)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditLibelle, self.pushButtonEnregistrer)
        Dialog.setTabOrder(self.pushButtonEnregistrer, self.pushButtonAnnuler)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Couche Additionnelle", None))
        self.label_4.setText(_translate("Dialog", "Source d la couche", None))
        self.label_2.setText(_translate("Dialog", "Type", None))
        self.label_3.setText(_translate("Dialog", "Couleur de Fond", None))
        self.comboBoxType.setItemText(0, _translate("Dialog", "Vecteur", None))
        self.comboBoxType.setItemText(1, _translate("Dialog", "Raster", None))
        self.label_5.setText(_translate("Dialog", "Propriétés Générales", None))
        self.label.setText(_translate("Dialog", "Nom de la couche", None))
        self.label_12.setText(_translate("Dialog", "Remplissage", None))
        self.pushButtonCouleur.setText(_translate("Dialog", "...", None))
        self.label_13.setText(_translate("Dialog", "Type PLOF PAPIER", None))
        self.labelCertifiable.setText(_translate("Dialog", "Zone certifiable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Général", None))
        self.label_11.setText(_translate("Dialog", "Propriétés de l\'Etiquette", None))
        self.checkBoxLabel.setText(_translate("Dialog", "Etiquetter la couche avec", None))
        self.groupBoxText.setTitle(_translate("Dialog", "Texte du libellé", None))
        self.label_6.setText(_translate("Dialog", "Police", None))
        self.label_7.setText(_translate("Dialog", "Taille de la Police", None))
        self.label_8.setText(_translate("Dialog", "Couleur", None))
        self.pushButtonLabelColor.setText(_translate("Dialog", "...", None))
        self.checkBoxMapUnit.setText(_translate("Dialog", "Taille en unité de carte", None))
        self.groupBoxStroke.setTitle(_translate("Dialog", "Contour du libellé", None))
        self.checkBoxStroke.setText(_translate("Dialog", "Afficher le contour", None))
        self.label_9.setText(_translate("Dialog", "Taille", None))
        self.label_10.setText(_translate("Dialog", "Couleur", None))
        self.pushButtonColorStroke.setText(_translate("Dialog", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Etiquette", None))
        self.pushButtonEnregistrer.setText(_translate("Dialog", "Ajouter Couche", None))
        self.pushButtonAnnuler.setText(_translate("Dialog", "Annuler", None))

import icons_rc
