# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'servitudePassageConsultation.ui'
#
# Created: Tue Nov 28 11:09:04 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(789, 702)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(10, 10, 371, 121))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditDateInscription = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditDateInscription.setObjectName(_fromUtf8("lineEditDateInscription"))
        self.gridLayout.addWidget(self.lineEditDateInscription, 1, 1, 1, 1)
        self.comboBoxOrigine = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBoxOrigine.setObjectName(_fromUtf8("comboBoxOrigine"))
        self.gridLayout.addWidget(self.comboBoxOrigine, 0, 1, 1, 1)
        self.toolBtnDate = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolBtnDate.setObjectName(_fromUtf8("toolBtnDate"))
        self.gridLayout.addWidget(self.toolBtnDate, 1, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(19, 150, 371, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 351, 141))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditIdentifiant = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditIdentifiant.setObjectName(_fromUtf8("lineEditIdentifiant"))
        self.gridLayout_2.addWidget(self.lineEditIdentifiant, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 2, 2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 350, 371, 191))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 351, 141))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.textEdit_2 = QtGui.QTextEdit(self.gridLayoutWidget_3)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_3.addWidget(self.textEdit_2, 1, 0, 2, 2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 550, 371, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEditDateLevee = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEditDateLevee.setObjectName(_fromUtf8("lineEditDateLevee"))
        self.gridLayout_4.addWidget(self.lineEditDateLevee, 0, 1, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(160, 650, 191, 41))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnAide = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnAide.setObjectName(_fromUtf8("btnAide"))
        self.gridLayout_5.addWidget(self.btnAide, 0, 0, 1, 1)
        self.btnAnnuler = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnAnnuler.setObjectName(_fromUtf8("btnAnnuler"))
        self.gridLayout_5.addWidget(self.btnAnnuler, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_5.addWidget(self.checkBox, 0, 2, 1, 1)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(400, 10, 381, 481))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(420, 500, 191, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_3 = QtGui.QTextEdit(Dialog)
        self.textEdit_3.setEnabled(False)
        self.textEdit_3.setGeometry(QtCore.QRect(410, 530, 361, 151))
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Origine", None))
        self.label_2.setText(_translate("Dialog", "Date d\'inscription", None))
        self.toolBtnDate.setText(_translate("Dialog", "...", None))
        self.groupBox.setTitle(_translate("Dialog", "Liste des parcelles grévées", None))
        self.label_3.setText(_translate("Dialog", "Identifiant", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Liste des bénéficiaires", None))
        self.label_4.setText(_translate("Dialog", "Identifiant", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Levée de la servitude", None))
        self.label_5.setText(_translate("Dialog", "Date", None))
        self.btnAide.setText(_translate("Dialog", "Aide", None))
        self.btnAnnuler.setText(_translate("Dialog", "Fermer", None))
        self.label_6.setText(_translate("Dialog", "Description de la servitude", None))

