# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demande.ui'
#
# Created: Tue May 14 04:00:42 2024
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreateDemandeForm(object):
    def setupUi(self, CreateDemandeForm):
        CreateDemandeForm.setObjectName(_fromUtf8("CreateDemandeForm"))
        CreateDemandeForm.resize(998, 664)
        self.gridLayout_5 = QtGui.QGridLayout(CreateDemandeForm)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalGroupBox = QtGui.QGroupBox(CreateDemandeForm)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setContentsMargins(16, 8, 8, 8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.numeroDemandeLineEdit1 = QtGui.QLineEdit(self.horizontalGroupBox)
        self.numeroDemandeLineEdit1.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numeroDemandeLineEdit1.setFont(font)
        self.numeroDemandeLineEdit1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numeroDemandeLineEdit1.setObjectName(_fromUtf8("numeroDemandeLineEdit1"))
        self.horizontalLayout_3.addWidget(self.numeroDemandeLineEdit1)
        self.label_4 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.numeroDemandeLineEdit2 = QtGui.QLineEdit(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numeroDemandeLineEdit2.setFont(font)
        self.numeroDemandeLineEdit2.setObjectName(_fromUtf8("numeroDemandeLineEdit2"))
        self.horizontalLayout_3.addWidget(self.numeroDemandeLineEdit2)
        self.gridLayout_5.addWidget(self.horizontalGroupBox, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabVoisin = QtGui.QLabel(CreateDemandeForm)
        self.tabVoisin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabVoisin.setText(_fromUtf8(""))
        self.tabVoisin.setObjectName(_fromUtf8("tabVoisin"))
        self.horizontalLayout_2.addWidget(self.tabVoisin)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 1, 3, 1)
        self.verticalGroupBox = QtGui.QGroupBox(CreateDemandeForm)
        self.verticalGroupBox.setObjectName(_fromUtf8("verticalGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidgetOppositionDemande = QtGui.QTabWidget(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidgetOppositionDemande.setFont(font)
        self.tabWidgetOppositionDemande.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidgetOppositionDemande.setObjectName(_fromUtf8("tabWidgetOppositionDemande"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableDemande = QtGui.QTableWidget(self.tab_2)
        self.tableDemande.setObjectName(_fromUtf8("tableDemande"))
        self.tableDemande.setColumnCount(6)
        self.tableDemande.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableDemande.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableDemande)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comboBoxPrincipale = QtGui.QComboBox(self.tab_2)
        self.comboBoxPrincipale.setObjectName(_fromUtf8("comboBoxPrincipale"))
        self.gridLayout_3.addWidget(self.comboBoxPrincipale, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.tabWidgetOppositionDemande.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableVoisin = QtGui.QTableWidget(self.tab)
        self.tableVoisin.setGeometry(QtCore.QRect(1, 1, 289, 111))
        self.tableVoisin.setObjectName(_fromUtf8("tableVoisin"))
        self.tableVoisin.setColumnCount(2)
        self.tableVoisin.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableVoisin.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableVoisin.setHorizontalHeaderItem(1, item)
        self.tabWidgetOppositionDemande.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidgetOppositionDemande)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.addBtn = QtGui.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/users/icone/user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtn.setIcon(icon)
        self.addBtn.setObjectName(_fromUtf8("addBtn"))
        self.horizontalLayout_4.addWidget(self.addBtn)
        self.delBtn = QtGui.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delBtn.setIcon(icon1)
        self.delBtn.setObjectName(_fromUtf8("delBtn"))
        self.horizontalLayout_4.addWidget(self.delBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_5.addWidget(self.verticalGroupBox, 2, 0, 3, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formGroupBox = QtGui.QGroupBox(CreateDemandeForm)
        self.formGroupBox.setObjectName(_fromUtf8("formGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.numeroGrilleLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numeroGrilleLabel.setFont(font)
        self.numeroGrilleLabel.setObjectName(_fromUtf8("numeroGrilleLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.numeroGrilleLabel)
        self.numeroGrilleLineEdit = QtGui.QLineEdit(self.formGroupBox)
        self.numeroGrilleLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.numeroGrilleLineEdit.setObjectName(_fromUtf8("numeroGrilleLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.numeroGrilleLineEdit)
        self.numeroDemandeSurPapierPLOFLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numeroDemandeSurPapierPLOFLabel.setFont(font)
        self.numeroDemandeSurPapierPLOFLabel.setObjectName(_fromUtf8("numeroDemandeSurPapierPLOFLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.numeroDemandeSurPapierPLOFLabel)
        self.numeroDemandeSurPapierPLOFLineEdit = QtGui.QLineEdit(self.formGroupBox)
        self.numeroDemandeSurPapierPLOFLineEdit.setObjectName(_fromUtf8("numeroDemandeSurPapierPLOFLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.numeroDemandeSurPapierPLOFLineEdit)
        self.observationsLabel = QtGui.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.observationsLabel.setFont(font)
        self.observationsLabel.setObjectName(_fromUtf8("observationsLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.observationsLabel)
        self.observationsLineEdit = QtGui.QLineEdit(self.formGroupBox)
        self.observationsLineEdit.setObjectName(_fromUtf8("observationsLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.observationsLineEdit)
        self.verticalLayout_2.addWidget(self.formGroupBox)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 3, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(CreateDemandeForm)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEditDureeMiseEnValeur = QtGui.QLineEdit(self.groupBox)
        self.lineEditDureeMiseEnValeur.setObjectName(_fromUtf8("lineEditDureeMiseEnValeur"))
        self.gridLayout_4.addWidget(self.lineEditDureeMiseEnValeur, 0, 1, 1, 1)
        self.textEditOrigine = QtGui.QTextEdit(self.groupBox)
        self.textEditOrigine.setObjectName(_fromUtf8("textEditOrigine"))
        self.gridLayout_4.addWidget(self.textEditOrigine, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 4, 1, 2, 1)
        self.horizontalGroupBox1 = QtGui.QGroupBox(CreateDemandeForm)
        self.horizontalGroupBox1.setObjectName(_fromUtf8("horizontalGroupBox1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout.setMargin(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.BtnCreate = QtGui.QPushButton(self.horizontalGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnCreate.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/accept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnCreate.setIcon(icon2)
        self.BtnCreate.setObjectName(_fromUtf8("BtnCreate"))
        self.horizontalLayout.addWidget(self.BtnCreate)
        self.BtnCancel = QtGui.QPushButton(self.horizontalGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnCancel.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/std/icone/if_minus_10199.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnCancel.setIcon(icon3)
        self.BtnCancel.setObjectName(_fromUtf8("BtnCancel"))
        self.horizontalLayout.addWidget(self.BtnCancel)
        self.gridLayout_5.addWidget(self.horizontalGroupBox1, 6, 0, 1, 1)
        self.formGroupBox_2 = QtGui.QGroupBox(CreateDemandeForm)
        self.formGroupBox_2.setObjectName(_fromUtf8("formGroupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.formGroupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.districtLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.districtLabel.setFont(font)
        self.districtLabel.setObjectName(_fromUtf8("districtLabel"))
        self.gridLayout_2.addWidget(self.districtLabel, 0, 2, 1, 1)
        self.districtLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.districtLineEdit.setObjectName(_fromUtf8("districtLineEdit"))
        self.gridLayout_2.addWidget(self.districtLineEdit, 0, 3, 1, 1)
        self.communeLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.communeLabel.setFont(font)
        self.communeLabel.setObjectName(_fromUtf8("communeLabel"))
        self.gridLayout_2.addWidget(self.communeLabel, 0, 4, 1, 1)
        self.fokontanyLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fokontanyLabel.setFont(font)
        self.fokontanyLabel.setObjectName(_fromUtf8("fokontanyLabel"))
        self.gridLayout_2.addWidget(self.fokontanyLabel, 3, 0, 1, 1)
        self.fokontanyComboBox = QtGui.QComboBox(self.formGroupBox_2)
        self.fokontanyComboBox.setObjectName(_fromUtf8("fokontanyComboBox"))
        self.gridLayout_2.addWidget(self.fokontanyComboBox, 3, 1, 1, 1)
        self.regionLabel = QtGui.QLabel(self.formGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.regionLabel.setFont(font)
        self.regionLabel.setObjectName(_fromUtf8("regionLabel"))
        self.gridLayout_2.addWidget(self.regionLabel, 0, 0, 1, 1)
        self.regionLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.regionLineEdit.setObjectName(_fromUtf8("regionLineEdit"))
        self.gridLayout_2.addWidget(self.regionLineEdit, 0, 1, 1, 1)
        self.communeLineEdit = QtGui.QLineEdit(self.formGroupBox_2)
        self.communeLineEdit.setObjectName(_fromUtf8("communeLineEdit"))
        self.gridLayout_2.addWidget(self.communeLineEdit, 0, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.formGroupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
        self.HameauComboBox = QtGui.QComboBox(self.formGroupBox_2)
        self.HameauComboBox.setObjectName(_fromUtf8("HameauComboBox"))
        self.gridLayout_2.addWidget(self.HameauComboBox, 3, 3, 1, 1)
        self.toolButtonHameau = QtGui.QToolButton(self.formGroupBox_2)
        self.toolButtonHameau.setObjectName(_fromUtf8("toolButtonHameau"))
        self.gridLayout_2.addWidget(self.toolButtonHameau, 3, 4, 1, 1)
        self.gridLayout_5.addWidget(self.formGroupBox_2, 5, 0, 1, 1)
        self.formGroupBox1 = QtGui.QGroupBox(CreateDemandeForm)
        self.formGroupBox1.setObjectName(_fromUtf8("formGroupBox1"))
        self.gridLayout = QtGui.QGridLayout(self.formGroupBox1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dateDemandeLabel = QtGui.QLabel(self.formGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateDemandeLabel.setFont(font)
        self.dateDemandeLabel.setObjectName(_fromUtf8("dateDemandeLabel"))
        self.gridLayout.addWidget(self.dateDemandeLabel, 1, 0, 1, 1)
        self.consistanceLabel = QtGui.QLabel(self.formGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consistanceLabel.setFont(font)
        self.consistanceLabel.setObjectName(_fromUtf8("consistanceLabel"))
        self.gridLayout.addWidget(self.consistanceLabel, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.formGroupBox1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.consistanceComboBox = QtGui.QComboBox(self.formGroupBox1)
        self.consistanceComboBox.setObjectName(_fromUtf8("consistanceComboBox"))
        self.gridLayout.addWidget(self.consistanceComboBox, 3, 1, 1, 1)
        self.lineEditConsistances = QtGui.QLineEdit(self.formGroupBox1)
        self.lineEditConsistances.setObjectName(_fromUtf8("lineEditConsistances"))
        self.gridLayout.addWidget(self.lineEditConsistances, 3, 3, 1, 1)
        self.coutLabel = QtGui.QLabel(self.formGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coutLabel.setFont(font)
        self.coutLabel.setObjectName(_fromUtf8("coutLabel"))
        self.gridLayout.addWidget(self.coutLabel, 3, 4, 1, 1)
        self.label = QtGui.QLabel(self.formGroupBox1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 2, 1, 1)
        self.coutLineEdit = QtGui.QLineEdit(self.formGroupBox1)
        self.coutLineEdit.setObjectName(_fromUtf8("coutLineEdit"))
        self.gridLayout.addWidget(self.coutLineEdit, 3, 5, 1, 1)
        self.lineEditCodeParcelle = QtGui.QLineEdit(self.formGroupBox1)
        self.lineEditCodeParcelle.setObjectName(_fromUtf8("lineEditCodeParcelle"))
        self.gridLayout.addWidget(self.lineEditCodeParcelle, 0, 1, 1, 3)
        self.dateDemandeDateEdit = QtGui.QDateEdit(self.formGroupBox1)
        self.dateDemandeDateEdit.setCalendarPopup(True)
        self.dateDemandeDateEdit.setObjectName(_fromUtf8("dateDemandeDateEdit"))
        self.gridLayout.addWidget(self.dateDemandeDateEdit, 1, 1, 1, 3)
        self.groupBoxDates = QtGui.QGroupBox(self.formGroupBox1)
        self.groupBoxDates.setCheckable(True)
        self.groupBoxDates.setObjectName(_fromUtf8("groupBoxDates"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBoxDates)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.checkBoxFinAffichage = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxFinAffichage.setText(_fromUtf8(""))
        self.checkBoxFinAffichage.setObjectName(_fromUtf8("checkBoxFinAffichage"))
        self.gridLayout_8.addWidget(self.checkBoxFinAffichage, 4, 0, 1, 1)
        self.dateEditDebutAffichage = QtGui.QDateEdit(self.groupBoxDates)
        self.dateEditDebutAffichage.setCalendarPopup(True)
        self.dateEditDebutAffichage.setObjectName(_fromUtf8("dateEditDebutAffichage"))
        self.gridLayout_8.addWidget(self.dateEditDebutAffichage, 3, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBoxDates)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBoxDates)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 4, 1, 1, 1)
        self.checkBoxDebutAffichage = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxDebutAffichage.setText(_fromUtf8(""))
        self.checkBoxDebutAffichage.setObjectName(_fromUtf8("checkBoxDebutAffichage"))
        self.gridLayout_8.addWidget(self.checkBoxDebutAffichage, 3, 0, 1, 1)
        self.checkBoxDateReconnaissance = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxDateReconnaissance.setText(_fromUtf8(""))
        self.checkBoxDateReconnaissance.setObjectName(_fromUtf8("checkBoxDateReconnaissance"))
        self.gridLayout_8.addWidget(self.checkBoxDateReconnaissance, 1, 0, 1, 1)
        self.dateDCisionLabel_2 = QtGui.QLabel(self.groupBoxDates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateDCisionLabel_2.setFont(font)
        self.dateDCisionLabel_2.setObjectName(_fromUtf8("dateDCisionLabel_2"))
        self.gridLayout_8.addWidget(self.dateDCisionLabel_2, 0, 1, 1, 1)
        self.dateDecision = QtGui.QDateEdit(self.groupBoxDates)
        self.dateDecision.setCalendarPopup(True)
        self.dateDecision.setObjectName(_fromUtf8("dateDecision"))
        self.gridLayout_8.addWidget(self.dateDecision, 0, 2, 1, 1)
        self.dateReconnaissanceDateEdit = QtGui.QDateEdit(self.groupBoxDates)
        self.dateReconnaissanceDateEdit.setCalendarPopup(True)
        self.dateReconnaissanceDateEdit.setObjectName(_fromUtf8("dateReconnaissanceDateEdit"))
        self.gridLayout_8.addWidget(self.dateReconnaissanceDateEdit, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBoxDates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 2, 1, 1, 1)
        self.lineEditNumDecision = QtGui.QLineEdit(self.groupBoxDates)
        self.lineEditNumDecision.setObjectName(_fromUtf8("lineEditNumDecision"))
        self.gridLayout_8.addWidget(self.lineEditNumDecision, 2, 2, 1, 1)
        self.checkBoxNumDecision = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxNumDecision.setText(_fromUtf8(""))
        self.checkBoxNumDecision.setObjectName(_fromUtf8("checkBoxNumDecision"))
        self.gridLayout_8.addWidget(self.checkBoxNumDecision, 2, 0, 1, 1)
        self.checkBoxDateDecision = QtGui.QCheckBox(self.groupBoxDates)
        self.checkBoxDateDecision.setText(_fromUtf8(""))
        self.checkBoxDateDecision.setObjectName(_fromUtf8("checkBoxDateDecision"))
        self.gridLayout_8.addWidget(self.checkBoxDateDecision, 0, 0, 1, 1)
        self.dateReconnaissanceLabel_2 = QtGui.QLabel(self.groupBoxDates)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateReconnaissanceLabel_2.setFont(font)
        self.dateReconnaissanceLabel_2.setObjectName(_fromUtf8("dateReconnaissanceLabel_2"))
        self.gridLayout_8.addWidget(self.dateReconnaissanceLabel_2, 1, 1, 1, 1)
        self.dateEditFinAffichage = QtGui.QDateEdit(self.groupBoxDates)
        self.dateEditFinAffichage.setCalendarPopup(True)
        self.dateEditFinAffichage.setObjectName(_fromUtf8("dateEditFinAffichage"))
        self.gridLayout_8.addWidget(self.dateEditFinAffichage, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBoxDates, 2, 0, 1, 4)
        self.gridLayout_5.addWidget(self.formGroupBox1, 1, 0, 1, 1)

        self.retranslateUi(CreateDemandeForm)
        self.tabWidgetOppositionDemande.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CreateDemandeForm)

    def retranslateUi(self, CreateDemandeForm):
        CreateDemandeForm.setWindowTitle(_translate("CreateDemandeForm", "Informations Demande", None))
        self.label_3.setText(_translate("CreateDemandeForm", "Numero Demande :           ", None))
        self.label_4.setText(_translate("CreateDemandeForm", "-F-", None))
        item = self.tableDemande.horizontalHeaderItem(0)
        item.setText(_translate("CreateDemandeForm", "Nom", None))
        item = self.tableDemande.horizontalHeaderItem(1)
        item.setText(_translate("CreateDemandeForm", "Prenom", None))
        item = self.tableDemande.horizontalHeaderItem(2)
        item.setText(_translate("CreateDemandeForm", "Date Naissance", None))
        item = self.tableDemande.horizontalHeaderItem(3)
        item.setText(_translate("CreateDemandeForm", "CIN", None))
        item = self.tableDemande.horizontalHeaderItem(4)
        item.setText(_translate("CreateDemandeForm", "Sexe", None))
        item = self.tableDemande.horizontalHeaderItem(5)
        item.setText(_translate("CreateDemandeForm", "id", None))
        self.label_7.setText(_translate("CreateDemandeForm", "Principale", None))
        self.tabWidgetOppositionDemande.setTabText(self.tabWidgetOppositionDemande.indexOf(self.tab_2), _translate("CreateDemandeForm", "Demandeurs", None))
        item = self.tableVoisin.horizontalHeaderItem(0)
        item.setText(_translate("CreateDemandeForm", "Repère", None))
        item = self.tableVoisin.horizontalHeaderItem(1)
        item.setText(_translate("CreateDemandeForm", "Description", None))
        self.tabWidgetOppositionDemande.setTabText(self.tabWidgetOppositionDemande.indexOf(self.tab), _translate("CreateDemandeForm", "Voisins", None))
        self.addBtn.setText(_translate("CreateDemandeForm", "Nouveau ", None))
        self.delBtn.setText(_translate("CreateDemandeForm", "Supprimer", None))
        self.numeroGrilleLabel.setText(_translate("CreateDemandeForm", "Numero grille", None))
        self.numeroDemandeSurPapierPLOFLabel.setText(_translate("CreateDemandeForm", "Numero  sur papier PLOF", None))
        self.observationsLabel.setText(_translate("CreateDemandeForm", "Observations", None))
        self.groupBox.setTitle(_translate("CreateDemandeForm", "Mise en valeur", None))
        self.label_8.setText(_translate("CreateDemandeForm", "Durée occupation (ans):", None))
        self.label_9.setText(_translate("CreateDemandeForm", "Origine:", None))
        self.BtnCreate.setText(_translate("CreateDemandeForm", "Enregistrer", None))
        self.BtnCancel.setText(_translate("CreateDemandeForm", "Annuler", None))
        self.districtLabel.setText(_translate("CreateDemandeForm", "District", None))
        self.communeLabel.setText(_translate("CreateDemandeForm", "Commune", None))
        self.fokontanyLabel.setText(_translate("CreateDemandeForm", "Fokontany", None))
        self.regionLabel.setText(_translate("CreateDemandeForm", "Region", None))
        self.label_5.setText(_translate("CreateDemandeForm", "Hameau", None))
        self.toolButtonHameau.setText(_translate("CreateDemandeForm", "...", None))
        self.dateDemandeLabel.setText(_translate("CreateDemandeForm", "Date Demande", None))
        self.consistanceLabel.setText(_translate("CreateDemandeForm", "Categorie", None))
        self.label_6.setText(_translate("CreateDemandeForm", "Code parcelle", None))
        self.coutLabel.setText(_translate("CreateDemandeForm", "Cout", None))
        self.label.setText(_translate("CreateDemandeForm", "Consistance ", None))
        self.groupBoxDates.setTitle(_translate("CreateDemandeForm", "Remplir toutes les dates", None))
        self.label_12.setText(_translate("CreateDemandeForm", "Date Début Affichage", None))
        self.label_13.setText(_translate("CreateDemandeForm", "Date Fin Affichage", None))
        self.dateDCisionLabel_2.setText(_translate("CreateDemandeForm", "Date Decision", None))
        self.label_14.setText(_translate("CreateDemandeForm", "Num Decision", None))
        self.dateReconnaissanceLabel_2.setText(_translate("CreateDemandeForm", "Date Reconnaissance", None))

import icons_rc
