CREATE ROLE adminfiplof LOGIN ENCRYPTED PASSWORD 'md54152c95ad399ececcc24661652b146c8'
  SUPERUSER CREATEDB CREATEROLE REPLICATION
   VALID UNTIL 'infinity';

DISCONNECT ALL;

CONNECT TO @localhost adminfiplof USING AdminF1pl0f*2K24;

ALTER ROLE postgres
  NOSUPERUSER NOCREATEDB NOCREATEROLE
   VALID UNTIL 'infinity';
UPDATE pg_authid SET rolcatupdate=false WHERE OID=10::oid;
