INSERT INTO acces VALUES (1, 'DEMANDE/CREATE', 'Creation Demande');
INSERT INTO acces VALUES (2, 'DEMANDE/READ', 'Consultation Demande');
INSERT INTO acces VALUES (3, 'DEMANDE/EDIT_INFO', 'Edition des informations des demandes');
INSERT INTO acces VALUES (4, 'DEMANDE/EDIT_GEO', 'Edition des geometries des demandes');
INSERT INTO acces VALUES (5, 'CERTIFICAT/CREATE', 'Creation Certificat');
INSERT INTO acces VALUES (6, 'CERTIFICAT/READ', 'Consultation Certificat');
INSERT INTO acces VALUES (7, 'CERTIFICAT/EDIT_INFO', 'Edition des informations des certificats');
INSERT INTO acces VALUES (8, 'CERTIFICAT/EDIT_GEO', 'Edition des geometries des certificats');
INSERT INTO acces VALUES (9, 'PERSONNE_PHYSIQUE/CREATE', 'Creation Personne Physique');
INSERT INTO acces VALUES (10, 'PERSONNE_PHYSIQUE/READ', 'Consultation Personne Physique');
INSERT INTO acces VALUES (11, 'PERSONNE_PHYSIQUE/EDIT', 'Edition Personne Physique');
INSERT INTO acces VALUES (12, 'PERSONNE_MORALE/CREATE', 'Creation Personne Morale');
INSERT INTO acces VALUES (13, 'PERSONNE_MORALE/READ', 'Consultation Personne Morale');
INSERT INTO acces VALUES (14, 'PERSONNE_MORALE/EDIT', 'Edition Personne Morale');
INSERT INTO acces VALUES (15, 'PERSONNE_MORALE_TYPE/CREATE', 'Creation Type de Personnes Morales');
INSERT INTO acces VALUES (16, 'PERSONNE_MORALE_TYPE/READ', 'Consultation Type de Personnes Morales');
INSERT INTO acces VALUES (17, 'PERSONNE_MORALE_TYPE/EDIT', 'Edition Type de Personnes Morales');
INSERT INTO acces VALUES (18, 'PERSONNE_MORALE_TYPE/DELETE', 'Supression Type de Personnes Morales');
INSERT INTO acces VALUES (19, 'KARATANY/PRINT', 'Impression Karatany');
INSERT INTO acces VALUES (21, 'CERTIFICAT/ATTESTATION', 'Attestation Certificat');
INSERT INTO acces VALUES (23, 'CERTIFICAT/ANNULATION', 'Annulation Certificat');
INSERT INTO acces VALUES (24, 'OPERATIONS_SUBSEQUENTES', 'Operations Subsequentes');
INSERT INTO acces VALUES (25, 'IMPOT_FONCIER/CREATE', 'Saisie des Donnees');
INSERT INTO acces VALUES (26, 'IMPOT_FONCIER/CALCUL', 'Calcul Impots');
INSERT INTO acces VALUES (27, 'IMPOT_FONCIER/PARAMETRES', 'Parametres');
INSERT INTO acces VALUES (28, 'IMPOT_FONCIER/REGISTRE', 'Registre des Demandes');
INSERT INTO acces VALUES (29, 'IMPOT_FONCIER/BENEFICIAIRES', 'Liste des Beneficiaires');
INSERT INTO acces VALUES (30, 'IMPOT_FONCIER/AFFICHAGE', 'Affichage');
INSERT INTO acces VALUES (33, 'FICHIER/LOAD_PTS_XLS', 'Charger des points depuis xls');
INSERT INTO acces VALUES (34, 'FICHIER/LEVE_GPS', 'Leve parcelle GPS');
INSERT INTO acces VALUES (35, 'DEMANDE/LISTIN_IMPORT', 'Import Listing');
INSERT INTO acces VALUES (36, 'DEMANDE/DATE_ATTRIB', 'Attribution des dates');
INSERT INTO acces VALUES (37, 'DEMANDE/OPPOSITION', 'Signaler Opposition');
INSERT INTO acces VALUES (38, 'RECONNAISSANCE_LOCALE/EXPORT_RL', 'Export données pour RL');
INSERT INTO acces VALUES (39, 'RECONNAISSANCE_LOCALE/IMPORT_RL', 'Import données après RL');
INSERT INTO acces VALUES (40, 'CERTIFICAT/TRANSFO_GROUPEE', 'Transformation groupée');
INSERT INTO acces VALUES (41, 'CERTIFICAT/ANNULLE', 'Annulation certificat');
INSERT INTO acces VALUES (42, 'IMPOT_FONCIER/AUTRES', 'Autres_Liste des beneficiaires');
INSERT INTO acces VALUES (43, 'IMPORT_EXPORT/EXPORT_SHAPE', 'Export shapefile');
INSERT INTO acces VALUES (45, 'PROJET/ANCIENNE_DONNEES', 'Anciennes données');
INSERT INTO acces VALUES (46, 'PROJET/DONNEES_TERRAIN', 'Données Terrains');
INSERT INTO acces VALUES (47, 'PROJET/NEW', 'Nouveau projet');
INSERT INTO acces VALUES (48, 'PROJET/LIST', 'Liste des projets');
INSERT INTO acces VALUES (49, 'PROJET/PARAMS', 'Paramètres projet');
INSERT INTO acces VALUES (50, 'PARAMETRES/HAMEAU', 'Hameau');
INSERT INTO acces VALUES (51, 'PARAMETRES/CATEGORIE', 'Categorie');
INSERT INTO acces VALUES (52, 'PARAMETRES/CONSISTANCE_BAT', 'Consistance batiment');
INSERT INTO acces VALUES (53, 'PARAMETRES/TERRITOIRE', 'Territoires');
INSERT INTO acces VALUES (54, 'PARAMETRES/CONTENANCE_MAX', 'Contenance maximale');
INSERT INTO acces VALUES (55, 'PARAMETRES/BDD', 'Base de données');
INSERT INTO acces VALUES (56, 'PARAMETRES/COMPTEUR', 'Compteur');
INSERT INTO acces VALUES (57, 'PARAMETRES/BD_VIDE', 'Créer une base de données vide');
INSERT INTO acces VALUES (58, 'PARAMETRES/BD_SPLIT', 'Séparer la base en base de données par commune');
INSERT INTO acces VALUES (59, 'ETATS/AFFICHAGE', 'Affichage collectif');
INSERT INTO acces VALUES (60, 'ETATS/FANAPAHANA', 'Decision');
INSERT INTO acces VALUES (61, 'ETATS/ATTESTATION', 'Attestation');
INSERT INTO acces VALUES (62, 'ETATS/RP', 'Registre Parcellaire');
INSERT INTO acces VALUES (63, 'ETATS/PAGE_OP', 'Page Operations subsequentes');
INSERT INTO acces VALUES (64, 'ETATS/RDD', 'Registre de demande');
INSERT INTO acces VALUES (65, 'ETATS/AVIS_IMPOSITION', 'Avis imposition');
INSERT INTO acces VALUES (66, 'ETATS/CERTIFICAT_AFFICHAGE', 'Certificat affichage');
INSERT INTO acces VALUES (67, 'ETATS/LISTING_DEMANDE', 'Listing Demande');
INSERT INTO acces VALUES (68, 'ETATS/PVRL', 'PVRL');
INSERT INTO acces VALUES (69, 'ETATS/NOMBRE_CF', 'Nombre de demande et CF');
INSERT INTO acces VALUES (70, 'ETATS/STATISTIQUES', 'Statistique');
INSERT INTO acces VALUES (71, 'INVENTAIRE/IMPORT_DATA', 'Import Données inventaire');
INSERT INTO acces VALUES (72, 'INVENTAIRE/FILTRE', 'Filtre inventaire');
INSERT INTO acces VALUES (73, 'PLOF/IMPORT_SHAPE', 'Import Shape PLOF');
INSERT INTO acces VALUES (74, 'PLOF/IMPORT_DXF', 'Import Fichier DXF');

SELECT pg_catalog.setval('acces_id_seq', 74, true);

