# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PersonnePhysiqueConsultation.ui'
#
# Created: Tue Nov 28 11:05:24 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(466, 783)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(10, 10, 441, 201))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 113))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditDateNaiss = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditDateNaiss.setObjectName(_fromUtf8("lineEditDateNaiss"))
        self.gridLayout.addWidget(self.lineEditDateNaiss, 2, 1, 1, 1)
        self.lineEditPrenom = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditPrenom.setObjectName(_fromUtf8("lineEditPrenom"))
        self.gridLayout.addWidget(self.lineEditPrenom, 1, 1, 1, 1)
        self.lineEditNom = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditNom.setObjectName(_fromUtf8("lineEditNom"))
        self.gridLayout.addWidget(self.lineEditNom, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 411, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.radioBtnMale = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioBtnMale.setObjectName(_fromUtf8("radioBtnMale"))
        self.horizontalLayout.addWidget(self.radioBtnMale)
        self.radioBtnFemale = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioBtnFemale.setObjectName(_fromUtf8("radioBtnFemale"))
        self.horizontalLayout.addWidget(self.radioBtnFemale)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 411, 35))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEditAdresse = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditAdresse.setObjectName(_fromUtf8("lineEditAdresse"))
        self.gridLayout_2.addWidget(self.lineEditAdresse, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 441, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 29, 421, 81))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.nomDuPReLabel = QtGui.QLabel(self.formLayoutWidget)
        self.nomDuPReLabel.setObjectName(_fromUtf8("nomDuPReLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nomDuPReLabel)
        self.nomDuPReLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.nomDuPReLineEdit.setObjectName(_fromUtf8("nomDuPReLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nomDuPReLineEdit)
        self.nomDeLaMReLabel = QtGui.QLabel(self.formLayoutWidget)
        self.nomDeLaMReLabel.setObjectName(_fromUtf8("nomDeLaMReLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.nomDeLaMReLabel)
        self.nomDeLaMReLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.nomDeLaMReLineEdit.setObjectName(_fromUtf8("nomDeLaMReLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nomDeLaMReLineEdit)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 360, 241, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 211, 129))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioBtnCelib = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioBtnCelib.setEnabled(False)
        self.radioBtnCelib.setObjectName(_fromUtf8("radioBtnCelib"))
        self.verticalLayout.addWidget(self.radioBtnCelib)
        self.radioBtnMarie = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioBtnMarie.setEnabled(False)
        self.radioBtnMarie.setObjectName(_fromUtf8("radioBtnMarie"))
        self.verticalLayout.addWidget(self.radioBtnMarie)
        self.radioBtnVeuf = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioBtnVeuf.setEnabled(False)
        self.radioBtnVeuf.setObjectName(_fromUtf8("radioBtnVeuf"))
        self.verticalLayout.addWidget(self.radioBtnVeuf)
        self.btnEtatConjoint = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnEtatConjoint.setAutoDefault(True)
        self.btnEtatConjoint.setDefault(False)
        self.btnEtatConjoint.setFlat(False)
        self.btnEtatConjoint.setObjectName(_fromUtf8("btnEtatConjoint"))
        self.verticalLayout.addWidget(self.btnEtatConjoint)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 360, 181, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 160, 92))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioBtnCIN = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioBtnCIN.setEnabled(False)
        self.radioBtnCIN.setObjectName(_fromUtf8("radioBtnCIN"))
        self.verticalLayout_2.addWidget(self.radioBtnCIN)
        self.radioBtnActeDeNaiss = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioBtnActeDeNaiss.setEnabled(False)
        self.radioBtnActeDeNaiss.setObjectName(_fromUtf8("radioBtnActeDeNaiss"))
        self.verticalLayout_2.addWidget(self.radioBtnActeDeNaiss)
        self.radioBtnRien = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioBtnRien.setEnabled(False)
        self.radioBtnRien.setObjectName(_fromUtf8("radioBtnRien"))
        self.verticalLayout_2.addWidget(self.radioBtnRien)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 530, 431, 191))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox_4 = QtGui.QGroupBox(self.page)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 30, 361, 171))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 321, 35))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEditCIN_1 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditCIN_1.setObjectName(_fromUtf8("lineEditCIN_1"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_1)
        self.lineEditCIN_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditCIN_2.setObjectName(_fromUtf8("lineEditCIN_2"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_2)
        self.lineEditCIN_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditCIN_3.setObjectName(_fromUtf8("lineEditCIN_3"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_3)
        self.lineEditCIN_4 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditCIN_4.setObjectName(_fromUtf8("lineEditCIN_4"))
        self.horizontalLayout_2.addWidget(self.lineEditCIN_4)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 80, 321, 74))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEditDateCIN = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditDateCIN.setObjectName(_fromUtf8("lineEditDateCIN"))
        self.gridLayout_3.addWidget(self.lineEditDateCIN, 0, 1, 1, 1)
        self.lineEditLeuCIN = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditLeuCIN.setObjectName(_fromUtf8("lineEditLeuCIN"))
        self.gridLayout_3.addWidget(self.lineEditLeuCIN, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.gridLayoutWidget_3)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout_3.addWidget(self.toolButton_2, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.page_2)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 30, 361, 171))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 321, 35))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lineEditNumActeNaiss = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEditNumActeNaiss.setObjectName(_fromUtf8("lineEditNumActeNaiss"))
        self.horizontalLayout_5.addWidget(self.lineEditNumActeNaiss)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 80, 321, 74))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEditDateActeNaiss = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEditDateActeNaiss.setObjectName(_fromUtf8("lineEditDateActeNaiss"))
        self.gridLayout_4.addWidget(self.lineEditDateActeNaiss, 0, 1, 1, 1)
        self.lineEditLieuActeNaiss = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEditLieuActeNaiss.setObjectName(_fromUtf8("lineEditLieuActeNaiss"))
        self.gridLayout_4.addWidget(self.lineEditLieuActeNaiss, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.toolBtnCalendrier_2 = QtGui.QToolButton(self.gridLayoutWidget_4)
        self.toolBtnCalendrier_2.setObjectName(_fromUtf8("toolBtnCalendrier_2"))
        self.gridLayout_4.addWidget(self.toolBtnCalendrier_2, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.btnFermer = QtGui.QPushButton(Dialog)
        self.btnFermer.setGeometry(QtCore.QRect(300, 740, 95, 31))
        self.btnFermer.setObjectName(_fromUtf8("btnFermer"))

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Personne physique", None))
        self.label.setText(_translate("Dialog", "Nom", None))
        self.label_3.setText(_translate("Dialog", "Date de naissance", None))
        self.label_2.setText(_translate("Dialog", "Prénom", None))
        self.label_4.setText(_translate("Dialog", "Sexe ", None))
        self.radioBtnMale.setText(_translate("Dialog", "Macsulin", None))
        self.radioBtnFemale.setText(_translate("Dialog", "Feminin", None))
        self.label_5.setText(_translate("Dialog", "Adresse", None))
        self.groupBox.setTitle(_translate("Dialog", "Filiation", None))
        self.nomDuPReLabel.setText(_translate("Dialog", "Nom du père", None))
        self.nomDeLaMReLabel.setText(_translate("Dialog", "Nom de la mère", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Situation matrimoniale", None))
        self.radioBtnCelib.setText(_translate("Dialog", "Célibataire", None))
        self.radioBtnMarie.setText(_translate("Dialog", "Marié(e)", None))
        self.radioBtnVeuf.setText(_translate("Dialog", "Veuf(ve)", None))
        self.btnEtatConjoint.setText(_translate("Dialog", "Etat civil du /de la conjoint(e)", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Pièces d\'identification", None))
        self.radioBtnCIN.setText(_translate("Dialog", "CIN", None))
        self.radioBtnActeDeNaiss.setText(_translate("Dialog", "Acte de naissance", None))
        self.radioBtnRien.setText(_translate("Dialog", "Rien", None))
        self.groupBox_4.setTitle(_translate("Dialog", "CIN", None))
        self.label_6.setText(_translate("Dialog", "Numéro", None))
        self.label_7.setText(_translate("Dialog", "Date", None))
        self.label_8.setText(_translate("Dialog", "Lieu", None))
        self.toolButton_2.setText(_translate("Dialog", "...", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Acte de naissance", None))
        self.label_11.setText(_translate("Dialog", "Numéro", None))
        self.label_12.setText(_translate("Dialog", "Date", None))
        self.label_13.setText(_translate("Dialog", "Lieu", None))
        self.toolBtnCalendrier_2.setText(_translate("Dialog", "...", None))
        self.btnFermer.setText(_translate("Dialog", "Fermer", None))

